In [1]:

import pandas as pd
import numpy as np
import os
import json
import time
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Import from our project
from src.embeddings import (
    pca_embedding, lle_embedding, umap_embedding, 
    wavelet_embedding, fft_embedding, AE_embedding,
    graph_embedding, tda_embedding, 
    nnclr_cnn_embedding, nnclr_lstm_embedding
)
from src.classifiers import (
    optimize_LOGRG, optimize_DT, optimize_RF, optimize_KNN, 
    optimize_XGBOOST, optimize_SVM, optimize_MLP, optimize_NB
)
from src.utils.preprocessing import load_dataset, prepare_dataset
from src.utils.evaluation import (
    evaluate_embeddings, visualize_embeddings, 
    compare_classifiers, generate_classification_report
)
from src.utils.visualization import umap_plt, plot_embedding_comparison

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792412592.015229  808586 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
import sys
sys.path.insert(0, "src")
from run_experiments import *

In [3]:
from sklearn.model_selection import train_test_split
# Get the list of countries and their corresponding continents from the provided URL.
url_data = (r'https://raw.githubusercontent.com/oderofrancis/rona/main/Countries-Continents.csv')
data_countries = pd.read_csv(url_data)


""" 
List of countries in the ntl data that are not present in the provided countries-continents CSV file.
{'DR Congo',
 'Mayotte',
 'Myanmar',
 'Myanmar (post-coup)',
 'México',
 'Palestine (Israel)',
 'Puerto Rico',
 'Réunion',
 'Taiwan',
 'United States'}
"""
# Do I make MENA a seperate region? I think I should.

missing_countries = {
    "Continent": [
        "Africa",
        "Africa",
        "Asia",
        "Asia",
        "North America",
        "Asia",
        "North America",
        "Africa",
        "Asia",
        "North America",
    ],
    "Country": [
        "DR Congo",
        "Mayotte",
        "Myanmar",
        "Myanmar (post-coup)",
        "México",
        "Palestine (Israel)",
        "Puerto Rico",
        "Réunion",
        "Taiwan",
        "United States",
    ],
}

data_countries = pd.concat([
    data_countries,
    pd.DataFrame(missing_countries)
], ignore_index=True)
data_countries.rename(columns={"Country": "country"}, inplace=True)


ntl_data = pd.read_csv('final_pre365/ntl_cases.csv')[['case_id', 'time', 'ntl_filled']]
ntl_data['time'] = pd.to_datetime(ntl_data['time'])
ntl_data = ntl_data.sort_values(['case_id', 'time']).reset_index(drop=True)
ntl_data['time_step'] = ntl_data.groupby('case_id').cumcount()

cases = pd.read_csv('final_pre365/cases.csv')
cases['event_date'] = pd.to_datetime(cases['event_date'])
"""
# Split data into train (test) and val
split_cases = pd.read_csv('final/split.csv')
cases = cases.merge(
    split_cases[['case_id', 'split']],
    on='case_id',
    how='left'
)
"""
"""
train_idx, val_idx = train_test_split(
    cases.index,
    test_size=0.2,
    stratify=cases['event_type'],
    random_state=42,
)

cases['split'] = 'train'
cases.loc[val_idx, 'split'] = 'val'

ntl_data = ntl_data.merge(
    cases[['case_id', 'split']],
    on='case_id',
    how='left'
)
"""
# Add the continent/

cases = cases.merge(
    data_countries[['country', 'Continent']],
    on='country',
    how='left'
).set_index('case_id')

event_types = sorted(cases['event_type'].unique())

for date_col in ['event_start', 'event_end', 'window_start', 'window_end']:
    cases[date_col] = pd.to_datetime(cases[date_col] )

feature_list = ['event_type', 'Continent']
feature_dict = dict()
for feature in feature_list:
    feature_value_dict = {feature_value : i for i, feature_value in enumerate(cases[feature].unique())}
    
    cases[feature + '_class'] = cases[feature].map(feature_value_dict)
    feature_dict[feature] = feature_value_dict

In [4]:
colors = {'Continent': {
            'Africa':'green', 
            'Asia': 'red',
            'Europe': 'darkviolet',
            'North America': 'blue',
            'South America': 'darkorange',
            'Oceania': 'mediumturquoise'}, 
            'event_type': {'conflict': 'tomato', 'cyclone': 'cadetblue', 'earthquake': 'mediumseagreen', 'flood': 'dodgerblue'}}

In [5]:
from sklearn.preprocessing import StandardScaler
def calculate_window(ntl_data, cases, d_window):
    case_ids = dict()
    frames = []                       # collect pieces, concat once at the end
    cases_window = cases.copy()

    # plain Python float -> no NumPy "generic unit" timedelta warning
    window = pd.Timedelta(days=float(d_window))

    def _rescale(frame):
        frame = frame.copy()          # avoids SettingWithCopyWarning
        frame['time_step'] = frame.groupby('case_id').cumcount()
        frame['ntl_std'] = StandardScaler().fit_transform(
            frame['ntl_filled'].values.reshape(-1, 1)
        ).ravel()
        return frame

    for case_id, df in ntl_data.groupby('case_id'):
        if cases.loc[case_id, 'n_events'] == 1:
            event_date = cases.loc[case_id, 'event_date']
            start_date = event_date - window
            end_date = event_date + window

            cases_window.loc[case_id, 'window_start'] = start_date
            cases_window.loc[case_id, 'window_end'] = end_date

            df = df[(df['time'] >= start_date) & (df['time'] <= end_date)]
            case_ids[case_id] = case_id

            if not df.empty and not df.isna().all().all():
                frames.append(_rescale(df))

        else:
            event_dates = pd.to_datetime(
                list(set(cases.loc[case_id, 'event_dates'].split(';')))
            )
            cases_window.drop(index=case_id, inplace=True)

            for i, event_date in enumerate(event_dates):
                new_case_id = f"{case_id}_event_{i+1}"
                start_date = event_date - window
                end_date = event_date + window

                cases_window.loc[new_case_id] = cases.loc[case_id]
                cases_window.loc[new_case_id, 'event_date'] = event_date
                cases_window.loc[new_case_id, 'window_start'] = start_date
                cases_window.loc[new_case_id, 'window_end'] = end_date

                case_ids[new_case_id] = case_id

                df_event = df[(df['time'] >= start_date) & (df['time'] <= end_date)]

                if not df_event.empty and not df_event.isna().all().all():
                    df_event = df_event.copy()
                    df_event['case_id'] = new_case_id   # set before cumcount
                    frames.append(_rescale(df_event))

    new_ntl = (pd.concat(frames, ignore_index=True)
               if frames else pd.DataFrame(columns=ntl_data.columns))
    
    cases_window['original_id'] = cases_window.index.map(case_ids)

    return case_ids, new_ntl, cases_window

In [6]:
#d_window = 30

#case_ids,  ntl_window, cases_window = calculate_window(ntl_data, cases, d_window)

In [7]:
#results = {
#        'dataset': d_window,
 #       'embedding_results': {},
  #      'classifier_results': {},
   #     'combined_results': {}
    #7}

In [8]:
cases

,event_type,source_cluster_id,city,country,event_date,event_dates,n_events,catalog_event_date,catalog_event_dates,shift_reason,event_start,event_end,window_anchor,window_start,window_end,notes,raster_path,Continent,event_type_class,Continent_class
case_id,,,,,,,,,,,,,,,,,,,,
earthquake_2,earthquake,2,Sagaing,Myanmar,2025-03-28,2025-03-28,1,2025-03-28 06:20:52.715,2025-03-28,NaN,2025-03-28 06:20:52.715,2025-03-28 06:20:52.715,2025-03-28,2024-03-28,2025-09-24,NaN,rasters/earthquake_2.npz,Asia,0,0
earthquake_3,earthquake,3,Iquique,Chile,2014-04-03,2014-04-03,1,2014-04-03 02:43:13.110,2014-04-03;2014-04-03,NaN,2014-04-03 01:58:30.530,2014-04-03 02:43:13.110,2014-04-03,2013-04-03,2014-09-30,NaN,rasters/earthquake_3.npz,South America,0,1
earthquake_7,earthquake,7,Catia La Mar [La Guaira],Venezuela,2026-06-24,2026-06-24,1,2026-06-24 22:05:04.012,2026-06-24,NaN,2026-06-24 22:05:04.012,2026-06-24 22:05:04.012,2026-06-24,2025-06-24,2026-10-08,NaN,rasters/earthquake_7.npz,South America,0,1
earthquake_11,earthquake,11,Halabja,Iraq,2017-11-20,2017-11-20,1,2017-11-12 18:18:17.180,2017-11-12,NaN,2017-11-12 18:18:17.180,2017-11-12 18:18:17.180,2017-11-12,2016-11-12,2018-05-11,NaN,rasters/earthquake_11.npz,Asia,0,0
earthquake_29,earthquake,29,Valparaíso,Chile,2017-05-05,2017-05-05,1,2017-04-24 21:38:30.820,2017-04-23;2017-04-24,NaN,2017-04-23 02:36:07.830,2017-04-24 21:38:30.820,2017-04-23,2016-04-23,2017-10-21,NaN,rasters/earthquake_29.npz,South America,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
conflict_615_0,conflict,615,Mek'elē,Ethiopia,2020-12-01,2020-12-01;2021-02-16;2021-04-01;2021-06-30;20...,6,NaN,NaN,NaN,2020-12-01 00:00:00.000,2021-12-01 00:00:00.000,2020-12-01,2019-12-02,2022-06-01,NaN,rasters/conflict_615_0.npz,Africa,3,4
conflict_616_0,conflict,616,Quiha,Ethiopia,2020-12-03,2020-12-03,1,NaN,NaN,NaN,2020-12-03 00:00:00.000,2020-12-03 00:00:00.000,2020-12-03,2019-12-04,2021-06-03,NaN,rasters/conflict_616_0.npz,Africa,3,4
conflict_617_0,conflict,617,Wukro,Ethiopia,2020-11-16,2020-11-16;2021-02-18;2021-04-01;2021-06-29,4,NaN,NaN,NaN,2020-11-16 00:00:00.000,2021-06-29 00:00:00.000,2020-11-16,2019-11-17,2021-12-29,NaN,rasters/conflict_617_0.npz,Africa,3,4
conflict_618_0,conflict,618,Maychew,Ethiopia,2020-11-08,2020-11-08;2021-07-09;2021-12-25,3,NaN,NaN,NaN,2020-11-08 00:00:00.000,2021-12-25 00:00:00.000,2020-11-08,2019-11-09,2022-06-25,NaN,rasters/conflict_618_0.npz,Africa,3,4
conflict_621_0,conflict,621,Mekoni,Ethiopia,2020-11-07,2020-11-07,1,NaN,NaN,NaN,2020-11-07 00:00:00.000,2020-11-07 00:00:00.000,2020-11-07,2019-11-08,2021-05-07,NaN,rasters/conflict_621_0.npz,Africa,3,4

In [11]:
ntl_data

               case_id       time  ntl_filled  time_step split_x split_y
0       conflict_100_0 2013-11-21   26.959764          0   train   train
1       conflict_100_0 2013-11-22   16.383764          1   train   train
2       conflict_100_0 2013-11-23   23.448994          2   train   train
3       conflict_100_0 2013-11-24   24.762720          3   train   train
4       conflict_100_0 2013-11-25   23.340550          4   train   train
...                ...        ...         ...        ...     ...     ...
172095       flood_942 2024-06-27    6.411082        557   train   train
172096       flood_942 2024-06-28    6.411082        558   train   train
172097       flood_942 2024-06-29    6.411082        559   train   train
172098       flood_942 2024-06-30    6.411082        560   train   train
172099       flood_942 2024-07-01    6.411082        561   train   train

[172100 rows x 6 columns]

In [ ]:
embedding_methods = ['pca', 'lle', 'umap']#,'nnclr_cnn']
#embedding_methods = ['nnclr_cnn']
classifiers = ['logreg', 'dt', 'rf', 'knn','xgboost', 'svm', 'mlp','nb']
for feature in feature_list:
    train_idx, val_idx = train_test_split(
        cases.index,
        test_size=0.2,
        stratify=cases[feature],
        random_state=42,
    )

    cases[f'split_{feature}'] = 'train'
    cases.loc[val_idx, f'split_{feature}'] = 'val'

    ntl_data = ntl_data.merge(
    cases[[f'split_{feature}']].reset_index(inplace=False),
    on='case_id',
    how='left')
            
    
    for d_window in [7, 14, 30]:
        case_ids,  ntl_window, cases_window = calculate_window(ntl_data, cases, d_window)
        results = {
                'dataset': d_window,
                'embedding_results': {},
                'classifier_results': {},
                'combined_results': {}
            }
        X_train_norm = ntl_window[ntl_window[f'split_{feature}'] == 'train'].pivot(index='case_id', columns='time_step', values='ntl_std').dropna()
        X_val_norm = ntl_window[ntl_window[f'split_{feature}'] == 'val'].pivot(index='case_id', columns='time_step', values='ntl_std').dropna()
        X_test_norm = X_val_norm
        #X_full = ntl_window.pivot(index='case_id', columns='time_step', values='ntl_std').dropna()
        
        

        dataset_path = f'results/{feature}/data_{str(d_window)}/data_{str(d_window)}'
        os.makedirs(f'results/{feature}/data_{str(d_window)}',exist_ok=True)

        output_dir = f'plots/{feature}/data_{str(d_window)}'
        os.makedirs(output_dir ,exist_ok=True)

        y_train = cases_window.loc[X_train_norm.index, feature + '_class'].values
        y_val = cases_window.loc[X_val_norm.index, feature + '_class'].values
        y_test =y_val
        
        y_train_labels = cases_window.loc[X_train_norm.index, feature].values
        y_val_labels = cases_window.loc[X_val_norm.index, feature ].values
        y_test_labels =y_val_labels

        for embed_method in embedding_methods:
            print(f"\nEvaluating embedding method: {embed_method}")
            # Run embedding
            try:
                train_emb, val_emb, test_emb, embed_time = run_embedding_experiment(
            X_train_norm.values, X_val_norm.values, X_test_norm, y_train, y_val, y_test, embed_method
                )

                # Store embedding results
                results['embedding_results'][embed_method] = {
                'time': embed_time,
                'shape': train_emb.shape if hasattr(train_emb, 'shape') else None
                }

                # Visualize embeddings
                try:
                    if embed_method in ['nnclr_cnn', 'nnclr_lstm']:
                        # For NNCLR methods, use umap_plt from visualization module
                        umap_plt(
                        train_emb, val_emb, test_emb, 
                        y_train, y_val, y_test, 
                        f"{embed_method.upper()} Embedding (window = {d_window})"
                            )
                    else:
                        # For other methods, use visualize_embeddings from evaluation module
                        fig = visualize_embeddings(
                        train_emb,labels= y_train_labels, method='tsne', colors= colors[feature],
                        title=f'{embed_method.upper()} Embedding Visualization (window = {d_window})'
                            )
                        fig.savefig(os.path.join(output_dir, f'{embed_method}_visualization.png'))
                        plt.close(fig)
                except Exception as viz_error:
                    print(f"  - Warning: Visualization failed: {viz_error}")

                # Run classifier experiments
                for clf_name in classifiers:
                    print(f"  - Testing classifier: {clf_name}")

                    experiment_name = f"{dataset_path}_{embed_method}_{clf_name}"

                    try:
                        best_params, test_score, clf_time = run_classifier_experiment(
                train_emb, val_emb, test_emb, y_train, y_val, y_test, 
                clf_name, experiment_name
                    )

                        # Store results
                        if embed_method not in results['combined_results']:
                            results['combined_results'][embed_method] = {}

                        results['combined_results'][embed_method][clf_name] = {
                    'accuracy': test_score,
                    'params': best_params,
                    'time': clf_time
                        }

                        print(f"    Accuracy: {test_score:.4f}, Time: {clf_time:.2f}s")

                    except Exception as e:
                        print(f"    Error with classifier {clf_name}: {e}")
                        results['combined_results'][embed_method][clf_name] = {
                    'error': str(e)
                    }
                    

            except Exception as e:
                print(f"Error with embedding method {embed_method}: {e}")
                results['embedding_results'][embed_method] = {
                'error': str(e)
                    }
        # Save results
        rows = []

        for embedding, classifiers in results["combined_results"].items():
            for classifier, metrics in classifiers.items():
                rows.append({
                    "embedding": embedding,
                    "classifier": classifier,
                    "accuracy": metrics["accuracy"],
                    "time": metrics["time"],
                    "params": metrics["params"]
                })

        results_df = pd.DataFrame(rows)    
        results_df.to_csv(dataset_path+'_results.csv')

Evaluating embedding method: pca

[I 2026-10-19 14:46:07,920] A new study created in memory with name: no-name-c60faa63-4870-4ce3-ac15-d7ed96c17f58
[I 2026-10-19 14:46:07,935] Trial 0 finished with value: 0.4675324675324675 and parameters: {'C': 0.018281667216737203, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6045572732356488}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:46:07,951] Trial 1 finished with value: 0.5064935064935064 and parameters: {'C': 0.1356046262445642, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3940811665404621}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:07,966] Trial 2 finished with value: 0.36363636363636365 and parameters: {'C': 0.0761416973744006, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.13671056011179405}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:07,981] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 8.314155685882988e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8036296530466364}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,087] Trial 4 finished with value: 0.45454545454545453 and parameters: {'C': 7.7162718539232555, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0124224516007585}. Best is trial 1 with value: 0.5064935064935064.

  - Testing classifier: logreg

[I 2026-10-19 14:46:08,397] Trial 5 finished with value: 0.44155844155844154 and parameters: {'C': 89.88014098122673, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06748734675628343}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,415] Trial 6 finished with value: 0.33766233766233766 and parameters: {'C': 114.89465081823104, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04420134126284192}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,432] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 1.1904622883210919e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9784651031255993}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,450] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 3.6854593156891155e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.22432107352878428}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,468] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 5.811795774538766e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04016624929784651}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,923] Trial 10 finished with value: 0.44155844155844154 and parameters: {'C': 509.68537650834804, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6722017996834224}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,944] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 0.021921774898306743, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4855289823433163}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:08,964] Trial 12 finished with value: 0.35064935064935066 and parameters: {'C': 0.9667072377410609, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.644234447284724}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,076] Trial 13 finished with value: 0.45454545454545453 and parameters: {'C': 6.040117008390978, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3627858701596592}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,097] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 8.219809499412586e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.27373224345719427}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,117] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 3.8517280567811955e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46957310642453554}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,138] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 7.991467702785359e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.918873928841557}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,157] Trial 17 finished with value: 0.33766233766233766 and parameters: {'C': 415.12046495371743, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26898757076212454}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,184] Trial 18 finished with value: 0.4805194805194805 and parameters: {'C': 0.48296474019148017, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.876179352570778}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,214] Trial 19 finished with value: 0.4935064935064935 and parameters: {'C': 0.5008428813706962, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8874104527787688}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,235] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 1.4981902570337163e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6653746203720199}. Best is trial 1 with value: 0.5064935064935064.
[I 2026-10-19 14:46:09,255] Trial 21 finished with value: 0.5194805194805194 and parameters: {'C': 0.2816987456606341, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8656204572709211}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:09,276] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 0.007592729820804533, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.918587781514536}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:09,407] Trial 23 finished with value: 0.45454545454545453 and parameters: {'C': 6.833319729902097, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6409319074502782}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:09,438] Trial 24 finished with value: 0.35064935064935066 and parameters: {'C': 23.47769494492567, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8331243273304042}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:09,459] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 0.0004137230755332075, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7449440303974582}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:09,601] Trial 26 finished with value: 0.45454545454545453 and parameters: {'C': 5.885709109875273, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7908702607450917}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,027] Trial 27 finished with value: 0.44155844155844154 and parameters: {'C': 320.2371955119436, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.41852524445214556}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,401] Trial 28 finished with value: 0.45454545454545453 and parameters: {'C': 26.374545106809567, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9795706548276123}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,422] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 0.000566943397019329, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.42898915084766537}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,443] Trial 30 finished with value: 0.4675324675324675 and parameters: {'C': 5.755404446308802e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9654938321663585}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,475] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.28002178782885934, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.20484159863489182}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,494] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.0014749180117971912, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18234238399650912}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,522] Trial 33 finished with value: 0.4805194805194805 and parameters: {'C': 0.5986022247080145, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5185365305023308}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,553] Trial 34 finished with value: 0.4805194805194805 and parameters: {'C': 0.5823934475978291, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9669345120239129}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:10,573] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 0.025516932436855322, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6034353624742523}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,028] Trial 36 finished with value: 0.44155844155844154 and parameters: {'C': 251.97232326062334, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8581741101285097}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,050] Trial 37 finished with value: 0.37662337662337664 and parameters: {'C': 0.24808029718695826, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8704606141232392}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,091] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 0.9137631143480511, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.885619681880869}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,112] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.027277322078444008, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9841932780452207}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,133] Trial 40 finished with value: 0.4935064935064935 and parameters: {'C': 0.17224822428745137, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7615090944134635}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,155] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.14236881801673712, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8049739722808944}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,177] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 0.004473823743461116, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7790599200507874}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,339] Trial 43 finished with value: 0.45454545454545453 and parameters: {'C': 6.660880763687064, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8656060809680763}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,360] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 0.03739882522927822, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2556745235280018}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,381] Trial 45 finished with value: 0.5064935064935064 and parameters: {'C': 0.061744884771119855, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.03539883103055258}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,401] Trial 46 finished with value: 0.5064935064935064 and parameters: {'C': 0.10719493356519012, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.02097766655551013}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,432] Trial 47 finished with value: 0.4935064935064935 and parameters: {'C': 0.12831984216785228, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0006892659501384693}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,463] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.4761061846346744, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10221369526071301}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,482] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 0.004037168466521217, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.03909258065192654}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,502] Trial 50 finished with value: 0.5194805194805194 and parameters: {'C': 0.07012127295855644, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1360177109645039}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,582] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 3.924298321242624, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1201106087411821}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,898] Trial 52 finished with value: 0.45454545454545453 and parameters: {'C': 36.56183235812616, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7342520037378746}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,921] Trial 53 finished with value: 0.38961038961038963 and parameters: {'C': 0.018234940496273146, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.015230273289534767}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,944] Trial 54 finished with value: 0.5064935064935064 and parameters: {'C': 0.049468950637106754, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07862189225358288}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:11,966] Trial 55 finished with value: 0.4935064935064935 and parameters: {'C': 0.041374381254514286, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10236938603000179}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,038] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 3.3633245960621996, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06365255591563314}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,061] Trial 57 finished with value: 0.19480519480519481 and parameters: {'C': 0.005824069432952146, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.11987280101706148}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,089] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.49229794602543814, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2945039011468741}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,351] Trial 59 finished with value: 0.45454545454545453 and parameters: {'C': 38.56340766537611, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.33752099472856234}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,705] Trial 60 finished with value: 0.44155844155844154 and parameters: {'C': 135.34830223675274, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1855285515781751}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,726] Trial 61 finished with value: 0.4935064935064935 and parameters: {'C': 0.03235015035516639, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.061012342415982114}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,747] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.021759292101694885, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.35140602296662876}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,768] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.0015332011716525026, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5388066152638187}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,790] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.014360680290017337, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16080160779061692}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,811] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.00020697337676182822, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09056651430883472}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,842] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 0.7268315028199288, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.15465778704914385}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,864] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.000282060349083303, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.27427736941438907}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:12,906] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 1.0938211510885716, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6595376715124446}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,078] Trial 69 finished with value: 0.45454545454545453 and parameters: {'C': 17.518385642762865, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1345110070521821}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,141] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 1.9549610454323505, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7411037498668375}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,355] Trial 71 finished with value: 0.45454545454545453 and parameters: {'C': 8.08718655960307, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9357132810483142}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,377] Trial 72 finished with value: 0.4805194805194805 and parameters: {'C': 0.12463503510068016, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5966470088143949}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,398] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.09739782287163469, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9653806639457476}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,459] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 2.574724905222646, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18933384607600232}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,481] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.023260571130401315, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7221821699636433}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,542] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 2.214536263531199, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0077090676789600045}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,563] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.005155486950135015, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2808046723635115}. Best is trial 21 with value: 0.5194805194805194.
[I 2026-10-19 14:46:13,594] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.23871271700747762, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04734425194039293}. Best is trial 21 with value: 0.5194805194805194.

0.014403343200683594  seconds
Classification report saved as results/Continent/data_7/data_7_pca_logreg_classification_report.txt
    Accuracy: 0.5195, Time: 6.82s
  - Testing classifier: dt

[I 2026-10-19 14:46:14,939] Trial 41 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,944] Trial 42 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,948] Trial 43 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,951] Trial 44 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,956] Trial 45 finished with value: 0.4155844155844156 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,962] Trial 46 finished with value: 0.38961038961038963 and parameters: {'max_depth': 10, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,967] Trial 47 finished with value: 0.38961038961038963 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,971] Trial 48 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,975] Trial 49 finished with value: 0.36363636363636365 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,978] Trial 50 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,983] Trial 51 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,987] Trial 52 finished with value: 0.37662337662337664 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,992] Trial 53 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:14,996] Trial 54 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,001] Trial 55 finished with value: 0.37662337662337664 and parameters: {'max_depth': 9, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,005] Trial 56 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,009] Trial 57 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,013] Trial 58 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,018] Trial 59 finished with value: 0.36363636363636365 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,022] Trial 60 finished with value: 0.2987012987012987 and parameters: {'max_depth': 9, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,026] Trial 61 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,029] Trial 62 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,033] Trial 63 finished with value: 0.4155844155844156 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,036] Trial 64 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,041] Trial 65 finished with value: 0.3246753246753247 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,046] Trial 66 finished with value: 0.35064935064935066 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,052] Trial 67 finished with value: 0.4155844155844156 and parameters: {'max_depth': 10, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,058] Trial 68 finished with value: 0.38961038961038963 and parameters: {'max_depth': 9, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,065] Trial 69 finished with value: 0.38961038961038963 and parameters: {'max_depth': 12, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,071] Trial 70 finished with value: 0.37662337662337664 and parameters: {'max_depth': 14, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,075] Trial 71 finished with value: 0.37662337662337664 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,080] Trial 72 finished with value: 0.33766233766233766 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,083] Trial 73 finished with value: 0.38961038961038963 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,090] Trial 74 finished with value: 0.36363636363636365 and parameters: {'max_depth': 32, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,095] Trial 75 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,101] Trial 76 finished with value: 0.33766233766233766 and parameters: {'max_depth': 10, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,107] Trial 77 finished with value: 0.38961038961038963 and parameters: {'max_depth': 9, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,110] Trial 78 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,114] Trial 79 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,119] Trial 80 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,123] Trial 81 finished with value: 0.37662337662337664 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,127] Trial 82 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,132] Trial 83 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,135] Trial 84 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,141] Trial 85 finished with value: 0.35064935064935066 and parameters: {'max_depth': 12, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,145] Trial 86 finished with value: 0.38961038961038963 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,149] Trial 87 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,153] Trial 88 finished with value: 0.4155844155844156 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,159] Trial 89 finished with value: 0.3246753246753247 and parameters: {'max_depth': 25, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,163] Trial 90 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,167] Trial 91 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,173] Trial 92 finished with value: 0.36363636363636365 and parameters: {'max_depth': 8, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,177] Trial 93 finished with value: 0.36363636363636365 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,182] Trial 94 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,186] Trial 95 finished with value: 0.37662337662337664 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,190] Trial 96 finished with value: 0.4025974025974026 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,195] Trial 97 finished with value: 0.3116883116883117 and parameters: {'max_depth': 22, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,199] Trial 98 finished with value: 0.38961038961038963 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4155844155844156.
[I 2026-10-19 14:46:15,203] Trial 99 finished with value: 0.38961038961038963 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 14 with value: 0.4155844155844156.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:46:15,209] A new study created in memory with name: no-name-fdce2e0c-843c-47bc-aa33-31603e98892b
[I 2026-10-19 14:46:15,332] Trial 0 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 151, 'max_depth': 2}. Best is trial 0 with value: 0.44155844155844154.
[I 2026-10-19 14:46:15,391] Trial 1 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 53, 'max_depth': 26}. Best is trial 0 with value: 0.44155844155844154.

0.0018963813781738281  seconds
Classification report saved as results/Continent/data_7/data_7_pca_dt_classification_report.txt
    Accuracy: 0.4156, Time: 0.47s
  - Testing classifier: rf

[I 2026-10-19 14:46:15,566] Trial 2 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 168, 'max_depth': 8}. Best is trial 0 with value: 0.44155844155844154.
[I 2026-10-19 14:46:15,648] Trial 3 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 80, 'max_depth': 7}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:15,754] Trial 4 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 100, 'max_depth': 24}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:15,783] Trial 5 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 27, 'max_depth': 25}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:15,853] Trial 6 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 81, 'max_depth': 4}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,034] Trial 7 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 176, 'max_depth': 26}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,183] Trial 8 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 139, 'max_depth': 24}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,258] Trial 9 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 89, 'max_depth': 3}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,281] Trial 10 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 18, 'max_depth': 9}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,456] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 163, 'max_depth': 29}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,588] Trial 12 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,644] Trial 13 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 51, 'max_depth': 13}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,666] Trial 14 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 16, 'max_depth': 32}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:16,883] Trial 15 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 192, 'max_depth': 18}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:17,026] Trial 16 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 132, 'max_depth': 29}. Best is trial 3 with value: 0.45454545454545453.
[I 2026-10-19 14:46:17,058] Trial 17 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 27, 'max_depth': 19}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,120] Trial 18 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 54, 'max_depth': 32}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,170] Trial 19 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 46, 'max_depth': 7}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,264] Trial 20 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 83, 'max_depth': 12}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,302] Trial 21 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 31, 'max_depth': 20}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,370] Trial 22 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 59, 'max_depth': 17}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,484] Trial 23 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 102, 'max_depth': 30}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,561] Trial 24 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 70, 'max_depth': 24}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,758] Trial 25 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 197, 'max_depth': 7}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,794] Trial 26 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 30, 'max_depth': 28}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,878] Trial 27 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 76, 'max_depth': 23}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,915] Trial 28 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 40, 'max_depth': 3}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:17,978] Trial 29 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 63, 'max_depth': 6}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,089] Trial 30 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 101, 'max_depth': 19}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,284] Trial 31 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 180, 'max_depth': 21}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,404] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 118, 'max_depth': 7}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,522] Trial 33 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 120, 'max_depth': 6}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,639] Trial 34 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 109, 'max_depth': 10}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,792] Trial 35 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 145, 'max_depth': 9}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,810] Trial 36 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 13, 'max_depth': 18}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:18,895] Trial 37 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 76, 'max_depth': 30}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:19,062] Trial 38 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 154, 'max_depth': 12}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:19,077] Trial 39 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 10, 'max_depth': 13}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:19,102] Trial 40 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 20, 'max_depth': 16}. Best is trial 17 with value: 0.4935064935064935.
[I 2026-10-19 14:46:19,189] Trial 41 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 78, 'max_depth': 31}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,254] Trial 42 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 57, 'max_depth': 22}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,289] Trial 43 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 29, 'max_depth': 11}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,366] Trial 44 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 69, 'max_depth': 14}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,421] Trial 45 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 48, 'max_depth': 29}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,556] Trial 46 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 170, 'max_depth': 2}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,658] Trial 47 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 92, 'max_depth': 16}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,674] Trial 48 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 11, 'max_depth': 24}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,719] Trial 49 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 39, 'max_depth': 14}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:19,877] Trial 50 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 146, 'max_depth': 32}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,030] Trial 51 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 192, 'max_depth': 2}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,167] Trial 52 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 172, 'max_depth': 2}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,311] Trial 53 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 153, 'max_depth': 5}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,417] Trial 54 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 131, 'max_depth': 2}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,435] Trial 55 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 15, 'max_depth': 5}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,599] Trial 56 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 184, 'max_depth': 4}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,798] Trial 57 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 187, 'max_depth': 10}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,862] Trial 58 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 57, 'max_depth': 10}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:20,995] Trial 59 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 120, 'max_depth': 18}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,094] Trial 60 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 104, 'max_depth': 5}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,172] Trial 61 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 69, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,270] Trial 62 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 88, 'max_depth': 27}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,370] Trial 63 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 90, 'max_depth': 32}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,387] Trial 64 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 12, 'max_depth': 11}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,420] Trial 65 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 29, 'max_depth': 7}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,490] Trial 66 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 62, 'max_depth': 26}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,535] Trial 67 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 38, 'max_depth': 31}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,553] Trial 68 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 12, 'max_depth': 27}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,593] Trial 69 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 34, 'max_depth': 32}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,647] Trial 70 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 46, 'max_depth': 18}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,669] Trial 71 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 17, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,694] Trial 72 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 19, 'max_depth': 13}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,846] Trial 73 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 170, 'max_depth': 4}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,926] Trial 74 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 71, 'max_depth': 32}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,972] Trial 75 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 40, 'max_depth': 10}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:21,994] Trial 76 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 16, 'max_depth': 20}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,096] Trial 77 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 92, 'max_depth': 22}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,146] Trial 78 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 43, 'max_depth': 12}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,280] Trial 79 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 121, 'max_depth': 27}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,330] Trial 80 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 43, 'max_depth': 10}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,419] Trial 81 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 79, 'max_depth': 20}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,462] Trial 82 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 36, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,490] Trial 83 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 28, 'max_depth': 3}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,537] Trial 84 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 40, 'max_depth': 12}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,669] Trial 85 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 135, 'max_depth': 6}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,723] Trial 86 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 46, 'max_depth': 27}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,769] Trial 87 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 39, 'max_depth': 23}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,807] Trial 88 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 37, 'max_depth': 5}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:22,916] Trial 89 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 120, 'max_depth': 4}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,046] Trial 90 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 152, 'max_depth': 3}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,173] Trial 91 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 115, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,260] Trial 92 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 77, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,302] Trial 93 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 36, 'max_depth': 8}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,348] Trial 94 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 39, 'max_depth': 32}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,374] Trial 95 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 20, 'max_depth': 22}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,439] Trial 96 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 57, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,536] Trial 97 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 86, 'max_depth': 30}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,623] Trial 98 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 77, 'max_depth': 26}. Best is trial 41 with value: 0.5194805194805194.
[I 2026-10-19 14:46:23,655] Trial 99 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 25, 'max_depth': 31}. Best is trial 41 with value: 0.5194805194805194.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:46:23,743] A new study created in memory with name: no-name-37605c53-ea21-4f8d-acc1-36c8ec35864e
[I 2026-10-19 14:46:23,746] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4025974025974026.
[I 2026-10-19 14:46:23,747] Trial 1 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.44155844155844154.
[I 2026-10-19 14:46:23,749] Trial 2 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.44155844155844154.
[I 2026-10-19 14:46:23,751] Trial 3 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 1 with value: 0.44155844155844154.
[I 2026-10-19 14:46:23,753] Trial 4 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.45454545454545453.

0.08382034301757812  seconds
Classification report saved as results/Continent/data_7/data_7_pca_rf_classification_report.txt
    Accuracy: 0.4805, Time: 8.53s
  - Testing classifier: knn

[I 2026-10-19 14:46:23,944] Trial 59 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 7 with value: 0.4675324675324675.
[I 2026-10-19 14:46:23,947] Trial 60 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,951] Trial 61 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,955] Trial 62 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,958] Trial 63 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,962] Trial 64 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,965] Trial 65 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,970] Trial 66 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,974] Trial 67 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,978] Trial 68 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,981] Trial 69 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,985] Trial 70 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,988] Trial 71 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,992] Trial 72 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,995] Trial 73 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:23,999] Trial 74 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,002] Trial 75 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,005] Trial 76 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,009] Trial 77 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,012] Trial 78 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,018] Trial 79 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,021] Trial 80 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,025] Trial 81 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,029] Trial 82 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,033] Trial 83 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,036] Trial 84 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,040] Trial 85 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,043] Trial 86 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,047] Trial 87 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,050] Trial 88 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,054] Trial 89 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,058] Trial 90 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,061] Trial 91 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,065] Trial 92 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,068] Trial 93 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,072] Trial 94 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,075] Trial 95 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,079] Trial 96 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,082] Trial 97 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,087] Trial 98 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 60 with value: 0.4805194805194805.
[I 2026-10-19 14:46:24,091] Trial 99 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 60 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:46:24,097] A new study created in memory with name: no-name-60c614b8-b00a-4a2a-922e-e8c5e09009d7
[I 2026-10-19 14:46:24,120] Trial 0 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 27, 'learning_rate': 0.2405032917787852, 'max_depth': 29, 'min_child_weight': 7.695133018167735, 'subsample': 0.3245754303174916, 'colsample_bytree': 0.902483204603647}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,179] Trial 1 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 55, 'learning_rate': 0.8405254942362306, 'max_depth': 9, 'min_child_weight': 4.505903077744972, 'subsample': 0.8386584349934629, 'colsample_bytree': 0.16461090782511761}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,258] Trial 2 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 163, 'learning_rate': 0.5309252004255712, 'max_depth': 12, 'min_child_weight': 7.3647332488588315, 'subsample': 0.13949831010165584, 'colsample_bytree': 0.36809170539520575}. Best is trial 0 with value: 0.4155844155844156.

0.0015780925750732422  seconds
Classification report saved as results/Continent/data_7/data_7_pca_knn_classification_report.txt
    Accuracy: 0.4805, Time: 0.35s
  - Testing classifier: xgboost

[I 2026-10-19 14:46:24,435] Trial 3 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 156, 'learning_rate': 0.298652827676204, 'max_depth': 25, 'min_child_weight': 1.6614277343328747, 'subsample': 0.5065043894557402, 'colsample_bytree': 0.5926913216291447}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,527] Trial 4 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 151, 'learning_rate': 0.9963859595775144, 'max_depth': 11, 'min_child_weight': 9.458235386130262, 'subsample': 0.4125532401096842, 'colsample_bytree': 0.10853080949741743}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,597] Trial 5 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 107, 'learning_rate': 0.7580675175548247, 'max_depth': 32, 'min_child_weight': 9.033773928814282, 'subsample': 0.39043227714314666, 'colsample_bytree': 0.15212678772035093}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,672] Trial 6 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 58, 'learning_rate': 0.8815306723981341, 'max_depth': 11, 'min_child_weight': 1.3361884287547494, 'subsample': 0.8247280064200092, 'colsample_bytree': 0.2482304007886781}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,770] Trial 7 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 85, 'learning_rate': 0.09659236689852362, 'max_depth': 26, 'min_child_weight': 3.765337703875581, 'subsample': 0.4417134297445431, 'colsample_bytree': 0.3772718100108272}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:24,927] Trial 8 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 199, 'learning_rate': 0.5193579566101645, 'max_depth': 21, 'min_child_weight': 6.796004704262063, 'subsample': 0.6870958969670864, 'colsample_bytree': 0.9558194811531342}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,026] Trial 9 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 100, 'learning_rate': 0.8435903289710125, 'max_depth': 16, 'min_child_weight': 2.486163157300613, 'subsample': 0.9524114886974135, 'colsample_bytree': 0.21990559624723074}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,058] Trial 10 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 19, 'learning_rate': 0.3049915443358811, 'max_depth': 26, 'min_child_weight': 7.172380637591531, 'subsample': 0.9620738185084692, 'colsample_bytree': 0.6810394327481433}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,133] Trial 11 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 148, 'learning_rate': 0.07841885905311624, 'max_depth': 25, 'min_child_weight': 8.114126811965605, 'subsample': 0.11416244479530208, 'colsample_bytree': 0.8525046161882994}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,163] Trial 12 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 30, 'learning_rate': 0.3494478124282973, 'max_depth': 26, 'min_child_weight': 9.520349925225375, 'subsample': 0.47237942582506753, 'colsample_bytree': 0.7832501186173138}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,239] Trial 13 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 69, 'learning_rate': 0.2633192423091625, 'max_depth': 21, 'min_child_weight': 1.0129519427216023, 'subsample': 0.15072560945200902, 'colsample_bytree': 0.6404379348051662}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,264] Trial 14 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 20, 'learning_rate': 0.302056471192518, 'max_depth': 28, 'min_child_weight': 5.1378439824313435, 'subsample': 0.34292267911478397, 'colsample_bytree': 0.8823280656354751}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,415] Trial 15 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 159, 'learning_rate': 0.22732930337225155, 'max_depth': 26, 'min_child_weight': 2.2137717378068977, 'subsample': 0.2272108914272521, 'colsample_bytree': 0.7915066807681915}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,558] Trial 16 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 154, 'learning_rate': 0.5007283271999239, 'max_depth': 28, 'min_child_weight': 2.82942151712821, 'subsample': 0.500100874872845, 'colsample_bytree': 0.4958297664675715}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,624] Trial 17 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 71, 'learning_rate': 0.11841616122787478, 'max_depth': 31, 'min_child_weight': 5.577543434932163, 'subsample': 0.32639559514815336, 'colsample_bytree': 0.6813863087714565}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,714] Trial 18 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 126, 'learning_rate': 0.3330679402787494, 'max_depth': 27, 'min_child_weight': 7.72714633031122, 'subsample': 0.3223675308995434, 'colsample_bytree': 0.5785832603067779}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,747] Trial 19 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 26, 'learning_rate': 0.5105503938441336, 'max_depth': 28, 'min_child_weight': 2.9939656363713594, 'subsample': 0.3015273327972712, 'colsample_bytree': 0.8685698920658331}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:46:25,769] Trial 20 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 27, 'learning_rate': 0.06299110090159776, 'max_depth': 29, 'min_child_weight': 8.100045453307606, 'subsample': 0.1960979733603201, 'colsample_bytree': 0.7810215594103983}. Best is trial 20 with value: 0.44155844155844154.
[I 2026-10-19 14:46:25,791] Trial 21 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 26, 'learning_rate': 0.2176655928080089, 'max_depth': 24, 'min_child_weight': 7.256386290867972, 'subsample': 0.20385957647042954, 'colsample_bytree': 0.7694750788986536}. Best is trial 20 with value: 0.44155844155844154.
[I 2026-10-19 14:46:25,829] Trial 22 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 63, 'learning_rate': 0.3912559708417258, 'max_depth': 32, 'min_child_weight': 7.515285545618723, 'subsample': 0.1489603460091154, 'colsample_bytree': 0.7012959208791636}. Best is trial 20 with value: 0.44155844155844154.
[I 2026-10-19 14:46:25,901] Trial 23 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 78, 'learning_rate': 0.05651199641034571, 'max_depth': 29, 'min_child_weight': 7.337384643616654, 'subsample': 0.40079892256282557, 'colsample_bytree': 0.8830872855047255}. Best is trial 20 with value: 0.44155844155844154.
[I 2026-10-19 14:46:25,933] Trial 24 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 31, 'learning_rate': 0.14841861675701962, 'max_depth': 31, 'min_child_weight': 9.118418020071868, 'subsample': 0.433750172738801, 'colsample_bytree': 0.8233401869251326}. Best is trial 20 with value: 0.44155844155844154.
[I 2026-10-19 14:46:25,948] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 14, 'learning_rate': 0.02057899939116177, 'max_depth': 28, 'min_child_weight': 8.33233925880564, 'subsample': 0.2308341121484562, 'colsample_bytree': 0.9309275349820947}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:25,983] Trial 26 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 34, 'learning_rate': 0.0516714213512177, 'max_depth': 31, 'min_child_weight': 6.19870169204215, 'subsample': 0.3304181861339925, 'colsample_bytree': 0.9847889592911018}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,007] Trial 27 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 36, 'learning_rate': 0.0532612239695446, 'max_depth': 29, 'min_child_weight': 9.628532980066945, 'subsample': 0.1715157206004993, 'colsample_bytree': 0.8370022611320087}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,031] Trial 28 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 20, 'learning_rate': 0.0310283185824147, 'max_depth': 28, 'min_child_weight': 7.3849486534060444, 'subsample': 0.4211265362184562, 'colsample_bytree': 0.9821872194503352}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,045] Trial 29 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 13, 'learning_rate': 0.0903278878628433, 'max_depth': 32, 'min_child_weight': 7.950020320593464, 'subsample': 0.2078164353764083, 'colsample_bytree': 0.9726164551063239}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,090] Trial 30 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 48, 'learning_rate': 0.13980726925953646, 'max_depth': 26, 'min_child_weight': 8.33876683315409, 'subsample': 0.41773977389036854, 'colsample_bytree': 0.9367078644125468}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,126] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 32, 'learning_rate': 0.00782764200704738, 'max_depth': 28, 'min_child_weight': 5.1636186216788875, 'subsample': 0.32145949391580275, 'colsample_bytree': 0.9748361990199997}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,168] Trial 32 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 56, 'learning_rate': 0.04935517636379694, 'max_depth': 30, 'min_child_weight': 6.137617370025664, 'subsample': 0.18943098188213695, 'colsample_bytree': 0.8100324122384506}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,182] Trial 33 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 11, 'learning_rate': 0.21541898060005293, 'max_depth': 30, 'min_child_weight': 9.50329310477769, 'subsample': 0.27349311293128203, 'colsample_bytree': 0.9737518554578645}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,249] Trial 34 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 47, 'learning_rate': 0.04860614474961831, 'max_depth': 30, 'min_child_weight': 3.3766103784100756, 'subsample': 0.44401272249411416, 'colsample_bytree': 0.9829049953630495}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,269] Trial 35 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 20, 'learning_rate': 0.08147807062325793, 'max_depth': 26, 'min_child_weight': 9.10527728376482, 'subsample': 0.3186478293401932, 'colsample_bytree': 0.8870760605231683}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,306] Trial 36 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 39, 'learning_rate': 0.02469627826259988, 'max_depth': 23, 'min_child_weight': 7.424691467327825, 'subsample': 0.32317543306894986, 'colsample_bytree': 0.9321684452404083}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,333] Trial 37 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 22, 'learning_rate': 0.11040655076630969, 'max_depth': 29, 'min_child_weight': 7.012140181992608, 'subsample': 0.4301126280137665, 'colsample_bytree': 0.8240938801943094}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,358] Trial 38 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 20, 'learning_rate': 0.09586001521360844, 'max_depth': 31, 'min_child_weight': 7.859899375063767, 'subsample': 0.5433593390658313, 'colsample_bytree': 0.9921531149281995}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,373] Trial 39 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 12, 'learning_rate': 0.031101536114626568, 'max_depth': 21, 'min_child_weight': 8.963220087698419, 'subsample': 0.27344012677364216, 'colsample_bytree': 0.8493283030146259}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,390] Trial 40 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 13, 'learning_rate': 0.06557150785510582, 'max_depth': 26, 'min_child_weight': 8.143196426091375, 'subsample': 0.42190627097531164, 'colsample_bytree': 0.8594134474359156}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,418] Trial 41 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 27, 'learning_rate': 0.14950864403535452, 'max_depth': 25, 'min_child_weight': 7.1768912733135135, 'subsample': 0.34364584339912435, 'colsample_bytree': 0.7934862640999482}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,450] Trial 42 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 40, 'learning_rate': 0.08364574924258325, 'max_depth': 23, 'min_child_weight': 9.428156869850987, 'subsample': 0.27515365760852073, 'colsample_bytree': 0.9273461018323012}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,465] Trial 43 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 10, 'learning_rate': 0.02383411697578152, 'max_depth': 28, 'min_child_weight': 8.423407577419253, 'subsample': 0.4590949370317209, 'colsample_bytree': 0.8611350815863127}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,487] Trial 44 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 30, 'learning_rate': 0.07392292654576722, 'max_depth': 24, 'min_child_weight': 8.064671246250889, 'subsample': 0.16532143491323428, 'colsample_bytree': 0.9250604597120269}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,515] Trial 45 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 28, 'learning_rate': 0.043799076197952105, 'max_depth': 26, 'min_child_weight': 9.441645594849795, 'subsample': 0.4225621126882445, 'colsample_bytree': 0.9809205273187358}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,537] Trial 46 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 20, 'learning_rate': 0.14447638271474877, 'max_depth': 20, 'min_child_weight': 8.46184651190294, 'subsample': 0.36082708376551564, 'colsample_bytree': 0.835119172088106}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,576] Trial 47 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 47, 'learning_rate': 0.15212972212085044, 'max_depth': 30, 'min_child_weight': 7.834921266598559, 'subsample': 0.30838573350060006, 'colsample_bytree': 0.9687953360211203}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,595] Trial 48 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 14, 'learning_rate': 0.04166550518174597, 'max_depth': 28, 'min_child_weight': 7.26883586936912, 'subsample': 0.3954632349400795, 'colsample_bytree': 0.9563347732016481}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,611] Trial 49 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 17, 'learning_rate': 0.01954567391257649, 'max_depth': 28, 'min_child_weight': 7.079320195608726, 'subsample': 0.18295245549715228, 'colsample_bytree': 0.8543724694800867}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,651] Trial 50 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 36, 'learning_rate': 0.06619150122035458, 'max_depth': 29, 'min_child_weight': 7.527760743152118, 'subsample': 0.3546492728026083, 'colsample_bytree': 0.8781446726734962}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,672] Trial 51 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 17, 'learning_rate': 0.018671341311409413, 'max_depth': 21, 'min_child_weight': 7.224269417434471, 'subsample': 0.4078869300219901, 'colsample_bytree': 0.916714067236278}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,702] Trial 52 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 30, 'learning_rate': 0.0786880819904992, 'max_depth': 24, 'min_child_weight': 6.244348450880338, 'subsample': 0.2871904045390446, 'colsample_bytree': 0.9215380398409139}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,725] Trial 53 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 21, 'learning_rate': 0.04015297681026213, 'max_depth': 25, 'min_child_weight': 6.985509256841546, 'subsample': 0.33511671005070615, 'colsample_bytree': 0.7901498484501492}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,766] Trial 54 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 37, 'learning_rate': 0.041153345764156676, 'max_depth': 31, 'min_child_weight': 6.892541963617516, 'subsample': 0.41803997772209384, 'colsample_bytree': 0.9702971958904136}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,783] Trial 55 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 20, 'learning_rate': 0.11324617372509414, 'max_depth': 25, 'min_child_weight': 8.887163495822984, 'subsample': 0.1263659180665201, 'colsample_bytree': 0.9326408373340292}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,797] Trial 56 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 10, 'learning_rate': 0.03547271163640387, 'max_depth': 23, 'min_child_weight': 8.558114686832493, 'subsample': 0.378904800382693, 'colsample_bytree': 0.8550101242609257}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,814] Trial 57 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 14, 'learning_rate': 0.027526095790730655, 'max_depth': 24, 'min_child_weight': 7.670585998680108, 'subsample': 0.3022915791715082, 'colsample_bytree': 0.9049975960305587}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,841] Trial 58 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 24, 'learning_rate': 0.06918971458001472, 'max_depth': 26, 'min_child_weight': 7.715399110246719, 'subsample': 0.4512085048636954, 'colsample_bytree': 0.786427907576294}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,861] Trial 59 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 24, 'learning_rate': 0.00764745102653637, 'max_depth': 22, 'min_child_weight': 8.877039671378101, 'subsample': 0.20087878029907014, 'colsample_bytree': 0.9873710981904199}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,891] Trial 60 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 27, 'learning_rate': 0.05667475694087788, 'max_depth': 28, 'min_child_weight': 7.46125538386863, 'subsample': 0.45426904347034536, 'colsample_bytree': 0.9106188918215228}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,905] Trial 61 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 12, 'learning_rate': 0.041313953734226805, 'max_depth': 28, 'min_child_weight': 8.489465396084235, 'subsample': 0.17965497529466223, 'colsample_bytree': 0.9071052505320565}. Best is trial 25 with value: 0.4675324675324675.
[I 2026-10-19 14:46:26,924] Trial 62 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 14, 'learning_rate': 0.10253032573713405, 'max_depth': 27, 'min_child_weight': 8.645949796370973, 'subsample': 0.5102796334398005, 'colsample_bytree': 0.8737908186020409}. Best is trial 25 with value: 0.4675324675324675.

0.013091564178466797  seconds
Classification report saved as results/Continent/data_7/data_7_pca_xgboost_classification_report.txt
    Accuracy: 0.4675, Time: 3.68s
  - Testing classifier: svm

[I 2026-10-19 14:46:27,970] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:27,976] Trial 36 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:27,982] Trial 37 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:27,988] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:27,994] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:27,999] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,005] Trial 41 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,010] Trial 42 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,016] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,022] Trial 44 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,028] Trial 45 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,035] Trial 46 finished with value: 0.45454545454545453 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,041] Trial 47 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,046] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,052] Trial 49 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,058] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,064] Trial 51 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,070] Trial 52 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,076] Trial 53 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,082] Trial 54 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,089] Trial 55 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,094] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,100] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,106] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,112] Trial 59 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,118] Trial 60 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,124] Trial 61 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,130] Trial 62 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,136] Trial 63 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,142] Trial 64 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,148] Trial 65 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,154] Trial 66 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,161] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,166] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,173] Trial 69 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,179] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,185] Trial 71 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,191] Trial 72 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,197] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,203] Trial 74 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,209] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,215] Trial 76 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,221] Trial 77 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,227] Trial 78 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,232] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,238] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,243] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,250] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,256] Trial 83 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,261] Trial 84 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,268] Trial 85 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,274] Trial 86 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,280] Trial 87 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,286] Trial 88 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,293] Trial 89 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,299] Trial 90 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,305] Trial 91 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,311] Trial 92 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,317] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,322] Trial 94 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,328] Trial 95 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,335] Trial 96 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,341] Trial 97 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,347] Trial 98 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 14:46:28,353] Trial 99 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:46:28,362] A new study created in memory with name: no-name-c2c9d34b-9cb7-4507-a2ab-98802aed3b51
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.0043566226959228516  seconds
Classification report saved as results/Continent/data_7/data_7_pca_svm_classification_report.txt
    Accuracy: 0.5195, Time: 0.59s
  - Testing classifier: mlp

[I 2026-10-19 14:47:27,226] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_layers': 3, 'n_neurons_layer0': 99, 'n_neurons_layer1': 77, 'n_neurons_layer2': 53, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.01943676870363661}. Best is trial 0 with value: 0.4025974025974026.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:47:27,808] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 69, 'n_neurons_layer1': 60, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.05187674685082788}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:47:28,281] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 38, 'n_neurons_layer1': 86, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.061172429501729686}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:28,729] Trial 3 finished with value: 0.35064935064935066 and parameters: {'n_layers': 2, 'n_neurons_layer0': 33, 'n_neurons_layer1': 42, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.009652776659243148}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:29,376] Trial 4 finished with value: 0.37662337662337664 and parameters: {'n_layers': 3, 'n_neurons_layer0': 81, 'n_neurons_layer1': 60, 'n_neurons_layer2': 7, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.0396146930237785}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:29,660] Trial 5 finished with value: 0.5194805194805194 and parameters: {'n_layers': 2, 'n_neurons_layer0': 25, 'n_neurons_layer1': 68, 'activation': 'identity', 'solver': 'sgd', 'alpha': 4.59520211489218e-05}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:29,864] Trial 6 finished with value: 0.5064935064935064 and parameters: {'n_layers': 2, 'n_neurons_layer0': 88, 'n_neurons_layer1': 5, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0417653643853034}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:30,254] Trial 7 finished with value: 0.33766233766233766 and parameters: {'n_layers': 3, 'n_neurons_layer0': 24, 'n_neurons_layer1': 19, 'n_neurons_layer2': 64, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.03344467756194809}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:30,343] Trial 8 finished with value: 0.4025974025974026 and parameters: {'n_layers': 2, 'n_neurons_layer0': 70, 'n_neurons_layer1': 26, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.00014822206306135187}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:30,748] Trial 9 finished with value: 0.5194805194805194 and parameters: {'n_layers': 2, 'n_neurons_layer0': 56, 'n_neurons_layer1': 65, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.09085580772602422}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:30,958] Trial 10 finished with value: 0.5194805194805194 and parameters: {'n_layers': 2, 'n_neurons_layer0': 13, 'n_neurons_layer1': 8, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.0015639827443996736}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:31,344] Trial 11 finished with value: 0.5324675324675324 and parameters: {'n_layers': 2, 'n_neurons_layer0': 42, 'n_neurons_layer1': 79, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 5.29574086144581e-05}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:31,520] Trial 12 finished with value: 0.5324675324675324 and parameters: {'n_layers': 1, 'n_neurons_layer0': 51, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00014859235009178346}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:31,705] Trial 13 finished with value: 0.5324675324675324 and parameters: {'n_layers': 1, 'n_neurons_layer0': 64, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0002212776033115887}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:31,760] Trial 14 finished with value: 0.4155844155844156 and parameters: {'n_layers': 1, 'n_neurons_layer0': 42, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 1.213405873888718e-05}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:31,895] Trial 15 finished with value: 0.5324675324675324 and parameters: {'n_layers': 1, 'n_neurons_layer0': 21, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00038507139329909025}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:32,384] Trial 16 finished with value: 0.5324675324675324 and parameters: {'n_layers': 2, 'n_neurons_layer0': 52, 'n_neurons_layer1': 100, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00014607025314906214}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:32,752] Trial 17 finished with value: 0.5324675324675324 and parameters: {'n_layers': 2, 'n_neurons_layer0': 76, 'n_neurons_layer1': 37, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0025312968094430045}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:47:33,258] Trial 18 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 52, 'n_neurons_layer1': 46, 'n_neurons_layer2': 98, 'activation': 'identity', 'solver': 'sgd', 'alpha': 1.8224652476114303e-05}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:33,433] Trial 19 finished with value: 0.5194805194805194 and parameters: {'n_layers': 1, 'n_neurons_layer0': 53, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.011714607389875528}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:34,265] Trial 20 finished with value: 0.38961038961038963 and parameters: {'n_layers': 3, 'n_neurons_layer0': 35, 'n_neurons_layer1': 99, 'n_neurons_layer2': 13, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.00015070807551996148}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:47:34,474] Trial 21 finished with value: 0.5324675324675324 and parameters: {'n_layers': 1, 'n_neurons_layer0': 81, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0027514686428194587}. Best is trial 11 with value: 0.5324675324675324.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.


{'activation': 'identity', 'solver': 'lbfgs', 'alpha': 5.29574086144581e-05, 'hidden_layer_sizes': [42, 79]}
Classification report saved as results/Continent/data_7/data_7_pca_mlp_classification_report_2026-10-19_14-47-56.txt
    Accuracy: 0.5195, Time: 88.09s
  - Testing classifier: nb

[I 2026-10-19 14:47:56,491] Trial 20 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 6.687112412512273e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,494] Trial 21 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.1523151576651094e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,496] Trial 22 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.4314608872926728e-10}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,498] Trial 23 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.5213727126541326e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,501] Trial 24 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 7.244351903923854e-12}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,503] Trial 25 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 5.933030370190577e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,505] Trial 26 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.938885182296284e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,508] Trial 27 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.8156898742606253e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,510] Trial 28 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.5327826885246817e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,512] Trial 29 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.6902290875164135e-11}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,515] Trial 30 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00140785695027056}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,517] Trial 31 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0024909033276832057}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,520] Trial 32 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00019498148164326658}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,522] Trial 33 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.008764058928120478}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,525] Trial 34 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.0400522733349632e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,527] Trial 35 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.531349082621335e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,529] Trial 36 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 5.2539635323302343e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,532] Trial 37 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0009369696550661943}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,534] Trial 38 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.748170347487625e-10}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,537] Trial 39 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00015599911627323397}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,539] Trial 40 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.1852822573035934e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,542] Trial 41 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.6441146933481155e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,544] Trial 42 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 6.395772587145364e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,546] Trial 43 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.593369705268021e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,549] Trial 44 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 9.164445436755967e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,551] Trial 45 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 5.964414059002375e-10}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,554] Trial 46 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0038295789289542748}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,556] Trial 47 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.372624513152654e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,558] Trial 48 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.1057776357540855e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,561] Trial 49 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 5.0464223082584445e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,563] Trial 50 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00043093493296390893}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,565] Trial 51 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00013759865758502832}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,568] Trial 52 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.873546043005642e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,570] Trial 53 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.1928718171970366e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,572] Trial 54 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0005513474347537687}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,574] Trial 55 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.005797688234814247}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,577] Trial 56 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.0584730315761888e-12}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,579] Trial 57 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.001825623199075538}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,581] Trial 58 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.1808766143023944e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,584] Trial 59 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.849556004568965e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,586] Trial 60 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.3457931911012513e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,589] Trial 61 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.2716225692370986e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,591] Trial 62 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.466084300799465e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,593] Trial 63 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 6.34357816311705e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,596] Trial 64 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.4505643925133601e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,598] Trial 65 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.695979554250827e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,600] Trial 66 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.000331989169253424}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,603] Trial 67 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.8557187473067182e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,605] Trial 68 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 9.286245438462825e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,607] Trial 69 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 7.715611678981574e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,609] Trial 70 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0010862139484100223}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,612] Trial 71 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.8602068033942134e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,614] Trial 72 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.991030271093906e-10}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,616] Trial 73 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 9.162627780861791e-10}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,619] Trial 74 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.6261479007438593e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,621] Trial 75 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.965062992954412e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,623] Trial 76 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 5.869866606574211e-11}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,625] Trial 77 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 7.718847382238737e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,628] Trial 78 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.2465061067461293e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,630] Trial 79 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.1867445701548318e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,632] Trial 80 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.003612716638997947}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,635] Trial 81 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.9324458736099995e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,637] Trial 82 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 4.990843393555767e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,639] Trial 83 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.780283975961751e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,642] Trial 84 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 7.63912809897246e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,644] Trial 85 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.240686052716813e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,646] Trial 86 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 8.526970163377785e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,649] Trial 87 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00022216230074469792}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,651] Trial 88 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0007489437972273747}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,653] Trial 89 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.835023173086889e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,656] Trial 90 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 8.010423843624073e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,658] Trial 91 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.5915898515581487e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,660] Trial 92 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.7953141125084744e-08}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,663] Trial 93 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.1937852984344558e-09}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,665] Trial 94 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 7.418472430617013e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,667] Trial 95 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.15971340053456e-12}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,670] Trial 96 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.2780316077599951e-07}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,672] Trial 97 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 1.493513927679704e-05}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,674] Trial 98 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 2.4510549590807463e-06}. Best is trial 0 with value: 0.4155844155844156.
[I 2026-10-19 14:47:56,677] Trial 99 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 3.0712781689306875e-07}. Best is trial 0 with value: 0.4155844155844156.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 5.798534652072663e-08}
Best validation accuracy:  0.4155844155844156
Test accuracy: 0.4155844155844156
Time taken: 0.0010907649993896484 seconds
Classification report saved as results/Continent/data_7/data_7_pca_nb_classification_report_2026-10-19_14-47-56.txt
    Accuracy: 0.4156, Time: 0.23s

Evaluating embedding method: lle

[I 2026-10-19 14:47:57,396] A new study created in memory with name: no-name-9b0c7ac0-a3d4-4e3f-83c3-9f1bb8d147fa
[I 2026-10-19 14:47:57,412] Trial 0 finished with value: 0.4675324675324675 and parameters: {'C': 1.1251118331999435e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5616971552087405}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:47:57,427] Trial 1 finished with value: 0.4805194805194805 and parameters: {'C': 3.0766279248744253, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18910097030797302}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,442] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 3.1883715184111456e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6707393914661616}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,458] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 0.00036197565294020137, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.29473639440741173}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,473] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 0.07498958508389003, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4865231706222173}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,488] Trial 5 finished with value: 0.2727272727272727 and parameters: {'C': 0.0028414132762625307, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7757131910033468}. Best is trial 1 with value: 0.4805194805194805.

  - Testing classifier: logreg

[I 2026-10-19 14:47:57,655] Trial 6 finished with value: 0.4155844155844156 and parameters: {'C': 673.5434798628982, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6373898636814458}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,673] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 0.2578600520757597, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9659154634487811}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,691] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 1.4857140082399165, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6991260913919707}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,709] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 0.00038532972060865403, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1365798782071479}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,757] Trial 10 finished with value: 0.4155844155844156 and parameters: {'C': 114.757800705225, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2670932414372126}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,778] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 6.123842562719211e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5514454124699264}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,798] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 7.172092439119389e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09985356683982793}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,818] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 1.0109387825466607e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.891110277136417}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,839] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 2.57570261668069e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21301818644091197}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,890] Trial 15 finished with value: 0.4155844155844156 and parameters: {'C': 168.475227554701, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.021199324201153835}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,910] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 4.987422823071191e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.39028672205336307}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,931] Trial 17 finished with value: 0.45454545454545453 and parameters: {'C': 6.35553047951704, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4605794951807033}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,951] Trial 18 finished with value: 0.18181818181818182 and parameters: {'C': 4.41339514421613, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.24602438060367993}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,971] Trial 19 finished with value: 0.4675324675324675 and parameters: {'C': 0.11963260259014624, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.013091718882136921}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:57,992] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 0.08251033550445633, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1652193138944555}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,013] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 1.9315038722050295e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.011817820140320956}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,034] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 6.70908658673659e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6631388906305143}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,054] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 1.615691074081469e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8863452457160103}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,075] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 0.00032870152587609265, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8628057935680181}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,094] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 2.9017852587703264e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.29026912078246914}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,113] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 0.00021428910517909923, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5382617087838931}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,132] Trial 27 finished with value: 0.4805194805194805 and parameters: {'C': 3.2350848082314663, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1003582428302361}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,152] Trial 28 finished with value: 0.2727272727272727 and parameters: {'C': 0.019951960208274798, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.34286013713066127}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,172] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 1.2862670943930464e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.02612583015623482}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,211] Trial 30 finished with value: 0.4025974025974026 and parameters: {'C': 58.54583602884009, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1207781770217073}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,232] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 6.94878898564443e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7148804548097597}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,253] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.4698345384891355, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1531085818533382}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,273] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 2.527095122593726e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7245875871081711}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,294] Trial 34 finished with value: 0.4805194805194805 and parameters: {'C': 2.815306530221294, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.046675192630724796}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,315] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 0.0025435835265932667, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.031232199295813143}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,334] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 1.6586598376791704, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06472459564135788}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,354] Trial 37 finished with value: 0.2077922077922078 and parameters: {'C': 13.991109542877375, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0629655905872672}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,375] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 5.525182993330993e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19470209983064385}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,396] Trial 39 finished with value: 0.2077922077922078 and parameters: {'C': 843.6151284024795, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.29309414394929517}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,417] Trial 40 finished with value: 0.2077922077922078 and parameters: {'C': 29.600091022153794, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40873828805664225}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,438] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.1041821131682604, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5952697107619954}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,459] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 4.1381180280902e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4261138954484174}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,551] Trial 43 finished with value: 0.4155844155844156 and parameters: {'C': 274.7729673292122, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.43422920868236903}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,582] Trial 44 finished with value: 0.4025974025974026 and parameters: {'C': 16.488889264319763, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2201980487389789}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,603] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 1.654006103074186e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6336973602304549}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,725] Trial 46 finished with value: 0.4155844155844156 and parameters: {'C': 761.5837388871636, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1658077479443889}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,816] Trial 47 finished with value: 0.4155844155844156 and parameters: {'C': 273.6394334536289, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5381541902564269}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,838] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 3.806166259026674e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.511410417726038}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,860] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 1.6061729259152842, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21911187834829676}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,881] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 7.3006441784344635e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6562491786421555}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,902] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.0008031917617456068, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.33977741760439806}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,923] Trial 52 finished with value: 0.2727272727272727 and parameters: {'C': 0.003288648459129826, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.12097631818083912}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,944] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 0.00018232797228941695, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6926737306681008}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,964] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 1.7956588717034467e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1583374228861813}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:58,984] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 1.9885433698652777e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5060539173811476}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,006] Trial 56 finished with value: 0.4805194805194805 and parameters: {'C': 5.965333610664306, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3120284503999458}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,028] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 1.5392844558105918, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5831830693439344}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,049] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 1.5607244230048056e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.08973180795500431}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,070] Trial 59 finished with value: 0.4025974025974026 and parameters: {'C': 11.77687284042702, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.30971523540314616}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,091] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.09631508885541125, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.23217589550487533}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,113] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 1.160662975866079e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.277248767335399}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,135] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.22425891583400406, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3489025282326485}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,156] Trial 63 finished with value: 0.2727272727272727 and parameters: {'C': 0.007183253332123952, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19371578225646902}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,177] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 1.5299222947513143e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.37220062324535197}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,198] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.00022133667200830307, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04548716561059198}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,220] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 0.666187363026625, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4239734373607105}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,241] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 4.599797852697795e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.15822412612783437}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,262] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.5584645756541986, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3008310577497272}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,283] Trial 69 finished with value: 0.4025974025974026 and parameters: {'C': 14.86750663523738, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0075234445153010004}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,304] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 9.041682430087885e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6079176798108777}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,326] Trial 71 finished with value: 0.4805194805194805 and parameters: {'C': 5.1066472611254765, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1379642623276598}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,347] Trial 72 finished with value: 0.4805194805194805 and parameters: {'C': 3.8024815081728947, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.12360750668408281}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,368] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.11327714320461091, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10262724642587145}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,389] Trial 74 finished with value: 0.42857142857142855 and parameters: {'C': 8.942574728199228, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16532728013914116}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,440] Trial 75 finished with value: 0.4155844155844156 and parameters: {'C': 53.35566614224875, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.690357579492003}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,462] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 1.6846656807771736e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.052618384373599836}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,513] Trial 77 finished with value: 0.4155844155844156 and parameters: {'C': 153.1254548269814, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.17121533771244327}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,534] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.03164092590438454, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.056827858939318715}. Best is trial 1 with value: 0.4805194805194805.
[I 2026-10-19 14:47:59,555] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.07145823955811607, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6799863339863228}. Best is trial 1 with value: 0.4805194805194805.

0.0077440738677978516  seconds
Classification report saved as results/Continent/data_7/data_7_lle_logreg_classification_report.txt
    Accuracy: 0.4805, Time: 2.86s
  - Testing classifier: dt

[I 2026-10-19 14:48:00,458] Trial 40 finished with value: 0.2857142857142857 and parameters: {'max_depth': 10, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,462] Trial 41 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,465] Trial 42 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,468] Trial 43 finished with value: 0.4155844155844156 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,473] Trial 44 finished with value: 0.4155844155844156 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,476] Trial 45 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,480] Trial 46 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,485] Trial 47 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,489] Trial 48 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,494] Trial 49 finished with value: 0.4155844155844156 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,499] Trial 50 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,504] Trial 51 finished with value: 0.3116883116883117 and parameters: {'max_depth': 8, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,508] Trial 52 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,511] Trial 53 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,515] Trial 54 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,520] Trial 55 finished with value: 0.3116883116883117 and parameters: {'max_depth': 22, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,523] Trial 56 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,529] Trial 57 finished with value: 0.3246753246753247 and parameters: {'max_depth': 12, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,534] Trial 58 finished with value: 0.3116883116883117 and parameters: {'max_depth': 18, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,539] Trial 59 finished with value: 0.3116883116883117 and parameters: {'max_depth': 8, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,544] Trial 60 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,547] Trial 61 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,552] Trial 62 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,558] Trial 63 finished with value: 0.33766233766233766 and parameters: {'max_depth': 30, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,561] Trial 64 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,565] Trial 65 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,570] Trial 66 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,576] Trial 67 finished with value: 0.3246753246753247 and parameters: {'max_depth': 32, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,582] Trial 68 finished with value: 0.36363636363636365 and parameters: {'max_depth': 28, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,588] Trial 69 finished with value: 0.3116883116883117 and parameters: {'max_depth': 28, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,592] Trial 70 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,595] Trial 71 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,600] Trial 72 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,603] Trial 73 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,607] Trial 74 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,612] Trial 75 finished with value: 0.42857142857142855 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,616] Trial 76 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,620] Trial 77 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,625] Trial 78 finished with value: 0.36363636363636365 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,629] Trial 79 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,632] Trial 80 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,636] Trial 81 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,640] Trial 82 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,646] Trial 83 finished with value: 0.3116883116883117 and parameters: {'max_depth': 20, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,652] Trial 84 finished with value: 0.3116883116883117 and parameters: {'max_depth': 19, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,657] Trial 85 finished with value: 0.4155844155844156 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,660] Trial 86 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,664] Trial 87 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,669] Trial 88 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,672] Trial 89 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,676] Trial 90 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,681] Trial 91 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,684] Trial 92 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,689] Trial 93 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,693] Trial 94 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,696] Trial 95 finished with value: 0.44155844155844154 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,699] Trial 96 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,705] Trial 97 finished with value: 0.36363636363636365 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,709] Trial 98 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
[I 2026-10-19 14:48:00,714] Trial 99 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 8 with value: 0.45454545454545453.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:48:00,720] A new study created in memory with name: no-name-cd14fb64-c2e4-4c8a-872b-8f612adb1cbc
[I 2026-10-19 14:48:00,834] Trial 0 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 100, 'max_depth': 21}. Best is trial 0 with value: 0.4155844155844156.

0.001836538314819336  seconds
Classification report saved as results/Continent/data_7/data_7_lle_dt_classification_report.txt
    Accuracy: 0.4545, Time: 0.46s
  - Testing classifier: rf

[I 2026-10-19 14:48:00,918] Trial 1 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 85, 'max_depth': 6}. Best is trial 1 with value: 0.42857142857142855.
[I 2026-10-19 14:48:01,122] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 180, 'max_depth': 26}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:48:01,179] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 49, 'max_depth': 22}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:48:01,387] Trial 4 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 186, 'max_depth': 20}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:48:01,419] Trial 5 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 36, 'max_depth': 4}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:48:01,531] Trial 6 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 100, 'max_depth': 22}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:01,660] Trial 7 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 115, 'max_depth': 28}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:01,709] Trial 8 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 48, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:01,752] Trial 9 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 38, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:01,908] Trial 10 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:02,129] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 197, 'max_depth': 30}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:02,291] Trial 12 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 144, 'max_depth': 28}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:02,501] Trial 13 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 192, 'max_depth': 11}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:02,587] Trial 14 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 75, 'max_depth': 16}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:48:02,604] Trial 15 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 12, 'max_depth': 25}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:02,676] Trial 16 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 63, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:02,700] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 19, 'max_depth': 20}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:02,719] Trial 18 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 14, 'max_depth': 27}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:02,739] Trial 19 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 15, 'max_depth': 15}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:02,872] Trial 20 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 138, 'max_depth': 6}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,050] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 157, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,149] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 87, 'max_depth': 25}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,341] Trial 23 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 172, 'max_depth': 30}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,492] Trial 24 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 133, 'max_depth': 24}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,615] Trial 25 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 109, 'max_depth': 13}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,668] Trial 26 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 45, 'max_depth': 17}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,857] Trial 27 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 169, 'max_depth': 17}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:03,972] Trial 28 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 101, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,118] Trial 29 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 129, 'max_depth': 20}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,336] Trial 30 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 196, 'max_depth': 25}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,489] Trial 31 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 136, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,615] Trial 32 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 112, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,662] Trial 33 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 38, 'max_depth': 24}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,730] Trial 34 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 55, 'max_depth': 26}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:04,919] Trial 35 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 163, 'max_depth': 12}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,019] Trial 36 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 85, 'max_depth': 20}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,045] Trial 37 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 19, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,065] Trial 38 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 14, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,092] Trial 39 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 21, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,135] Trial 40 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 35, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,208] Trial 41 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 61, 'max_depth': 29}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,276] Trial 42 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 57, 'max_depth': 22}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,312] Trial 43 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 28, 'max_depth': 26}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,347] Trial 44 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 27, 'max_depth': 29}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,381] Trial 45 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 28, 'max_depth': 26}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,415] Trial 46 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 27, 'max_depth': 22}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,502] Trial 47 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 76, 'max_depth': 29}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,531] Trial 48 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 22, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,567] Trial 49 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 30, 'max_depth': 11}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,611] Trial 50 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 37, 'max_depth': 27}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,645] Trial 51 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 27, 'max_depth': 30}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,667] Trial 52 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 17, 'max_depth': 30}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,720] Trial 53 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 43, 'max_depth': 30}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:05,889] Trial 54 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 151, 'max_depth': 26}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,003] Trial 55 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 100, 'max_depth': 22}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,078] Trial 56 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 65, 'max_depth': 20}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,134] Trial 57 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 47, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,156] Trial 58 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 17, 'max_depth': 25}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,217] Trial 59 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 52, 'max_depth': 28}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,257] Trial 60 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 33, 'max_depth': 21}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,283] Trial 61 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 19, 'max_depth': 28}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,314] Trial 62 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 24, 'max_depth': 24}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,396] Trial 63 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 72, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,460] Trial 64 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 54, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,547] Trial 65 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 76, 'max_depth': 27}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,601] Trial 66 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 46, 'max_depth': 32}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,676] Trial 67 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 65, 'max_depth': 24}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,761] Trial 68 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 74, 'max_depth': 23}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,823] Trial 69 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 52, 'max_depth': 19}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,866] Trial 70 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 36, 'max_depth': 15}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,897] Trial 71 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 24, 'max_depth': 16}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:06,931] Trial 72 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 28, 'max_depth': 17}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,007] Trial 73 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 65, 'max_depth': 15}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,031] Trial 74 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 18, 'max_depth': 17}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,048] Trial 75 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 12, 'max_depth': 10}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,062] Trial 76 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 10, 'max_depth': 7}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,107] Trial 77 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 36, 'max_depth': 15}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,168] Trial 78 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 56, 'max_depth': 9}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,254] Trial 79 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 74, 'max_depth': 19}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,279] Trial 80 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 24, 'max_depth': 4}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,295] Trial 81 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 10, 'max_depth': 31}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,367] Trial 82 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 62, 'max_depth': 27}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,385] Trial 83 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 12, 'max_depth': 21}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,441] Trial 84 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 47, 'max_depth': 15}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,488] Trial 85 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 40, 'max_depth': 11}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,533] Trial 86 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 38, 'max_depth': 12}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,556] Trial 87 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 19, 'max_depth': 8}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,573] Trial 88 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 11, 'max_depth': 12}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,638] Trial 89 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 68, 'max_depth': 5}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,671] Trial 90 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 26, 'max_depth': 19}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,701] Trial 91 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 23, 'max_depth': 13}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,767] Trial 92 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 56, 'max_depth': 17}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,800] Trial 93 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 30, 'max_depth': 7}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,857] Trial 94 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 49, 'max_depth': 11}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,943] Trial 95 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 76, 'max_depth': 12}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:07,988] Trial 96 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 40, 'max_depth': 9}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:08,030] Trial 97 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 42, 'max_depth': 5}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:08,079] Trial 98 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 41, 'max_depth': 18}. Best is trial 15 with value: 0.5194805194805194.
[I 2026-10-19 14:48:08,140] Trial 99 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 51, 'max_depth': 30}. Best is trial 15 with value: 0.5194805194805194.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:48:08,158] A new study created in memory with name: no-name-a4c98f82-f128-453d-ad9c-cae4ad0a2446
[I 2026-10-19 14:48:08,162] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4025974025974026.
[I 2026-10-19 14:48:08,165] Trial 1 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 1 with value: 0.42857142857142855.
[I 2026-10-19 14:48:08,168] Trial 2 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,171] Trial 3 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.

0.01387786865234375  seconds
Classification report saved as results/Continent/data_7/data_7_lle_rf_classification_report.txt
    Accuracy: 0.3766, Time: 7.44s
  - Testing classifier: knn

[I 2026-10-19 14:48:08,358] Trial 57 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,362] Trial 58 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,366] Trial 59 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,370] Trial 60 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,374] Trial 61 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,379] Trial 62 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,383] Trial 63 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,387] Trial 64 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,391] Trial 65 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,395] Trial 66 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,398] Trial 67 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,403] Trial 68 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,406] Trial 69 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,409] Trial 70 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,413] Trial 71 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,417] Trial 72 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,421] Trial 73 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,425] Trial 74 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,429] Trial 75 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,433] Trial 76 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,437] Trial 77 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,441] Trial 78 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,444] Trial 79 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,448] Trial 80 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,452] Trial 81 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,456] Trial 82 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,459] Trial 83 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,464] Trial 84 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,467] Trial 85 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,471] Trial 86 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,474] Trial 87 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,478] Trial 88 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,482] Trial 89 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,486] Trial 90 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,490] Trial 91 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,494] Trial 92 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,498] Trial 93 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,502] Trial 94 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,506] Trial 95 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,511] Trial 96 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,514] Trial 97 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,519] Trial 98 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:48:08,523] Trial 99 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.5064935064935064.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:48:08,531] A new study created in memory with name: no-name-c9efcc3c-6610-452b-8660-d4cc919db5eb
[I 2026-10-19 14:48:08,607] Trial 0 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 75, 'learning_rate': 0.42165226979308457, 'max_depth': 31, 'min_child_weight': 6.139348782418182, 'subsample': 0.3379744012159489, 'colsample_bytree': 0.6740220198405142}. Best is trial 0 with value: 0.37662337662337664.
[I 2026-10-19 14:48:08,646] Trial 1 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 20, 'learning_rate': 0.6235379178500802, 'max_depth': 18, 'min_child_weight': 4.422277072724057, 'subsample': 0.886336181120994, 'colsample_bytree': 0.30001088648163843}. Best is trial 0 with value: 0.37662337662337664.

0.0022840499877929688  seconds
Classification report saved as results/Continent/data_7/data_7_lle_knn_classification_report.txt
    Accuracy: 0.5065, Time: 0.37s
  - Testing classifier: xgboost

[I 2026-10-19 14:48:08,831] Trial 2 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 168, 'learning_rate': 0.445115029803922, 'max_depth': 13, 'min_child_weight': 1.0953526269954055, 'subsample': 0.3361197028315164, 'colsample_bytree': 0.18936323651289577}. Best is trial 0 with value: 0.37662337662337664.
[I 2026-10-19 14:48:08,889] Trial 3 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 67, 'learning_rate': 0.8342746699893816, 'max_depth': 4, 'min_child_weight': 9.888328757697558, 'subsample': 0.920543743536758, 'colsample_bytree': 0.49975539589872575}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:08,931] Trial 4 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 36, 'learning_rate': 0.43027867712502227, 'max_depth': 29, 'min_child_weight': 5.244365778204807, 'subsample': 0.6010634866704708, 'colsample_bytree': 0.43180499715078835}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,049] Trial 5 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 183, 'learning_rate': 0.7974501900917482, 'max_depth': 12, 'min_child_weight': 9.865176540089388, 'subsample': 0.4489652520116346, 'colsample_bytree': 0.9564701718415389}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,135] Trial 6 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 172, 'learning_rate': 0.8689656737320878, 'max_depth': 5, 'min_child_weight': 8.871550953141977, 'subsample': 0.20154127781510406, 'colsample_bytree': 0.34823745953794083}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,224] Trial 7 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 147, 'learning_rate': 0.3282404102160749, 'max_depth': 9, 'min_child_weight': 3.420216364817442, 'subsample': 0.1141051093880639, 'colsample_bytree': 0.5977526210051937}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,326] Trial 8 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 117, 'learning_rate': 0.04079777677434816, 'max_depth': 8, 'min_child_weight': 8.413348872082851, 'subsample': 0.5054387521129263, 'colsample_bytree': 0.6159672536641708}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,412] Trial 9 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 107, 'learning_rate': 0.8689305245671115, 'max_depth': 8, 'min_child_weight': 9.68558537343132, 'subsample': 0.7680503973788236, 'colsample_bytree': 0.8360452671069722}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,499] Trial 10 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 88, 'learning_rate': 0.9311731702161238, 'max_depth': 8, 'min_child_weight': 3.2938137711109237, 'subsample': 0.9169341200720803, 'colsample_bytree': 0.7399828405904789}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,532] Trial 11 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 44, 'learning_rate': 0.847941028373125, 'max_depth': 2, 'min_child_weight': 9.950284797774097, 'subsample': 0.7458180838894136, 'colsample_bytree': 0.3155402739402201}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,593] Trial 12 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 59, 'learning_rate': 0.47022681592971416, 'max_depth': 5, 'min_child_weight': 9.69935489154452, 'subsample': 0.9867795771765222, 'colsample_bytree': 0.6656711468838292}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,667] Trial 13 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 86, 'learning_rate': 0.7090603482736803, 'max_depth': 15, 'min_child_weight': 9.596759385196583, 'subsample': 0.7218437411221063, 'colsample_bytree': 0.45884650154871753}. Best is trial 3 with value: 0.44155844155844154.
[I 2026-10-19 14:48:09,743] Trial 14 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 119, 'learning_rate': 0.8224503406777574, 'max_depth': 8, 'min_child_weight': 9.16780712020021, 'subsample': 0.34261149409784064, 'colsample_bytree': 0.4900329944440735}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:09,790] Trial 15 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 86, 'learning_rate': 0.8285579900276107, 'max_depth': 10, 'min_child_weight': 8.71698546089652, 'subsample': 0.16136262877503102, 'colsample_bytree': 0.6031100618711613}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:09,886] Trial 16 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 124, 'learning_rate': 0.6336361753462152, 'max_depth': 5, 'min_child_weight': 9.587461072124114, 'subsample': 0.6187361515313314, 'colsample_bytree': 0.35468037893401666}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:09,922] Trial 17 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 47, 'learning_rate': 0.8779372500829432, 'max_depth': 2, 'min_child_weight': 8.025876748451417, 'subsample': 0.8211825972224277, 'colsample_bytree': 0.5297998480509726}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:09,950] Trial 18 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 35, 'learning_rate': 0.7717724727812578, 'max_depth': 5, 'min_child_weight': 9.385729012130366, 'subsample': 0.35622041411558614, 'colsample_bytree': 0.4131859331246925}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,046] Trial 19 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 155, 'learning_rate': 0.8286799630642637, 'max_depth': 6, 'min_child_weight': 8.836128044434783, 'subsample': 0.31537749976745333, 'colsample_bytree': 0.6838921751108316}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,068] Trial 20 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 18, 'learning_rate': 0.7652487307101076, 'max_depth': 12, 'min_child_weight': 9.748004912779935, 'subsample': 0.6793340076484062, 'colsample_bytree': 0.5867711286365348}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,128] Trial 21 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 89, 'learning_rate': 0.9579443166117001, 'max_depth': 2, 'min_child_weight': 9.740221973366442, 'subsample': 0.9088998513868264, 'colsample_bytree': 0.3437137473000057}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,186] Trial 22 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 89, 'learning_rate': 0.44851555092969286, 'max_depth': 2, 'min_child_weight': 9.391470115362791, 'subsample': 0.3427171359743828, 'colsample_bytree': 0.5196660963667742}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,252] Trial 23 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 123, 'learning_rate': 0.5941948395958258, 'max_depth': 7, 'min_child_weight': 8.316879527431327, 'subsample': 0.1639284339006964, 'colsample_bytree': 0.5886210284134855}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,351] Trial 24 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 119, 'learning_rate': 0.015041471630397908, 'max_depth': 7, 'min_child_weight': 9.29105873428122, 'subsample': 0.47165051615260545, 'colsample_bytree': 0.5527628922683628}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,381] Trial 25 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 23, 'learning_rate': 0.8657175912439646, 'max_depth': 8, 'min_child_weight': 8.48083190569961, 'subsample': 0.868169040822328, 'colsample_bytree': 0.40389499596544026}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,452] Trial 26 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 101, 'learning_rate': 0.9314623950922971, 'max_depth': 4, 'min_child_weight': 8.22733510609251, 'subsample': 0.39485323338352063, 'colsample_bytree': 0.5841410048967797}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,536] Trial 27 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 128, 'learning_rate': 0.7309329322820727, 'max_depth': 13, 'min_child_weight': 8.863874053377538, 'subsample': 0.3480947380697425, 'colsample_bytree': 0.5744720221031548}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,590] Trial 28 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 70, 'learning_rate': 0.9514254834142837, 'max_depth': 5, 'min_child_weight': 9.70587488898721, 'subsample': 0.46704110587373937, 'colsample_bytree': 0.4999125134151746}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,655] Trial 29 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 94, 'learning_rate': 0.9797092460209358, 'max_depth': 11, 'min_child_weight': 9.053781419466853, 'subsample': 0.39902763051095136, 'colsample_bytree': 0.4638512868386305}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,701] Trial 30 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 51, 'learning_rate': 0.7987001645560613, 'max_depth': 11, 'min_child_weight': 9.993864051021426, 'subsample': 0.6237124737215651, 'colsample_bytree': 0.5326894918682527}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,784] Trial 31 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 110, 'learning_rate': 0.20001963105416898, 'max_depth': 3, 'min_child_weight': 7.8089739840614385, 'subsample': 0.3681002738177847, 'colsample_bytree': 0.5190710863728656}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,817] Trial 32 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 34, 'learning_rate': 0.8655992288655754, 'max_depth': 3, 'min_child_weight': 9.36085561772368, 'subsample': 0.9830168362247457, 'colsample_bytree': 0.432347486490463}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,892] Trial 33 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 105, 'learning_rate': 0.0459203650177783, 'max_depth': 16, 'min_child_weight': 9.617602254253763, 'subsample': 0.3657284485563933, 'colsample_bytree': 0.42208347304435}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:10,940] Trial 34 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 53, 'learning_rate': 0.8584532236144018, 'max_depth': 8, 'min_child_weight': 8.624997869039397, 'subsample': 0.5769307424928632, 'colsample_bytree': 0.6459172979645477}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,001] Trial 35 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 88, 'learning_rate': 0.8552077078686782, 'max_depth': 2, 'min_child_weight': 8.628265930484378, 'subsample': 0.6801921019702579, 'colsample_bytree': 0.4349748180436523}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,086] Trial 36 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 104, 'learning_rate': 0.12486029407709986, 'max_depth': 8, 'min_child_weight': 8.96706392888919, 'subsample': 0.45859854884821755, 'colsample_bytree': 0.45549836270046556}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,194] Trial 37 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 138, 'learning_rate': 0.12434648208197302, 'max_depth': 3, 'min_child_weight': 9.38388967986412, 'subsample': 0.5012022130228102, 'colsample_bytree': 0.7342281366740337}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,289] Trial 38 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 118, 'learning_rate': 0.09925594065268345, 'max_depth': 5, 'min_child_weight': 9.014069201711466, 'subsample': 0.3923492808352709, 'colsample_bytree': 0.33496179946166404}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,397] Trial 39 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 139, 'learning_rate': 0.17970693619471056, 'max_depth': 9, 'min_child_weight': 8.943390646419425, 'subsample': 0.4295033129251442, 'colsample_bytree': 0.506375923489079}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,516] Trial 40 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 147, 'learning_rate': 0.06807317328119877, 'max_depth': 7, 'min_child_weight': 8.246860767151972, 'subsample': 0.39854362971334434, 'colsample_bytree': 0.6536431904166182}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,593] Trial 41 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 127, 'learning_rate': 0.05648649394591314, 'max_depth': 6, 'min_child_weight': 9.244318178199212, 'subsample': 0.24376053024967265, 'colsample_bytree': 0.5004861219531489}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,732] Trial 42 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 126, 'learning_rate': 0.02681514738351623, 'max_depth': 7, 'min_child_weight': 6.559349966362185, 'subsample': 0.5943586854866605, 'colsample_bytree': 0.5609292537890912}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,853] Trial 43 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 139, 'learning_rate': 0.05124920576423616, 'max_depth': 8, 'min_child_weight': 8.530720175867422, 'subsample': 0.48856363510731426, 'colsample_bytree': 0.6920614657150028}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:11,891] Trial 44 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 38, 'learning_rate': 0.8889335490293611, 'max_depth': 5, 'min_child_weight': 9.656970744179329, 'subsample': 0.6749287431037317, 'colsample_bytree': 0.5627847798684478}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,009] Trial 45 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 164, 'learning_rate': 0.08983220173964812, 'max_depth': 6, 'min_child_weight': 8.53997922075582, 'subsample': 0.345372439096237, 'colsample_bytree': 0.5778131713411928}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,097] Trial 46 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 98, 'learning_rate': 0.11816448212517011, 'max_depth': 9, 'min_child_weight': 9.660790477702317, 'subsample': 0.5865567648152882, 'colsample_bytree': 0.5375516121881725}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,175] Trial 47 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 83, 'learning_rate': 0.032469939920481375, 'max_depth': 7, 'min_child_weight': 9.377971143013914, 'subsample': 0.5549657732546555, 'colsample_bytree': 0.6388064554459377}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,285] Trial 48 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 144, 'learning_rate': 0.05129859557752576, 'max_depth': 4, 'min_child_weight': 7.4027757412295445, 'subsample': 0.32120341825089954, 'colsample_bytree': 0.5581711968935102}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,354] Trial 49 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 109, 'learning_rate': 0.07777038949145959, 'max_depth': 8, 'min_child_weight': 9.834328314833732, 'subsample': 0.27779972286181814, 'colsample_bytree': 0.5842436540956083}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,429] Trial 50 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 102, 'learning_rate': 0.08378100698511745, 'max_depth': 6, 'min_child_weight': 8.891181577438157, 'subsample': 0.3383729248004242, 'colsample_bytree': 0.6402081051738416}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,511] Trial 51 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 121, 'learning_rate': 0.08694108825177291, 'max_depth': 2, 'min_child_weight': 8.357448159483893, 'subsample': 0.3963469372098656, 'colsample_bytree': 0.6885953693061551}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,661] Trial 52 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 173, 'learning_rate': 0.01976756794060639, 'max_depth': 10, 'min_child_weight': 7.811598318797236, 'subsample': 0.4404309488527981, 'colsample_bytree': 0.6948188982713595}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,798] Trial 53 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 170, 'learning_rate': 0.13493459863917917, 'max_depth': 4, 'min_child_weight': 8.528095755793526, 'subsample': 0.4412183283259138, 'colsample_bytree': 0.6924263766308635}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:12,920] Trial 54 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 144, 'learning_rate': 0.07954036941980604, 'max_depth': 8, 'min_child_weight': 8.47686062057707, 'subsample': 0.5064532746506938, 'colsample_bytree': 0.38747521838859317}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:13,023] Trial 55 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 110, 'learning_rate': 0.02678590153143208, 'max_depth': 5, 'min_child_weight': 8.653486552547129, 'subsample': 0.5357740577750969, 'colsample_bytree': 0.5896552671570554}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:13,138] Trial 56 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 132, 'learning_rate': 0.07712547546708279, 'max_depth': 9, 'min_child_weight': 8.70380378916776, 'subsample': 0.5114106209823064, 'colsample_bytree': 0.5980785893051955}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:48:13,233] Trial 57 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 135, 'learning_rate': 0.00926650675394207, 'max_depth': 7, 'min_child_weight': 9.09020364816873, 'subsample': 0.3217795574039203, 'colsample_bytree': 0.6272767953849261}. Best is trial 57 with value: 0.4805194805194805.
[I 2026-10-19 14:48:13,346] Trial 58 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 153, 'learning_rate': 0.12120023795643187, 'max_depth': 8, 'min_child_weight': 9.218513869755256, 'subsample': 0.3829104150166718, 'colsample_bytree': 0.6026934573597539}. Best is trial 57 with value: 0.4805194805194805.
[I 2026-10-19 14:48:13,435] Trial 59 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 123, 'learning_rate': 0.013253639176777156, 'max_depth': 10, 'min_child_weight': 8.32836679762454, 'subsample': 0.3003959773361124, 'colsample_bytree': 0.6320701266863665}. Best is trial 57 with value: 0.4805194805194805.
[I 2026-10-19 14:48:13,534] Trial 60 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 119, 'learning_rate': 0.022002949809426905, 'max_depth': 7, 'min_child_weight': 8.042600906683024, 'subsample': 0.3865851606811007, 'colsample_bytree': 0.6372743486509814}. Best is trial 57 with value: 0.4805194805194805.
[I 2026-10-19 14:48:13,622] Trial 61 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 149, 'learning_rate': 0.03860515717947248, 'max_depth': 9, 'min_child_weight': 8.84617251331171, 'subsample': 0.22167712469576445, 'colsample_bytree': 0.5891931836303401}. Best is trial 57 with value: 0.4805194805194805.

0.08993411064147949  seconds
Classification report saved as results/Continent/data_7/data_7_lle_xgboost_classification_report.txt
    Accuracy: 0.4805, Time: 8.94s
  - Testing classifier: svm

[I 2026-10-19 14:48:17,677] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,683] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,687] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,692] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,696] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,701] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,705] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,711] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,717] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,723] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,729] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,734] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,739] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,743] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,749] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,756] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,760] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,766] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,772] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,779] Trial 58 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,783] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,788] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,793] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,799] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,804] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,811] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,817] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,824] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,830] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,836] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,842] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,847] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,852] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,857] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,861] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,866] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,871] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,877] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,884] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,888] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,895] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,901] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,907] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,911] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,916] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,922] Trial 84 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,929] Trial 85 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,933] Trial 86 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,938] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,944] Trial 88 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,950] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,955] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,960] Trial 91 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,965] Trial 92 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,970] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,975] Trial 94 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,979] Trial 95 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,986] Trial 96 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,991] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:17,996] Trial 98 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:48:18,002] Trial 99 finished with value: 0.44155844155844154 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:48:18,012] A new study created in memory with name: no-name-720ed1a4-77fc-4564-8801-1705e69c4313
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:48:18,195] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 5, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0006826403885302483}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.004570484161376953  seconds
Classification report saved as results/Continent/data_7/data_7_lle_svm_classification_report.txt
    Accuracy: 0.4675, Time: 0.54s
  - Testing classifier: mlp

[I 2026-10-19 14:48:18,325] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 69, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.048917242839047505}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:49,126] Trial 2 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 87, 'n_neurons_layer1': 98, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 5.5060652493420885e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:49,453] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 58, 'n_neurons_layer1': 76, 'n_neurons_layer2': 36, 'activation': 'relu', 'solver': 'sgd', 'alpha': 7.07863841067149e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:48:50,048] Trial 4 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 71, 'n_neurons_layer1': 18, 'n_neurons_layer2': 75, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0007828130629244507}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:50,326] Trial 5 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 15, 'n_neurons_layer1': 32, 'n_neurons_layer2': 25, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.00019153111732546802}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:50,625] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 70, 'n_neurons_layer1': 74, 'n_neurons_layer2': 90, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.00014936050582276173}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:48:51,891] Trial 7 finished with value: 0.4155844155844156 and parameters: {'n_layers': 3, 'n_neurons_layer0': 100, 'n_neurons_layer1': 59, 'n_neurons_layer2': 84, 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.006184449806389985}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:52,075] Trial 8 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 48, 'n_neurons_layer1': 56, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0002629369753112001}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:48:52,286] Trial 9 finished with value: 0.4805194805194805 and parameters: {'n_layers': 1, 'n_neurons_layer0': 36, 'activation': 'identity', 'solver': 'adam', 'alpha': 2.0577632314499175e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:23,945] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 94, 'n_neurons_layer1': 97, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 2.2706790546872626e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:24,233] Trial 11 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 24, 'n_neurons_layer1': 3, 'n_neurons_layer2': 2, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.003239829628759685}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:24,421] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 1, 'n_neurons_layer1': 33, 'activation': 'logistic', 'solver': 'adam', 'alpha': 2.1763689186627673e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:24,554] Trial 13 finished with value: 0.4805194805194805 and parameters: {'n_layers': 1, 'n_neurons_layer0': 76, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00010384679218584166}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:24,790] Trial 14 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 37, 'n_neurons_layer1': 40, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.000767380914703967}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:49:25,460] Trial 15 finished with value: 0.42857142857142855 and parameters: {'n_layers': 3, 'n_neurons_layer0': 4, 'n_neurons_layer1': 99, 'n_neurons_layer2': 42, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 1.4176488294686617e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:49:25,726] Trial 16 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 86, 'n_neurons_layer1': 4, 'n_neurons_layer2': 1, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0006181344022559831}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:26,484] Trial 17 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 92, 'n_neurons_layer1': 1, 'n_neurons_layer2': 62, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00277318508935031}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:26,674] Trial 18 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 84, 'n_neurons_layer1': 2, 'n_neurons_layer2': 61, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0023927777190957096}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:49:27,030] Trial 19 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 82, 'n_neurons_layer1': 16, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.013809048739733206}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:49:27,363] Trial 20 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 60, 'n_neurons_layer1': 18, 'n_neurons_layer2': 5, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.010224102402734659}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:27,758] Trial 21 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 89, 'n_neurons_layer1': 1, 'n_neurons_layer2': 59, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0016986713641258403}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:28,013] Trial 22 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 59, 'n_neurons_layer1': 11, 'n_neurons_layer2': 64, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0008965948204133363}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:28,328] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 95, 'n_neurons_layer1': 1, 'n_neurons_layer2': 100, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.017548877304623088}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:28,625] Trial 24 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 76, 'n_neurons_layer1': 10, 'n_neurons_layer2': 55, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0002094535068741173}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:28,898] Trial 25 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 77, 'n_neurons_layer1': 26, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.001680648959828201}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:29,152] Trial 26 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 81, 'n_neurons_layer1': 8, 'n_neurons_layer2': 19, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.06997457941439549}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:29,284] Trial 27 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 73, 'n_neurons_layer1': 23, 'n_neurons_layer2': 46, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.0018574709000275169}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:49:29,583] Trial 28 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 93, 'n_neurons_layer1': 9, 'n_neurons_layer2': 67, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 2.182649882739962e-05}. Best is trial 16 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

{'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0006181344022559831, 'hidden_layer_sizes': [86, 4, 1]}
Classification report saved as results/Continent/data_7/data_7_lle_mlp_classification_report_2026-10-19_14-50-53.txt
    Accuracy: 0.4805, Time: 155.37s
  - Testing classifier: nb

[I 2026-10-19 14:50:53,480] Trial 45 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.3692812154018635e-12}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,482] Trial 46 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.832101214383841e-08}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,484] Trial 47 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.3118653670755923e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,487] Trial 48 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.469230986664745e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,489] Trial 49 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.1461338127508116e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,492] Trial 50 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.4455518659597633e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,494] Trial 51 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.4699076273668375e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,496] Trial 52 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 7.906524384595422e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,499] Trial 53 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.2498901283035278e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,501] Trial 54 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 8.889608771628252e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,504] Trial 55 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.4491013855213406e-08}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,506] Trial 56 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.815516742885845e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,508] Trial 57 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.025085317020697e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,511] Trial 58 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.1314454998450155e-12}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,513] Trial 59 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.782817125180599e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,515] Trial 60 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.2022368008755632e-08}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,518] Trial 61 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 7.847152744635936e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,520] Trial 62 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 7.733409685532859e-08}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,523] Trial 63 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.9535224739917313e-06}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,525] Trial 64 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.52005912188412e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,527] Trial 65 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.0208870725843638e-05}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,530] Trial 66 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 6.85316093990581e-05}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,532] Trial 67 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.5039949596974252e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,535] Trial 68 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.7396068708935916e-12}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,537] Trial 69 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.0368636524886855e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,540] Trial 70 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.302058234850618e-06}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,543] Trial 71 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.0009694814997042705}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,545] Trial 72 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.00012965033425251792}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,548] Trial 73 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.847175531846175e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,550] Trial 74 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.0687283458779272e-05}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,553] Trial 75 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.0005038420503763868}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,555] Trial 76 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.00591213081154358}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,558] Trial 77 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.016551144585998e-05}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,560] Trial 78 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.1015666491565238e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,563] Trial 79 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.7448292976350546e-06}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,566] Trial 80 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 8.024351632935924e-07}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,568] Trial 81 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.003342693366029671}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,571] Trial 82 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.0003496182623794007}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,573] Trial 83 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 0.00017287766896922408}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,576] Trial 84 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.3448630796316333e-05}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,578] Trial 85 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 9.76189983873823e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,581] Trial 86 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.2576975769578627e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,583] Trial 87 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 7.178457499328518e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,586] Trial 88 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.991895041121529e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,589] Trial 89 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 6.512407965589762e-06}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,591] Trial 90 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.037947576345831e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,594] Trial 91 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 6.63458246790577e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,596] Trial 92 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.671570143075641e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,599] Trial 93 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 7.079004744281513e-12}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,601] Trial 94 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.3148848322182876e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,604] Trial 95 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 4.013112277630734e-08}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,606] Trial 96 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.0013903762528872e-11}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,609] Trial 97 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 1.9575070727539413e-09}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,611] Trial 98 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 3.987034293022528e-10}. Best is trial 0 with value: 0.2597402597402597.
[I 2026-10-19 14:50:53,614] Trial 99 finished with value: 0.2597402597402597 and parameters: {'var_smoothing': 2.4166120485025504e-10}. Best is trial 0 with value: 0.2597402597402597.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 2.826391673447248e-10}
Best validation accuracy:  0.2597402597402597
Test accuracy: 0.2597402597402597
Time taken: 0.001325845718383789 seconds
Classification report saved as results/Continent/data_7/data_7_lle_nb_classification_report_2026-10-19_14-50-53.txt
    Accuracy: 0.2597, Time: 0.24s

Evaluating embedding method: umap

[I 2026-10-19 14:50:53,960] A new study created in memory with name: no-name-61861acf-d991-453f-b26a-508e6effbd5b
[I 2026-10-19 14:50:53,976] Trial 0 finished with value: 0.4675324675324675 and parameters: {'C': 3.7756906401488844e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7054918459280806}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:53,991] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 1.697068634476768e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5339156254289862}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,006] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 0.5697910646100102, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.43335017313677204}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,042] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 1.9368885870949446, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3641021847715463}. Best is trial 0 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 14:50:54,190] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 596.6106130638306, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04576725988940333}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,208] Trial 5 finished with value: 0.4675324675324675 and parameters: {'C': 6.030804675794768e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.22337087922980292}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,225] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 0.0002653380355923899, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.00383129201798893}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,242] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 1.0287834103904758e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19674812430766908}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,280] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 0.023130158340786532, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2312106468157521}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,298] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 0.01299516934386479, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.524616265597234}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,318] Trial 10 finished with value: 0.4675324675324675 and parameters: {'C': 3.1136115743374463e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8024493924205335}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,338] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 4.088910427524785e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5308878862787294}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,398] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 0.14613705607628175, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8132109275893445}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,419] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 0.0003941338079326562, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7502795325750349}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,438] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 4.393575838331151e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5503181514131061}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,455] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 4.090943836377281e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9076627388484003}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,472] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 1.9321728183333893e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7231523121111446}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,489] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 1.2390614415149884e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9614026782878613}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,516] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 281.1243748288645, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7998749775892168}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,537] Trial 19 finished with value: 0.4675324675324675 and parameters: {'C': 4.993170280446883e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5799736474667587}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,558] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 3.0265398839160125e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4332248673021254}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,579] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 0.0001682506637105526, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9577237626051648}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,730] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 10.931976561044051, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.539732995793788}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,751] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 0.0017217633611526307, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2036857401736557}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,771] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 1.6141502209322946e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5945168443026971}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,793] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 2.3047345243248654e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7398384567290184}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,814] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 0.0004082011804938537, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3373352609007717}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,835] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 1.5123180263407828e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6710083704302982}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,856] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 8.754784294836192e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.39220255154114775}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,887] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 29.060294865213713, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2664346527370408}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,919] Trial 30 finished with value: 0.4675324675324675 and parameters: {'C': 203.75512926966763, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.525199002517471}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,942] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.6162979928204463, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40758292930598194}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,965] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.9242120458460578, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7016162118884035}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:54,998] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 556.2190144577243, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10425917822203395}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,020] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 0.25108168650861445, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10530369286073532}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,204] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 27.853714894688572, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3320825906440444}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,225] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 0.05647303013617211, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.32455301087281013}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,247] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 4.558847266239296e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3686452475103285}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,267] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 6.069496587229537e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.17720336490299016}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,289] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.002549928987541023, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3665244630999427}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,311] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.0007679825067925567, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46325773589826963}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,462] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 14.794929538418295, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0005689901826696209}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,513] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 7.258472469324068, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.601868617030847}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,545] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 0.6787578679161301, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9063569401005602}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,697] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 43.727669490766814, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1035958226396716}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,719] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 2.2716881208781905e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4459096278837836}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,851] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.7166419341396524, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.017005214116495027}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,872] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 7.580729517057836e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.25073746402090014}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,892] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 1.183877415372682e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.41004988430789424}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:55,911] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 591.5711281673599, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3474962623604956}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,062] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 98.24010388562058, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4450311568869025}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,085] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 1.5689438405845023e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3366747150014434}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,108] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 4.051888204722347e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.41853486639501614}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,130] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 3.931968265419314e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21818984083600243}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,152] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 1.8068503737303888e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8867952742215047}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,173] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 552.9965527248156, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2565862451949015}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,194] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 1.4424236704443565e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1468717382222317}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,211] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 1.638275640471194e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16563568961950453}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,238] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 4.1959611775823635, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2792752451374506}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,255] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 5.7839500539580925e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.27403314065858975}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,272] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 2.569141069629261e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9044396846268932}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,293] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.00018113302904909594, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09523683821360038}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,334] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.001983944207064542, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01046348146366037}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,357] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 6.4312566528243075e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5138238222805049}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,510] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 169.2947738293249, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.17302699788453335}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,652] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 403.8262604334577, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.016460489176425737}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,674] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 5.706554020712217e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0849167777379263}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,786] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.043847793196417635, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01512819792576855}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,808] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 5.258857378155065e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7018811006673565}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,829] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 5.070097309346116e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01914803296967051}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,850] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 1.1741968733265217e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.012618337770372579}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,872] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.4585431976064693, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4645173828075615}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,893] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 1.7310108103203314e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21887600149022943}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:56,915] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 1.0154865471741314e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09819863275493525}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:57,067] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.8550247942600387, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.11642268817259122}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:57,088] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.007411125871252422, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5653962448178664}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:57,109] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 1.1612484997896832e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0008561035403690429}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:50:57,130] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 9.32322464574848e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26932305093694847}. Best is trial 0 with value: 0.4675324675324675.

0.0028221607208251953  seconds
Classification report saved as results/Continent/data_7/data_7_umap_logreg_classification_report.txt
    Accuracy: 0.4675, Time: 4.07s
  - Testing classifier: dt

[I 2026-10-19 14:50:58,227] Trial 64 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,230] Trial 65 finished with value: 0.33766233766233766 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,233] Trial 66 finished with value: 0.2077922077922078 and parameters: {'max_depth': 16, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,236] Trial 67 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,239] Trial 68 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,242] Trial 69 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,245] Trial 70 finished with value: 0.22077922077922077 and parameters: {'max_depth': 8, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,248] Trial 71 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,250] Trial 72 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,253] Trial 73 finished with value: 0.2987012987012987 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,256] Trial 74 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,259] Trial 75 finished with value: 0.2857142857142857 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,262] Trial 76 finished with value: 0.23376623376623376 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,265] Trial 77 finished with value: 0.18181818181818182 and parameters: {'max_depth': 23, 'criterion': 'gini'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,268] Trial 78 finished with value: 0.33766233766233766 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,271] Trial 79 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,273] Trial 80 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,276] Trial 81 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,279] Trial 82 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,282] Trial 83 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,284] Trial 84 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,288] Trial 85 finished with value: 0.22077922077922077 and parameters: {'max_depth': 25, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,290] Trial 86 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,293] Trial 87 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,296] Trial 88 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,299] Trial 89 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,301] Trial 90 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,304] Trial 91 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,307] Trial 92 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,310] Trial 93 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,313] Trial 94 finished with value: 0.33766233766233766 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,315] Trial 95 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,318] Trial 96 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,321] Trial 97 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,324] Trial 98 finished with value: 0.24675324675324675 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
[I 2026-10-19 14:50:58,327] Trial 99 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.45454545454545453.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:50:58,332] A new study created in memory with name: no-name-a69d04d4-cca1-420b-af8b-417617148639
[I 2026-10-19 14:50:58,368] Trial 0 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 44, 'max_depth': 6}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,498] Trial 1 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 147, 'max_depth': 26}. Best is trial 0 with value: 0.38961038961038963.

0.0009944438934326172  seconds
Classification report saved as results/Continent/data_7/data_7_umap_dt_classification_report.txt
    Accuracy: 0.4675, Time: 0.30s
  - Testing classifier: rf

[I 2026-10-19 14:50:58,578] Trial 2 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 93, 'max_depth': 11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,682] Trial 3 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 120, 'max_depth': 31}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,766] Trial 4 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 96, 'max_depth': 16}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,812] Trial 5 finished with value: 0.2727272727272727 and parameters: {'n_estimators': 53, 'max_depth': 11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,856] Trial 6 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 50, 'max_depth': 25}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,884] Trial 7 finished with value: 0.22077922077922077 and parameters: {'n_estimators': 31, 'max_depth': 31}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:58,921] Trial 8 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 45, 'max_depth': 8}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:59,059] Trial 9 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 160, 'max_depth': 21}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:50:59,160] Trial 10 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 136, 'max_depth': 3}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 14:50:59,265] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 147, 'max_depth': 2}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 14:50:59,370] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 146, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:50:59,517] Trial 13 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 194, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:50:59,601] Trial 14 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 117, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:50:59,673] Trial 15 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 97, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:50:59,826] Trial 16 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 182, 'max_depth': 11}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:50:59,933] Trial 17 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 133, 'max_depth': 8}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,065] Trial 18 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 165, 'max_depth': 8}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,169] Trial 19 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,254] Trial 20 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 107, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,345] Trial 21 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 122, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,467] Trial 22 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 162, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,587] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 172, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,751] Trial 24 finished with value: 0.2727272727272727 and parameters: {'n_estimators': 192, 'max_depth': 18}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:00,883] Trial 25 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 179, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,004] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 173, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,112] Trial 27 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,166] Trial 28 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 74, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,279] Trial 29 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 148, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,413] Trial 30 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 159, 'max_depth': 13}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,539] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 179, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,679] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 200, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,743] Trial 33 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 82, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,887] Trial 34 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 184, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:01,980] Trial 35 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 113, 'max_depth': 9}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,086] Trial 36 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 123, 'max_depth': 22}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,158] Trial 37 finished with value: 0.2727272727272727 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,189] Trial 38 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 38, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,307] Trial 39 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 168, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,475] Trial 40 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 200, 'max_depth': 12}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,593] Trial 41 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 150, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,695] Trial 42 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 134, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,758] Trial 43 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 74, 'max_depth': 9}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:02,890] Trial 44 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 171, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,018] Trial 45 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 181, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,133] Trial 46 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 159, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,163] Trial 47 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 31, 'max_depth': 28}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,288] Trial 48 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 151, 'max_depth': 10}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,382] Trial 49 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 133, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,542] Trial 50 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 200, 'max_depth': 8}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,682] Trial 51 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 196, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,810] Trial 52 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 173, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:03,892] Trial 53 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 114, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,036] Trial 54 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 176, 'max_depth': 9}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,178] Trial 55 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 188, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,312] Trial 56 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 190, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,465] Trial 57 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 200, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,615] Trial 58 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 185, 'max_depth': 9}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,697] Trial 59 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 108, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,759] Trial 60 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 69, 'max_depth': 30}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,873] Trial 61 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 154, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:04,992] Trial 62 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 167, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,111] Trial 63 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 155, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,221] Trial 64 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 141, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,372] Trial 65 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 177, 'max_depth': 29}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,513] Trial 66 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 200, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,616] Trial 67 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 141, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,754] Trial 68 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 168, 'max_depth': 10}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,847] Trial 69 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 119, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:05,974] Trial 70 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 175, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,101] Trial 71 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 181, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,237] Trial 72 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 185, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,350] Trial 73 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 160, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,420] Trial 74 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 97, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,526] Trial 75 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 142, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,673] Trial 76 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 200, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,729] Trial 77 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 68, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,851] Trial 78 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 168, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:06,974] Trial 79 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 174, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,106] Trial 80 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 175, 'max_depth': 5}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,216] Trial 81 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 155, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,338] Trial 82 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 164, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,431] Trial 83 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 127, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,529] Trial 84 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 137, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,637] Trial 85 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 149, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,790] Trial 86 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 194, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:07,888] Trial 87 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 131, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,021] Trial 88 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 184, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,149] Trial 89 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 161, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,288] Trial 90 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 176, 'max_depth': 7}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,369] Trial 91 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 112, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,461] Trial 92 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 129, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,549] Trial 93 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 117, 'max_depth': 4}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,719] Trial 94 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 198, 'max_depth': 29}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,808] Trial 95 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 123, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,908] Trial 96 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 128, 'max_depth': 6}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:08,983] Trial 97 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 103, 'max_depth': 2}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:09,081] Trial 98 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 120, 'max_depth': 8}. Best is trial 12 with value: 0.4675324675324675.
[I 2026-10-19 14:51:09,167] Trial 99 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 118, 'max_depth': 3}. Best is trial 12 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:51:09,273] A new study created in memory with name: no-name-c0fb9e39-4a5f-47f9-b907-1341568eae5e
[I 2026-10-19 14:51:09,275] Trial 0 finished with value: 0.23376623376623376 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.23376623376623376.
[I 2026-10-19 14:51:09,277] Trial 1 finished with value: 0.3246753246753247 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 1 with value: 0.3246753246753247.
[I 2026-10-19 14:51:09,279] Trial 2 finished with value: 0.2987012987012987 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.3246753246753247.
[I 2026-10-19 14:51:09,281] Trial 3 finished with value: 0.3246753246753247 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 1 with value: 0.3246753246753247.
[I 2026-10-19 14:51:09,283] Trial 4 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.

0.10115766525268555  seconds
Classification report saved as results/Continent/data_7/data_7_umap_rf_classification_report.txt
    Accuracy: 0.4416, Time: 10.94s
  - Testing classifier: knn

[I 2026-10-19 14:51:09,475] Trial 65 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,478] Trial 66 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,482] Trial 67 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,485] Trial 68 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,489] Trial 69 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,493] Trial 70 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,496] Trial 71 finished with value: 0.2987012987012987 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,500] Trial 72 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,503] Trial 73 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,507] Trial 74 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,510] Trial 75 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,513] Trial 76 finished with value: 0.3246753246753247 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,517] Trial 77 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,521] Trial 78 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,524] Trial 79 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,527] Trial 80 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,530] Trial 81 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,534] Trial 82 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,537] Trial 83 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,541] Trial 84 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,545] Trial 85 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,548] Trial 86 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,551] Trial 87 finished with value: 0.23376623376623376 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,554] Trial 88 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,558] Trial 89 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,562] Trial 90 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,566] Trial 91 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,570] Trial 92 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,574] Trial 93 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,578] Trial 94 finished with value: 0.2987012987012987 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,582] Trial 95 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,585] Trial 96 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,589] Trial 97 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,593] Trial 98 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 14:51:09,597] Trial 99 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 4 with value: 0.4155844155844156.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:51:09,603] A new study created in memory with name: no-name-f4bbf6e2-5986-4a00-bbf3-a8a1e9b6411a
[I 2026-10-19 14:51:09,636] Trial 0 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 35, 'learning_rate': 0.5516927629398488, 'max_depth': 23, 'min_child_weight': 2.465874130100969, 'subsample': 0.22426674790133141, 'colsample_bytree': 0.7773321694320176}. Best is trial 0 with value: 0.36363636363636365.
[I 2026-10-19 14:51:09,656] Trial 1 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 14, 'learning_rate': 0.8187585894752624, 'max_depth': 9, 'min_child_weight': 5.337536913975668, 'subsample': 0.9223190228840917, 'colsample_bytree': 0.23020106734721088}. Best is trial 0 with value: 0.36363636363636365.
[I 2026-10-19 14:51:09,732] Trial 2 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 116, 'learning_rate': 0.9696987748140798, 'max_depth': 26, 'min_child_weight': 8.63363766280754, 'subsample': 0.44577324785031824, 'colsample_bytree': 0.8143110651147436}. Best is trial 0 with value: 0.36363636363636365.

0.0015327930450439453  seconds
Classification report saved as results/Continent/data_7/data_7_umap_knn_classification_report.txt
    Accuracy: 0.4156, Time: 0.33s
  - Testing classifier: xgboost

[I 2026-10-19 14:51:09,904] Trial 3 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 164, 'learning_rate': 0.5862404626751141, 'max_depth': 27, 'min_child_weight': 4.454081819997398, 'subsample': 0.800362985957348, 'colsample_bytree': 0.8651236724811064}. Best is trial 0 with value: 0.36363636363636365.
[I 2026-10-19 14:51:09,941] Trial 4 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 69, 'learning_rate': 0.3561037576396457, 'max_depth': 32, 'min_child_weight': 4.509116706880228, 'subsample': 0.11074292705033822, 'colsample_bytree': 0.13775911196239513}. Best is trial 4 with value: 0.4025974025974026.
[I 2026-10-19 14:51:09,954] Trial 5 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 11, 'learning_rate': 0.9432949188262145, 'max_depth': 27, 'min_child_weight': 7.5623759125210945, 'subsample': 0.7670160664458325, 'colsample_bytree': 0.9570447405464675}. Best is trial 4 with value: 0.4025974025974026.
[I 2026-10-19 14:51:10,008] Trial 6 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 30, 'learning_rate': 0.12634565007451254, 'max_depth': 20, 'min_child_weight': 2.1576354489914342, 'subsample': 0.6688175881294698, 'colsample_bytree': 0.6487801533859696}. Best is trial 4 with value: 0.4025974025974026.
[I 2026-10-19 14:51:10,130] Trial 7 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 173, 'learning_rate': 0.7410136818568216, 'max_depth': 13, 'min_child_weight': 8.780018524728838, 'subsample': 0.5697660720256945, 'colsample_bytree': 0.21341403517219487}. Best is trial 4 with value: 0.4025974025974026.
[I 2026-10-19 14:51:10,211] Trial 8 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 159, 'learning_rate': 0.7347390128424027, 'max_depth': 24, 'min_child_weight': 6.909768950918919, 'subsample': 0.18535573146080075, 'colsample_bytree': 0.9420452131402851}. Best is trial 4 with value: 0.4025974025974026.
[I 2026-10-19 14:51:10,265] Trial 9 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 108, 'learning_rate': 0.821299939645361, 'max_depth': 26, 'min_child_weight': 6.179490053373445, 'subsample': 0.14849563383562045, 'colsample_bytree': 0.2510163271082992}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,363] Trial 10 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 113, 'learning_rate': 0.6825435228601161, 'max_depth': 32, 'min_child_weight': 6.92622511521207, 'subsample': 0.6439696204858394, 'colsample_bytree': 0.1745693967929992}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,434] Trial 11 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 89, 'learning_rate': 0.5928353110214328, 'max_depth': 28, 'min_child_weight': 3.7270387684836934, 'subsample': 0.25249262920559895, 'colsample_bytree': 0.3020526708536105}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,494] Trial 12 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 112, 'learning_rate': 0.39101691239679526, 'max_depth': 29, 'min_child_weight': 7.7068670828684285, 'subsample': 0.19043941335696338, 'colsample_bytree': 0.41015028901305156}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,516] Trial 13 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 34, 'learning_rate': 0.8916189662823728, 'max_depth': 26, 'min_child_weight': 7.292688485467914, 'subsample': 0.12970465774464163, 'colsample_bytree': 0.10055988144680413}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,568] Trial 14 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 95, 'learning_rate': 0.7744145456061895, 'max_depth': 19, 'min_child_weight': 4.472570941410971, 'subsample': 0.12449518038446782, 'colsample_bytree': 0.18782999584911142}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,641] Trial 15 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 134, 'learning_rate': 0.9488452524117219, 'max_depth': 26, 'min_child_weight': 4.77741404584971, 'subsample': 0.14078299019768253, 'colsample_bytree': 0.36773307913651554}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,730] Trial 16 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 153, 'learning_rate': 0.7974031252371874, 'max_depth': 22, 'min_child_weight': 2.4365737848405313, 'subsample': 0.10278302303344637, 'colsample_bytree': 0.3396258762918716}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,817] Trial 17 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 146, 'learning_rate': 0.972583044903959, 'max_depth': 25, 'min_child_weight': 7.765720738224891, 'subsample': 0.2882168976355848, 'colsample_bytree': 0.12619790408367298}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,914] Trial 18 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 169, 'learning_rate': 0.7704884371731974, 'max_depth': 30, 'min_child_weight': 6.534472812825779, 'subsample': 0.23649847776390298, 'colsample_bytree': 0.3919482233740982}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:10,978] Trial 19 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 135, 'learning_rate': 0.8179998541186697, 'max_depth': 19, 'min_child_weight': 7.172230484560565, 'subsample': 0.1119601580292009, 'colsample_bytree': 0.5078246368211237}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:11,037] Trial 20 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 118, 'learning_rate': 0.5124483805313798, 'max_depth': 22, 'min_child_weight': 5.599290501376483, 'subsample': 0.10450261305370637, 'colsample_bytree': 0.12919532455440563}. Best is trial 9 with value: 0.44155844155844154.
[I 2026-10-19 14:51:11,093] Trial 21 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 105, 'learning_rate': 0.910783347139299, 'max_depth': 18, 'min_child_weight': 5.76648241286767, 'subsample': 0.140064213488055, 'colsample_bytree': 0.5736597954036559}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,145] Trial 22 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 101, 'learning_rate': 0.975340582831045, 'max_depth': 29, 'min_child_weight': 5.531444988519487, 'subsample': 0.11322339838748292, 'colsample_bytree': 0.31846879181781385}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,236] Trial 23 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 115, 'learning_rate': 0.9541096161906865, 'max_depth': 30, 'min_child_weight': 3.22270985769054, 'subsample': 0.28702198127779516, 'colsample_bytree': 0.43197424297001696}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,306] Trial 24 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 139, 'learning_rate': 0.8947775292542816, 'max_depth': 16, 'min_child_weight': 4.668230568938023, 'subsample': 0.10285206682230384, 'colsample_bytree': 0.5168539218003481}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,354] Trial 25 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 90, 'learning_rate': 0.9457866049248685, 'max_depth': 27, 'min_child_weight': 4.7838437220797365, 'subsample': 0.10924748112159956, 'colsample_bytree': 0.48035666909707764}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,401] Trial 26 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 89, 'learning_rate': 0.9834094695437409, 'max_depth': 32, 'min_child_weight': 5.312063656465476, 'subsample': 0.10331703178903645, 'colsample_bytree': 0.5182173602448814}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,464] Trial 27 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 91, 'learning_rate': 0.9459100419581707, 'max_depth': 31, 'min_child_weight': 5.624173146113794, 'subsample': 0.3004431153355155, 'colsample_bytree': 0.207768297652874}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,504] Trial 28 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 72, 'learning_rate': 0.952474031997504, 'max_depth': 24, 'min_child_weight': 6.590900542609277, 'subsample': 0.13422144357907165, 'colsample_bytree': 0.6380415115634506}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,579] Trial 29 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 116, 'learning_rate': 0.814198172130671, 'max_depth': 24, 'min_child_weight': 6.149611218210804, 'subsample': 0.27157351612856356, 'colsample_bytree': 0.5314707400581424}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,649] Trial 30 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 90, 'learning_rate': 0.9251783379131471, 'max_depth': 13, 'min_child_weight': 4.6451090016177305, 'subsample': 0.32495941440626214, 'colsample_bytree': 0.5708876304174259}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,763] Trial 31 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 170, 'learning_rate': 0.8665023240307912, 'max_depth': 28, 'min_child_weight': 4.770992440218595, 'subsample': 0.27668783779024275, 'colsample_bytree': 0.44720848319499656}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,818] Trial 32 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 83, 'learning_rate': 0.7820995334469988, 'max_depth': 23, 'min_child_weight': 4.392451908135909, 'subsample': 0.16963637831805428, 'colsample_bytree': 0.6248802333701722}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,899] Trial 33 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 126, 'learning_rate': 0.9644642184937424, 'max_depth': 25, 'min_child_weight': 3.8072125802993413, 'subsample': 0.1917212753430468, 'colsample_bytree': 0.4765451926986023}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:11,943] Trial 34 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 74, 'learning_rate': 0.8146195803193159, 'max_depth': 29, 'min_child_weight': 5.306221983968706, 'subsample': 0.1454189806568364, 'colsample_bytree': 0.39166624729115895}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,042] Trial 35 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 149, 'learning_rate': 0.8688583354438045, 'max_depth': 23, 'min_child_weight': 5.239699160599376, 'subsample': 0.28205684711557655, 'colsample_bytree': 0.3718370077854479}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,109] Trial 36 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 117, 'learning_rate': 0.9728693636819497, 'max_depth': 15, 'min_child_weight': 5.656074082023286, 'subsample': 0.18105112647394422, 'colsample_bytree': 0.48293094786339674}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,172] Trial 37 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 120, 'learning_rate': 0.8175064878782401, 'max_depth': 27, 'min_child_weight': 4.972592028877331, 'subsample': 0.10950715155295321, 'colsample_bytree': 0.47378468843026667}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,236] Trial 38 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 112, 'learning_rate': 0.8558448513205317, 'max_depth': 21, 'min_child_weight': 5.335564140931871, 'subsample': 0.15291505748267575, 'colsample_bytree': 0.3183114149886317}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,308] Trial 39 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 118, 'learning_rate': 0.865754693266, 'max_depth': 25, 'min_child_weight': 4.414008259066151, 'subsample': 0.1702277442933097, 'colsample_bytree': 0.34317972614737197}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,398] Trial 40 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 163, 'learning_rate': 0.9712643720190557, 'max_depth': 30, 'min_child_weight': 5.061416737495859, 'subsample': 0.1583542001242666, 'colsample_bytree': 0.37197511119512305}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,461] Trial 41 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 113, 'learning_rate': 0.8297323887264012, 'max_depth': 26, 'min_child_weight': 5.906313680646284, 'subsample': 0.16817247290245618, 'colsample_bytree': 0.3612447211481481}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,528] Trial 42 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 109, 'learning_rate': 0.962172441747745, 'max_depth': 28, 'min_child_weight': 4.224409607628917, 'subsample': 0.15928797890645818, 'colsample_bytree': 0.5941427664662018}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,589] Trial 43 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 118, 'learning_rate': 0.862259727661711, 'max_depth': 31, 'min_child_weight': 5.804079591928218, 'subsample': 0.11803451423879234, 'colsample_bytree': 0.40639317834851996}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,644] Trial 44 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 110, 'learning_rate': 0.9204694603520699, 'max_depth': 22, 'min_child_weight': 7.004479385343947, 'subsample': 0.12513180176299524, 'colsample_bytree': 0.49916410568136366}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,717] Trial 45 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 130, 'learning_rate': 0.9542908859001957, 'max_depth': 30, 'min_child_weight': 4.449947830365735, 'subsample': 0.1405230622559966, 'colsample_bytree': 0.28499972980223104}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,764] Trial 46 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 76, 'learning_rate': 0.8620120522274047, 'max_depth': 29, 'min_child_weight': 4.116147068822371, 'subsample': 0.12486808748868616, 'colsample_bytree': 0.45678667053662525}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,828] Trial 47 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 99, 'learning_rate': 0.903111069182777, 'max_depth': 30, 'min_child_weight': 4.891937197577932, 'subsample': 0.20720453435167002, 'colsample_bytree': 0.39074268779756993}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,897] Trial 48 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 113, 'learning_rate': 0.9908606719350507, 'max_depth': 26, 'min_child_weight': 6.029194271281817, 'subsample': 0.22178895504518376, 'colsample_bytree': 0.318777357097765}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:12,971] Trial 49 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 126, 'learning_rate': 0.9461153224644726, 'max_depth': 20, 'min_child_weight': 4.637623921596738, 'subsample': 0.16421165679154345, 'colsample_bytree': 0.4345910000114634}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,043] Trial 50 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 148, 'learning_rate': 0.952800393004351, 'max_depth': 25, 'min_child_weight': 5.942373094919771, 'subsample': 0.10158446562558392, 'colsample_bytree': 0.28233338390679347}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,101] Trial 51 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 106, 'learning_rate': 0.9141221194326363, 'max_depth': 19, 'min_child_weight': 5.8075980153311155, 'subsample': 0.1497505795748524, 'colsample_bytree': 0.6563398847990025}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,188] Trial 52 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 146, 'learning_rate': 0.9622421649872592, 'max_depth': 24, 'min_child_weight': 5.3955009926655775, 'subsample': 0.20306376310186164, 'colsample_bytree': 0.23243731005439588}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,247] Trial 53 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 101, 'learning_rate': 0.8536685106076536, 'max_depth': 24, 'min_child_weight': 6.554179211213537, 'subsample': 0.19380474907515252, 'colsample_bytree': 0.20435724884160197}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,307] Trial 54 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 113, 'learning_rate': 0.8591245351707407, 'max_depth': 28, 'min_child_weight': 7.2275288710567445, 'subsample': 0.1553776805191488, 'colsample_bytree': 0.24032830585945986}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,383] Trial 55 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 142, 'learning_rate': 0.9193947876734079, 'max_depth': 22, 'min_child_weight': 6.366815525431565, 'subsample': 0.1702759492842662, 'colsample_bytree': 0.25531015276323904}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,446] Trial 56 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 104, 'learning_rate': 0.9609174269993825, 'max_depth': 26, 'min_child_weight': 4.685314276289778, 'subsample': 0.16346503477033156, 'colsample_bytree': 0.3383786731887848}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,524] Trial 57 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 140, 'learning_rate': 0.8142179577267962, 'max_depth': 25, 'min_child_weight': 6.155883882111226, 'subsample': 0.17766681998053643, 'colsample_bytree': 0.4397901117656936}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,578] Trial 58 finished with value: 0.24675324675324675 and parameters: {'n_estimators': 81, 'learning_rate': 0.9041602058268782, 'max_depth': 32, 'min_child_weight': 4.405038508257068, 'subsample': 0.17522049030042317, 'colsample_bytree': 0.5168719010418096}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,630] Trial 59 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 91, 'learning_rate': 0.9761031729031964, 'max_depth': 22, 'min_child_weight': 5.0876621778856945, 'subsample': 0.1328419312077778, 'colsample_bytree': 0.4259271926423991}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,719] Trial 60 finished with value: 0.2857142857142857 and parameters: {'n_estimators': 147, 'learning_rate': 0.8513268327185107, 'max_depth': 26, 'min_child_weight': 5.527096151719154, 'subsample': 0.21855750761927528, 'colsample_bytree': 0.27918865406857096}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,789] Trial 61 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 131, 'learning_rate': 0.9950528480736673, 'max_depth': 25, 'min_child_weight': 5.757627444507072, 'subsample': 0.14154282649923286, 'colsample_bytree': 0.42107136069057494}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:13,856] Trial 62 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 115, 'learning_rate': 0.8452947390505398, 'max_depth': 18, 'min_child_weight': 4.52396037674202, 'subsample': 0.14839906992190652, 'colsample_bytree': 0.49418047273665106}. Best is trial 21 with value: 0.4805194805194805.

0.05247950553894043  seconds
Classification report saved as results/Continent/data_7/data_7_umap_xgboost_classification_report.txt
    Accuracy: 0.3377, Time: 6.88s
  - Testing classifier: svm

[I 2026-10-19 14:51:16,679] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,685] Trial 47 finished with value: 0.4155844155844156 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,691] Trial 48 finished with value: 0.4025974025974026 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,696] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,700] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,704] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,708] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,712] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,716] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,719] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,723] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,728] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,732] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,736] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,740] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,744] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,748] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,753] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,759] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,762] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,766] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,770] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,775] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,779] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,784] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,790] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,796] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,800] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,806] Trial 74 finished with value: 0.4155844155844156 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,812] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,817] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,822] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,829] Trial 78 finished with value: 0.4155844155844156 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,833] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,838] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,844] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,851] Trial 82 finished with value: 0.4025974025974026 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,857] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,861] Trial 84 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,865] Trial 85 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,869] Trial 86 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,873] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,880] Trial 88 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,886] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,890] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,897] Trial 91 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,903] Trial 92 finished with value: 0.4155844155844156 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,909] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,914] Trial 94 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,919] Trial 95 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,924] Trial 96 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,928] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,933] Trial 98 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:51:16,937] Trial 99 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:51:16,946] A new study created in memory with name: no-name-c13a8cd7-de7a-479d-b2cc-90f6ade19286
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:17,019] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 85, 'n_neurons_layer1': 35, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.010382625517030526}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.003476858139038086  seconds
Classification report saved as results/Continent/data_7/data_7_umap_svm_classification_report.txt
    Accuracy: 0.4675, Time: 0.46s
  - Testing classifier: mlp

[I 2026-10-19 14:51:17,206] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 30, 'n_neurons_layer1': 38, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 9.170500868640715e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:17,415] Trial 2 finished with value: 0.45454545454545453 and parameters: {'n_layers': 1, 'n_neurons_layer0': 70, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.046560456977222595}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:17,553] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 26, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00013969058293274652}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:17,816] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 50, 'n_neurons_layer1': 12, 'n_neurons_layer2': 44, 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.011890185908252695}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:17,876] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 29, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0006442753342506762}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:18,152] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 18, 'n_neurons_layer1': 98, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.01846363090079663}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:18,517] Trial 7 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 15, 'n_neurons_layer1': 89, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.0030522929767150364}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:18,606] Trial 8 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 95, 'n_neurons_layer1': 64, 'activation': 'identity', 'solver': 'sgd', 'alpha': 3.2811052326797336e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:19,253] Trial 9 finished with value: 0.4155844155844156 and parameters: {'n_layers': 3, 'n_neurons_layer0': 68, 'n_neurons_layer1': 96, 'n_neurons_layer2': 7, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.0016733349061381876}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:19,345] Trial 10 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 79, 'n_neurons_layer1': 3, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0029888191427584363}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:19,366] Trial 11 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 98, 'n_neurons_layer1': 36, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09563910207442707}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:19,554] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 51, 'n_neurons_layer1': 37, 'n_neurons_layer2': 100, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 2.0044706478785652e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:19,699] Trial 13 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 39, 'n_neurons_layer1': 39, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0001662457775752739}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL: .

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:19,838] Trial 14 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 83, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0008027976435623635}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,106] Trial 15 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 94, 'n_neurons_layer1': 57, 'n_neurons_layer2': 100, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01677357728576525}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,174] Trial 16 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 15, 'n_neurons_layer1': 23, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 1.1360892335831479e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL: .

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:20,477] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 9, 'n_neurons_layer1': 60, 'n_neurons_layer2': 53, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00015379342995230298}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,620] Trial 18 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 55, 'n_neurons_layer1': 22, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.013409306748119094}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,730] Trial 19 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 46, 'n_neurons_layer1': 46, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00933834881456753}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,769] Trial 20 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 91, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0012765557168562837}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:20,895] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 38, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00021727671145287429}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:21,031] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 31, 'n_neurons_layer1': 70, 'activation': 'relu', 'solver': 'adam', 'alpha': 2.3568810261218436e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:21,295] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 69, 'n_neurons_layer1': 49, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 5.6024282014181767e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:51:21,513] Trial 24 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 12, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02912144422423749}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:51:21,722] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 6, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004034468894647754}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:51:21,945] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 32, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.024871676383829675}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:22,190] Trial 27 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 99, 'n_neurons_layer1': 24, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.000402730521368628}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:51:22,410] Trial 28 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 5, 'activation': 'relu', 'solver': 'adam', 'alpha': 7.28422727126808e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

{'activation': 'relu', 'solver': 'sgd', 'alpha': 0.010382625517030526, 'hidden_layer_sizes': [85, 35]}
Classification report saved as results/Continent/data_7/data_7_umap_mlp_classification_report_2026-10-19_14-51-33.txt
    Accuracy: 0.4675, Time: 16.77s
  - Testing classifier: nb

[I 2026-10-19 14:51:33,842] Trial 57 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 9.310792121333523e-12}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,845] Trial 58 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.2963365758227622e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,847] Trial 59 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.045978315814529e-07}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,849] Trial 60 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.2220393947327834e-11}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,852] Trial 61 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 2.2156804927342718e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,854] Trial 62 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 7.22967679531978e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,856] Trial 63 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.4470812734986618e-12}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,859] Trial 64 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 6.134724416101913e-11}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,861] Trial 65 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.5300759787053215e-11}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,863] Trial 66 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.6033207084509686e-09}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,866] Trial 67 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.0021815798059938024}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,868] Trial 68 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 7.948449881664829e-05}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,870] Trial 69 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.6862219822538297e-12}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,873] Trial 70 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.6276449360741603e-06}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,875] Trial 71 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.058173919258266e-09}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,878] Trial 72 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 4.164751558278433e-08}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,880] Trial 73 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 6.176618980608127e-07}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,882] Trial 74 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.6913148947572195e-07}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,885] Trial 75 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 2.3953091680656478e-08}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,887] Trial 76 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.3864657426373236e-08}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,890] Trial 77 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 6.0355768702151635e-12}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,892] Trial 78 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 6.021187687804522e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,894] Trial 79 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 6.80423503928405e-06}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,897] Trial 80 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.4750377437193812e-09}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,899] Trial 81 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 2.453948112828502e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,901] Trial 82 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 7.881684025683365e-11}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,904] Trial 83 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.2113808729996086e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,906] Trial 84 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 4.873602210014465e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,909] Trial 85 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.002754978132184297}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,911] Trial 86 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 2.7502054924526357e-11}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,914] Trial 87 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 2.098422899559916e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,916] Trial 88 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.044916485554762e-12}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,919] Trial 89 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 1.4053580146058546e-09}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,921] Trial 90 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.0006831100647000607}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,924] Trial 91 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.009029094175395306}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,926] Trial 92 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.0008028779966969576}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,928] Trial 93 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.004142939645761041}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,931] Trial 94 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 8.200553784403858e-08}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,933] Trial 95 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.00016505549355155287}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,936] Trial 96 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 0.00028712910896987046}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,938] Trial 97 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 4.931645362479058e-09}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,941] Trial 98 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 4.130700555900766e-10}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:33,943] Trial 99 finished with value: 0.4805194805194805 and parameters: {'var_smoothing': 3.585572701293975e-11}. Best is trial 0 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 3.6767299601945016e-08}
Best validation accuracy:  0.4805194805194805
Test accuracy: 0.4805194805194805
Time taken: 0.0011851787567138672 seconds
Classification report saved as results/Continent/data_7/data_7_umap_nb_classification_report_2026-10-19_14-51-33.txt
    Accuracy: 0.4805, Time: 0.23s

Evaluating embedding method: pca

[I 2026-10-19 14:51:35,245] A new study created in memory with name: no-name-ab3d8304-cdff-4dbc-aea5-321634bc5f06
[I 2026-10-19 14:51:35,262] Trial 0 finished with value: 0.4805194805194805 and parameters: {'C': 0.11929823189612401, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.31454964292776144}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,277] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 1.1472604514508812e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.34832773882821944}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,293] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 1.1331654320775484e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3588490164575542}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,308] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 0.022639249191743253, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8094091481148727}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,324] Trial 4 finished with value: 0.2597402597402597 and parameters: {'C': 0.012583303871715013, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.287551069926023}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,339] Trial 5 finished with value: 0.4675324675324675 and parameters: {'C': 3.704462630042975e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5007500653138802}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,354] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 0.0010850443956270026, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6221318162147563}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,370] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 6.85077770141007e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9285037783924193}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,385] Trial 8 finished with value: 0.24675324675324675 and parameters: {'C': 0.03298994964988334, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8195253659557995}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,400] Trial 9 finished with value: 0.33766233766233766 and parameters: {'C': 0.15320242013111252, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06362996434708423}. Best is trial 0 with value: 0.4805194805194805.

  - Testing classifier: logreg

[I 2026-10-19 14:51:35,922] Trial 10 finished with value: 0.45454545454545453 and parameters: {'C': 471.3745618902485, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18175961314077915}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:35,943] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 1.173560368537944e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5298971378819473}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,407] Trial 12 finished with value: 0.45454545454545453 and parameters: {'C': 69.42228103093022, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6626981440595252}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,426] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 1.0224077537168287e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.28593384531205984}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,487] Trial 14 finished with value: 0.3246753246753247 and parameters: {'C': 25.650874194576094, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4162680271312638}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,507] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 2.3091118373261627e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07669678795320861}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,528] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 1.4299020585766388e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1379901624760012}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,549] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 0.013681778472319255, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.38890467512568977}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,650] Trial 18 finished with value: 0.45454545454545453 and parameters: {'C': 5.147875579953518, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3136506053048699}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,671] Trial 19 finished with value: 0.4675324675324675 and parameters: {'C': 0.0001696489836762116, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18947265638216568}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,689] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 8.025451142129774e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5419339964525045}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,706] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 3.182133722488052e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.38773800019280213}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,722] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 1.1073174947009119e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3170310100888365}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,739] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 8.705219190502356e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2439560389395775}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,756] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 2.3462669079123395e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09932603648555166}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,783] Trial 25 finished with value: 0.45454545454545453 and parameters: {'C': 0.49259493429640855, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.17778581352942158}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,801] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 3.9468308270884755e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4171810014349096}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,817] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 0.0003627603308171991, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7467709202100327}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,834] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 0.009243537146707339, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5181993446571894}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,851] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 1.036447821778045e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.44818620167578804}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,867] Trial 30 finished with value: 0.4675324675324675 and parameters: {'C': 3.350232676828874e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07512557157973421}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,886] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.011425918739121032, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2526916114089491}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,906] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.17375595597288992, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9008020598431341}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,927] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 2.3441911249987942e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8125367132357557}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,948] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 7.924833736564206e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6401980121126754}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,969] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 1.9388743081221878e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6115473909811685}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:36,990] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 0.013589957620063306, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6351908449163249}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,011] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 0.14921595613578995, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.44103520951661485}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,032] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 0.0020535834906575123, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01792206428881038}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,054] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 1.0762016898690483e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.15575009630277514}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,075] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.004001794040565443, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9368576639485574}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,096] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 9.20939665617037e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.43397757045809876}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,117] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 4.096431414249547e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2857214147941329}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,139] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 6.4393915845057215e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7083647039776447}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,191] Trial 44 finished with value: 0.45454545454545453 and parameters: {'C': 1.296744233972627, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5298158079615976}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,213] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 1.8376408569695212e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5109374490851153}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,233] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 8.140763704806046e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9454965788797769}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,252] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 1.8097320605315862e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2142560896372877}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,272] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 7.568522937852873e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.24314652102091466}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,292] Trial 49 finished with value: 0.36363636363636365 and parameters: {'C': 0.2444980399929476, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26112174418761946}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,312] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 8.829295687540352e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.35492371790539123}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,333] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 6.98811404360962e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.37679405774288743}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,355] Trial 52 finished with value: 0.35064935064935066 and parameters: {'C': 1.6162712564862263, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6065430858789502}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,376] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 6.916935597383114e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.312805060918}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,498] Trial 54 finished with value: 0.45454545454545453 and parameters: {'C': 4.573765638414276, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7784180588599547}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,519] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 4.7554189896935645e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5292028900855564}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,538] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 9.157570804001222e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.700118206183976}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,558] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.0010442209161862768, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46704321065006293}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,575] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.007786882880417532, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8553026925033069}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,666] Trial 59 finished with value: 0.45454545454545453 and parameters: {'C': 2.9326972799377953, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9632745384381971}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,697] Trial 60 finished with value: 0.42857142857142855 and parameters: {'C': 0.40207246544930936, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.362106677754479}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,714] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.05081081315985146, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7216628373596435}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,731] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 4.452134496330722e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9731636825370656}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,749] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 8.866323460777873e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9791573473488384}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,766] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 8.708167152986323e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4950021186829208}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,783] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 7.914617282777422e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.30654858690897163}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,800] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 2.9615028320965715e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3664143859797924}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,818] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.0002596371101448502, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3331142131269775}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,900] Trial 68 finished with value: 0.45454545454545453 and parameters: {'C': 3.6496121061122935, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3668262668450549}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,921] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 9.766113564986991e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5783931540813328}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,943] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.005964576757358369, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19398146231410718}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,966] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 1.0417544346495906e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5405845743932393}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:37,985] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 4.00621202191831e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4290683828570622}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,006] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 7.059909491398308e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6335871752501272}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,028] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.03460729112793939, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.30481202630796195}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,048] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 8.866056485997505e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.47804286963824194}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,069] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 4.0451506817428995e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8256121809836199}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,090] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 1.7639161195675396e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6196797202154051}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,111] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 6.988150498248019e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5788937416897393}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,132] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 1.0747774084876554e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6505333960245887}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,153] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 9.595785302335964e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.42995753694269523}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,175] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 2.6697171180639227e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9319301284123716}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,237] Trial 82 finished with value: 0.45454545454545453 and parameters: {'C': 2.1908528465564716, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.25697746855126447}. Best is trial 0 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,259] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 5.22497398106417e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.27125294817303086}. Best is trial 0 with value: 0.4805194805194805.

0.015958786010742188  seconds
Classification report saved as results/Continent/data_14/data_14_pca_logreg_classification_report.txt
    Accuracy: 0.4805, Time: 3.39s
  - Testing classifier: dt

[I 2026-10-19 14:51:38,830] Trial 46 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,834] Trial 47 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,838] Trial 48 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,842] Trial 49 finished with value: 0.36363636363636365 and parameters: {'max_depth': 12, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,845] Trial 50 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,848] Trial 51 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,851] Trial 52 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,855] Trial 53 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,858] Trial 54 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 5 with value: 0.4805194805194805.
[I 2026-10-19 14:51:38,861] Trial 55 finished with value: 0.4935064935064935 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,865] Trial 56 finished with value: 0.35064935064935066 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,869] Trial 57 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,872] Trial 58 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,876] Trial 59 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,880] Trial 60 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,884] Trial 61 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,887] Trial 62 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,890] Trial 63 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,894] Trial 64 finished with value: 0.38961038961038963 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,897] Trial 65 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,901] Trial 66 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,905] Trial 67 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,910] Trial 68 finished with value: 0.4155844155844156 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,914] Trial 69 finished with value: 0.4025974025974026 and parameters: {'max_depth': 9, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,919] Trial 70 finished with value: 0.42857142857142855 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,925] Trial 71 finished with value: 0.42857142857142855 and parameters: {'max_depth': 29, 'criterion': 'log_loss'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,928] Trial 72 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,931] Trial 73 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,935] Trial 74 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,938] Trial 75 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,941] Trial 76 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,946] Trial 77 finished with value: 0.42857142857142855 and parameters: {'max_depth': 23, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,949] Trial 78 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,953] Trial 79 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,956] Trial 80 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,960] Trial 81 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,963] Trial 82 finished with value: 0.4935064935064935 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,967] Trial 83 finished with value: 0.4935064935064935 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,970] Trial 84 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,974] Trial 85 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,977] Trial 86 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,981] Trial 87 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,984] Trial 88 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,988] Trial 89 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,993] Trial 90 finished with value: 0.42857142857142855 and parameters: {'max_depth': 9, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:38,996] Trial 91 finished with value: 0.36363636363636365 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,000] Trial 92 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,005] Trial 93 finished with value: 0.36363636363636365 and parameters: {'max_depth': 14, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,008] Trial 94 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,012] Trial 95 finished with value: 0.36363636363636365 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,015] Trial 96 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,018] Trial 97 finished with value: 0.4935064935064935 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,022] Trial 98 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 55 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,027] Trial 99 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 55 with value: 0.4935064935064935.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:51:39,033] A new study created in memory with name: no-name-3063644e-a84c-4be8-89f5-fd9e6c15c652
[I 2026-10-19 14:51:39,048] Trial 0 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 14, 'max_depth': 6}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,132] Trial 1 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 76, 'max_depth': 31}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 14:51:39,167] Trial 2 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 32, 'max_depth': 10}. Best is trial 2 with value: 0.5064935064935064.

0.0017924308776855469  seconds
Classification report saved as results/Continent/data_14/data_14_pca_dt_classification_report.txt
    Accuracy: 0.4805, Time: 0.40s
  - Testing classifier: rf

[I 2026-10-19 14:51:39,277] Trial 3 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 141, 'max_depth': 2}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 14:51:39,298] Trial 4 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 19, 'max_depth': 25}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,334] Trial 5 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 37, 'max_depth': 6}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,358] Trial 6 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 23, 'max_depth': 9}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,445] Trial 7 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 82, 'max_depth': 32}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,488] Trial 8 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 40, 'max_depth': 19}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,584] Trial 9 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 90, 'max_depth': 32}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,782] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 188, 'max_depth': 25}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,836] Trial 11 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,958] Trial 12 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 117, 'max_depth': 14}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:39,986] Trial 13 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 24, 'max_depth': 24}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,002] Trial 14 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 12, 'max_depth': 31}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,075] Trial 15 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 69, 'max_depth': 14}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,128] Trial 16 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 48, 'max_depth': 28}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,186] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 63, 'max_depth': 5}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,290] Trial 18 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 98, 'max_depth': 22}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,487] Trial 19 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 190, 'max_depth': 16}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,590] Trial 20 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 98, 'max_depth': 21}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,670] Trial 21 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 75, 'max_depth': 26}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,742] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 67, 'max_depth': 28}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:40,874] Trial 23 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 126, 'max_depth': 29}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:41,031] Trial 24 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 151, 'max_depth': 19}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:41,141] Trial 25 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 105, 'max_depth': 25}. Best is trial 4 with value: 0.5194805194805194.
[I 2026-10-19 14:51:41,328] Trial 26 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 176, 'max_depth': 9}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:41,502] Trial 27 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 155, 'max_depth': 14}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:41,691] Trial 28 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 199, 'max_depth': 5}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:41,758] Trial 29 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 84, 'max_depth': 2}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:41,958] Trial 30 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 192, 'max_depth': 10}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,077] Trial 31 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 126, 'max_depth': 6}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,129] Trial 32 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 46, 'max_depth': 31}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,168] Trial 33 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 34, 'max_depth': 31}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,222] Trial 34 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 50, 'max_depth': 31}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,279] Trial 35 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 52, 'max_depth': 23}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,302] Trial 36 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 19, 'max_depth': 21}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,336] Trial 37 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 29, 'max_depth': 31}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,352] Trial 38 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 13, 'max_depth': 27}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,422] Trial 39 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 65, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,471] Trial 40 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 43, 'max_depth': 25}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,508] Trial 41 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 33, 'max_depth': 17}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,679] Trial 42 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 164, 'max_depth': 30}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,710] Trial 43 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 26, 'max_depth': 28}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:42,875] Trial 44 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 161, 'max_depth': 11}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,009] Trial 45 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 128, 'max_depth': 21}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,107] Trial 46 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 93, 'max_depth': 12}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,122] Trial 47 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 11, 'max_depth': 11}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,231] Trial 48 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 103, 'max_depth': 28}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,347] Trial 49 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 110, 'max_depth': 31}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,504] Trial 50 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 170, 'max_depth': 6}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,588] Trial 51 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 79, 'max_depth': 25}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,672] Trial 52 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 78, 'max_depth': 20}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,799] Trial 53 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 121, 'max_depth': 24}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:43,888] Trial 54 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 83, 'max_depth': 29}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,070] Trial 55 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 175, 'max_depth': 22}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,191] Trial 56 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,259] Trial 57 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 62, 'max_depth': 26}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,302] Trial 58 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 38, 'max_depth': 30}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,376] Trial 59 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 68, 'max_depth': 18}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,561] Trial 60 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 178, 'max_depth': 14}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,676] Trial 61 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 115, 'max_depth': 8}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,708] Trial 62 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 28, 'max_depth': 12}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,730] Trial 63 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 18, 'max_depth': 16}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,783] Trial 64 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 50, 'max_depth': 9}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,803] Trial 65 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 15, 'max_depth': 24}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,820] Trial 66 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 18, 'max_depth': 2}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,883] Trial 67 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 57, 'max_depth': 29}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,926] Trial 68 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 38, 'max_depth': 22}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:44,965] Trial 69 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 45, 'max_depth': 3}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,002] Trial 70 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 32, 'max_depth': 25}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,030] Trial 71 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 23, 'max_depth': 26}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,085] Trial 72 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 53, 'max_depth': 8}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,128] Trial 73 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 38, 'max_depth': 11}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,197] Trial 74 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 66, 'max_depth': 9}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,250] Trial 75 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 48, 'max_depth': 14}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,327] Trial 76 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 78, 'max_depth': 7}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,357] Trial 77 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 31, 'max_depth': 4}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,495] Trial 78 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 134, 'max_depth': 10}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,658] Trial 79 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 166, 'max_depth': 8}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,673] Trial 80 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 13, 'max_depth': 4}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,813] Trial 81 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 139, 'max_depth': 9}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,846] Trial 82 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 28, 'max_depth': 12}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:45,986] Trial 83 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 151, 'max_depth': 6}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,082] Trial 84 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 98, 'max_depth': 7}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,127] Trial 85 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 40, 'max_depth': 27}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,181] Trial 86 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 55, 'max_depth': 6}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,223] Trial 87 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 37, 'max_depth': 27}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,339] Trial 88 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 111, 'max_depth': 12}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,388] Trial 89 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 44, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,412] Trial 90 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 19, 'max_depth': 30}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,508] Trial 91 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 91, 'max_depth': 23}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,559] Trial 92 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 56, 'max_depth': 4}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,597] Trial 93 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 32, 'max_depth': 30}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,695] Trial 94 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 92, 'max_depth': 27}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,716] Trial 95 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 17, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,756] Trial 96 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 35, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,778] Trial 97 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 17, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,963] Trial 98 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 189, 'max_depth': 8}. Best is trial 26 with value: 0.5454545454545454.
[I 2026-10-19 14:51:46,978] Trial 99 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 10, 'max_depth': 32}. Best is trial 26 with value: 0.5454545454545454.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:51:47,154] A new study created in memory with name: no-name-fbe5f81e-4d44-45c7-a663-ed794edc9831
[I 2026-10-19 14:51:47,157] Trial 0 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:51:47,159] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:51:47,161] Trial 2 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:51:47,162] Trial 3 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:51:47,166] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:51:47,168] Trial 5 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 1 with value: 0.4675324675324675.

0.1726088523864746  seconds
Classification report saved as results/Continent/data_14/data_14_pca_rf_classification_report.txt
    Accuracy: 0.5195, Time: 8.12s
  - Testing classifier: knn

[I 2026-10-19 14:51:47,354] Trial 59 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,359] Trial 60 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,362] Trial 61 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,366] Trial 62 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,369] Trial 63 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,373] Trial 64 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,376] Trial 65 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,380] Trial 66 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,383] Trial 67 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,386] Trial 68 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,390] Trial 69 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,393] Trial 70 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,396] Trial 71 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,400] Trial 72 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,403] Trial 73 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,407] Trial 74 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,411] Trial 75 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,416] Trial 76 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,420] Trial 77 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,424] Trial 78 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,428] Trial 79 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,431] Trial 80 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,435] Trial 81 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,438] Trial 82 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,442] Trial 83 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,445] Trial 84 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,449] Trial 85 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,453] Trial 86 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,457] Trial 87 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,461] Trial 88 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,465] Trial 89 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,468] Trial 90 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,472] Trial 91 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,476] Trial 92 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,480] Trial 93 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,484] Trial 94 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,488] Trial 95 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,491] Trial 96 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,495] Trial 97 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,498] Trial 98 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
[I 2026-10-19 14:51:47,502] Trial 99 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 21 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:51:47,507] A new study created in memory with name: no-name-391326ef-6c46-4f2d-9f48-d3f46e29152b
[I 2026-10-19 14:51:47,642] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 191, 'learning_rate': 0.9129546037932769, 'max_depth': 9, 'min_child_weight': 4.027540719902069, 'subsample': 0.7575741907089154, 'colsample_bytree': 0.6913584028439032}. Best is trial 0 with value: 0.4025974025974026.

0.0014197826385498047  seconds
Classification report saved as results/Continent/data_14/data_14_pca_knn_classification_report.txt
    Accuracy: 0.4805, Time: 0.35s
  - Testing classifier: xgboost

[I 2026-10-19 14:51:47,798] Trial 1 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 95, 'learning_rate': 0.16803565892477618, 'max_depth': 10, 'min_child_weight': 2.4466406873452287, 'subsample': 0.9381008854530886, 'colsample_bytree': 0.37779989132151115}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 14:51:47,886] Trial 2 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 105, 'learning_rate': 0.5986385970404078, 'max_depth': 21, 'min_child_weight': 3.7824864598756247, 'subsample': 0.3166740339350195, 'colsample_bytree': 0.5188441599022813}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 14:51:47,914] Trial 3 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 39, 'learning_rate': 0.8672877745287458, 'max_depth': 2, 'min_child_weight': 8.78918420396004, 'subsample': 0.8164727031396553, 'colsample_bytree': 0.1508165691758867}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 14:51:48,016] Trial 4 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 115, 'learning_rate': 0.6484592296803356, 'max_depth': 26, 'min_child_weight': 5.952088137427106, 'subsample': 0.8516796172901993, 'colsample_bytree': 0.36200462776395603}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 14:51:48,124] Trial 5 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 94, 'learning_rate': 0.4746381511549573, 'max_depth': 9, 'min_child_weight': 1.85250255592265, 'subsample': 0.5708150129173359, 'colsample_bytree': 0.5897495503701806}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 14:51:48,229] Trial 6 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 84, 'learning_rate': 0.6057864065935479, 'max_depth': 21, 'min_child_weight': 1.1471747429743493, 'subsample': 0.7675735787990332, 'colsample_bytree': 0.36492281888420086}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:48,317] Trial 7 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 106, 'learning_rate': 0.9347194399223968, 'max_depth': 12, 'min_child_weight': 6.195085087376263, 'subsample': 0.8728473305771038, 'colsample_bytree': 0.8608551290300112}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:48,372] Trial 8 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 95, 'learning_rate': 0.06274621612377215, 'max_depth': 19, 'min_child_weight': 8.548115936497297, 'subsample': 0.21973372537168373, 'colsample_bytree': 0.3802342458804714}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:48,490] Trial 9 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 176, 'learning_rate': 0.5659230205550944, 'max_depth': 4, 'min_child_weight': 6.395166652580981, 'subsample': 0.2695232664238143, 'colsample_bytree': 0.8803730959028696}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:48,564] Trial 10 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 37, 'learning_rate': 0.48120684544398107, 'max_depth': 18, 'min_child_weight': 1.0605664101811823, 'subsample': 0.6414482401762506, 'colsample_bytree': 0.25641910775442756}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:48,889] Trial 11 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 136, 'learning_rate': 0.024321576640343567, 'max_depth': 11, 'min_child_weight': 2.7216233145681223, 'subsample': 0.9733661083493546, 'colsample_bytree': 0.200625965169281}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:49,008] Trial 12 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 88, 'learning_rate': 0.2905195089957826, 'max_depth': 6, 'min_child_weight': 4.225303656889872, 'subsample': 0.7563178176957763, 'colsample_bytree': 0.36803150722314193}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:49,094] Trial 13 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 53, 'learning_rate': 0.9984214248492892, 'max_depth': 15, 'min_child_weight': 1.1824212882217915, 'subsample': 0.611492664068727, 'colsample_bytree': 0.19752727845202706}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:49,215] Trial 14 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 65, 'learning_rate': 0.10173407140288068, 'max_depth': 29, 'min_child_weight': 1.6558517018980563, 'subsample': 0.5963844516480266, 'colsample_bytree': 0.3545336570231986}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:49,280] Trial 15 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 60, 'learning_rate': 0.9243721587735505, 'max_depth': 18, 'min_child_weight': 2.406758674964517, 'subsample': 0.9330380170874502, 'colsample_bytree': 0.514503352606}. Best is trial 6 with value: 0.5324675324675324.
[I 2026-10-19 14:51:49,379] Trial 16 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 89, 'learning_rate': 0.7822047206509702, 'max_depth': 20, 'min_child_weight': 1.970204579914048, 'subsample': 0.7276502538034437, 'colsample_bytree': 0.18070261701929308}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,486] Trial 17 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 111, 'learning_rate': 0.9167739594766376, 'max_depth': 20, 'min_child_weight': 1.9730634911004146, 'subsample': 0.7044285605178248, 'colsample_bytree': 0.1267642286637348}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,615] Trial 18 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 100, 'learning_rate': 0.4985488446170135, 'max_depth': 24, 'min_child_weight': 1.3505594369635028, 'subsample': 0.6366830413677805, 'colsample_bytree': 0.1187189806637691}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,692] Trial 19 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 54, 'learning_rate': 0.6497239863008641, 'max_depth': 21, 'min_child_weight': 2.296025204301353, 'subsample': 0.8494747395599974, 'colsample_bytree': 0.1365980901100445}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,792] Trial 20 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 92, 'learning_rate': 0.7738481656915005, 'max_depth': 14, 'min_child_weight': 1.4133037357523686, 'subsample': 0.475971434877309, 'colsample_bytree': 0.11577309936660979}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,858] Trial 21 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 52, 'learning_rate': 0.7208103747693297, 'max_depth': 24, 'min_child_weight': 3.479378262814894, 'subsample': 0.8151950289308642, 'colsample_bytree': 0.11594851818788568}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:49,936] Trial 22 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 73, 'learning_rate': 0.7188410369819873, 'max_depth': 23, 'min_child_weight': 2.3397349380431014, 'subsample': 0.5752006935462559, 'colsample_bytree': 0.26112390343703096}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,034] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 90, 'learning_rate': 0.7389544540284381, 'max_depth': 22, 'min_child_weight': 1.0315715984231395, 'subsample': 0.7371462649711714, 'colsample_bytree': 0.37492078986844357}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,088] Trial 24 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 38, 'learning_rate': 0.594429849196415, 'max_depth': 20, 'min_child_weight': 3.292021285113866, 'subsample': 0.8127346694225744, 'colsample_bytree': 0.25004044065000414}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,158] Trial 25 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 48, 'learning_rate': 0.48688884211190653, 'max_depth': 26, 'min_child_weight': 2.3618829468960385, 'subsample': 0.8075804161169796, 'colsample_bytree': 0.22829078294453858}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,262] Trial 26 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 99, 'learning_rate': 0.58545342181353, 'max_depth': 18, 'min_child_weight': 3.3440832374009397, 'subsample': 0.7381317528889623, 'colsample_bytree': 0.16592342814246408}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,364] Trial 27 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 88, 'learning_rate': 0.6249706904112844, 'max_depth': 19, 'min_child_weight': 1.4174150518297957, 'subsample': 0.7541636173630476, 'colsample_bytree': 0.25293957672886813}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,452] Trial 28 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 73, 'learning_rate': 0.5690309410339685, 'max_depth': 15, 'min_child_weight': 3.5676306678419887, 'subsample': 0.8722147780401354, 'colsample_bytree': 0.16699674874832968}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,563] Trial 29 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 112, 'learning_rate': 0.5852715330839284, 'max_depth': 25, 'min_child_weight': 2.0235939518060144, 'subsample': 0.6888896516969432, 'colsample_bytree': 0.5045738376234956}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,656] Trial 30 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 71, 'learning_rate': 0.7657248833263713, 'max_depth': 26, 'min_child_weight': 1.301807207639695, 'subsample': 0.7097620711663692, 'colsample_bytree': 0.17128016565260604}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,735] Trial 31 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 54, 'learning_rate': 0.7604332254927997, 'max_depth': 20, 'min_child_weight': 1.818835559864021, 'subsample': 0.9926349269612981, 'colsample_bytree': 0.1372301565122376}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,819] Trial 32 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 87, 'learning_rate': 0.8750351111303051, 'max_depth': 19, 'min_child_weight': 2.0918591036800938, 'subsample': 0.7436109112408706, 'colsample_bytree': 0.2766857599836126}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,904] Trial 33 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 87, 'learning_rate': 0.8164378065440179, 'max_depth': 24, 'min_child_weight': 2.730257575680937, 'subsample': 0.8261913296823883, 'colsample_bytree': 0.2042413667162265}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:50,979] Trial 34 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 69, 'learning_rate': 0.6964011503151384, 'max_depth': 18, 'min_child_weight': 3.4001952873372057, 'subsample': 0.8000546479677638, 'colsample_bytree': 0.2822271349143859}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,094] Trial 35 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 109, 'learning_rate': 0.6441543578439869, 'max_depth': 20, 'min_child_weight': 2.4059526875594592, 'subsample': 0.6903860270700014, 'colsample_bytree': 0.18462104619788303}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,173] Trial 36 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 65, 'learning_rate': 0.7981468064474705, 'max_depth': 25, 'min_child_weight': 2.832293707152008, 'subsample': 0.9675203513379275, 'colsample_bytree': 0.1470185244437256}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,279] Trial 37 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 83, 'learning_rate': 0.4790302473793581, 'max_depth': 19, 'min_child_weight': 2.642416409323352, 'subsample': 0.8168584658678913, 'colsample_bytree': 0.13350249564595548}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,357] Trial 38 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 56, 'learning_rate': 0.676908301713284, 'max_depth': 27, 'min_child_weight': 2.113045661127518, 'subsample': 0.7946128394726649, 'colsample_bytree': 0.17728541297240002}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,445] Trial 39 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 83, 'learning_rate': 0.715859919951193, 'max_depth': 15, 'min_child_weight': 3.3864603026917726, 'subsample': 0.7026954169425577, 'colsample_bytree': 0.10876805887027209}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,529] Trial 40 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 80, 'learning_rate': 0.7918973341599373, 'max_depth': 18, 'min_child_weight': 1.8252444360170939, 'subsample': 0.7989312455253748, 'colsample_bytree': 0.4394585377226015}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,638] Trial 41 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 104, 'learning_rate': 0.710861401400318, 'max_depth': 20, 'min_child_weight': 2.4666704648524638, 'subsample': 0.7405005777359999, 'colsample_bytree': 0.16402196627980614}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,737] Trial 42 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 101, 'learning_rate': 0.6803884173120157, 'max_depth': 19, 'min_child_weight': 2.9046689371961234, 'subsample': 0.802627867180518, 'colsample_bytree': 0.28081045130274795}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,833] Trial 43 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 63, 'learning_rate': 0.6516345102784552, 'max_depth': 17, 'min_child_weight': 1.0956182221838762, 'subsample': 0.8101691409177579, 'colsample_bytree': 0.14264654758285283}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:51,947] Trial 44 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 102, 'learning_rate': 0.6619879127187042, 'max_depth': 17, 'min_child_weight': 2.4204325904753925, 'subsample': 0.8962108684125658, 'colsample_bytree': 0.1448768798502661}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:52,046] Trial 45 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 102, 'learning_rate': 0.8065942753303528, 'max_depth': 23, 'min_child_weight': 3.070052055642906, 'subsample': 0.7144812150242481, 'colsample_bytree': 0.1418226293063009}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:52,120] Trial 46 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 66, 'learning_rate': 0.7398941687715451, 'max_depth': 20, 'min_child_weight': 3.2281729015462317, 'subsample': 0.6302302051271859, 'colsample_bytree': 0.19336147138007795}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:52,234] Trial 47 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 106, 'learning_rate': 0.6649231454413428, 'max_depth': 25, 'min_child_weight': 2.1794492055181935, 'subsample': 0.7210348883514495, 'colsample_bytree': 0.11518614411746772}. Best is trial 16 with value: 0.5584415584415584.
[I 2026-10-19 14:51:52,338] Trial 48 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 97, 'learning_rate': 0.6028306127169321, 'max_depth': 16, 'min_child_weight': 3.3274627939863137, 'subsample': 0.7658892623298711, 'colsample_bytree': 0.1423150507785249}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,428] Trial 49 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 64, 'learning_rate': 0.6141212236357315, 'max_depth': 20, 'min_child_weight': 1.0478594874466771, 'subsample': 0.7220134421140795, 'colsample_bytree': 0.21452622477225114}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,515] Trial 50 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 60, 'learning_rate': 0.6522839783355474, 'max_depth': 21, 'min_child_weight': 1.879025860038038, 'subsample': 0.9639435669941346, 'colsample_bytree': 0.1897532286388537}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,612] Trial 51 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 88, 'learning_rate': 0.7127493274763439, 'max_depth': 19, 'min_child_weight': 2.811788573082705, 'subsample': 0.7836726935209126, 'colsample_bytree': 0.1053046063433207}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,715] Trial 52 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 94, 'learning_rate': 0.5395250160054331, 'max_depth': 18, 'min_child_weight': 3.1082777291518053, 'subsample': 0.6094868150116252, 'colsample_bytree': 0.15051915380696707}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,821] Trial 53 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 101, 'learning_rate': 0.5816855347017829, 'max_depth': 16, 'min_child_weight': 3.3825776968498067, 'subsample': 0.7094151022500214, 'colsample_bytree': 0.1859969104654178}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:52,906] Trial 54 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 87, 'learning_rate': 0.6829206073790074, 'max_depth': 19, 'min_child_weight': 3.534777654199692, 'subsample': 0.7120589093716977, 'colsample_bytree': 0.20223428261355567}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,005] Trial 55 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 100, 'learning_rate': 0.6031068549049038, 'max_depth': 18, 'min_child_weight': 3.2310975182814463, 'subsample': 0.7620403235146438, 'colsample_bytree': 0.2065007663976944}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,112] Trial 56 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 98, 'learning_rate': 0.8066200728375486, 'max_depth': 23, 'min_child_weight': 1.7423042639037527, 'subsample': 0.8141511462474834, 'colsample_bytree': 0.1789243784424927}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,231] Trial 57 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 84, 'learning_rate': 0.5463819988199925, 'max_depth': 20, 'min_child_weight': 1.185598843250947, 'subsample': 0.7233193832842775, 'colsample_bytree': 0.15571621652154322}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,315] Trial 58 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 79, 'learning_rate': 0.8353464737759944, 'max_depth': 21, 'min_child_weight': 3.197215120163411, 'subsample': 0.7673901279474152, 'colsample_bytree': 0.12910773270727147}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,407] Trial 59 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 74, 'learning_rate': 0.6938064626907304, 'max_depth': 18, 'min_child_weight': 2.17451082963935, 'subsample': 0.802333198026574, 'colsample_bytree': 0.11544419942669051}. Best is trial 48 with value: 0.5714285714285714.
[I 2026-10-19 14:51:53,527] Trial 60 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 123, 'learning_rate': 0.7721814353726939, 'max_depth': 16, 'min_child_weight': 3.0096958920885313, 'subsample': 0.7131242334993846, 'colsample_bytree': 0.17783058022277448}. Best is trial 48 with value: 0.5714285714285714.

0.09682154655456543  seconds
Classification report saved as results/Continent/data_14/data_14_pca_xgboost_classification_report.txt
    Accuracy: 0.4675, Time: 10.15s
  - Testing classifier: svm

[I 2026-10-19 14:51:57,856] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,863] Trial 35 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,869] Trial 36 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,876] Trial 37 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,882] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,888] Trial 39 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,895] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,901] Trial 41 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,907] Trial 42 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,914] Trial 43 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,921] Trial 44 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,927] Trial 45 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,934] Trial 46 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,941] Trial 47 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,948] Trial 48 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,954] Trial 49 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,960] Trial 50 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,967] Trial 51 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,973] Trial 52 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,980] Trial 53 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,986] Trial 54 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,992] Trial 55 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:57,997] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,003] Trial 57 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,010] Trial 58 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,017] Trial 59 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,023] Trial 60 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,031] Trial 61 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,038] Trial 62 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,044] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,051] Trial 64 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,057] Trial 65 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,064] Trial 66 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,070] Trial 67 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,077] Trial 68 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,084] Trial 69 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,089] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,096] Trial 71 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,103] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,109] Trial 73 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,116] Trial 74 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,123] Trial 75 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,129] Trial 76 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,136] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,143] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,149] Trial 79 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,156] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,162] Trial 81 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,169] Trial 82 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,175] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,182] Trial 84 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,189] Trial 85 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,195] Trial 86 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,202] Trial 87 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,209] Trial 88 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,216] Trial 89 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,223] Trial 90 finished with value: 0.4805194805194805 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,230] Trial 91 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,236] Trial 92 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,242] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,248] Trial 94 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,255] Trial 95 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,260] Trial 96 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,267] Trial 97 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,273] Trial 98 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
[I 2026-10-19 14:51:58,279] Trial 99 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 5 with value: 0.4935064935064935.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:51:58,289] A new study created in memory with name: no-name-8b9f4513-1295-4a69-b3de-42a063bf5cd8
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.004785776138305664  seconds
Classification report saved as results/Continent/data_14/data_14_pca_svm_classification_report.txt
    Accuracy: 0.4935, Time: 0.63s
  - Testing classifier: mlp

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:51:58,772] Trial 0 finished with value: 0.38961038961038963 and parameters: {'n_layers': 2, 'n_neurons_layer0': 54, 'n_neurons_layer1': 24, 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.052979186111889814}. Best is trial 0 with value: 0.38961038961038963.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:51:59,128] Trial 1 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 70, 'n_neurons_layer1': 7, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.09036864707399946}. Best is trial 1 with value: 0.45454545454545453.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:51:59,252] Trial 2 finished with value: 0.4805194805194805 and parameters: {'n_layers': 1, 'n_neurons_layer0': 7, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 7.417252352391886e-05}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:00,130] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 66, 'n_neurons_layer1': 82, 'n_neurons_layer2': 47, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0017401174948622016}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:00,909] Trial 4 finished with value: 0.5064935064935064 and parameters: {'n_layers': 3, 'n_neurons_layer0': 49, 'n_neurons_layer1': 86, 'n_neurons_layer2': 64, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.05502878602015328}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:01,104] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 24, 'n_neurons_layer1': 17, 'n_neurons_layer2': 64, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.009532374325024993}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:01,200] Trial 6 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 50, 'n_neurons_layer1': 80, 'n_neurons_layer2': 50, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.003219718042646679}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:52:02,342] Trial 7 finished with value: 0.42857142857142855 and parameters: {'n_layers': 3, 'n_neurons_layer0': 73, 'n_neurons_layer1': 68, 'n_neurons_layer2': 53, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.04211639837590771}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:02,470] Trial 8 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 74, 'n_neurons_layer1': 47, 'n_neurons_layer2': 80, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0867973170627102}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:02,682] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 25, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.004979758152042827}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:03,240] Trial 10 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 93, 'n_neurons_layer1': 46, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003445453352931398}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:03,350] Trial 11 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 89, 'n_neurons_layer1': 98, 'n_neurons_layer2': 96, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.024965982329835025}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:03,986] Trial 12 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 45, 'n_neurons_layer1': 43, 'n_neurons_layer2': 87, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.07847062133130518}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:52:04,430] Trial 13 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 48, 'n_neurons_layer1': 53, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.014472589961993644}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:04,618] Trial 14 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 82, 'n_neurons_layer1': 96, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.009774591669375419}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:04,766] Trial 15 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 43, 'n_neurons_layer1': 64, 'n_neurons_layer2': 17, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0890791833571188}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:05,130] Trial 16 finished with value: 0.4025974025974026 and parameters: {'n_layers': 2, 'n_neurons_layer0': 31, 'n_neurons_layer1': 34, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0021558519606328097}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:52:05,368] Trial 17 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 44, 'n_neurons_layer1': 66, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.09626270037408913}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:52:06,088] Trial 18 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 16, 'n_neurons_layer1': 83, 'n_neurons_layer2': 77, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.08785741710300884}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:06,715] Trial 19 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 53, 'n_neurons_layer1': 31, 'n_neurons_layer2': 74, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.020583508595386383}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:07,367] Trial 20 finished with value: 0.44155844155844154 and parameters: {'n_layers': 3, 'n_neurons_layer0': 92, 'n_neurons_layer1': 4, 'n_neurons_layer2': 31, 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0053525508702077194}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:08,096] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 78, 'n_neurons_layer1': 44, 'n_neurons_layer2': 98, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.020334676021144513}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:08,646] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 5, 'n_neurons_layer1': 51, 'n_neurons_layer2': 82, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.010323326930428109}. Best is trial 4 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:52:09,278] Trial 23 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 31, 'n_neurons_layer1': 58, 'n_neurons_layer2': 86, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.029243785268116718}. Best is trial 4 with value: 0.5064935064935064.

{'activation': 'relu', 'solver': 'adam', 'alpha': 0.05502878602015328, 'hidden_layer_sizes': [49, 86, 64]}

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:52:39,532] A new study created in memory with name: no-name-92f83a9d-3342-4961-ae1c-be94fce70801
[I 2026-10-19 14:52:39,534] Trial 0 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.068428759802488e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,535] Trial 1 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.25620780249668e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,537] Trial 2 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.8591489103865443e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,538] Trial 3 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.003375321669893681}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,540] Trial 4 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.9245014637721136e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,541] Trial 5 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.320265068751468e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,542] Trial 6 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.091235090749422e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,544] Trial 7 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.0001948373264490723}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,545] Trial 8 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.260966692383081e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,546] Trial 9 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.6545861686521845e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,549] Trial 10 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.127815133769198e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,551] Trial 11 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.459644335083509e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,553] Trial 12 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.642343399157546e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,555] Trial 13 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 8.390852765608029e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,557] Trial 14 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.08231252863864e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,560] Trial 15 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.8228615255325475e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,562] Trial 16 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.003483320787871941}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,564] Trial 17 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.0526115428278347e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,566] Trial 18 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.096542143937356e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,568] Trial 19 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.625109809757663e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,571] Trial 20 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.00014161609110014244}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,573] Trial 21 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.291976449491471e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,575] Trial 22 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 9.767207530837373e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,578] Trial 23 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.222273117638397e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,581] Trial 24 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.0019378101443378e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,584] Trial 25 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.2315947847102828e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,586] Trial 26 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 9.380512709056332e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,589] Trial 27 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.055182067741731e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,592] Trial 28 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.843971357234556e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,594] Trial 29 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.835650652588948e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,597] Trial 30 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.970004118722798e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,600] Trial 31 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.00487504732863079}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,603] Trial 32 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.0006617748703898598}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,605] Trial 33 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.528966416004541e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,607] Trial 34 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.6197709411031125e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,610] Trial 35 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.3424007700171234e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,612] Trial 36 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.00035694772680969244}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,614] Trial 37 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.2727089728946493e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,616] Trial 38 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.0013762082002423493}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,619] Trial 39 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.2567823413195293e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,621] Trial 40 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.2461909217527465e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,624] Trial 41 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.9459564057983015e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,626] Trial 42 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.789745551235953e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,629] Trial 43 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.2562157033854384e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,631] Trial 44 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.9405652536267827e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,634] Trial 45 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.154433619965336e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,637] Trial 46 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.4580836739517935e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,639] Trial 47 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.25271890216389e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,642] Trial 48 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.9174435662047784e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,644] Trial 49 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.4906958119719854e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,646] Trial 50 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.008642519592407236}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,649] Trial 51 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.131080523936148e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,652] Trial 52 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 8.998200789932122e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,654] Trial 53 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.7624712980039285e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,657] Trial 54 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.7140392762337639e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,660] Trial 55 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 9.72864534164019e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,662] Trial 56 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.441563749273688e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,665] Trial 57 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.281502492538733e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,668] Trial 58 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.6535090219539365e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,671] Trial 59 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.2813006013239906e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,673] Trial 60 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 8.137211876059423e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,676] Trial 61 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.992736534320444e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,679] Trial 62 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.1416540255500783e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,681] Trial 63 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.3662978520877692e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,684] Trial 64 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.9579125238072543e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,687] Trial 65 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.5303983879419965e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,690] Trial 66 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.1718550727814251e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,693] Trial 67 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.0750880781852141e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,695] Trial 68 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.0461984112359903e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,698] Trial 69 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.928767431184339e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,701] Trial 70 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.3001487269864472e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,704] Trial 71 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.729780315419738e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,707] Trial 72 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.2969964382036955e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,709] Trial 73 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.001864724198214495}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,712] Trial 74 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.000251276411493734}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,715] Trial 75 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.0006595010747107174}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,717] Trial 76 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.864324252310396e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,720] Trial 77 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.7167919673288418e-05}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,723] Trial 78 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.489522670788348e-07}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,725] Trial 79 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.003501045840815999}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,728] Trial 80 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.120498793678388e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,731] Trial 81 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 4.311811824557216e-12}. Best is trial 0 with value: 0.4675324675324675.

Classification report saved as results/Continent/data_14/data_14_pca_mlp_classification_report_2026-10-19_14-52-39.txt
    Accuracy: 0.3766, Time: 41.24s
  - Testing classifier: nb

[I 2026-10-19 14:52:39,734] Trial 82 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.6520079733201773e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,737] Trial 83 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.2254265522411578e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,739] Trial 84 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.2464749846046542e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,742] Trial 85 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.1889149730322255e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,745] Trial 86 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 6.0516187777798504e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,748] Trial 87 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 5.380661471810298e-06}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,750] Trial 88 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.009445900926434945}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,753] Trial 89 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.101368578740068e-12}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,756] Trial 90 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.00022861230327241648}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,759] Trial 91 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.373949447822566e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,761] Trial 92 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.4166775024170976e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,764] Trial 93 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 1.448372333982651e-10}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,767] Trial 94 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 2.5932599604195873e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,770] Trial 95 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 0.0012791962385442297}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,773] Trial 96 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 9.321991599920132e-08}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,775] Trial 97 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 7.820802290568406e-11}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,778] Trial 98 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.174180805867628e-09}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:52:39,781] Trial 99 finished with value: 0.4675324675324675 and parameters: {'var_smoothing': 3.382352539804878e-10}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 2.068428759802488e-11}
Best validation accuracy:  0.4675324675324675
Test accuracy: 0.4675324675324675
Time taken: 0.0013079643249511719 seconds
Classification report saved as results/Continent/data_14/data_14_pca_nb_classification_report_2026-10-19_14-52-39.txt
    Accuracy: 0.4675, Time: 0.25s

Evaluating embedding method: lle

[I 2026-10-19 14:52:40,571] A new study created in memory with name: no-name-10637831-7fe8-4897-abf9-83c8a2e7c40a
[I 2026-10-19 14:52:40,587] Trial 0 finished with value: 0.22077922077922077 and parameters: {'C': 11.042470547372094, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2544102741255938}. Best is trial 0 with value: 0.22077922077922077.
[I 2026-10-19 14:52:40,603] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 0.052424516082052695, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3746251398424887}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,618] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 5.401123709209776e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.35110019585053154}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,634] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 4.405077130324028e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8861730007599301}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,650] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 7.811754520677827e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7172582824656023}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,666] Trial 5 finished with value: 0.23376623376623376 and parameters: {'C': 33.93918403284467, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3083211121120766}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,684] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 0.0008216668536263197, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.38283561925617837}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,701] Trial 7 finished with value: 0.4025974025974026 and parameters: {'C': 0.7769533156356837, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.986210177163391}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,719] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 0.00013951040306869149, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7087892363185364}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,737] Trial 9 finished with value: 0.2727272727272727 and parameters: {'C': 0.0022558248802427407, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1426958181354453}. Best is trial 1 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 14:52:40,778] Trial 10 finished with value: 0.38961038961038963 and parameters: {'C': 15.409543274142942, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7324254035012102}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,798] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 2.7009057338321813e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2785760402889138}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,818] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 3.862699289838262e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4879645567481882}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,838] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 2.234547496324188e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5953145005433552}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,855] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 1.774689698334796e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.00596753372189146}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,872] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 1.1970948776972427e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.33823028270542266}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,893] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 0.05797417257510373, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4389901665095282}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:40,914] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 5.0552737510110453e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16667268865086837}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,016] Trial 18 finished with value: 0.37662337662337664 and parameters: {'C': 604.2419403643987, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0017470859900013957}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,188] Trial 19 finished with value: 0.36363636363636365 and parameters: {'C': 876.5096563743124, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.37103489319873345}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,209] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 0.07302294421100461, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6614257899472328}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,230] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 1.326448437634978e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.940413267057859}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,250] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 0.05895827379251847, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5769813577612862}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,271] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 2.1378343120915596e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5007851418359299}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,292] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 7.137259680340249e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9495984411662574}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,313] Trial 25 finished with value: 0.2727272727272727 and parameters: {'C': 0.0023610776260526564, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8456198422128045}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,334] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 1.6071752075858318e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.415888504245495}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,355] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 6.353436908353487e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.13702986647541343}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,375] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 1.8168460003271156e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6363398799809548}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,396] Trial 29 finished with value: 0.4025974025974026 and parameters: {'C': 17.505580903243644, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19630446930622408}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,417] Trial 30 finished with value: 0.4675324675324675 and parameters: {'C': 0.5361720504880688, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2234610180833916}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,437] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 8.690374789869598e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4974993456124166}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,458] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 2.98909794621453e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8148468158296824}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,480] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 7.596499771528403e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7351382626469704}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,500] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 8.748794902430092e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7462894604817139}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,518] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 6.935508284990944e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9897127109445324}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,539] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 0.05818231947808578, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06647810448139135}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,559] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 6.515602819806383e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9508976051813175}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,580] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 3.168789135347544e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2096200313749026}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,601] Trial 39 finished with value: 0.2727272727272727 and parameters: {'C': 0.0020358693516379592, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2856593084059438}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,623] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 6.780096991997338e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.34224080331995466}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,645] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.0001804624905795023, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4633987761648886}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,666] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 1.025797091829733e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2013909469646361}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,687] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 6.891237295025371e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5607988378799631}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,709] Trial 44 finished with value: 0.2727272727272727 and parameters: {'C': 0.0021409295057702752, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3529448553294273}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,731] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 0.3934075743399985, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.428593290655939}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,752] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.0002774087991168713, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5692493593192122}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,773] Trial 47 finished with value: 0.45454545454545453 and parameters: {'C': 1.9495900667541493, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5306242070549124}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,795] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 7.295095935849126e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8359288583274305}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,816] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 1.0968304666896466e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7918420547235753}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,837] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.5674367264406142, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.33552234319028595}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,858] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.00035861477895454013, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8565784129102822}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,879] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.00021055749153015707, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6265662422320054}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,900] Trial 53 finished with value: 0.2727272727272727 and parameters: {'C': 0.0003834342461384346, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7703635045291276}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,921] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.032891196997436825, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3520969665417436}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,939] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 5.049021503898765e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8893446370622095}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,955] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 1.3508106814193283e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6666655055572763}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,972] Trial 57 finished with value: 0.2727272727272727 and parameters: {'C': 0.0021291495800350242, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6367153641408934}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:41,990] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 8.918803338213174e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3979886930004033}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,007] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.0004901129626628175, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9909946362676927}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,024] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.001835738943597147, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7285217889779881}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,042] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 1.8509929531478696e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2888972843730694}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,062] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.00010806092258351968, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.23169910806520438}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,083] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 6.31214940830225e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8951816868042078}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,100] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 4.154296786256187e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.275586510723091}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,117] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 1.5623269047219417e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5999359601196994}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,138] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 0.006560716049752476, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.47347752531421894}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,159] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 2.596732031828123e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.43762448860231484}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,180] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 4.957500059500863e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3435247647526605}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,201] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 6.38774449562807e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6551119499643592}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,222] Trial 70 finished with value: 0.2727272727272727 and parameters: {'C': 0.0053131444132125906, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.22561403754586806}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,242] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 8.872028814123468e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6802300393849444}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,262] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 1.2465742785428547e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2685961264320985}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,283] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 4.7159398649458124e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3191209202737829}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,304] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 1.6068251385766574e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46475937481410684}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,326] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 2.543342959957664e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5984217136223803}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,347] Trial 76 finished with value: 0.2727272727272727 and parameters: {'C': 0.0003863783877310497, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9453478821577693}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,368] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 1.759278073623236e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40454220945246633}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,389] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 2.583171023891735e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16328628415561805}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,410] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 1.3691172279472966e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3883664757107018}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,431] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.005015786309159707, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9295218453695543}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,452] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 8.039741857619312e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7328766592396811}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,473] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 1.2274231568011037e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6787582819236128}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:52:42,495] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 7.474949011064553e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5560170092242005}. Best is trial 1 with value: 0.4675324675324675.

0.002666473388671875  seconds
Classification report saved as results/Continent/data_14/data_14_lle_logreg_classification_report.txt
    Accuracy: 0.4675, Time: 2.27s
  - Testing classifier: dt

[I 2026-10-19 14:52:43,046] Trial 45 finished with value: 0.3116883116883117 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,050] Trial 46 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,055] Trial 47 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,058] Trial 48 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,063] Trial 49 finished with value: 0.36363636363636365 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,069] Trial 50 finished with value: 0.3116883116883117 and parameters: {'max_depth': 32, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,072] Trial 51 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,075] Trial 52 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,080] Trial 53 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,084] Trial 54 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,088] Trial 55 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,093] Trial 56 finished with value: 0.33766233766233766 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,098] Trial 57 finished with value: 0.35064935064935066 and parameters: {'max_depth': 21, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,102] Trial 58 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,105] Trial 59 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,110] Trial 60 finished with value: 0.37662337662337664 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,113] Trial 61 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,116] Trial 62 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,121] Trial 63 finished with value: 0.3116883116883117 and parameters: {'max_depth': 9, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,126] Trial 64 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,130] Trial 65 finished with value: 0.37662337662337664 and parameters: {'max_depth': 9, 'criterion': 'gini'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,134] Trial 66 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,138] Trial 67 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,142] Trial 68 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,148] Trial 69 finished with value: 0.33766233766233766 and parameters: {'max_depth': 30, 'criterion': 'log_loss'}. Best is trial 15 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,151] Trial 70 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,155] Trial 71 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,159] Trial 72 finished with value: 0.37662337662337664 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,163] Trial 73 finished with value: 0.36363636363636365 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,167] Trial 74 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,170] Trial 75 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,173] Trial 76 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,176] Trial 77 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,179] Trial 78 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,183] Trial 79 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,186] Trial 80 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,190] Trial 81 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,193] Trial 82 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,196] Trial 83 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,199] Trial 84 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,203] Trial 85 finished with value: 0.44155844155844154 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,206] Trial 86 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,210] Trial 87 finished with value: 0.37662337662337664 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,214] Trial 88 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,218] Trial 89 finished with value: 0.4155844155844156 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,221] Trial 90 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,224] Trial 91 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,228] Trial 92 finished with value: 0.45454545454545453 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,231] Trial 93 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,234] Trial 94 finished with value: 0.44155844155844154 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,237] Trial 95 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,241] Trial 96 finished with value: 0.38961038961038963 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,245] Trial 97 finished with value: 0.44155844155844154 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,248] Trial 98 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
[I 2026-10-19 14:52:43,251] Trial 99 finished with value: 0.4935064935064935 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 70 with value: 0.4935064935064935.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:52:43,257] A new study created in memory with name: no-name-66f1c861-d9fe-46e9-8a9a-6b58b4bb42da

0.0015196800231933594  seconds
Classification report saved as results/Continent/data_14/data_14_lle_dt_classification_report.txt
    Accuracy: 0.4935, Time: 0.41s
  - Testing classifier: rf

[I 2026-10-19 14:52:43,462] Trial 0 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 184, 'max_depth': 27}. Best is trial 0 with value: 0.44155844155844154.
[I 2026-10-19 14:52:43,612] Trial 1 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 137, 'max_depth': 24}. Best is trial 1 with value: 0.45454545454545453.
[I 2026-10-19 14:52:43,712] Trial 2 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 94, 'max_depth': 9}. Best is trial 1 with value: 0.45454545454545453.
[I 2026-10-19 14:52:43,872] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 148, 'max_depth': 14}. Best is trial 3 with value: 0.4675324675324675.
[I 2026-10-19 14:52:43,980] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 100, 'max_depth': 28}. Best is trial 3 with value: 0.4675324675324675.
[I 2026-10-19 14:52:44,117] Trial 5 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 128, 'max_depth': 27}. Best is trial 3 with value: 0.4675324675324675.
[I 2026-10-19 14:52:44,134] Trial 6 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 16, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,165] Trial 7 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 29, 'max_depth': 10}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,177] Trial 8 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 10, 'max_depth': 31}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,196] Trial 9 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 16, 'max_depth': 19}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,315] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 152, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,466] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 175, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,497] Trial 12 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 37, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,586] Trial 13 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 81, 'max_depth': 14}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,654] Trial 14 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 67, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,778] Trial 15 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 126, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:44,868] Trial 16 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 115, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,080] Trial 17 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 196, 'max_depth': 18}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,249] Trial 18 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 159, 'max_depth': 11}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,375] Trial 19 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 116, 'max_depth': 15}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,450] Trial 20 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 67, 'max_depth': 20}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,577] Trial 21 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 155, 'max_depth': 3}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,703] Trial 22 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 153, 'max_depth': 3}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,840] Trial 23 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 144, 'max_depth': 6}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,853] Trial 24 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 10, 'max_depth': 6}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:45,933] Trial 25 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 90, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,131] Trial 26 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 190, 'max_depth': 10}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,286] Trial 27 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 199, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,324] Trial 28 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 39, 'max_depth': 5}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,490] Trial 29 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 169, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,502] Trial 30 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 11, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,657] Trial 31 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,841] Trial 32 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 164, 'max_depth': 25}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:46,862] Trial 33 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 15, 'max_depth': 15}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,014] Trial 34 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 140, 'max_depth': 10}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,210] Trial 35 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 176, 'max_depth': 15}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,285] Trial 36 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 67, 'max_depth': 10}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,317] Trial 37 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 27, 'max_depth': 24}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,511] Trial 38 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 195, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,632] Trial 39 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 112, 'max_depth': 12}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,772] Trial 40 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 180, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:47,880] Trial 41 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 123, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,019] Trial 42 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 179, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,149] Trial 43 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 167, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,253] Trial 44 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 133, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,398] Trial 45 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 187, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,577] Trial 46 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 197, 'max_depth': 5}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,685] Trial 47 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 108, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,818] Trial 48 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 126, 'max_depth': 10}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:48,978] Trial 49 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 185, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,037] Trial 50 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 52, 'max_depth': 12}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,197] Trial 51 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 176, 'max_depth': 5}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,230] Trial 52 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 27, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,338] Trial 53 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 96, 'max_depth': 20}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,493] Trial 54 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 153, 'max_depth': 8}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,633] Trial 55 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 162, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,794] Trial 56 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 147, 'max_depth': 20}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:49,850] Trial 57 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 51, 'max_depth': 9}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,039] Trial 58 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 186, 'max_depth': 8}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,241] Trial 59 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 186, 'max_depth': 23}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,311] Trial 60 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 62, 'max_depth': 26}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,351] Trial 61 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 33, 'max_depth': 28}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,396] Trial 62 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 39, 'max_depth': 28}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,422] Trial 63 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 25, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,496] Trial 64 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 65, 'max_depth': 27}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,524] Trial 65 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 22, 'max_depth': 27}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,584] Trial 66 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 52, 'max_depth': 25}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,665] Trial 67 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 72, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,803] Trial 68 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 125, 'max_depth': 19}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,857] Trial 69 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 59, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:50,993] Trial 70 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 174, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,028] Trial 71 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 28, 'max_depth': 17}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,079] Trial 72 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 44, 'max_depth': 14}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,218] Trial 73 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 152, 'max_depth': 5}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,243] Trial 74 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 19, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,330] Trial 75 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 78, 'max_depth': 19}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,464] Trial 76 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 121, 'max_depth': 25}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,569] Trial 77 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 94, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,648] Trial 78 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 99, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,669] Trial 79 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 16, 'max_depth': 9}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,782] Trial 80 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 146, 'max_depth': 2}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:51,910] Trial 81 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 133, 'max_depth': 6}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,000] Trial 82 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 81, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,180] Trial 83 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 165, 'max_depth': 27}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,252] Trial 84 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 63, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,281] Trial 85 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 25, 'max_depth': 7}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,326] Trial 86 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 38, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,424] Trial 87 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 89, 'max_depth': 26}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,569] Trial 88 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 132, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,629] Trial 89 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 52, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,782] Trial 90 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 139, 'max_depth': 16}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:52,930] Trial 91 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 179, 'max_depth': 3}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,070] Trial 92 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 137, 'max_depth': 8}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,106] Trial 93 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 32, 'max_depth': 8}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,146] Trial 94 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 33, 'max_depth': 26}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,272] Trial 95 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 145, 'max_depth': 4}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,329] Trial 96 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 50, 'max_depth': 30}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,462] Trial 97 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 121, 'max_depth': 32}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,580] Trial 98 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 106, 'max_depth': 28}. Best is trial 6 with value: 0.4805194805194805.
[I 2026-10-19 14:52:53,747] Trial 99 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 152, 'max_depth': 29}. Best is trial 6 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:52:53,768] A new study created in memory with name: no-name-6e74b614-c666-49a7-bfb5-f9221c74fa83
[I 2026-10-19 14:52:53,770] Trial 0 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:52:53,772] Trial 1 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 1 with value: 0.42857142857142855.
[I 2026-10-19 14:52:53,774] Trial 2 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 1 with value: 0.42857142857142855.

0.016351699829101562  seconds
Classification report saved as results/Continent/data_14/data_14_lle_rf_classification_report.txt
    Accuracy: 0.4026, Time: 10.51s
  - Testing classifier: knn

[I 2026-10-19 14:52:53,970] Trial 61 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,975] Trial 62 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,978] Trial 63 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,983] Trial 64 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,988] Trial 65 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,992] Trial 66 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:53,996] Trial 67 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,000] Trial 68 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,004] Trial 69 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,008] Trial 70 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,011] Trial 71 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,015] Trial 72 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,018] Trial 73 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,021] Trial 74 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,025] Trial 75 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,028] Trial 76 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,032] Trial 77 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,035] Trial 78 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,040] Trial 79 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,044] Trial 80 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,047] Trial 81 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,051] Trial 82 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,054] Trial 83 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,058] Trial 84 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,062] Trial 85 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,066] Trial 86 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,070] Trial 87 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,073] Trial 88 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,077] Trial 89 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,080] Trial 90 finished with value: 0.35064935064935066 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,084] Trial 91 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,088] Trial 92 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,092] Trial 93 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,096] Trial 94 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,100] Trial 95 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,103] Trial 96 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,107] Trial 97 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,110] Trial 98 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 30 with value: 0.4675324675324675.
[I 2026-10-19 14:52:54,114] Trial 99 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 30 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:52:54,120] A new study created in memory with name: no-name-7f5bc867-6656-43a6-a122-d70bfa9c37f5
[I 2026-10-19 14:52:54,140] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 15, 'learning_rate': 0.1822768696701464, 'max_depth': 25, 'min_child_weight': 8.549378855877004, 'subsample': 0.5042583632236403, 'colsample_bytree': 0.432896239244145}. Best is trial 0 with value: 0.4025974025974026.
[I 2026-10-19 14:52:54,243] Trial 1 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 91, 'learning_rate': 0.997002835243148, 'max_depth': 32, 'min_child_weight': 1.8388050120355162, 'subsample': 0.7336657068317123, 'colsample_bytree': 0.8371063060091897}. Best is trial 1 with value: 0.42857142857142855.

0.001367330551147461  seconds
Classification report saved as results/Continent/data_14/data_14_lle_knn_classification_report.txt
    Accuracy: 0.4675, Time: 0.35s
  - Testing classifier: xgboost

[I 2026-10-19 14:52:54,325] Trial 2 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 131, 'learning_rate': 0.8942849989691319, 'max_depth': 24, 'min_child_weight': 8.710682236655778, 'subsample': 0.3393761970719788, 'colsample_bytree': 0.8592558749559309}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,518] Trial 3 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 177, 'learning_rate': 0.15704485772970472, 'max_depth': 9, 'min_child_weight': 7.9819739691963205, 'subsample': 0.9448096341821752, 'colsample_bytree': 0.824269626951095}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,648] Trial 4 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 122, 'learning_rate': 0.3586135106973318, 'max_depth': 18, 'min_child_weight': 6.585159230972942, 'subsample': 0.8311305041321593, 'colsample_bytree': 0.17875619354147532}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,766] Trial 5 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 103, 'learning_rate': 0.42715690251366356, 'max_depth': 18, 'min_child_weight': 4.146227392502422, 'subsample': 0.9280809333132354, 'colsample_bytree': 0.9967467341649847}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,792] Trial 6 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 14, 'learning_rate': 0.7245278420810222, 'max_depth': 25, 'min_child_weight': 1.5906383614684092, 'subsample': 0.5214377520123571, 'colsample_bytree': 0.4066295803505402}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,898] Trial 7 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 162, 'learning_rate': 0.5455497716939091, 'max_depth': 17, 'min_child_weight': 8.112693076523835, 'subsample': 0.31872874205758117, 'colsample_bytree': 0.5471657543068746}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:54,976] Trial 8 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 82, 'learning_rate': 0.9992923519947197, 'max_depth': 7, 'min_child_weight': 2.6918917927524224, 'subsample': 0.5334601288019776, 'colsample_bytree': 0.4860951920370259}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,034] Trial 9 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 32, 'learning_rate': 0.1573524574011851, 'max_depth': 26, 'min_child_weight': 1.5810223259971252, 'subsample': 0.4354993487897427, 'colsample_bytree': 0.8030663823832549}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,158] Trial 10 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 139, 'learning_rate': 0.5608816266659339, 'max_depth': 32, 'min_child_weight': 5.238172182623291, 'subsample': 0.5080851351721342, 'colsample_bytree': 0.6272778827454814}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,242] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 99, 'learning_rate': 0.9753214549149912, 'max_depth': 4, 'min_child_weight': 6.082913003428584, 'subsample': 0.5997662693829312, 'colsample_bytree': 0.6443942934634055}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,362] Trial 12 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 128, 'learning_rate': 0.9342512721057135, 'max_depth': 8, 'min_child_weight': 1.3137183251192495, 'subsample': 0.33008810711216197, 'colsample_bytree': 0.5093048132165067}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,417] Trial 13 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 96, 'learning_rate': 0.8691051363289627, 'max_depth': 25, 'min_child_weight': 9.706881087105211, 'subsample': 0.1915303109750744, 'colsample_bytree': 0.6886948278364666}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,511] Trial 14 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 108, 'learning_rate': 0.7284902389000927, 'max_depth': 15, 'min_child_weight': 5.5553702440845125, 'subsample': 0.4125505806004297, 'colsample_bytree': 0.608155031615677}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,597] Trial 15 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 80, 'learning_rate': 0.835306598117213, 'max_depth': 12, 'min_child_weight': 2.520260556517804, 'subsample': 0.6204866689149375, 'colsample_bytree': 0.5193843756437491}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,659] Trial 16 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 84, 'learning_rate': 0.8923721904257402, 'max_depth': 4, 'min_child_weight': 8.278071310047352, 'subsample': 0.3833418585145897, 'colsample_bytree': 0.8010376712840258}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,754] Trial 17 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 115, 'learning_rate': 0.8103970755455899, 'max_depth': 23, 'min_child_weight': 5.515559881535047, 'subsample': 0.4329109596203079, 'colsample_bytree': 0.8621911911904876}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,832] Trial 18 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 134, 'learning_rate': 0.9584628364464813, 'max_depth': 26, 'min_child_weight': 6.9707815715897, 'subsample': 0.1873343431635791, 'colsample_bytree': 0.8563489073832425}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:55,952] Trial 19 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 149, 'learning_rate': 0.9433567750367924, 'max_depth': 16, 'min_child_weight': 3.5427449395451402, 'subsample': 0.3909562872587712, 'colsample_bytree': 0.6951636730933181}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,037] Trial 20 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 108, 'learning_rate': 0.8291446414564311, 'max_depth': 20, 'min_child_weight': 4.268655903171963, 'subsample': 0.26404768866924555, 'colsample_bytree': 0.7593436668524838}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,105] Trial 21 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 68, 'learning_rate': 0.9696349573839763, 'max_depth': 8, 'min_child_weight': 3.3050137650812808, 'subsample': 0.3970725603264754, 'colsample_bytree': 0.15957721117895335}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,240] Trial 22 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 184, 'learning_rate': 0.6547597321868467, 'max_depth': 19, 'min_child_weight': 8.814762680718536, 'subsample': 0.47146248486698483, 'colsample_bytree': 0.9270639482488328}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,333] Trial 23 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 150, 'learning_rate': 0.7853047617069215, 'max_depth': 21, 'min_child_weight': 8.2172350436611, 'subsample': 0.2725489398614534, 'colsample_bytree': 0.7134905109515408}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,401] Trial 24 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 79, 'learning_rate': 0.989894729739585, 'max_depth': 3, 'min_child_weight': 4.968877702646188, 'subsample': 0.7166120670601142, 'colsample_bytree': 0.2499244872654277}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,498] Trial 25 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 99, 'learning_rate': 0.9593951263200544, 'max_depth': 5, 'min_child_weight': 1.2228995213644778, 'subsample': 0.7641090171627398, 'colsample_bytree': 0.6171588206103997}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,600] Trial 26 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 102, 'learning_rate': 0.9865334729854252, 'max_depth': 6, 'min_child_weight': 1.9152859574907217, 'subsample': 0.48547100659302866, 'colsample_bytree': 0.6663590301772483}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,678] Trial 27 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 99, 'learning_rate': 0.8554470428116528, 'max_depth': 2, 'min_child_weight': 1.532467903199222, 'subsample': 0.6608985523204178, 'colsample_bytree': 0.6251807396887339}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,786] Trial 28 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 109, 'learning_rate': 0.8742731452651862, 'max_depth': 10, 'min_child_weight': 1.651348069938893, 'subsample': 0.7127591051518076, 'colsample_bytree': 0.6787352699778606}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,888] Trial 29 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 109, 'learning_rate': 0.9664936473514917, 'max_depth': 7, 'min_child_weight': 2.6621312333998803, 'subsample': 0.6796031487922222, 'colsample_bytree': 0.5347694567708118}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,930] Trial 30 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 39, 'learning_rate': 0.953489072955429, 'max_depth': 3, 'min_child_weight': 1.4097689109106777, 'subsample': 0.6408650932251431, 'colsample_bytree': 0.4002023998773948}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:56,988] Trial 31 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 46, 'learning_rate': 0.9742682394532034, 'max_depth': 5, 'min_child_weight': 1.221483190716123, 'subsample': 0.619001834950877, 'colsample_bytree': 0.4228645678995543}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:57,071] Trial 32 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 86, 'learning_rate': 0.9159819661131725, 'max_depth': 4, 'min_child_weight': 2.2793988047020624, 'subsample': 0.7469684770470955, 'colsample_bytree': 0.39956135451706404}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:57,111] Trial 33 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 48, 'learning_rate': 0.998187037037837, 'max_depth': 2, 'min_child_weight': 1.4058536817551186, 'subsample': 0.4803905554808259, 'colsample_bytree': 0.3493618191733485}. Best is trial 2 with value: 0.4935064935064935.
[I 2026-10-19 14:52:57,154] Trial 34 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 39, 'learning_rate': 0.8689602595695568, 'max_depth': 3, 'min_child_weight': 1.333187284326497, 'subsample': 0.7061932509045289, 'colsample_bytree': 0.5482482184704939}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,201] Trial 35 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 44, 'learning_rate': 0.7999459987042196, 'max_depth': 3, 'min_child_weight': 1.4236594912669844, 'subsample': 0.8135776076684063, 'colsample_bytree': 0.7444092391094113}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,252] Trial 36 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 40, 'learning_rate': 0.8903385562305975, 'max_depth': 4, 'min_child_weight': 1.100231593824177, 'subsample': 0.8078277503697963, 'colsample_bytree': 0.4947715058470452}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,293] Trial 37 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 47, 'learning_rate': 0.7369190646991893, 'max_depth': 2, 'min_child_weight': 1.750262366331266, 'subsample': 0.655110168371674, 'colsample_bytree': 0.5652820850770524}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,372] Trial 38 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 80, 'learning_rate': 0.9559406015326418, 'max_depth': 4, 'min_child_weight': 1.9664807840698666, 'subsample': 0.8311213967678335, 'colsample_bytree': 0.6507982381950013}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,433] Trial 39 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 47, 'learning_rate': 0.7827992029336928, 'max_depth': 5, 'min_child_weight': 1.745227446519246, 'subsample': 0.670618555535959, 'colsample_bytree': 0.7667472472811532}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,528] Trial 40 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 83, 'learning_rate': 0.8271653221982189, 'max_depth': 7, 'min_child_weight': 1.3275676325312666, 'subsample': 0.9812092397648217, 'colsample_bytree': 0.5726383515895902}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,558] Trial 41 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 20, 'learning_rate': 0.9060886512490516, 'max_depth': 4, 'min_child_weight': 1.4781401538959744, 'subsample': 0.5882273841713623, 'colsample_bytree': 0.33494234783314825}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,591] Trial 42 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 40, 'learning_rate': 0.8681573255795868, 'max_depth': 2, 'min_child_weight': 2.7276190359082264, 'subsample': 0.49430509796664357, 'colsample_bytree': 0.30961452284408136}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,696] Trial 43 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 109, 'learning_rate': 0.9681717748358346, 'max_depth': 6, 'min_child_weight': 1.6571316858233076, 'subsample': 0.8799926451459064, 'colsample_bytree': 0.6652822406052177}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,736] Trial 44 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 21, 'learning_rate': 0.9344312702894746, 'max_depth': 8, 'min_child_weight': 1.3683256571858948, 'subsample': 0.7603632967528526, 'colsample_bytree': 0.588673996179807}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,808] Trial 45 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 63, 'learning_rate': 0.831451600792727, 'max_depth': 5, 'min_child_weight': 1.8143086490518165, 'subsample': 0.5693559715677554, 'colsample_bytree': 0.41122525364555457}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,833] Trial 46 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 14, 'learning_rate': 0.9266082327346216, 'max_depth': 5, 'min_child_weight': 2.7989390437353756, 'subsample': 0.7044072177104125, 'colsample_bytree': 0.37735819704164053}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,906] Trial 47 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 97, 'learning_rate': 0.9689724240964182, 'max_depth': 2, 'min_child_weight': 2.051413033136832, 'subsample': 0.7186764298316364, 'colsample_bytree': 0.5718259372876726}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,957] Trial 48 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 65, 'learning_rate': 0.9921007991467518, 'max_depth': 2, 'min_child_weight': 2.3531491078529, 'subsample': 0.6442475193543583, 'colsample_bytree': 0.3209203828289392}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:57,993] Trial 49 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 32, 'learning_rate': 0.7761605240359088, 'max_depth': 3, 'min_child_weight': 2.4772479332169115, 'subsample': 0.7793265234905611, 'colsample_bytree': 0.40626699368530783}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,047] Trial 50 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 42, 'learning_rate': 0.9752920551040588, 'max_depth': 5, 'min_child_weight': 1.6968193546393184, 'subsample': 0.678812108917255, 'colsample_bytree': 0.5436988172532095}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,128] Trial 51 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 74, 'learning_rate': 0.9618441295515542, 'max_depth': 7, 'min_child_weight': 1.8058432030182905, 'subsample': 0.7258486089638598, 'colsample_bytree': 0.4759443151546868}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,162] Trial 52 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 28, 'learning_rate': 0.9330300838984381, 'max_depth': 3, 'min_child_weight': 2.01301213589343, 'subsample': 0.6263880426723532, 'colsample_bytree': 0.5912200329618124}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,235] Trial 53 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 61, 'learning_rate': 0.8880419611365834, 'max_depth': 5, 'min_child_weight': 1.1593412098770877, 'subsample': 0.7000946290668247, 'colsample_bytree': 0.6052337085591009}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,318] Trial 54 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 73, 'learning_rate': 0.7550078294776807, 'max_depth': 5, 'min_child_weight': 1.5358949563737332, 'subsample': 0.7821226270543604, 'colsample_bytree': 0.6096193566554156}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,383] Trial 55 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 48, 'learning_rate': 0.7589746824091828, 'max_depth': 6, 'min_child_weight': 1.9508999577757242, 'subsample': 0.7013773034058982, 'colsample_bytree': 0.48337818165815605}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,463] Trial 56 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 74, 'learning_rate': 0.976498245510836, 'max_depth': 5, 'min_child_weight': 1.2426853593694087, 'subsample': 0.7557796218883821, 'colsample_bytree': 0.44611852086826104}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,521] Trial 57 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 55, 'learning_rate': 0.9054276839278564, 'max_depth': 3, 'min_child_weight': 1.1943328934715645, 'subsample': 0.6648170773030424, 'colsample_bytree': 0.7155326025155074}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,594] Trial 58 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 82, 'learning_rate': 0.8492531975876617, 'max_depth': 3, 'min_child_weight': 3.1265716318937935, 'subsample': 0.7017222024950391, 'colsample_bytree': 0.49296573678724864}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,679] Trial 59 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 78, 'learning_rate': 0.9669284133465799, 'max_depth': 8, 'min_child_weight': 1.6514231971805806, 'subsample': 0.8392325730263916, 'colsample_bytree': 0.5526545640707012}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,768] Trial 60 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 80, 'learning_rate': 0.8366675203501595, 'max_depth': 5, 'min_child_weight': 1.3239610798655883, 'subsample': 0.6752501987885998, 'colsample_bytree': 0.5408265439765588}. Best is trial 34 with value: 0.5064935064935064.
[I 2026-10-19 14:52:58,834] Trial 61 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 52, 'learning_rate': 0.9883969499548981, 'max_depth': 7, 'min_child_weight': 1.4640903368432763, 'subsample': 0.7136216657179978, 'colsample_bytree': 0.44277439397601986}. Best is trial 34 with value: 0.5064935064935064.

0.03906655311584473  seconds
Classification report saved as results/Continent/data_14/data_14_lle_xgboost_classification_report.txt
    Accuracy: 0.5325, Time: 6.85s
  - Testing classifier: svm

[I 2026-10-19 14:53:01,168] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,173] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,177] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,182] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,188] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,194] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,200] Trial 49 finished with value: 0.45454545454545453 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,206] Trial 50 finished with value: 0.45454545454545453 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,211] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,216] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,221] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,225] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,230] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,236] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,240] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,246] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,250] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,256] Trial 60 finished with value: 0.42857142857142855 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,262] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,266] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,271] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,276] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,280] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,284] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,290] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,295] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,301] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,305] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,309] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,314] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,319] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,323] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,328] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,332] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,337] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,342] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,347] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,353] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,359] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,364] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,369] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,374] Trial 84 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,378] Trial 85 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,383] Trial 86 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,387] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,392] Trial 88 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,398] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,403] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,408] Trial 91 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,412] Trial 92 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,416] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,422] Trial 94 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,426] Trial 95 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,432] Trial 96 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,438] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,442] Trial 98 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:53:01,448] Trial 99 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:53:01,455] A new study created in memory with name: no-name-d952f40f-ba7c-4c66-90fe-f0ddc521bb78
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.002511739730834961  seconds
Classification report saved as results/Continent/data_14/data_14_lle_svm_classification_report.txt
    Accuracy: 0.4675, Time: 0.49s
  - Testing classifier: mlp

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:01,193] Trial 0 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 80, 'n_neurons_layer1': 87, 'n_neurons_layer2': 63, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.038676125076266395}. Best is trial 0 with value: 0.45454545454545453.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:01,367] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 42, 'n_neurons_layer1': 49, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0001240328993196302}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:01,604] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 99, 'n_neurons_layer1': 5, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09154401625871057}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:01,704] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 27, 'activation': 'identity', 'solver': 'sgd', 'alpha': 8.703493260381135e-05}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:01,990] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 87, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00018480121950043802}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:02,400] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 84, 'n_neurons_layer1': 1, 'n_neurons_layer2': 43, 'activation': 'logistic', 'solver': 'adam', 'alpha': 3.291246098660272e-05}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:02,614] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 8, 'n_neurons_layer1': 13, 'n_neurons_layer2': 38, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 9.626978381140095e-05}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:02,890] Trial 7 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 95, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.08602673888274284}. Best is trial 1 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:03,180] Trial 8 finished with value: 0.4805194805194805 and parameters: {'n_layers': 1, 'n_neurons_layer0': 55, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.010191098666190111}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:03,382] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 81, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.012362429743705572}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:03,647] Trial 10 finished with value: 0.42857142857142855 and parameters: {'n_layers': 1, 'n_neurons_layer0': 48, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 1.3418980745520523e-05}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:03,917] Trial 11 finished with value: 0.45454545454545453 and parameters: {'n_layers': 1, 'n_neurons_layer0': 49, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.011882148724097381}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:04,084] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 53, 'n_neurons_layer1': 60, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0014926986999964475}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:54:04,471] Trial 13 finished with value: 0.44155844155844154 and parameters: {'n_layers': 2, 'n_neurons_layer0': 36, 'n_neurons_layer1': 41, 'activation': 'relu', 'solver': 'adam', 'alpha': 1.983956486226823e-05}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:05,719] Trial 14 finished with value: 0.42857142857142855 and parameters: {'n_layers': 2, 'n_neurons_layer0': 72, 'n_neurons_layer1': 93, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.0013200242215927404}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:05,939] Trial 15 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 45, 'n_neurons_layer1': 42, 'n_neurons_layer2': 100, 'activation': 'logistic', 'solver': 'adam', 'alpha': 1.917267962333842e-05}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:06,198] Trial 16 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 50, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.00016863912940267146}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:54:06,885] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 68, 'n_neurons_layer1': 71, 'n_neurons_layer2': 3, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.000796409723769852}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:07,575] Trial 18 finished with value: 0.42857142857142855 and parameters: {'n_layers': 2, 'n_neurons_layer0': 55, 'n_neurons_layer1': 30, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 3.1887720460969124e-05}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:07,872] Trial 19 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 21, 'n_neurons_layer1': 59, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0013282018135328268}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:08,214] Trial 20 finished with value: 0.4155844155844156 and parameters: {'n_layers': 1, 'n_neurons_layer0': 68, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.08117510345450564}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:08,401] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 27, 'n_neurons_layer1': 21, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.021079455616678386}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:54:08,854] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 98, 'n_neurons_layer1': 1, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.04075110146955906}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:09,191] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 100, 'n_neurons_layer1': 43, 'n_neurons_layer2': 93, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08775578822489188}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:09,420] Trial 24 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 54, 'n_neurons_layer1': 77, 'n_neurons_layer2': 10, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09522158629331198}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:09,618] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 28, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.004744196216485266}. Best is trial 8 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:09,807] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 58, 'n_neurons_layer1': 27, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.02782391542094509}. Best is trial 8 with value: 0.4805194805194805.

{'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.010191098666190111, 'hidden_layer_sizes': [55]}
Classification report saved as results/Continent/data_14/data_14_lle_mlp_classification_report_2026-10-19_14-54-27.txt
    Accuracy: 0.4286, Time: 85.67s
  - Testing classifier: nb

[I 2026-10-19 14:54:27,202] Trial 40 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.1868154349218566e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,204] Trial 41 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.408559944052604e-06}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,207] Trial 42 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.857895339083323e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,209] Trial 43 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 7.616583144656858e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,211] Trial 44 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.2038102368932526e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,213] Trial 45 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.7556142405005126e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,216] Trial 46 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.414975583103287e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,218] Trial 47 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 6.666635001181986e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,220] Trial 48 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.0296552142182017e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,222] Trial 49 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.5657031139326716e-06}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,224] Trial 50 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.5261861133981228e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,227] Trial 51 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.5313732579367502e-05}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,229] Trial 52 finished with value: 0.3246753246753247 and parameters: {'var_smoothing': 0.0001750449857285711}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,231] Trial 53 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.8042862897398146e-06}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,233] Trial 54 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 8.781964883448025e-06}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,236] Trial 55 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.3684555197326083e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,238] Trial 56 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 9.247487696567318e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,240] Trial 57 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.8268604480226545e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,242] Trial 58 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.14732286599733e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,245] Trial 59 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.982995815280013e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,247] Trial 60 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 4.507863950218403e-05}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,249] Trial 61 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.3180238005306655e-12}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,251] Trial 62 finished with value: 0.3246753246753247 and parameters: {'var_smoothing': 0.0006536356041953475}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,254] Trial 63 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.1335890627348344e-05}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,256] Trial 64 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.84420111339972e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,258] Trial 65 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.257748188654623e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,260] Trial 66 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.45257561987848e-12}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,263] Trial 67 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.7385241255280082e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,265] Trial 68 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.1798581853184689e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,267] Trial 69 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.8476938779883214e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,269] Trial 70 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 0.00014749324925877687}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,272] Trial 71 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.4995104613077427e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,274] Trial 72 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 2.8792970750624304e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,276] Trial 73 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 7.634698449026505e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,278] Trial 74 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.9108829241653174e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,281] Trial 75 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 8.436956387701743e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,283] Trial 76 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 7.246345732837039e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,285] Trial 77 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 4.3903426664819514e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,288] Trial 78 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 4.231080157563632e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,290] Trial 79 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.2963685266693456e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,292] Trial 80 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.7062050097131824e-06}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,295] Trial 81 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.2011729141129877e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,297] Trial 82 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.950475790055769e-12}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,300] Trial 83 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.374868424258491e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,303] Trial 84 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.8317866702718134e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,305] Trial 85 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.204022014233634e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,308] Trial 86 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 4.38186276090738e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,310] Trial 87 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.0898710885653778e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,313] Trial 88 finished with value: 0.3246753246753247 and parameters: {'var_smoothing': 0.0023820212096552352}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,316] Trial 89 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 4.540322964448542e-11}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,318] Trial 90 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.783311914241144e-10}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,321] Trial 91 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.0893478255359314e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,323] Trial 92 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.24893950138078e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,326] Trial 93 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.464336836762453e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,328] Trial 94 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.4361385834873286e-08}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,331] Trial 95 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.043995887421628e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,333] Trial 96 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 6.001419572750549e-07}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,336] Trial 97 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 5.222174329234973e-09}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,338] Trial 98 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 1.051023424577221e-12}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 14:54:27,341] Trial 99 finished with value: 0.33766233766233766 and parameters: {'var_smoothing': 3.2093395952559884e-09}. Best is trial 1 with value: 0.33766233766233766.

Best hyperparameters:  {'var_smoothing': 9.013231392641612e-09}
Best validation accuracy:  0.33766233766233766
Test accuracy: 0.33766233766233766
Time taken: 0.0012557506561279297 seconds
Classification report saved as results/Continent/data_14/data_14_lle_nb_classification_report_2026-10-19_14-54-27.txt
    Accuracy: 0.3377, Time: 0.23s

Evaluating embedding method: umap

[I 2026-10-19 14:54:27,682] A new study created in memory with name: no-name-1f490f61-1078-417e-b344-8f8f566b75dd
[I 2026-10-19 14:54:27,839] Trial 0 finished with value: 0.42857142857142855 and parameters: {'C': 0.5587630910758823, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5834408099700085}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 14:54:27,857] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 1.6322705525253697e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5214167489379694}. Best is trial 1 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 14:54:28,046] Trial 2 finished with value: 0.42857142857142855 and parameters: {'C': 431.0440591957647, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7325425773506893}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,074] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 27.00062307299447, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.557243951069878}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,092] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 0.0028650997179100867, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8294203197793903}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,110] Trial 5 finished with value: 0.4675324675324675 and parameters: {'C': 0.047907137720272074, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5980064434404113}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,128] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 2.510457287243549e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6893486918583055}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,145] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 1.0701229791311054e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3581113849673534}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,163] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 6.061641626767689e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.963853087181691}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,181] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 4.290899974483626e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.11754523581290333}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,352] Trial 10 finished with value: 0.4155844155844156 and parameters: {'C': 0.8049744345231976, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0811926227191731}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,373] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 9.580993596307522e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4261981990646202}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,394] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 0.27531272381055777, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3381807331783183}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,415] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 287.96804271016276, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5993357900735372}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,436] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 2.7536123706926463e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9184182354806457}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,628] Trial 15 finished with value: 0.42857142857142855 and parameters: {'C': 80.86583530887725, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3245899917014399}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,649] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 37.94171070524432, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21702017462809087}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,671] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 1.3159717417017788e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7466407938270843}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,692] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 0.0011251560108645866, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26382924472187885}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,712] Trial 19 finished with value: 0.4675324675324675 and parameters: {'C': 0.0033847723790921508, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.446663155073163}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,743] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 42.183599989774216, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9165342113567652}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,763] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 0.009575236847247797, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7590194238663897}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,784] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 0.00020640492236313467, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7459483458803997}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,805] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 2.0371358820798278e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6116962204980837}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,824] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 1.2061227341289735e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5759238990117926}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,843] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 0.6740282789230376, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7744557570348256}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,863] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 0.0022350824816967396, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9369980161081394}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,883] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 1.5931245686330722e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6036310580288095}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,935] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 0.019155921456228815, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46325007772241367}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:28,957] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 2.6227373920292093e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8038748143696883}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,100] Trial 30 finished with value: 0.42857142857142855 and parameters: {'C': 0.9051912123115432, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4723680450921195}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,122] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.048256640097276066, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5939681932948677}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,143] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.40265201384948807, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4368032885851439}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,244] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 0.08046357872428071, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8871421056031499}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,266] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 2.1475044210843062e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5041550632067169}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,286] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 127.58262439193791, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7024587318405581}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,307] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 7.307991948725393, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7112769621303792}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,328] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 9.16323728456563, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6105741455384507}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,350] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 132.84916127637794, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.49823355969075905}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,371] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.0011717431142835033, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6343170718256633}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,392] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.6814419437246669, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5512369923735562}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,414] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 1.6685824520273217e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7438564049466855}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,436] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 6.281957875254618e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6399241573512875}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,457] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 0.0023155603062752625, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5652914792080054}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,478] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 1.7054331567547103e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5824115959479879}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,500] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 1.0115839280136476e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.45394555510796447}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,522] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.46897382317818964, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9741497420444022}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,543] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 0.037035956374142115, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8408924740071624}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,563] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 7.827085539062395e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5198010183697949}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,584] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 0.0006688027493387337, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5434966205817502}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,606] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 1.934239918220394e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6947619382296364}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,627] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 1.0085298982178359e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3120876223718608}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,648] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 5.691109051569384e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3782745429999212}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,669] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 2.8629239861780723e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.28515246601341393}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,690] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 4.878449462785269e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.19491955484248458}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,712] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 2.1876426518728748e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9158361117388308}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,733] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 5.413951958036714, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4250987106462328}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,754] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.0012651472800264513, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.48513502581136986}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,776] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.021235568297598578, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6913134345344243}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,798] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 8.668629265228292e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9488565935704762}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,820] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 1.8852599335321008e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.38221906649978993}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,841] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 3.1390918013385275e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9323012872899301}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,863] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 1.98469233185452e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8535578610127311}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,884] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 1.7631283811901886e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9352154826980837}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,903] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 1.5971085401423887e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4120695942910355}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,926] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 9.676966050056949, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5124033429948212}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,947] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 2.1974992706945494e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8548272312162205}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,968] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 1.2393238638150096e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6303674017122601}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:29,990] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 6.218437923520743e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.677799016645515}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,012] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 1.3770031332491987e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8310050015764873}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,034] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 5.022800309834271e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7140537401553478}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,057] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.044404960695920107, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5042323706198331}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,078] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 1.2167600631714856e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.14684742618399552}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,099] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.7384294896743269, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6494978011841744}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,120] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 6.347035492626138, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.822616907326216}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,142] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 9.063087778763479e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9888220450828932}. Best is trial 1 with value: 0.4675324675324675.

0.0028684139251708984  seconds
Classification report saved as results/Continent/data_14/data_14_umap_logreg_classification_report.txt
    Accuracy: 0.4675, Time: 3.00s
  - Testing classifier: dt

[I 2026-10-19 14:54:30,872] Trial 63 finished with value: 0.2987012987012987 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,874] Trial 64 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,877] Trial 65 finished with value: 0.38961038961038963 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,880] Trial 66 finished with value: 0.2857142857142857 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,883] Trial 67 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,885] Trial 68 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,888] Trial 69 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,891] Trial 70 finished with value: 0.38961038961038963 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,894] Trial 71 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,896] Trial 72 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,899] Trial 73 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,902] Trial 74 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,905] Trial 75 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,907] Trial 76 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,910] Trial 77 finished with value: 0.35064935064935066 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,913] Trial 78 finished with value: 0.38961038961038963 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,916] Trial 79 finished with value: 0.38961038961038963 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,919] Trial 80 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,922] Trial 81 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,925] Trial 82 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,928] Trial 83 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,931] Trial 84 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,934] Trial 85 finished with value: 0.38961038961038963 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,937] Trial 86 finished with value: 0.2857142857142857 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,940] Trial 87 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,943] Trial 88 finished with value: 0.3116883116883117 and parameters: {'max_depth': 30, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,946] Trial 89 finished with value: 0.33766233766233766 and parameters: {'max_depth': 9, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,949] Trial 90 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,954] Trial 91 finished with value: 0.35064935064935066 and parameters: {'max_depth': 16, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,957] Trial 92 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,960] Trial 93 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,963] Trial 94 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,965] Trial 95 finished with value: 0.4675324675324675 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,968] Trial 96 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,971] Trial 97 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,974] Trial 98 finished with value: 0.42857142857142855 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 14:54:30,977] Trial 99 finished with value: 0.38961038961038963 and parameters: {'max_depth': 4, 'criterion': 'gini'}. Best is trial 2 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:54:30,983] A new study created in memory with name: no-name-ef84a31c-c1e9-4ec3-9653-91ce0f7bf173
[I 2026-10-19 14:54:31,009] Trial 0 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 28, 'max_depth': 15}. Best is trial 0 with value: 0.36363636363636365.
[I 2026-10-19 14:54:31,161] Trial 1 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 179, 'max_depth': 14}. Best is trial 1 with value: 0.37662337662337664.

0.0009827613830566406  seconds
Classification report saved as results/Continent/data_14/data_14_umap_dt_classification_report.txt
    Accuracy: 0.4675, Time: 0.31s
  - Testing classifier: rf

[I 2026-10-19 14:54:31,300] Trial 2 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 165, 'max_depth': 10}. Best is trial 1 with value: 0.37662337662337664.
[I 2026-10-19 14:54:31,413] Trial 3 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 133, 'max_depth': 24}. Best is trial 1 with value: 0.37662337662337664.
[I 2026-10-19 14:54:31,561] Trial 4 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 198, 'max_depth': 4}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:31,705] Trial 5 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 179, 'max_depth': 10}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:31,829] Trial 6 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 149, 'max_depth': 14}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:31,933] Trial 7 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 128, 'max_depth': 10}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:31,965] Trial 8 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 38, 'max_depth': 27}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:32,111] Trial 9 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 167, 'max_depth': 25}. Best is trial 4 with value: 0.45454545454545453.
[I 2026-10-19 14:54:32,233] Trial 10 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 167, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,371] Trial 11 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 189, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,462] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 123, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,572] Trial 13 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 140, 'max_depth': 5}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,645] Trial 14 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 83, 'max_depth': 10}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,710] Trial 15 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 72, 'max_depth': 18}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:32,838] Trial 16 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 175, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,010] Trial 17 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 199, 'max_depth': 13}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,182] Trial 18 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 197, 'max_depth': 24}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,266] Trial 19 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 102, 'max_depth': 7}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,382] Trial 20 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 131, 'max_depth': 31}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,479] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 129, 'max_depth': 3}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,507] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 33, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,567] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 80, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,721] Trial 24 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 173, 'max_depth': 32}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,833] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 150, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:33,968] Trial 26 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 169, 'max_depth': 5}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,051] Trial 27 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 109, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,171] Trial 28 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 141, 'max_depth': 8}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,216] Trial 29 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 52, 'max_depth': 5}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,384] Trial 30 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 199, 'max_depth': 8}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,517] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 180, 'max_depth': 2}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 14:54:34,656] Trial 32 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 185, 'max_depth': 3}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:34,789] Trial 33 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 160, 'max_depth': 8}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:34,921] Trial 34 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 150, 'max_depth': 30}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,068] Trial 35 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 186, 'max_depth': 5}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,146] Trial 36 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 86, 'max_depth': 31}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,268] Trial 37 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 155, 'max_depth': 5}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,395] Trial 38 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 157, 'max_depth': 6}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,540] Trial 39 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 178, 'max_depth': 7}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,702] Trial 40 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 189, 'max_depth': 10}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,843] Trial 41 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 194, 'max_depth': 2}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:35,934] Trial 42 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 116, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,056] Trial 43 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 161, 'max_depth': 3}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,183] Trial 44 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 148, 'max_depth': 10}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,321] Trial 45 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 157, 'max_depth': 20}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,417] Trial 46 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 109, 'max_depth': 13}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,575] Trial 47 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 197, 'max_depth': 6}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,696] Trial 48 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 161, 'max_depth': 3}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,842] Trial 49 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 170, 'max_depth': 10}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:36,959] Trial 50 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 133, 'max_depth': 15}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,064] Trial 51 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 139, 'max_depth': 3}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,233] Trial 52 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 193, 'max_depth': 30}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,392] Trial 53 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 183, 'max_depth': 12}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,510] Trial 54 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 148, 'max_depth': 5}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,562] Trial 55 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 59, 'max_depth': 9}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,699] Trial 56 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 177, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,821] Trial 57 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 165, 'max_depth': 2}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,918] Trial 58 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 115, 'max_depth': 8}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:37,990] Trial 59 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 90, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,132] Trial 60 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 189, 'max_depth': 3}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,273] Trial 61 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 170, 'max_depth': 8}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,421] Trial 62 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 193, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,569] Trial 63 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 170, 'max_depth': 13}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,723] Trial 64 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 188, 'max_depth': 7}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:38,863] Trial 65 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 182, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:39,009] Trial 66 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 189, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:39,115] Trial 67 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 131, 'max_depth': 6}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:39,244] Trial 68 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 167, 'max_depth': 4}. Best is trial 32 with value: 0.4805194805194805.
[I 2026-10-19 14:54:39,362] Trial 69 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 153, 'max_depth': 4}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:39,511] Trial 70 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 200, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:39,640] Trial 71 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 171, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:39,737] Trial 72 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 108, 'max_depth': 23}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:39,880] Trial 73 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 190, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,002] Trial 74 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 157, 'max_depth': 4}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,142] Trial 75 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 173, 'max_depth': 6}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,261] Trial 76 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 145, 'max_depth': 7}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,395] Trial 77 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 166, 'max_depth': 6}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,520] Trial 78 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 159, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,634] Trial 79 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 151, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,751] Trial 80 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 151, 'max_depth': 4}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:40,869] Trial 81 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 159, 'max_depth': 2}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,010] Trial 82 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 180, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,160] Trial 83 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 191, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,297] Trial 84 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 185, 'max_depth': 2}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,398] Trial 85 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 136, 'max_depth': 2}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,545] Trial 86 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 183, 'max_depth': 6}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,678] Trial 87 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 156, 'max_depth': 9}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,833] Trial 88 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 198, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:41,974] Trial 89 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 162, 'max_depth': 12}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,078] Trial 90 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 133, 'max_depth': 4}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,178] Trial 91 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 125, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,333] Trial 92 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 191, 'max_depth': 8}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,446] Trial 93 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 154, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,575] Trial 94 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 163, 'max_depth': 7}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,686] Trial 95 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 142, 'max_depth': 6}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,828] Trial 96 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 175, 'max_depth': 9}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:42,962] Trial 97 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 179, 'max_depth': 5}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:43,106] Trial 98 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 195, 'max_depth': 4}. Best is trial 69 with value: 0.5064935064935064.
[I 2026-10-19 14:54:43,195] Trial 99 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 123, 'max_depth': 3}. Best is trial 69 with value: 0.5064935064935064.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:54:43,310] A new study created in memory with name: no-name-df82762c-a61b-4a9e-ba8b-c30238c6c2ab
[I 2026-10-19 14:54:43,312] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,315] Trial 1 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,317] Trial 2 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,318] Trial 3 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,320] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.

0.11054539680480957  seconds
Classification report saved as results/Continent/data_14/data_14_umap_rf_classification_report.txt
    Accuracy: 0.4675, Time: 12.33s
  - Testing classifier: knn

[I 2026-10-19 14:54:43,507] Trial 64 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,511] Trial 65 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,514] Trial 66 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,517] Trial 67 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,521] Trial 68 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,524] Trial 69 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,528] Trial 70 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,531] Trial 71 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,534] Trial 72 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,537] Trial 73 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,540] Trial 74 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,544] Trial 75 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,547] Trial 76 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,550] Trial 77 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,554] Trial 78 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,558] Trial 79 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,562] Trial 80 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,566] Trial 81 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,569] Trial 82 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,572] Trial 83 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,576] Trial 84 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,579] Trial 85 finished with value: 0.37662337662337664 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,583] Trial 86 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,587] Trial 87 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,590] Trial 88 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,593] Trial 89 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,597] Trial 90 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,600] Trial 91 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,603] Trial 92 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,607] Trial 93 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,610] Trial 94 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,614] Trial 95 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,617] Trial 96 finished with value: 0.4155844155844156 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,620] Trial 97 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,624] Trial 98 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:43,627] Trial 99 finished with value: 0.4675324675324675 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 14:54:43,632] A new study created in memory with name: no-name-1e11be0a-b4a3-4c21-aaef-b2488a4af576
[I 2026-10-19 14:54:43,805] Trial 0 finished with value: 0.2987012987012987 and parameters: {'n_estimators': 128, 'learning_rate': 0.347954943811499, 'max_depth': 29, 'min_child_weight': 4.083932174367554, 'subsample': 0.9787269425246334, 'colsample_bytree': 0.7999557124011809}. Best is trial 0 with value: 0.2987012987012987.

0.0011327266693115234  seconds
Classification report saved as results/Continent/data_14/data_14_umap_knn_classification_report.txt
    Accuracy: 0.4416, Time: 0.32s
  - Testing classifier: xgboost

[I 2026-10-19 14:54:43,866] Trial 1 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 78, 'learning_rate': 0.9930088193804618, 'max_depth': 25, 'min_child_weight': 5.819710016004379, 'subsample': 0.4806307524115785, 'colsample_bytree': 0.46617975675513046}. Best is trial 1 with value: 0.37662337662337664.
[I 2026-10-19 14:54:43,922] Trial 2 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 64, 'learning_rate': 0.4657899414243066, 'max_depth': 21, 'min_child_weight': 6.8359827441799865, 'subsample': 0.5624811187029412, 'colsample_bytree': 0.6274478867228324}. Best is trial 2 with value: 0.38961038961038963.
[I 2026-10-19 14:54:44,034] Trial 3 finished with value: 0.2597402597402597 and parameters: {'n_estimators': 108, 'learning_rate': 0.7512749295823801, 'max_depth': 30, 'min_child_weight': 4.040851648680974, 'subsample': 0.747471151593854, 'colsample_bytree': 0.589745759829426}. Best is trial 2 with value: 0.38961038961038963.
[I 2026-10-19 14:54:44,060] Trial 4 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 26, 'learning_rate': 0.505611410728673, 'max_depth': 6, 'min_child_weight': 6.825809272962482, 'subsample': 0.605890149646366, 'colsample_bytree': 0.6573899819827039}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,136] Trial 5 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 127, 'learning_rate': 0.16569716101979276, 'max_depth': 18, 'min_child_weight': 9.898194650477064, 'subsample': 0.3725048466044093, 'colsample_bytree': 0.7765987276614439}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,207] Trial 6 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 116, 'learning_rate': 0.8476951240792675, 'max_depth': 15, 'min_child_weight': 7.7243891469173995, 'subsample': 0.3355100959600637, 'colsample_bytree': 0.9033461929033393}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,307] Trial 7 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 146, 'learning_rate': 0.3730950209483349, 'max_depth': 24, 'min_child_weight': 7.651548914011984, 'subsample': 0.4266752133211341, 'colsample_bytree': 0.11382593031740856}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,386] Trial 8 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 64, 'learning_rate': 0.8286325313924828, 'max_depth': 29, 'min_child_weight': 1.0470843930875884, 'subsample': 0.37655874361382513, 'colsample_bytree': 0.5144292086403977}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,469] Trial 9 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 98, 'learning_rate': 0.06414779516269124, 'max_depth': 25, 'min_child_weight': 9.398675412514784, 'subsample': 0.7057128783513092, 'colsample_bytree': 0.29119592044600395}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,547] Trial 10 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 87, 'learning_rate': 0.29083836972048815, 'max_depth': 7, 'min_child_weight': 8.115024109215149, 'subsample': 0.6556171878326704, 'colsample_bytree': 0.7486229489438688}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,656] Trial 11 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 170, 'learning_rate': 0.2898011633636411, 'max_depth': 22, 'min_child_weight': 9.118805074145312, 'subsample': 0.39301762348252584, 'colsample_bytree': 0.8992329999876894}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,677] Trial 12 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 26, 'learning_rate': 0.13682369856546706, 'max_depth': 32, 'min_child_weight': 9.587159828756084, 'subsample': 0.3295885387444836, 'colsample_bytree': 0.8827653691589052}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,711] Trial 13 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 48, 'learning_rate': 0.06020039373489218, 'max_depth': 22, 'min_child_weight': 8.901950520513152, 'subsample': 0.3346954092548019, 'colsample_bytree': 0.9894370189920753}. Best is trial 4 with value: 0.44155844155844154.
[I 2026-10-19 14:54:44,734] Trial 14 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 36, 'learning_rate': 0.3252289921736961, 'max_depth': 16, 'min_child_weight': 9.4911608665043, 'subsample': 0.17904485907036094, 'colsample_bytree': 0.9017637843679746}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:54:44,762] Trial 15 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 32, 'learning_rate': 0.27138572838013175, 'max_depth': 13, 'min_child_weight': 8.460505588554929, 'subsample': 0.4290681953543226, 'colsample_bytree': 0.8308244760059886}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:54:44,785] Trial 16 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 20, 'learning_rate': 0.5740806725831359, 'max_depth': 5, 'min_child_weight': 6.821111753325602, 'subsample': 0.6060289532116239, 'colsample_bytree': 0.41622977126784755}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 14:54:44,821] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 72, 'learning_rate': 0.17279778987534442, 'max_depth': 15, 'min_child_weight': 9.488151669055966, 'subsample': 0.1116620134246362, 'colsample_bytree': 0.6603169112869487}. Best is trial 17 with value: 0.4675324675324675.
[I 2026-10-19 14:54:44,838] Trial 18 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 22, 'learning_rate': 0.39240421619209553, 'max_depth': 22, 'min_child_weight': 9.992140525926988, 'subsample': 0.19355554734134975, 'colsample_bytree': 0.966238754396424}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:44,865] Trial 19 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 41, 'learning_rate': 0.429383884892052, 'max_depth': 20, 'min_child_weight': 8.476452469227931, 'subsample': 0.21294507211476665, 'colsample_bytree': 0.7075859047093637}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:44,903] Trial 20 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 66, 'learning_rate': 0.11375874989498269, 'max_depth': 13, 'min_child_weight': 8.687528026741667, 'subsample': 0.19873606107392128, 'colsample_bytree': 0.9785754060464901}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:44,918] Trial 21 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 16, 'learning_rate': 0.3614512794033738, 'max_depth': 29, 'min_child_weight': 9.375298956826207, 'subsample': 0.2758776423741568, 'colsample_bytree': 0.9860184301518781}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:44,930] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 14, 'learning_rate': 0.3732952329174308, 'max_depth': 19, 'min_child_weight': 9.562699367342292, 'subsample': 0.16597645622604557, 'colsample_bytree': 0.8781507301014664}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:44,981] Trial 23 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 109, 'learning_rate': 0.5124372826760379, 'max_depth': 19, 'min_child_weight': 9.345405250168534, 'subsample': 0.112352703829845, 'colsample_bytree': 0.7775277423368092}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,010] Trial 24 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 47, 'learning_rate': 0.3939009540548052, 'max_depth': 25, 'min_child_weight': 8.265987683006038, 'subsample': 0.16176289229832744, 'colsample_bytree': 0.9913027762529829}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,040] Trial 25 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 42, 'learning_rate': 0.28971806551472634, 'max_depth': 23, 'min_child_weight': 9.765834591847577, 'subsample': 0.3187130544850141, 'colsample_bytree': 0.9010043646607809}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,055] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 18, 'learning_rate': 0.635308331763063, 'max_depth': 21, 'min_child_weight': 9.259079834357111, 'subsample': 0.10905140618822493, 'colsample_bytree': 0.8220982712199562}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,083] Trial 27 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 44, 'learning_rate': 0.6617259584393029, 'max_depth': 27, 'min_child_weight': 8.13025758800396, 'subsample': 0.19629486039631158, 'colsample_bytree': 0.8026917225213382}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,096] Trial 28 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 10, 'learning_rate': 0.2015234856976723, 'max_depth': 21, 'min_child_weight': 9.743594702993446, 'subsample': 0.3034065216257086, 'colsample_bytree': 0.9505561584501677}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,110] Trial 29 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 17, 'learning_rate': 0.19351184572588692, 'max_depth': 18, 'min_child_weight': 9.741857197250269, 'subsample': 0.24158066443985987, 'colsample_bytree': 0.6885816073373942}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,130] Trial 30 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 34, 'learning_rate': 0.21623138316142795, 'max_depth': 22, 'min_child_weight': 9.593289797317736, 'subsample': 0.10251900557411049, 'colsample_bytree': 0.7875625668494374}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,143] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 15, 'learning_rate': 0.35512593076713356, 'max_depth': 15, 'min_child_weight': 8.434720479002731, 'subsample': 0.12914780180335164, 'colsample_bytree': 0.9635310577561094}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,171] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 56, 'learning_rate': 0.467653206945874, 'max_depth': 26, 'min_child_weight': 9.460432191910915, 'subsample': 0.10807969290677401, 'colsample_bytree': 0.8380573656051417}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,206] Trial 33 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 71, 'learning_rate': 0.35177784690774694, 'max_depth': 17, 'min_child_weight': 8.267008775198898, 'subsample': 0.10499007978291493, 'colsample_bytree': 0.8288400425648192}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,224] Trial 34 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 21, 'learning_rate': 0.5012317074980023, 'max_depth': 23, 'min_child_weight': 9.60334762032668, 'subsample': 0.27341703753734825, 'colsample_bytree': 0.8977168530751569}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,262] Trial 35 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 56, 'learning_rate': 0.47819105670374157, 'max_depth': 23, 'min_child_weight': 9.021308178520291, 'subsample': 0.33179437958550906, 'colsample_bytree': 0.9754559331359421}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,298] Trial 36 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 59, 'learning_rate': 0.5186707897014173, 'max_depth': 21, 'min_child_weight': 8.758435645389206, 'subsample': 0.24274550110510829, 'colsample_bytree': 0.8462865544381308}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,320] Trial 37 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 28, 'learning_rate': 0.384822631136692, 'max_depth': 20, 'min_child_weight': 8.862666370007425, 'subsample': 0.3115910709383737, 'colsample_bytree': 0.9925623531383108}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,337] Trial 38 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 21, 'learning_rate': 0.3676422701945473, 'max_depth': 13, 'min_child_weight': 9.958154630637527, 'subsample': 0.29198502708547025, 'colsample_bytree': 0.8179098248126653}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,367] Trial 39 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 55, 'learning_rate': 0.3552341981594769, 'max_depth': 19, 'min_child_weight': 8.655013298729234, 'subsample': 0.12866434465553753, 'colsample_bytree': 0.9869168200177897}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,394] Trial 40 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 43, 'learning_rate': 0.14987279818520466, 'max_depth': 17, 'min_child_weight': 9.613105372517479, 'subsample': 0.24524450400360895, 'colsample_bytree': 0.7818854103274475}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,406] Trial 41 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 12, 'learning_rate': 0.2039118737244276, 'max_depth': 19, 'min_child_weight': 8.376995978704128, 'subsample': 0.1430606317794545, 'colsample_bytree': 0.8789590784133625}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,466] Trial 42 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 133, 'learning_rate': 0.46191680942234337, 'max_depth': 20, 'min_child_weight': 8.456541736201105, 'subsample': 0.10814269279963011, 'colsample_bytree': 0.8360677785176779}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,485] Trial 43 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 24, 'learning_rate': 0.575243969374049, 'max_depth': 23, 'min_child_weight': 8.28128290267679, 'subsample': 0.19456483218565787, 'colsample_bytree': 0.9056670469934207}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,501] Trial 44 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 19, 'learning_rate': 0.5356977179392008, 'max_depth': 18, 'min_child_weight': 9.397533256707048, 'subsample': 0.20834438547776954, 'colsample_bytree': 0.840772822307155}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,515] Trial 45 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 18, 'learning_rate': 0.39710602021859115, 'max_depth': 18, 'min_child_weight': 9.830550389241454, 'subsample': 0.2027026086940158, 'colsample_bytree': 0.9977931007605048}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,540] Trial 46 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 43, 'learning_rate': 0.5566692634099036, 'max_depth': 20, 'min_child_weight': 8.949482585989665, 'subsample': 0.1472000549233461, 'colsample_bytree': 0.8022868163450636}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,554] Trial 47 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 16, 'learning_rate': 0.2738373924292973, 'max_depth': 21, 'min_child_weight': 9.343655111956814, 'subsample': 0.16933252014548336, 'colsample_bytree': 0.8516576909165443}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,564] Trial 48 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 10, 'learning_rate': 0.6675072235435466, 'max_depth': 20, 'min_child_weight': 8.641194770627996, 'subsample': 0.12278392862099434, 'colsample_bytree': 0.7287013149954388}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,587] Trial 49 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 40, 'learning_rate': 0.5281159331425153, 'max_depth': 23, 'min_child_weight': 9.139599854370102, 'subsample': 0.10470860486197035, 'colsample_bytree': 0.8845425838019166}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,619] Trial 50 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 60, 'learning_rate': 0.5053151603861271, 'max_depth': 20, 'min_child_weight': 9.733045579345404, 'subsample': 0.14673276758559756, 'colsample_bytree': 0.8481714948661124}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,638] Trial 51 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 28, 'learning_rate': 0.424117547407213, 'max_depth': 24, 'min_child_weight': 9.964600708240624, 'subsample': 0.14742598915755123, 'colsample_bytree': 0.9412780131171526}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,656] Trial 52 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 24, 'learning_rate': 0.6811031273261275, 'max_depth': 21, 'min_child_weight': 9.761501663759564, 'subsample': 0.18781205809447749, 'colsample_bytree': 0.7606439357312316}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,667] Trial 53 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 11, 'learning_rate': 0.6701751443555508, 'max_depth': 19, 'min_child_weight': 9.778797765787376, 'subsample': 0.18177593088192312, 'colsample_bytree': 0.8973682767867648}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,684] Trial 54 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 17, 'learning_rate': 0.3326132957113671, 'max_depth': 20, 'min_child_weight': 9.391263763449869, 'subsample': 0.3452154427294024, 'colsample_bytree': 0.9141622772418205}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,703] Trial 55 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 28, 'learning_rate': 0.26694937548749564, 'max_depth': 24, 'min_child_weight': 9.445263022632929, 'subsample': 0.171181481001597, 'colsample_bytree': 0.9595416559196718}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,715] Trial 56 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 10, 'learning_rate': 0.41364888749528095, 'max_depth': 24, 'min_child_weight': 9.281525887436082, 'subsample': 0.22024913936533008, 'colsample_bytree': 0.8666126724748605}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,734] Trial 57 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 26, 'learning_rate': 0.6585951551643175, 'max_depth': 22, 'min_child_weight': 9.14814267340053, 'subsample': 0.24314345512120242, 'colsample_bytree': 0.8661709279543898}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,748] Trial 58 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 17, 'learning_rate': 0.5717700200812807, 'max_depth': 18, 'min_child_weight': 8.509672194854426, 'subsample': 0.1411864880340924, 'colsample_bytree': 0.9019714200005535}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,764] Trial 59 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 20, 'learning_rate': 0.6523261115868008, 'max_depth': 23, 'min_child_weight': 8.744119256829828, 'subsample': 0.1454921229317615, 'colsample_bytree': 0.8093593471771549}. Best is trial 18 with value: 0.4805194805194805.
[I 2026-10-19 14:54:45,785] Trial 60 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 35, 'learning_rate': 0.31281893115623177, 'max_depth': 19, 'min_child_weight': 9.418041681467212, 'subsample': 0.12925577069013588, 'colsample_bytree': 0.8240451780860666}. Best is trial 18 with value: 0.4805194805194805.

0.01258230209350586  seconds
Classification report saved as results/Continent/data_14/data_14_umap_xgboost_classification_report.txt
    Accuracy: 0.4675, Time: 2.88s
  - Testing classifier: svm

[I 2026-10-19 14:54:46,709] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,713] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,716] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,722] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,725] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,731] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,736] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,742] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,747] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,751] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,755] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,760] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,764] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,768] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,772] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,778] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,782] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,787] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,793] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,797] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,802] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,808] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,812] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,817] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,821] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,827] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,832] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,838] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,842] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,846] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,851] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,857] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,861] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,865] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,869] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,873] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,879] Trial 84 finished with value: 0.45454545454545453 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,883] Trial 85 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,889] Trial 86 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,894] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,898] Trial 88 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,903] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,907] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,912] Trial 91 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,916] Trial 92 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,921] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,926] Trial 94 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,930] Trial 95 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,936] Trial 96 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,940] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,944] Trial 98 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:54:46,948] Trial 99 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 14:54:46,955] A new study created in memory with name: no-name-e584c543-6da5-45fa-a6c6-2de33d526c41
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:47,130] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 22, 'n_neurons_layer1': 16, 'n_neurons_layer2': 91, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0062425944725343}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.0022923946380615234  seconds
Classification report saved as results/Continent/data_14/data_14_umap_svm_classification_report.txt
    Accuracy: 0.4675, Time: 0.44s
  - Testing classifier: mlp

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:47,410] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 79, 'n_neurons_layer1': 12, 'n_neurons_layer2': 68, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.02499606544967961}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:47,581] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 63, 'n_neurons_layer1': 62, 'n_neurons_layer2': 18, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.02443648078333877}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:47,848] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 44, 'n_neurons_layer1': 66, 'activation': 'logistic', 'solver': 'adam', 'alpha': 4.069975060930683e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:47,920] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 11, 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.817970344921882e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:48,432] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 64, 'n_neurons_layer1': 43, 'n_neurons_layer2': 33, 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008573524113363012}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:48,968] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 70, 'n_neurons_layer1': 79, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00023887328867435294}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:49,278] Trial 7 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 92, 'activation': 'logistic', 'solver': 'adam', 'alpha': 1.7877448541531762e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:49,313] Trial 8 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 62, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.006450072252355851}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:49,429] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 30, 'n_neurons_layer1': 75, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.06853598726863287}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 14:54:49,742] Trial 10 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 100, 'n_neurons_layer1': 2, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.018629744113946155}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:49,866] Trial 11 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 2, 'n_neurons_layer1': 10, 'n_neurons_layer2': 95, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.020401318147282608}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:50,415] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 95, 'n_neurons_layer1': 25, 'n_neurons_layer2': 84, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.019398295045928316}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:50,636] Trial 13 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 18, 'n_neurons_layer1': 26, 'n_neurons_layer2': 63, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.001683024679083444}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:51,034] Trial 14 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 50, 'n_neurons_layer1': 19, 'n_neurons_layer2': 66, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.07308866698385663}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:51,477] Trial 15 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 17, 'n_neurons_layer1': 39, 'n_neurons_layer2': 65, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.014528026995003057}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:51,755] Trial 16 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 85, 'n_neurons_layer1': 96, 'n_neurons_layer2': 81, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0015890430591211943}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:51,945] Trial 17 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 24, 'n_neurons_layer1': 39, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.004467226020933812}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:52,122] Trial 18 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 8, 'n_neurons_layer1': 12, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.005900990302222537}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:52,371] Trial 19 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 55, 'n_neurons_layer1': 3, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0064412095556390095}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:52,764] Trial 20 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 81, 'n_neurons_layer1': 33, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.04986993732655029}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:52,884] Trial 21 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 50, 'n_neurons_layer1': 54, 'n_neurons_layer2': 14, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.028611691514384703}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:54:52,951] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 82, 'n_neurons_layer1': 53, 'n_neurons_layer2': 36, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.05416694143808467}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:54:53,790] Trial 23 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 72, 'n_neurons_layer1': 94, 'n_neurons_layer2': 7, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.08650218650895644}. Best is trial 23 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 14:55:51,584] Trial 24 finished with value: 0.44155844155844154 and parameters: {'n_layers': 3, 'n_neurons_layer0': 69, 'n_neurons_layer1': 91, 'n_neurons_layer2': 100, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.024161794467671274}. Best is trial 23 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 14:55:51,932] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 42, 'n_neurons_layer1': 86, 'n_neurons_layer2': 1, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.03472556676559459}. Best is trial 23 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

{'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.08650218650895644, 'hidden_layer_sizes': [72, 94, 7]}
Classification report saved as results/Continent/data_14/data_14_umap_mlp_classification_report_2026-10-19_14-59-54.txt
    Accuracy: 0.4675, Time: 307.54s
  - Testing classifier: nb

[I 2026-10-19 14:59:54,520] Trial 12 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.9146665244651e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,522] Trial 13 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.5318505696618466e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,525] Trial 14 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.958428366760386e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,527] Trial 15 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.8011450694084183e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,530] Trial 16 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.337988831762396e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,532] Trial 17 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.4373102760631046e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,535] Trial 18 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0003602420399732665}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,537] Trial 19 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.510962414027005e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,540] Trial 20 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.082662217850968e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,542] Trial 21 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.4836108198215845e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,545] Trial 22 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.000188970775986911}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,547] Trial 23 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.2047024334145253e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,550] Trial 24 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.006324700020499407}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,553] Trial 25 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.3325362628700423e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,555] Trial 26 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.9989399662724805e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,558] Trial 27 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 7.447119661875776e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,560] Trial 28 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.0706597236481187e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,563] Trial 29 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 6.952528765008977e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,565] Trial 30 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 8.780615640140171e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,568] Trial 31 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.884819960558071e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,570] Trial 32 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.6661433988404187e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,572] Trial 33 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0010798147858349725}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,574] Trial 34 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.8176460767245087e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,576] Trial 35 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.1292732788200278e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,579] Trial 36 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 6.0295666509083015e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,581] Trial 37 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 7.799416714053644e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,583] Trial 38 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.7411500452537954e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,586] Trial 39 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.87037365887577e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,588] Trial 40 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.8283952470975317e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,590] Trial 41 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.2649192035507166e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,593] Trial 42 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.849092363874581e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,595] Trial 43 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.05815780755363e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,597] Trial 44 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.0928038981961915e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,600] Trial 45 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.248035817278621e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,602] Trial 46 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.006202796593383e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,604] Trial 47 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0007015085860073733}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,607] Trial 48 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.064955818056257e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,609] Trial 49 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.2550977414131485e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,612] Trial 50 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.199174506972039e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,614] Trial 51 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.5929620319821047e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,616] Trial 52 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0001717684414684143}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,619] Trial 53 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0060252952109207695}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,621] Trial 54 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0013619970421333183}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,623] Trial 55 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.5326699339367992e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,626] Trial 56 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 7.866119461715731e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,628] Trial 57 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.9956812021868094e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,630] Trial 58 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.003379551560185189}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,633] Trial 59 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.00028630388893845373}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,635] Trial 60 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 8.770592936208681e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,637] Trial 61 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.3647021180569916e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,640] Trial 62 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.0596911189329385e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,642] Trial 63 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 7.855392957301948e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,644] Trial 64 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.635164589495554e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,647] Trial 65 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 9.810470254761247e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,649] Trial 66 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.612404643090265e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,651] Trial 67 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.003292400158572e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,654] Trial 68 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.893371293640839e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,656] Trial 69 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.0775790641029666e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,659] Trial 70 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.4565671467338053e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,661] Trial 71 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 8.290039788898634e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,663] Trial 72 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.2547114500079096e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,666] Trial 73 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.763711575049485e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,668] Trial 74 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.4354601919449984e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,670] Trial 75 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.3587179135679264e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,673] Trial 76 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.7191821328436418e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,675] Trial 77 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.280826698246816e-07}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,678] Trial 78 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 8.46937588508148e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,680] Trial 79 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 9.519662495792664e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,682] Trial 80 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.1401066101628924e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,685] Trial 81 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.855276423973713e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,687] Trial 82 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.6965955007461756e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,690] Trial 83 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.213353825465492e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,692] Trial 84 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 6.482173526535327e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,694] Trial 85 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.8872419874507864e-12}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,697] Trial 86 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.298547485545633e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,699] Trial 87 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 5.631383741265194e-08}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,702] Trial 88 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0026369221920708123}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,704] Trial 89 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.0006102795483313294}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,707] Trial 90 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.057301286233084e-05}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,709] Trial 91 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 6.657288066621964e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,711] Trial 92 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 4.5096817398875993e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,714] Trial 93 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 3.7299979777563403e-06}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,716] Trial 94 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.009607672929771476}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,719] Trial 95 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.3957265361250836e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,721] Trial 96 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.9174568159490578e-09}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,724] Trial 97 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 2.6953621339730445e-10}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,726] Trial 98 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 1.943865937179908e-11}. Best is trial 0 with value: 0.38961038961038963.
[I 2026-10-19 14:59:54,729] Trial 99 finished with value: 0.38961038961038963 and parameters: {'var_smoothing': 0.00014955013882849287}. Best is trial 0 with value: 0.38961038961038963.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 3.849262313097257e-09}
Best validation accuracy:  0.38961038961038963
Test accuracy: 0.4155844155844156
Time taken: 0.0011343955993652344 seconds
Classification report saved as results/Continent/data_14/data_14_umap_nb_classification_report_2026-10-19_14-59-54.txt
    Accuracy: 0.4156, Time: 0.24s

Evaluating embedding method: pca

[I 2026-10-19 14:59:56,167] A new study created in memory with name: no-name-e4c5b022-487e-45a0-b174-f2b3e44dce26
[I 2026-10-19 14:59:56,182] Trial 0 finished with value: 0.4675324675324675 and parameters: {'C': 9.955825070849785e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6082601338438572}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,198] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 1.9632208432520715e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07274501954066448}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,214] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 2.2342391689714935e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7561454725133063}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,229] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 0.03716165042972695, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4374888523265027}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,276] Trial 4 finished with value: 0.2987012987012987 and parameters: {'C': 48.99434943875393, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.768344136737241}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,294] Trial 5 finished with value: 0.4675324675324675 and parameters: {'C': 0.0002253632148141786, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9471900180477003}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,311] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 8.15164760090436e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.445539632698702}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,329] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 3.063724417304235e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9149306937986724}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,347] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 0.0008638107980207366, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9085595490309292}. Best is trial 0 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 14:59:56,384] Trial 9 finished with value: 0.2987012987012987 and parameters: {'C': 32.0445311303913, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.751147721818731}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,405] Trial 10 finished with value: 0.4675324675324675 and parameters: {'C': 8.979351530028393e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4066686250706383}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,426] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 6.633845093802028e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.002735857762648064}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,447] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 3.2779102656941167e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3824739977025723}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,468] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 1.671127343794294e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.648482773352551}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,488] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 0.017871303072711696, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5976241976294427}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,509] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 0.004472052093988297, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1985384541944327}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,529] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 1.189106951100491e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7895876108719548}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 14:59:56,788] Trial 17 finished with value: 0.4805194805194805 and parameters: {'C': 8.85733090517884, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.20484009356330432}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:56,960] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 3.003640138479499, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2686978685471214}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:57,399] Trial 19 finished with value: 0.4805194805194805 and parameters: {'C': 560.5973886012458, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5922608807827744}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:57,854] Trial 20 finished with value: 0.4805194805194805 and parameters: {'C': 320.5746727425228, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9605414113340508}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:58,290] Trial 21 finished with value: 0.4805194805194805 and parameters: {'C': 691.1614714060526, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9322563189370523}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:58,725] Trial 22 finished with value: 0.4805194805194805 and parameters: {'C': 120.03490087276384, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6063142891639878}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:58,992] Trial 23 finished with value: 0.4805194805194805 and parameters: {'C': 4.697178715812101, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.826328654114468}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:59,407] Trial 24 finished with value: 0.4805194805194805 and parameters: {'C': 184.76925323860752, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.060503755675479304}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:59,429] Trial 25 finished with value: 0.2987012987012987 and parameters: {'C': 382.4489059781875, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3296440225383029}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:59,490] Trial 26 finished with value: 0.4805194805194805 and parameters: {'C': 0.5929322420784462, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9997477167590608}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 14:59:59,934] Trial 27 finished with value: 0.4805194805194805 and parameters: {'C': 781.232764432357, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8234505331662356}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:00,066] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 1.7112620455990404, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5449848412797174}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:00,503] Trial 29 finished with value: 0.4805194805194805 and parameters: {'C': 598.1930053412633, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4964918940377485}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:00,918] Trial 30 finished with value: 0.4805194805194805 and parameters: {'C': 74.41200279460112, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3693223105126415}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:01,406] Trial 31 finished with value: 0.4805194805194805 and parameters: {'C': 91.11170051987884, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.905154336199937}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:01,437] Trial 32 finished with value: 0.2987012987012987 and parameters: {'C': 18.803022853654706, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.09471083254564631}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:01,457] Trial 33 finished with value: 0.2987012987012987 and parameters: {'C': 933.0860236914891, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.951768546679737}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:01,927] Trial 34 finished with value: 0.4805194805194805 and parameters: {'C': 82.73811404126695, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7257137022419454}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:02,351] Trial 35 finished with value: 0.4805194805194805 and parameters: {'C': 765.7393778958543, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7296275570293715}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:02,402] Trial 36 finished with value: 0.2987012987012987 and parameters: {'C': 35.81168351798965, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.48078625382942736}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:02,423] Trial 37 finished with value: 0.3246753246753247 and parameters: {'C': 0.2593777621037525, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7969593983730131}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:02,454] Trial 38 finished with value: 0.4805194805194805 and parameters: {'C': 0.17382792815676365, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3255334108986404}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:02,878] Trial 39 finished with value: 0.4805194805194805 and parameters: {'C': 505.5237323288216, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9609877386484889}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:03,322] Trial 40 finished with value: 0.4805194805194805 and parameters: {'C': 899.727023237468, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26751175770888713}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:03,344] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.022992639588453604, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8099064352730062}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:03,610] Trial 42 finished with value: 0.4805194805194805 and parameters: {'C': 8.786231431638116, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07760361329167564}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:04,044] Trial 43 finished with value: 0.4805194805194805 and parameters: {'C': 668.8630869050832, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6553144410064952}. Best is trial 17 with value: 0.4805194805194805.
[I 2026-10-19 15:00:04,076] Trial 44 finished with value: 0.5064935064935064 and parameters: {'C': 0.18993458645422995, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8637791988628538}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,127] Trial 45 finished with value: 0.4805194805194805 and parameters: {'C': 0.3760231936601327, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8753745490445908}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,158] Trial 46 finished with value: 0.2987012987012987 and parameters: {'C': 31.696662752491864, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9166693626627169}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,563] Trial 47 finished with value: 0.4805194805194805 and parameters: {'C': 33.97529960892551, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9741575594734361}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,585] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.014478930290084256, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9006086312457807}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,617] Trial 49 finished with value: 0.4935064935064935 and parameters: {'C': 0.16276063256686685, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.696747235392016}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:04,971] Trial 50 finished with value: 0.4805194805194805 and parameters: {'C': 28.68385540341169, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.24161056234995698}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,003] Trial 51 finished with value: 0.4935064935064935 and parameters: {'C': 0.14218335162774945, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6740304009554889}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,044] Trial 52 finished with value: 0.4805194805194805 and parameters: {'C': 0.29010237910078934, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7065117471285702}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,065] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 0.0011941206282372232, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5423937837408739}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,086] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.0018682545302863166, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7650657085911099}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,509] Trial 55 finished with value: 0.4805194805194805 and parameters: {'C': 45.02061098627316, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8060119976580254}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,843] Trial 56 finished with value: 0.4805194805194805 and parameters: {'C': 11.063264336294417, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6965533158004515}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,875] Trial 57 finished with value: 0.3116883116883117 and parameters: {'C': 0.31260222562360374, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6225705489627557}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,896] Trial 58 finished with value: 0.2987012987012987 and parameters: {'C': 360.16631256555394, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7926970243345186}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,927] Trial 59 finished with value: 0.4805194805194805 and parameters: {'C': 0.17255199498660706, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6421759803029717}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:05,948] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.04753343145681433, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7126357068038479}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:06,392] Trial 61 finished with value: 0.4805194805194805 and parameters: {'C': 439.06574180072784, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8826624568943511}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:06,575] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 2.24655359063976, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9302218503492568}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:06,596] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.00108467960017044, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7151470663021328}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:06,617] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.004188464792102338, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6415563739121405}. Best is trial 44 with value: 0.5064935064935064.
[I 2026-10-19 15:00:06,638] Trial 65 finished with value: 0.5194805194805194 and parameters: {'C': 0.09893640798995565, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.583973984422916}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,032] Trial 66 finished with value: 0.4805194805194805 and parameters: {'C': 30.193790106232672, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5756438721192336}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,456] Trial 67 finished with value: 0.4805194805194805 and parameters: {'C': 117.6541515579197, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5055213613616488}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,477] Trial 68 finished with value: 0.5194805194805194 and parameters: {'C': 0.09723884843876014, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7621824583969337}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,498] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.00023867405485243582, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6213135513907817}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,518] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.004191545039269352, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8171305602135438}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,538] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.019093310662615357, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.749735980218038}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,560] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.0009391951562722742, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8271509666003376}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:07,741] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 2.5328525132452273, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6876538439561074}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,023] Trial 74 finished with value: 0.4805194805194805 and parameters: {'C': 8.412679131516379, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.47668349641048835}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,095] Trial 75 finished with value: 0.2987012987012987 and parameters: {'C': 113.39782685152478, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.994533072501224}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,167] Trial 76 finished with value: 0.4805194805194805 and parameters: {'C': 0.7168364230488988, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7707763257369459}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,189] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.006553642502026388, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5202820128866923}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,552] Trial 78 finished with value: 0.4805194805194805 and parameters: {'C': 12.492930401796459, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8733764069434216}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,876] Trial 79 finished with value: 0.4805194805194805 and parameters: {'C': 21.56199843430405, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01760306364672723}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,908] Trial 80 finished with value: 0.4935064935064935 and parameters: {'C': 0.14318860394665772, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5743301071205335}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,950] Trial 81 finished with value: 0.4675324675324675 and parameters: {'C': 0.14995492418980755, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1341694265123436}. Best is trial 65 with value: 0.5194805194805194.
[I 2026-10-19 15:00:08,971] Trial 82 finished with value: 0.4675324675324675 and parameters: {'C': 0.030349323036169103, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9773183571384836}. Best is trial 65 with value: 0.5194805194805194.

0.01703810691833496  seconds
Classification report saved as results/Continent/data_30/data_30_pca_logreg_classification_report.txt
    Accuracy: 0.5195, Time: 14.73s
  - Testing classifier: dt

[I 2026-10-19 15:00:11,092] Trial 44 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,096] Trial 45 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,101] Trial 46 finished with value: 0.33766233766233766 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,105] Trial 47 finished with value: 0.36363636363636365 and parameters: {'max_depth': 26, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,110] Trial 48 finished with value: 0.37662337662337664 and parameters: {'max_depth': 8, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,114] Trial 49 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,119] Trial 50 finished with value: 0.3246753246753247 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,122] Trial 51 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,126] Trial 52 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,131] Trial 53 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,135] Trial 54 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,139] Trial 55 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,142] Trial 56 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,146] Trial 57 finished with value: 0.3246753246753247 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,151] Trial 58 finished with value: 0.35064935064935066 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,155] Trial 59 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,161] Trial 60 finished with value: 0.36363636363636365 and parameters: {'max_depth': 14, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,164] Trial 61 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,169] Trial 62 finished with value: 0.35064935064935066 and parameters: {'max_depth': 16, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,172] Trial 63 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,176] Trial 64 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,182] Trial 65 finished with value: 0.37662337662337664 and parameters: {'max_depth': 8, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,186] Trial 66 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,191] Trial 67 finished with value: 0.33766233766233766 and parameters: {'max_depth': 20, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,194] Trial 68 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,198] Trial 69 finished with value: 0.36363636363636365 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,203] Trial 70 finished with value: 0.4155844155844156 and parameters: {'max_depth': 21, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,209] Trial 71 finished with value: 0.35064935064935066 and parameters: {'max_depth': 31, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,213] Trial 72 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,216] Trial 73 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,220] Trial 74 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,224] Trial 75 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,228] Trial 76 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,233] Trial 77 finished with value: 0.3246753246753247 and parameters: {'max_depth': 27, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,238] Trial 78 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,242] Trial 79 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,246] Trial 80 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,250] Trial 81 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,254] Trial 82 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,259] Trial 83 finished with value: 0.3246753246753247 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,263] Trial 84 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,266] Trial 85 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,269] Trial 86 finished with value: 0.45454545454545453 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,274] Trial 87 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,279] Trial 88 finished with value: 0.2987012987012987 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,283] Trial 89 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,288] Trial 90 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,292] Trial 91 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,296] Trial 92 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,300] Trial 93 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,304] Trial 94 finished with value: 0.35064935064935066 and parameters: {'max_depth': 18, 'criterion': 'gini'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,308] Trial 95 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,312] Trial 96 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,316] Trial 97 finished with value: 0.45454545454545453 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,320] Trial 98 finished with value: 0.44155844155844154 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
[I 2026-10-19 15:00:11,325] Trial 99 finished with value: 0.3116883116883117 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 10 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:00:11,331] A new study created in memory with name: no-name-baba83dc-9438-4d00-a779-f15be4123ced

0.0019044876098632812  seconds
Classification report saved as results/Continent/data_30/data_30_pca_dt_classification_report.txt
    Accuracy: 0.4675, Time: 0.44s
  - Testing classifier: rf

[I 2026-10-19 15:00:11,548] Trial 0 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 194, 'max_depth': 24}. Best is trial 0 with value: 0.5584415584415584.
[I 2026-10-19 15:00:11,599] Trial 1 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 45, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:11,812] Trial 2 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 196, 'max_depth': 15}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:11,948] Trial 3 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,047] Trial 4 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,075] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 27, 'max_depth': 6}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,205] Trial 6 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 130, 'max_depth': 7}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,364] Trial 7 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 157, 'max_depth': 7}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,540] Trial 8 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 174, 'max_depth': 7}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,662] Trial 9 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 136, 'max_depth': 4}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,693] Trial 10 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 25, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,893] Trial 11 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 180, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:12,933] Trial 12 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 34, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,021] Trial 13 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 78, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,174] Trial 14 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 139, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,195] Trial 15 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 16, 'max_depth': 14}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,265] Trial 16 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 62, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,423] Trial 17 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 144, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,477] Trial 18 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 48, 'max_depth': 11}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,652] Trial 19 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 161, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,668] Trial 20 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 12, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,774] Trial 21 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 96, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:13,883] Trial 22 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 98, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,037] Trial 23 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 140, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,244] Trial 24 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 190, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,366] Trial 25 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 110, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,448] Trial 26 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 90, 'max_depth': 4}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,623] Trial 27 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 161, 'max_depth': 14}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,755] Trial 28 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 120, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:14,967] Trial 29 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 195, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,138] Trial 30 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 157, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,314] Trial 31 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 161, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,497] Trial 32 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 175, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,700] Trial 33 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 195, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,849] Trial 34 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 141, 'max_depth': 20}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:15,933] Trial 35 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 78, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,031] Trial 36 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 91, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,087] Trial 37 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 51, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,106] Trial 38 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 15, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,183] Trial 39 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 71, 'max_depth': 16}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,347] Trial 40 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 155, 'max_depth': 17}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,458] Trial 41 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 105, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,589] Trial 42 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 124, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,672] Trial 43 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 77, 'max_depth': 20}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,766] Trial 44 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 87, 'max_depth': 29}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,855] Trial 45 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 83, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,911] Trial 46 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 51, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:16,985] Trial 47 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 68, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,024] Trial 48 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 34, 'max_depth': 27}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,081] Trial 49 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 51, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,261] Trial 50 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 172, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,471] Trial 51 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 200, 'max_depth': 19}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,528] Trial 52 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 51, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,685] Trial 53 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 149, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,705] Trial 54 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 15, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,824] Trial 55 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 112, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,961] Trial 56 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 129, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:17,996] Trial 57 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 30, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,068] Trial 58 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 66, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,093] Trial 59 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 21, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,204] Trial 60 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 104, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,361] Trial 61 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 148, 'max_depth': 24}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,494] Trial 62 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 126, 'max_depth': 15}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,678] Trial 63 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 175, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,797] Trial 64 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 112, 'max_depth': 30}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:18,975] Trial 65 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 169, 'max_depth': 24}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,168] Trial 66 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 183, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,240] Trial 67 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 65, 'max_depth': 30}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,255] Trial 68 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 11, 'max_depth': 20}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,335] Trial 69 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 74, 'max_depth': 27}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,453] Trial 70 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 110, 'max_depth': 24}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,603] Trial 71 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 142, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,751] Trial 72 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 139, 'max_depth': 29}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:19,926] Trial 73 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 165, 'max_depth': 29}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,070] Trial 74 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 136, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,163] Trial 75 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 86, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,329] Trial 76 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 155, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,526] Trial 77 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 175, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,639] Trial 78 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 100, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,771] Trial 79 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 119, 'max_depth': 18}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:20,920] Trial 80 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 133, 'max_depth': 25}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,100] Trial 81 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 163, 'max_depth': 27}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,203] Trial 82 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 92, 'max_depth': 27}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,279] Trial 83 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 67, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,497] Trial 84 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 199, 'max_depth': 29}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,595] Trial 85 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 87, 'max_depth': 20}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,626] Trial 86 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 25, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,675] Trial 87 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 41, 'max_depth': 22}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,726] Trial 88 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 44, 'max_depth': 19}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,861] Trial 89 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 125, 'max_depth': 27}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:21,991] Trial 90 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 121, 'max_depth': 21}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,155] Trial 91 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 154, 'max_depth': 26}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,278] Trial 92 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 115, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,384] Trial 93 finished with value: 0.5714285714285714 and parameters: {'n_estimators': 97, 'max_depth': 31}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,581] Trial 94 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 186, 'max_depth': 20}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,680] Trial 95 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 91, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,787] Trial 96 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 99, 'max_depth': 28}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:22,896] Trial 97 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 101, 'max_depth': 30}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:23,084] Trial 98 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 178, 'max_depth': 23}. Best is trial 1 with value: 0.5714285714285714.
[I 2026-10-19 15:00:23,215] Trial 99 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 122, 'max_depth': 32}. Best is trial 1 with value: 0.5714285714285714.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:00:23,268] A new study created in memory with name: no-name-3d8512a5-99d9-4699-b795-d4f65e61c014
[I 2026-10-19 15:00:23,270] Trial 0 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.5194805194805194.
[I 2026-10-19 15:00:23,273] Trial 1 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 0 with value: 0.5194805194805194.
[I 2026-10-19 15:00:23,276] Trial 2 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 2 with value: 0.5714285714285714.

0.04799222946166992  seconds
Classification report saved as results/Continent/data_30/data_30_pca_rf_classification_report.txt
    Accuracy: 0.5065, Time: 11.94s
  - Testing classifier: knn

[I 2026-10-19 15:00:23,471] Trial 58 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,474] Trial 59 finished with value: 0.5454545454545454 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,479] Trial 60 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,483] Trial 61 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,487] Trial 62 finished with value: 0.5324675324675324 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,492] Trial 63 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,496] Trial 64 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,501] Trial 65 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,505] Trial 66 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,510] Trial 67 finished with value: 0.5324675324675324 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,514] Trial 68 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,520] Trial 69 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,525] Trial 70 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,531] Trial 71 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,538] Trial 72 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,544] Trial 73 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,550] Trial 74 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,554] Trial 75 finished with value: 0.5324675324675324 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,561] Trial 76 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,567] Trial 77 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,573] Trial 78 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,579] Trial 79 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,584] Trial 80 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,590] Trial 81 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,595] Trial 82 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,601] Trial 83 finished with value: 0.5324675324675324 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,607] Trial 84 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,612] Trial 85 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,618] Trial 86 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,622] Trial 87 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,627] Trial 88 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,632] Trial 89 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,636] Trial 90 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,642] Trial 91 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,647] Trial 92 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,651] Trial 93 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,656] Trial 94 finished with value: 0.5844155844155844 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,660] Trial 95 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,663] Trial 96 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,667] Trial 97 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,671] Trial 98 finished with value: 0.5584415584415584 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
[I 2026-10-19 15:00:23,676] Trial 99 finished with value: 0.5714285714285714 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 46 with value: 0.5844155844155844.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:00:23,683] A new study created in memory with name: no-name-60f5853a-d967-4414-b799-0c45301428fe
[I 2026-10-19 15:00:23,797] Trial 0 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 146, 'learning_rate': 0.6112760780345944, 'max_depth': 5, 'min_child_weight': 1.4163251081515345, 'subsample': 0.11586018454964536, 'colsample_bytree': 0.4602679645874247}. Best is trial 0 with value: 0.4155844155844156.

0.00222015380859375  seconds
Classification report saved as results/Continent/data_30/data_30_pca_knn_classification_report.txt
    Accuracy: 0.5844, Time: 0.42s
  - Testing classifier: xgboost

[I 2026-10-19 15:00:23,911] Trial 1 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 118, 'learning_rate': 0.2916668195112011, 'max_depth': 14, 'min_child_weight': 8.902677013370615, 'subsample': 0.9756423905750491, 'colsample_bytree': 0.5953755005051392}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 15:00:23,931] Trial 2 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 38, 'learning_rate': 0.2332376377004275, 'max_depth': 3, 'min_child_weight': 9.97890343134399, 'subsample': 0.10691013830151605, 'colsample_bytree': 0.8791456915425033}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 15:00:23,949] Trial 3 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 33, 'learning_rate': 0.5475846536442732, 'max_depth': 19, 'min_child_weight': 7.866953016184934, 'subsample': 0.11111743751676731, 'colsample_bytree': 0.3825216089834289}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 15:00:24,114] Trial 4 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 197, 'learning_rate': 0.6322793301909914, 'max_depth': 18, 'min_child_weight': 2.0446011653725713, 'subsample': 0.9375437227312421, 'colsample_bytree': 0.5005717884703749}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,215] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 195, 'learning_rate': 0.2535786500096576, 'max_depth': 25, 'min_child_weight': 6.335867603029234, 'subsample': 0.12761535370301594, 'colsample_bytree': 0.3237752605897969}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,263] Trial 6 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 73, 'learning_rate': 0.8971260516236427, 'max_depth': 4, 'min_child_weight': 4.963346068821465, 'subsample': 0.21068617976309523, 'colsample_bytree': 0.710481059116204}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,345] Trial 7 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 87, 'learning_rate': 0.927849400792624, 'max_depth': 24, 'min_child_weight': 2.1825934086205505, 'subsample': 0.971513518207474, 'colsample_bytree': 0.6419403543077685}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,403] Trial 8 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 54, 'learning_rate': 0.9183553841495473, 'max_depth': 8, 'min_child_weight': 4.4036647164686284, 'subsample': 0.9527254451913214, 'colsample_bytree': 0.24693386580862697}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,472] Trial 9 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 61, 'learning_rate': 0.42361453286577627, 'max_depth': 12, 'min_child_weight': 5.6225953876838615, 'subsample': 0.7669879867370334, 'colsample_bytree': 0.2523528416738021}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,590] Trial 10 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 160, 'learning_rate': 0.7660665832110845, 'max_depth': 19, 'min_child_weight': 6.64954332296273, 'subsample': 0.4839428712357109, 'colsample_bytree': 0.31657689627801244}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,678] Trial 11 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 90, 'learning_rate': 0.39270893187459455, 'max_depth': 21, 'min_child_weight': 9.869599482111122, 'subsample': 0.8251021053438643, 'colsample_bytree': 0.6556801459010884}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,809] Trial 12 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 172, 'learning_rate': 0.8453273894436277, 'max_depth': 11, 'min_child_weight': 7.018541972500592, 'subsample': 0.9337067677758282, 'colsample_bytree': 0.6506645108822054}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:24,997] Trial 13 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 182, 'learning_rate': 0.4532587665701969, 'max_depth': 16, 'min_child_weight': 1.2324509683711111, 'subsample': 0.823625978569924, 'colsample_bytree': 0.5983465200135097}. Best is trial 4 with value: 0.5064935064935064.
[I 2026-10-19 15:00:25,147] Trial 14 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 182, 'learning_rate': 0.9288512098297597, 'max_depth': 15, 'min_child_weight': 1.5432870558357026, 'subsample': 0.8902943853752102, 'colsample_bytree': 0.7641404842047378}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:25,304] Trial 15 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 187, 'learning_rate': 0.8117506004006287, 'max_depth': 13, 'min_child_weight': 1.453340894765636, 'subsample': 0.9791660646808706, 'colsample_bytree': 0.451097661418542}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:25,431] Trial 16 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 130, 'learning_rate': 0.6925413401775637, 'max_depth': 15, 'min_child_weight': 1.3270368594725641, 'subsample': 0.8346165233130979, 'colsample_bytree': 0.7439876158056883}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:25,576] Trial 17 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 184, 'learning_rate': 0.8009345878651655, 'max_depth': 23, 'min_child_weight': 2.503425670731638, 'subsample': 0.7999841294357578, 'colsample_bytree': 0.5358454787790139}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:25,722] Trial 18 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 178, 'learning_rate': 0.7775695784878957, 'max_depth': 6, 'min_child_weight': 1.9738055953686826, 'subsample': 0.9807860858605468, 'colsample_bytree': 0.6241201563249503}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:25,909] Trial 19 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 199, 'learning_rate': 0.6071073107727015, 'max_depth': 22, 'min_child_weight': 1.2932112685152326, 'subsample': 0.8232889718565941, 'colsample_bytree': 0.2849571172167272}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,083] Trial 20 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 181, 'learning_rate': 0.40947207545576525, 'max_depth': 8, 'min_child_weight': 2.6569514384375132, 'subsample': 0.9834573618033837, 'colsample_bytree': 0.6827823301284439}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,222] Trial 21 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 191, 'learning_rate': 0.8644146179224452, 'max_depth': 20, 'min_child_weight': 6.019974246220885, 'subsample': 0.7296569489409184, 'colsample_bytree': 0.5274967650815662}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,400] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 145, 'learning_rate': 0.31655826723823277, 'max_depth': 21, 'min_child_weight': 1.348459042572273, 'subsample': 0.8922741597504767, 'colsample_bytree': 0.4393777052553953}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,540] Trial 23 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 171, 'learning_rate': 0.5743028351412911, 'max_depth': 15, 'min_child_weight': 7.380324501548381, 'subsample': 0.9093980322413686, 'colsample_bytree': 0.5054580062472268}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,678] Trial 24 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 157, 'learning_rate': 0.6647989704306403, 'max_depth': 20, 'min_child_weight': 2.7753055664938877, 'subsample': 0.9816930856334882, 'colsample_bytree': 0.6556591604921228}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,828] Trial 25 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 199, 'learning_rate': 0.8816544620887778, 'max_depth': 16, 'min_child_weight': 3.31641277383889, 'subsample': 0.9719425013254751, 'colsample_bytree': 0.548873064681808}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:26,958] Trial 26 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 151, 'learning_rate': 0.6859944324207563, 'max_depth': 19, 'min_child_weight': 4.362409249213206, 'subsample': 0.8833079385275071, 'colsample_bytree': 0.3621427796827481}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,108] Trial 27 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 180, 'learning_rate': 0.5861090468947019, 'max_depth': 13, 'min_child_weight': 5.171925454704487, 'subsample': 0.9331211164410868, 'colsample_bytree': 0.5942550308605613}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,241] Trial 28 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 169, 'learning_rate': 0.9155761203493419, 'max_depth': 17, 'min_child_weight': 2.5674312422488677, 'subsample': 0.8672409071468237, 'colsample_bytree': 0.8812987632058753}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,378] Trial 29 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 189, 'learning_rate': 0.973322949820862, 'max_depth': 21, 'min_child_weight': 4.562393597465497, 'subsample': 0.9372654388733069, 'colsample_bytree': 0.6495532435944222}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,548] Trial 30 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 198, 'learning_rate': 0.4827387771594155, 'max_depth': 18, 'min_child_weight': 4.5642647881244685, 'subsample': 0.9272764653694257, 'colsample_bytree': 0.5430468246385951}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,725] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 199, 'learning_rate': 0.6021709089194077, 'max_depth': 22, 'min_child_weight': 1.5796414220226473, 'subsample': 0.9051831202955123, 'colsample_bytree': 0.4823605364186121}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,832] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 123, 'learning_rate': 0.9241790337331908, 'max_depth': 21, 'min_child_weight': 2.036794218092492, 'subsample': 0.802326727931276, 'colsample_bytree': 0.6988674503504041}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:27,921] Trial 33 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 89, 'learning_rate': 0.9082463024874081, 'max_depth': 12, 'min_child_weight': 1.9203696937208625, 'subsample': 0.9240920193657892, 'colsample_bytree': 0.679388173680222}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,009] Trial 34 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 87, 'learning_rate': 0.858490409539617, 'max_depth': 20, 'min_child_weight': 2.104861156352449, 'subsample': 0.9351934082594004, 'colsample_bytree': 0.7505526389086741}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,145] Trial 35 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 181, 'learning_rate': 0.9925985513003703, 'max_depth': 9, 'min_child_weight': 3.034430897598336, 'subsample': 0.9310317354517512, 'colsample_bytree': 0.5904519475617063}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,300] Trial 36 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 194, 'learning_rate': 0.6724876513717277, 'max_depth': 17, 'min_child_weight': 3.1192122304610823, 'subsample': 0.8923651248734776, 'colsample_bytree': 0.6679247833176936}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,413] Trial 37 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 133, 'learning_rate': 0.9265055913339839, 'max_depth': 19, 'min_child_weight': 3.2696232844222832, 'subsample': 0.9909620251559084, 'colsample_bytree': 0.6431764900969233}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,568] Trial 38 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 157, 'learning_rate': 0.5881569390197432, 'max_depth': 21, 'min_child_weight': 1.1488927395506987, 'subsample': 0.79435776046017, 'colsample_bytree': 0.5224083364862361}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,725] Trial 39 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 186, 'learning_rate': 0.6396557244368345, 'max_depth': 21, 'min_child_weight': 2.364412131799395, 'subsample': 0.7663608136601322, 'colsample_bytree': 0.4376125210606451}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,856] Trial 40 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 164, 'learning_rate': 0.9604473035309674, 'max_depth': 18, 'min_child_weight': 2.32691768373164, 'subsample': 0.9307519129544986, 'colsample_bytree': 0.574739501666036}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:28,958] Trial 41 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 114, 'learning_rate': 0.8897774022495428, 'max_depth': 20, 'min_child_weight': 3.0661862135628626, 'subsample': 0.8567553352193115, 'colsample_bytree': 0.5665684142738986}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,104] Trial 42 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 176, 'learning_rate': 0.7476679577649972, 'max_depth': 19, 'min_child_weight': 2.66355629198707, 'subsample': 0.924407981039959, 'colsample_bytree': 0.588726823234091}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,247] Trial 43 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 183, 'learning_rate': 0.9256505378313391, 'max_depth': 15, 'min_child_weight': 2.07904151056319, 'subsample': 0.9612723527502032, 'colsample_bytree': 0.7435241578873388}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,364] Trial 44 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 131, 'learning_rate': 0.9385161725394504, 'max_depth': 16, 'min_child_weight': 1.504465127002477, 'subsample': 0.925856683469806, 'colsample_bytree': 0.7692841896832088}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,447] Trial 45 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 82, 'learning_rate': 0.8680297701061023, 'max_depth': 27, 'min_child_weight': 2.8679240673929365, 'subsample': 0.9490952612290412, 'colsample_bytree': 0.7013985443680824}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,639] Trial 46 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 200, 'learning_rate': 0.4440900138594256, 'max_depth': 25, 'min_child_weight': 1.7613982590449975, 'subsample': 0.9048765066890943, 'colsample_bytree': 0.4217485212286635}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,719] Trial 47 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 74, 'learning_rate': 0.8500664424190826, 'max_depth': 26, 'min_child_weight': 1.9328870010726171, 'subsample': 0.8345157263027745, 'colsample_bytree': 0.7326664102998985}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,790] Trial 48 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 63, 'learning_rate': 0.9223603186787199, 'max_depth': 23, 'min_child_weight': 1.9193291682558518, 'subsample': 0.972833149964235, 'colsample_bytree': 0.5248425767791791}. Best is trial 14 with value: 0.5194805194805194.
[I 2026-10-19 15:00:29,891] Trial 49 finished with value: 0.5454545454545454 and parameters: {'n_estimators': 99, 'learning_rate': 0.8253269836290408, 'max_depth': 25, 'min_child_weight': 1.6872521738042292, 'subsample': 0.9691441543732677, 'colsample_bytree': 0.608695465733192}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,032] Trial 50 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 189, 'learning_rate': 0.9143044565771108, 'max_depth': 14, 'min_child_weight': 2.573595465152984, 'subsample': 0.7895963164249576, 'colsample_bytree': 0.794627176979191}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,123] Trial 51 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 92, 'learning_rate': 0.9256419141190846, 'max_depth': 31, 'min_child_weight': 1.9041699977395832, 'subsample': 0.9492934126955628, 'colsample_bytree': 0.7316821838437907}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,226] Trial 52 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 112, 'learning_rate': 0.9761931783398203, 'max_depth': 27, 'min_child_weight': 1.5020838666633858, 'subsample': 0.8417605460714481, 'colsample_bytree': 0.6356320491153431}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,324] Trial 53 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 103, 'learning_rate': 0.9936403328153172, 'max_depth': 25, 'min_child_weight': 1.2401302901926323, 'subsample': 0.7909154350296485, 'colsample_bytree': 0.6617105557679843}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,467] Trial 54 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 190, 'learning_rate': 0.977614071356724, 'max_depth': 14, 'min_child_weight': 2.027681444823594, 'subsample': 0.895693742584144, 'colsample_bytree': 0.8120054368222769}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,592] Trial 55 finished with value: 0.5324675324675324 and parameters: {'n_estimators': 143, 'learning_rate': 0.9464799461678111, 'max_depth': 12, 'min_child_weight': 1.2060579532477786, 'subsample': 0.8671929116080395, 'colsample_bytree': 0.7825242454090935}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,708] Trial 56 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 122, 'learning_rate': 0.9036125207341107, 'max_depth': 27, 'min_child_weight': 1.0902982261271663, 'subsample': 0.8465615185319159, 'colsample_bytree': 0.6456237145536186}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,825] Trial 57 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 136, 'learning_rate': 0.9589551700024428, 'max_depth': 12, 'min_child_weight': 1.7704310624469697, 'subsample': 0.8697239142924127, 'colsample_bytree': 0.7624257005054322}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:30,948] Trial 58 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 144, 'learning_rate': 0.9451824635379827, 'max_depth': 13, 'min_child_weight': 1.7946322953936855, 'subsample': 0.9796314632444612, 'colsample_bytree': 0.6642905212628658}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:31,101] Trial 59 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 187, 'learning_rate': 0.8429461515873506, 'max_depth': 16, 'min_child_weight': 1.3664490275319932, 'subsample': 0.8658374689696618, 'colsample_bytree': 0.6329815469945321}. Best is trial 49 with value: 0.5454545454545454.
[I 2026-10-19 15:00:31,204] Trial 60 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 108, 'learning_rate': 0.9877580410950512, 'max_depth': 29, 'min_child_weight': 1.367769697592057, 'subsample': 0.8935002298631123, 'colsample_bytree': 0.5403739539485944}. Best is trial 49 with value: 0.5454545454545454.

0.09533190727233887  seconds
Classification report saved as results/Continent/data_30/data_30_pca_xgboost_classification_report.txt
    Accuracy: 0.4805, Time: 13.23s
  - Testing classifier: svm

[I 2026-10-19 15:00:37,115] Trial 31 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,122] Trial 32 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,128] Trial 33 finished with value: 0.5064935064935064 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,135] Trial 34 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,142] Trial 35 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,149] Trial 36 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,155] Trial 37 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,161] Trial 38 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,168] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,174] Trial 40 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,181] Trial 41 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,188] Trial 42 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,195] Trial 43 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,202] Trial 44 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,208] Trial 45 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,215] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,222] Trial 47 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,228] Trial 48 finished with value: 0.5064935064935064 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,233] Trial 49 finished with value: 0.4805194805194805 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,241] Trial 50 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,248] Trial 51 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,255] Trial 52 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,262] Trial 53 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,268] Trial 54 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,273] Trial 55 finished with value: 0.4805194805194805 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,280] Trial 56 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,287] Trial 57 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,293] Trial 58 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,301] Trial 59 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,307] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,314] Trial 61 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,320] Trial 62 finished with value: 0.5064935064935064 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,325] Trial 63 finished with value: 0.4805194805194805 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,332] Trial 64 finished with value: 0.4935064935064935 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,339] Trial 65 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,346] Trial 66 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,353] Trial 67 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,360] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,366] Trial 69 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,374] Trial 70 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,381] Trial 71 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,388] Trial 72 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,394] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,401] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,408] Trial 75 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,415] Trial 76 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,421] Trial 77 finished with value: 0.5064935064935064 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,426] Trial 78 finished with value: 0.4805194805194805 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,433] Trial 79 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,440] Trial 80 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,446] Trial 81 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,454] Trial 82 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,460] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,465] Trial 84 finished with value: 0.4805194805194805 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,472] Trial 85 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,480] Trial 86 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,486] Trial 87 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,494] Trial 88 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,501] Trial 89 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,507] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,514] Trial 91 finished with value: 0.5194805194805194 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,521] Trial 92 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,527] Trial 93 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,534] Trial 94 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,541] Trial 95 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,548] Trial 96 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,554] Trial 97 finished with value: 0.5064935064935064 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,561] Trial 98 finished with value: 0.5064935064935064 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
[I 2026-10-19 15:00:37,568] Trial 99 finished with value: 0.5194805194805194 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 1 with value: 0.5194805194805194.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 15:00:37,578] A new study created in memory with name: no-name-ac342590-7b45-4a4b-b1b5-0dae82d2b57b
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.005285024642944336  seconds
Classification report saved as results/Continent/data_30/data_30_pca_svm_classification_report.txt
    Accuracy: 0.5195, Time: 0.66s
  - Testing classifier: mlp

[I 2026-10-19 15:00:37,883] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 4, 'n_neurons_layer1': 66, 'n_neurons_layer2': 5, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 2.036897814924019e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:38,078] Trial 1 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 88, 'n_neurons_layer1': 28, 'n_neurons_layer2': 94, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.04852891724300805}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:00:38,554] Trial 2 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 23, 'n_neurons_layer1': 84, 'n_neurons_layer2': 5, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08794551269053512}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:38,701] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 11, 'n_neurons_layer1': 40, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.00014947519518217496}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:38,901] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 46, 'n_neurons_layer1': 86, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.030227079845627086}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:39,234] Trial 5 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 82, 'n_neurons_layer1': 38, 'n_neurons_layer2': 23, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0011059372406142297}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:39,411] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 85, 'n_neurons_layer1': 44, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.003022925329332946}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:00:39,701] Trial 7 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 63, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0007681569392849505}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:00:40,039] Trial 8 finished with value: 0.5064935064935064 and parameters: {'n_layers': 1, 'n_neurons_layer0': 91, 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.0981046162095189}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:40,185] Trial 9 finished with value: 0.4935064935064935 and parameters: {'n_layers': 1, 'n_neurons_layer0': 70, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.00016262653167099005}. Best is trial 5 with value: 0.5194805194805194.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:42,436] Trial 10 finished with value: 0.5714285714285714 and parameters: {'n_layers': 3, 'n_neurons_layer0': 34, 'n_neurons_layer1': 1, 'n_neurons_layer2': 60, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 3.735092911078162e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:42,761] Trial 11 finished with value: 0.4155844155844156 and parameters: {'n_layers': 3, 'n_neurons_layer0': 29, 'n_neurons_layer1': 4, 'n_neurons_layer2': 55, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 3.1391300505521215e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:00:43,005] Trial 12 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 49, 'n_neurons_layer1': 4, 'n_neurons_layer2': 48, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0029859744790552384}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:43,319] Trial 13 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 99, 'n_neurons_layer1': 23, 'n_neurons_layer2': 39, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 1.3334949383399017e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:43,482] Trial 14 finished with value: 0.5064935064935064 and parameters: {'n_layers': 3, 'n_neurons_layer0': 10, 'n_neurons_layer1': 61, 'n_neurons_layer2': 74, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.00023815935111124695}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:43,549] Trial 15 finished with value: 0.42857142857142855 and parameters: {'n_layers': 2, 'n_neurons_layer0': 55, 'n_neurons_layer1': 19, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 1.88772218139662e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:43,915] Trial 16 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 97, 'n_neurons_layer1': 55, 'n_neurons_layer2': 35, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0025828644765062674}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:44,205] Trial 17 finished with value: 0.5324675324675324 and parameters: {'n_layers': 3, 'n_neurons_layer0': 70, 'n_neurons_layer1': 14, 'n_neurons_layer2': 21, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.00042381499183458425}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:44,273] Trial 18 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 29, 'n_neurons_layer1': 13, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.00010557370305658009}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:00:44,736] Trial 19 finished with value: 0.4025974025974026 and parameters: {'n_layers': 3, 'n_neurons_layer0': 54, 'n_neurons_layer1': 4, 'n_neurons_layer2': 82, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.00014563472785727156}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:45,037] Trial 20 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 39, 'n_neurons_layer1': 30, 'n_neurons_layer2': 66, 'activation': 'identity', 'solver': 'sgd', 'alpha': 2.3754717894945327e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:00:45,669] Trial 21 finished with value: 0.4025974025974026 and parameters: {'n_layers': 3, 'n_neurons_layer0': 77, 'n_neurons_layer1': 14, 'n_neurons_layer2': 21, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.0003440405585910553}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:45,991] Trial 22 finished with value: 0.5064935064935064 and parameters: {'n_layers': 3, 'n_neurons_layer0': 78, 'n_neurons_layer1': 39, 'n_neurons_layer2': 22, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.007278189952998676}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:46,181] Trial 23 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 17, 'n_neurons_layer1': 13, 'n_neurons_layer2': 22, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0007839001367710757}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:46,398] Trial 24 finished with value: 0.5194805194805194 and parameters: {'n_layers': 3, 'n_neurons_layer0': 39, 'n_neurons_layer1': 32, 'n_neurons_layer2': 32, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0004160909323531442}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:00:46,738] Trial 25 finished with value: 0.5324675324675324 and parameters: {'n_layers': 3, 'n_neurons_layer0': 80, 'n_neurons_layer1': 54, 'n_neurons_layer2': 58, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 7.962075597424829e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:01:09,221] Trial 26 finished with value: 0.5324675324675324 and parameters: {'n_layers': 3, 'n_neurons_layer0': 73, 'n_neurons_layer1': 97, 'n_neurons_layer2': 57, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 1.4109350461047354e-05}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:01:09,562] Trial 27 finished with value: 0.5194805194805194 and parameters: {'n_layers': 2, 'n_neurons_layer0': 78, 'n_neurons_layer1': 52, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.00016115087529636272}. Best is trial 10 with value: 0.5714285714285714.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:01:09,818] Trial 28 finished with value: 0.4025974025974026 and parameters: {'n_layers': 2, 'n_neurons_layer0': 8, 'n_neurons_layer1': 72, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 1.0724136364955151e-05}. Best is trial 10 with value: 0.5714285714285714.

{'activation': 'relu', 'solver': 'lbfgs', 'alpha': 3.735092911078162e-05, 'hidden_layer_sizes': [34, 1, 60]}

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:12:23,006] A new study created in memory with name: no-name-b8cf98bc-5da3-4b40-a6be-c27c0e954371
[I 2026-10-19 15:12:23,009] Trial 0 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.007234450163990737}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,010] Trial 1 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.720324415598778e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,012] Trial 2 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.246668302900763e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,014] Trial 3 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.786285094583247e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,016] Trial 4 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.245593001209734e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,017] Trial 5 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.000520480823146557}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,019] Trial 6 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.0286694756428625e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,021] Trial 7 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.1853809522235506e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,023] Trial 8 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 5.003335105161523e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,024] Trial 9 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.002575598634399193}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,028] Trial 10 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.238733222896457e-12}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,030] Trial 11 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.252975859931346e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,033] Trial 12 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.121970060234771e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,036] Trial 13 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.005596933325373911}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,039] Trial 14 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.549708575792885e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,042] Trial 15 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.158182114742141e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,045] Trial 16 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00019694839374740486}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,048] Trial 17 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.009346605014222553}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,051] Trial 18 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.4702060655993739e-12}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,054] Trial 19 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 5.034871800449301e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,057] Trial 20 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.968778516123978e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,060] Trial 21 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.2383327284285016e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,063] Trial 22 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0005900220776352197}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,065] Trial 23 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.6379270052022817e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,068] Trial 24 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.709038161232901e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,071] Trial 25 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.406510808306488e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,074] Trial 26 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0011380827999352792}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,076] Trial 27 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.9462408184112242e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,079] Trial 28 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 5.9599785023934234e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,081] Trial 29 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.4299354861731234e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,084] Trial 30 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.8435985905364682e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,086] Trial 31 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 6.821546878468711e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,088] Trial 32 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.482380996336875e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,091] Trial 33 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.5948667219841204e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,093] Trial 34 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.209209614114177e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,095] Trial 35 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 6.231523955495026e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,098] Trial 36 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0002231324504121259}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,100] Trial 37 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.3209333604170646e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,102] Trial 38 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.127570912238782e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,105] Trial 39 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0016106692578050272}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,107] Trial 40 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.76946669130445e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,110] Trial 41 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.7420865884046715e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,112] Trial 42 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00029970045591269}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,114] Trial 43 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.089644133043269e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,116] Trial 44 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.003948154939817293}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,119] Trial 45 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.30494844030131e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,121] Trial 46 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.601179105076987e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,123] Trial 47 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.5457576382198193e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,126] Trial 48 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 8.426882139696867e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,128] Trial 49 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0007880111432811545}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,130] Trial 50 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.9932432137003885e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,132] Trial 51 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.008936916500016408}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,135] Trial 52 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00031885818499438395}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,137] Trial 53 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.003582453794703769}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,139] Trial 54 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00013263453660697667}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,141] Trial 55 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0016767225303523626}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,144] Trial 56 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.951627082527887e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,146] Trial 57 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0006147512774364022}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,148] Trial 58 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.0990565309096909e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,151] Trial 59 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.0659262885806674e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,153] Trial 60 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 6.76327026821616e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,155] Trial 61 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.65830693773892e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,158] Trial 62 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.422743748648127e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,160] Trial 63 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.116005293173675e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,163] Trial 64 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.88538130795633e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,165] Trial 65 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.260530258507105e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,168] Trial 66 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.333848838052085e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,170] Trial 67 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 6.627444855527723e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,173] Trial 68 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.5786586814229272e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,175] Trial 69 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.0317055029879918e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,178] Trial 70 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.630858082829127e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,180] Trial 71 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.9982728813734986e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,183] Trial 72 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.2786071182532353e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,185] Trial 73 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 5.366894359924032e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,188] Trial 74 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.3015152001070803e-08}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,191] Trial 75 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00014543786012981627}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,193] Trial 76 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 7.782987052658837e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,196] Trial 77 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.959462947749195e-12}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,198] Trial 78 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.1241555741865693e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,201] Trial 79 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00044322042678220444}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,203] Trial 80 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0019646881423661796}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,206] Trial 81 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 6.413654987769401e-10}. Best is trial 0 with value: 0.42857142857142855.

Classification report saved as results/Continent/data_30/data_30_pca_mlp_classification_report_2026-10-19_15-12-23.txt
    Accuracy: 0.4416, Time: 705.43s
  - Testing classifier: nb

[I 2026-10-19 15:12:23,209] Trial 82 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.344078158086275e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,211] Trial 83 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.00892999564619517}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,214] Trial 84 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.0692535024343402e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,216] Trial 85 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 4.792401083432733e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,219] Trial 86 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 2.0821295102885904e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,222] Trial 87 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.350130103031839e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,225] Trial 88 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.43648352309053e-10}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,227] Trial 89 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.5245748745848305e-09}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,230] Trial 90 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.226571988860022e-06}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,233] Trial 91 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.003895119109975638}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,235] Trial 92 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.002466662644154253}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,238] Trial 93 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.001089078434775171}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,241] Trial 94 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.0010366804499214724}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,243] Trial 95 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 3.7845188604209136e-07}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,246] Trial 96 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 1.0016696650258016e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,248] Trial 97 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.184236089226196e-05}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,251] Trial 98 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 9.79352935164007e-11}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,253] Trial 99 finished with value: 0.42857142857142855 and parameters: {'var_smoothing': 0.005404786366443866}. Best is trial 0 with value: 0.42857142857142855.

Best hyperparameters:  {'var_smoothing': 0.007234450163990737}
Best validation accuracy:  0.42857142857142855
Test accuracy: 0.42857142857142855
Time taken: 0.0011878013610839844 seconds
Classification report saved as results/Continent/data_30/data_30_pca_nb_classification_report_2026-10-19_15-12-23.txt
    Accuracy: 0.4286, Time: 0.25s

Evaluating embedding method: lle

[I 2026-10-19 15:12:23,935] A new study created in memory with name: no-name-6972dfcd-6cb4-4a70-bf9f-80e1c7375dc4
[I 2026-10-19 15:12:23,961] Trial 0 finished with value: 0.42857142857142855 and parameters: {'C': 13.867639188465143, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6138417542246716}. Best is trial 0 with value: 0.42857142857142855.
[I 2026-10-19 15:12:23,977] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 0.00014976079562033971, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8870086827599557}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:23,993] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 0.0008651990530947549, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8822423015317664}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,019] Trial 3 finished with value: 0.22077922077922077 and parameters: {'C': 23.281143881577744, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7648160855850672}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,037] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 0.02851851631368536, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.18146290149167943}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,065] Trial 5 finished with value: 0.24675324675324675 and parameters: {'C': 97.0075442309469, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6816230943852244}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,083] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 2.9996194695567225e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10188907774617206}. Best is trial 1 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 15:12:24,172] Trial 7 finished with value: 0.38961038961038963 and parameters: {'C': 501.7864868293388, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.026881827629723132}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,190] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 0.0005405172610387398, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6283801708604618}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,208] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 1.0763970640725283e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4888468745259379}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,230] Trial 10 finished with value: 0.4675324675324675 and parameters: {'C': 2.932721182691981e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6122218431260839}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,250] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 2.874405641034892e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.937259052230038}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,271] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 0.1004002631369012, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9846457416480907}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,292] Trial 13 finished with value: 0.2727272727272727 and parameters: {'C': 0.0014947874254167186, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9781763132551574}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,313] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 0.9716575166197823, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8227605422460823}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,333] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 7.81512897593026e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40848673912198147}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,353] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 1.7749294102975198e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7688372430329815}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,375] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 0.03306109100127165, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.787551182196775}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,395] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 6.670097318354483e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9697616589323252}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,426] Trial 19 finished with value: 0.24675324675324675 and parameters: {'C': 877.5263892136369, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.38313518269960983}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,447] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 0.3241117783942467, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6120874923954425}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,468] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 0.0071026287427580865, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.01843733169399092}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,489] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 0.016285387710687955, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2940764811597242}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,510] Trial 23 finished with value: 0.22077922077922077 and parameters: {'C': 0.3937628420437028, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.16244022054204682}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,531] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 2.490987683796217e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7961484052300017}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,552] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 2.8959246149090773e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8832266512150477}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,574] Trial 26 finished with value: 0.2727272727272727 and parameters: {'C': 0.0029732660589039247, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7185677016846885}. Best is trial 1 with value: 0.4675324675324675.
[I 2026-10-19 15:12:24,596] Trial 27 finished with value: 0.4805194805194805 and parameters: {'C': 4.4509865973571685, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.31057040368919064}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,616] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 1.1680474196643316, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3827059531380795}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,636] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 1.7935328845660926e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5074785358373802}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,687] Trial 30 finished with value: 0.4025974025974026 and parameters: {'C': 27.957779083435188, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9278602048576956}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,709] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.0003037530770782406, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1881263343939205}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,729] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 0.002697187565654555, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.17891882101524992}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,750] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 5.862051778851017e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5894978031276795}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,772] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 1.1005461294765255, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.11945767385095242}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,794] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 0.0007153748572124255, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8786318331962637}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,816] Trial 36 finished with value: 0.2727272727272727 and parameters: {'C': 0.021068312060141373, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8426208607420839}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,838] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 0.011517689799775493, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.44545004743433325}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,862] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 9.569477720496884e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.701774716784324}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:24,885] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 2.0993153182188346e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.28285025797524815}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,058] Trial 40 finished with value: 0.38961038961038963 and parameters: {'C': 919.2597270141915, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5411645096109857}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,080] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 2.02169178102219e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.12647716189396987}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,101] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 5.660969983323309e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.027855056239142806}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,123] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 1.27420868571216e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.14501850783222925}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,145] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 0.17367011736942914, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7249909399818494}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,166] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 0.0003514279136424947, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07941999854302834}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,186] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 7.4246174827683935e-09, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.24455304496979247}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,208] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 1.6611243839584655e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.23882910053892462}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,230] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 1.6803067448945343e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.031178354568106692}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,252] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 1.489184877890306, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.67827278068516}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,274] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 8.312335544085932e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.23515485375347422}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,296] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.0004064769065621441, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5793730757714225}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,319] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.023093134893574205, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6780208610794365}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,351] Trial 53 finished with value: 0.42857142857142855 and parameters: {'C': 23.04995454771235, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2173215841092469}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,374] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.0025416530402839676, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.0778346015151763}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,396] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 0.1536053196154112, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3125603915024491}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,417] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.06347105086464744, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.06605430540816391}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,448] Trial 57 finished with value: 0.44155844155844154 and parameters: {'C': 27.180364444034712, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40241017664601353}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,469] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.003335171690154612, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6711612854808272}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,491] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.021558492832814947, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.21559276219174606}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,512] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 2.4750086647940652e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7027589710202744}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,533] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 0.00016041396683968973, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7336881746985114}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,555] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 5.363009640517724e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1247136311235689}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,576] Trial 63 finished with value: 0.2727272727272727 and parameters: {'C': 0.0025953396905835802, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4878436618076511}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,597] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.0062076119187793296, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9984259978572125}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,618] Trial 65 finished with value: 0.2727272727272727 and parameters: {'C': 0.0010780320385606608, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7777111100754426}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,640] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 8.697007622495677e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4792188115111942}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,661] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 2.3974517937028506e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8179760689935383}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,683] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 1.202604121764808e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6059878796605114}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,705] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 1.5049305954865648e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.12292762502243704}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,727] Trial 70 finished with value: 0.2727272727272727 and parameters: {'C': 0.0038764637704002385, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3530215679488734}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,748] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 1.1899206435205667e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6365992387759886}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,769] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 1.879523545278332e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.10797840986799355}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,792] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 1.1980249375304381, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1912766027554209}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,814] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 4.927222262741748e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46104650952127807}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,836] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 3.713626799291998e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3105484141865704}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,858] Trial 76 finished with value: 0.4675324675324675 and parameters: {'C': 3.040777340756944e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8587764173291098}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,879] Trial 77 finished with value: 0.2727272727272727 and parameters: {'C': 0.00017059935023305532, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9318333605632967}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,901] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 2.3878231313453513e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7315052255141925}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,953] Trial 79 finished with value: 0.4155844155844156 and parameters: {'C': 134.86069189471715, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.2743860186434586}. Best is trial 27 with value: 0.4805194805194805.
[I 2026-10-19 15:12:25,975] Trial 80 finished with value: 0.4675324675324675 and parameters: {'C': 6.321622996758605e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5248007205776984}. Best is trial 27 with value: 0.4805194805194805.

0.010513544082641602  seconds
Classification report saved as results/Continent/data_30/data_30_lle_logreg_classification_report.txt
    Accuracy: 0.4805, Time: 2.47s
  - Testing classifier: dt

[I 2026-10-19 15:12:26,603] Trial 37 finished with value: 0.4155844155844156 and parameters: {'max_depth': 19, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,608] Trial 38 finished with value: 0.2987012987012987 and parameters: {'max_depth': 9, 'criterion': 'gini'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,613] Trial 39 finished with value: 0.38961038961038963 and parameters: {'max_depth': 15, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,618] Trial 40 finished with value: 0.38961038961038963 and parameters: {'max_depth': 20, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,624] Trial 41 finished with value: 0.38961038961038963 and parameters: {'max_depth': 11, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,630] Trial 42 finished with value: 0.38961038961038963 and parameters: {'max_depth': 28, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,636] Trial 43 finished with value: 0.4025974025974026 and parameters: {'max_depth': 25, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,641] Trial 44 finished with value: 0.37662337662337664 and parameters: {'max_depth': 31, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,647] Trial 45 finished with value: 0.38961038961038963 and parameters: {'max_depth': 29, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,651] Trial 46 finished with value: 0.38961038961038963 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,656] Trial 47 finished with value: 0.2597402597402597 and parameters: {'max_depth': 25, 'criterion': 'gini'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,662] Trial 48 finished with value: 0.4155844155844156 and parameters: {'max_depth': 27, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,668] Trial 49 finished with value: 0.4155844155844156 and parameters: {'max_depth': 17, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,672] Trial 50 finished with value: 0.2857142857142857 and parameters: {'max_depth': 29, 'criterion': 'gini'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,678] Trial 51 finished with value: 0.3246753246753247 and parameters: {'max_depth': 22, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,684] Trial 52 finished with value: 0.4155844155844156 and parameters: {'max_depth': 32, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,688] Trial 53 finished with value: 0.3116883116883117 and parameters: {'max_depth': 19, 'criterion': 'gini'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,694] Trial 54 finished with value: 0.4025974025974026 and parameters: {'max_depth': 23, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,700] Trial 55 finished with value: 0.44155844155844154 and parameters: {'max_depth': 30, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,705] Trial 56 finished with value: 0.37662337662337664 and parameters: {'max_depth': 30, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,711] Trial 57 finished with value: 0.38961038961038963 and parameters: {'max_depth': 30, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,717] Trial 58 finished with value: 0.4025974025974026 and parameters: {'max_depth': 30, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,722] Trial 59 finished with value: 0.4155844155844156 and parameters: {'max_depth': 26, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,728] Trial 60 finished with value: 0.44155844155844154 and parameters: {'max_depth': 32, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,734] Trial 61 finished with value: 0.36363636363636365 and parameters: {'max_depth': 31, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,740] Trial 62 finished with value: 0.3116883116883117 and parameters: {'max_depth': 27, 'criterion': 'log_loss'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,745] Trial 63 finished with value: 0.37662337662337664 and parameters: {'max_depth': 32, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,751] Trial 64 finished with value: 0.35064935064935066 and parameters: {'max_depth': 28, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,755] Trial 65 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,759] Trial 66 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,764] Trial 67 finished with value: 0.4025974025974026 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 14 with value: 0.4675324675324675.
[I 2026-10-19 15:12:26,768] Trial 68 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,772] Trial 69 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,776] Trial 70 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,780] Trial 71 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,784] Trial 72 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,788] Trial 73 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,791] Trial 74 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,795] Trial 75 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,800] Trial 76 finished with value: 0.37662337662337664 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,804] Trial 77 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,808] Trial 78 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,813] Trial 79 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,817] Trial 80 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,821] Trial 81 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,826] Trial 82 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,830] Trial 83 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,835] Trial 84 finished with value: 0.38961038961038963 and parameters: {'max_depth': 8, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,840] Trial 85 finished with value: 0.4025974025974026 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,845] Trial 86 finished with value: 0.42857142857142855 and parameters: {'max_depth': 6, 'criterion': 'log_loss'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,849] Trial 87 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,854] Trial 88 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,858] Trial 89 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,862] Trial 90 finished with value: 0.4675324675324675 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,866] Trial 91 finished with value: 0.4155844155844156 and parameters: {'max_depth': 5, 'criterion': 'gini'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,870] Trial 92 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,874] Trial 93 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,878] Trial 94 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,883] Trial 95 finished with value: 0.38961038961038963 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,889] Trial 96 finished with value: 0.4025974025974026 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,893] Trial 97 finished with value: 0.4805194805194805 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,897] Trial 98 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
[I 2026-10-19 15:12:26,901] Trial 99 finished with value: 0.4155844155844156 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 68 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:12:26,908] A new study created in memory with name: no-name-4fdaf636-694f-4493-8df7-6b4b5a9ad44c
[I 2026-10-19 15:12:27,086] Trial 0 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 159, 'max_depth': 29}. Best is trial 0 with value: 0.4935064935064935.

0.0024480819702148438  seconds
Classification report saved as results/Continent/data_30/data_30_lle_dt_classification_report.txt
    Accuracy: 0.4805, Time: 0.50s
  - Testing classifier: rf

[I 2026-10-19 15:12:27,280] Trial 1 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 193, 'max_depth': 7}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:27,348] Trial 2 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 83, 'max_depth': 2}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:27,537] Trial 3 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 176, 'max_depth': 20}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:27,601] Trial 4 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 58, 'max_depth': 16}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:27,712] Trial 5 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 97, 'max_depth': 30}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:27,927] Trial 6 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 193, 'max_depth': 16}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,008] Trial 7 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 84, 'max_depth': 5}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,204] Trial 8 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 178, 'max_depth': 21}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,306] Trial 9 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 92, 'max_depth': 15}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,448] Trial 10 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 144, 'max_depth': 6}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,476] Trial 11 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 26, 'max_depth': 5}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,529] Trial 12 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 45, 'max_depth': 25}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,664] Trial 13 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 121, 'max_depth': 14}. Best is trial 0 with value: 0.4935064935064935.
[I 2026-10-19 15:12:28,828] Trial 14 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 147, 'max_depth': 31}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,000] Trial 15 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 154, 'max_depth': 32}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,201] Trial 16 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 182, 'max_depth': 32}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,350] Trial 17 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 133, 'max_depth': 22}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,505] Trial 18 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 139, 'max_depth': 30}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,607] Trial 19 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 91, 'max_depth': 24}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,737] Trial 20 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 117, 'max_depth': 28}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:29,910] Trial 21 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 155, 'max_depth': 25}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,075] Trial 22 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 145, 'max_depth': 19}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,195] Trial 23 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 105, 'max_depth': 19}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,348] Trial 24 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 136, 'max_depth': 32}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,371] Trial 25 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 17, 'max_depth': 32}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,517] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 129, 'max_depth': 24}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,572] Trial 27 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 46, 'max_depth': 31}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,705] Trial 28 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 163, 'max_depth': 2}. Best is trial 14 with value: 0.5064935064935064.
[I 2026-10-19 15:12:30,898] Trial 29 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 172, 'max_depth': 29}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,100] Trial 30 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 181, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,316] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 195, 'max_depth': 29}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,490] Trial 32 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 156, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,577] Trial 33 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 76, 'max_depth': 27}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,714] Trial 34 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 122, 'max_depth': 30}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:31,794] Trial 35 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 70, 'max_depth': 22}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,008] Trial 36 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 192, 'max_depth': 25}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,197] Trial 37 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 170, 'max_depth': 26}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,279] Trial 38 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 72, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,483] Trial 39 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 184, 'max_depth': 25}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,673] Trial 40 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 172, 'max_depth': 30}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:32,840] Trial 41 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 150, 'max_depth': 32}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,009] Trial 42 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 151, 'max_depth': 22}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,216] Trial 43 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 186, 'max_depth': 23}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,440] Trial 44 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 200, 'max_depth': 32}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,656] Trial 45 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 195, 'max_depth': 26}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,843] Trial 46 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 168, 'max_depth': 23}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,883] Trial 47 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 33, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,944] Trial 48 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 52, 'max_depth': 19}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:33,985] Trial 49 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 33, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,001] Trial 50 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 11, 'max_depth': 23}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,222] Trial 51 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 198, 'max_depth': 21}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,409] Trial 52 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 168, 'max_depth': 32}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,591] Trial 53 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 164, 'max_depth': 18}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,804] Trial 54 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 191, 'max_depth': 20}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:34,963] Trial 55 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 142, 'max_depth': 28}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,185] Trial 56 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 199, 'max_depth': 23}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,364] Trial 57 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 161, 'max_depth': 30}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,567] Trial 58 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 182, 'max_depth': 18}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,596] Trial 59 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 23, 'max_depth': 21}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,722] Trial 60 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 110, 'max_depth': 22}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,818] Trial 61 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 85, 'max_depth': 32}. Best is trial 29 with value: 0.5194805194805194.
[I 2026-10-19 15:12:35,838] Trial 62 finished with value: 0.5584415584415584 and parameters: {'n_estimators': 14, 'max_depth': 26}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:35,871] Trial 63 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 26, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,068] Trial 64 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,086] Trial 65 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 12, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,234] Trial 66 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 132, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,250] Trial 67 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 11, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,321] Trial 68 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 61, 'max_depth': 31}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,544] Trial 69 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 200, 'max_depth': 18}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,576] Trial 70 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 24, 'max_depth': 25}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,693] Trial 71 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 104, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,767] Trial 72 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 63, 'max_depth': 25}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:36,973] Trial 73 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 184, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,025] Trial 74 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 43, 'max_depth': 23}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,062] Trial 75 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 29, 'max_depth': 26}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,200] Trial 76 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 122, 'max_depth': 32}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,297] Trial 77 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 84, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,406] Trial 78 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 95, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,474] Trial 79 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 58, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,532] Trial 80 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 49, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,630] Trial 81 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 85, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,712] Trial 82 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 71, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,826] Trial 83 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 101, 'max_depth': 29}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,911] Trial 84 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 73, 'max_depth': 26}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:37,999] Trial 85 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 77, 'max_depth': 29}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,089] Trial 86 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 78, 'max_depth': 31}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,206] Trial 87 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 103, 'max_depth': 26}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,394] Trial 88 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 168, 'max_depth': 29}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,520] Trial 89 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 111, 'max_depth': 26}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,540] Trial 90 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 13, 'max_depth': 25}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,708] Trial 91 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 149, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:38,893] Trial 92 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 165, 'max_depth': 20}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,071] Trial 93 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 159, 'max_depth': 31}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,252] Trial 94 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 163, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,414] Trial 95 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 144, 'max_depth': 31}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,583] Trial 96 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 150, 'max_depth': 30}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,658] Trial 97 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 65, 'max_depth': 28}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:39,881] Trial 98 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 200, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
[I 2026-10-19 15:12:40,090] Trial 99 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 187, 'max_depth': 27}. Best is trial 62 with value: 0.5584415584415584.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:12:40,111] A new study created in memory with name: no-name-69f38793-aa82-49a8-b2d6-e1e3edaaabeb
[I 2026-10-19 15:12:40,113] Trial 0 finished with value: 0.37662337662337664 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 0 with value: 0.37662337662337664.
[I 2026-10-19 15:12:40,116] Trial 1 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 15:12:40,118] Trial 2 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 1 with value: 0.4935064935064935.
[I 2026-10-19 15:12:40,120] Trial 3 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 1 with value: 0.4935064935064935.

0.015956878662109375  seconds
Classification report saved as results/Continent/data_30/data_30_lle_rf_classification_report.txt
    Accuracy: 0.4675, Time: 13.20s
  - Testing classifier: knn

[I 2026-10-19 15:12:40,311] Trial 59 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,314] Trial 60 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,318] Trial 61 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,321] Trial 62 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,324] Trial 63 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,328] Trial 64 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,331] Trial 65 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,334] Trial 66 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,338] Trial 67 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,342] Trial 68 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,345] Trial 69 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,349] Trial 70 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,352] Trial 71 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,355] Trial 72 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,359] Trial 73 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,362] Trial 74 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,365] Trial 75 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,369] Trial 76 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,372] Trial 77 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,375] Trial 78 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,379] Trial 79 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,382] Trial 80 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,386] Trial 81 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,389] Trial 82 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,392] Trial 83 finished with value: 0.4805194805194805 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,396] Trial 84 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,400] Trial 85 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,405] Trial 86 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,408] Trial 87 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,412] Trial 88 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,416] Trial 89 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,420] Trial 90 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,424] Trial 91 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,428] Trial 92 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,431] Trial 93 finished with value: 0.37662337662337664 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,434] Trial 94 finished with value: 0.5194805194805194 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,438] Trial 95 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,442] Trial 96 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,446] Trial 97 finished with value: 0.4935064935064935 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,449] Trial 98 finished with value: 0.45454545454545453 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 17 with value: 0.5194805194805194.
[I 2026-10-19 15:12:40,453] Trial 99 finished with value: 0.5064935064935064 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 17 with value: 0.5194805194805194.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:12:40,459] A new study created in memory with name: no-name-79cb8d08-b2db-44e6-a3cf-41440bdb361d
[I 2026-10-19 15:12:40,511] Trial 0 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 44, 'learning_rate': 0.5091250362709587, 'max_depth': 4, 'min_child_weight': 8.728035170403988, 'subsample': 0.70310839286305, 'colsample_bytree': 0.7389902667517788}. Best is trial 0 with value: 0.4025974025974026.

0.0015299320220947266  seconds
Classification report saved as results/Continent/data_30/data_30_lle_knn_classification_report.txt
    Accuracy: 0.5195, Time: 0.35s
  - Testing classifier: xgboost

[I 2026-10-19 15:12:40,688] Trial 1 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 185, 'learning_rate': 0.16224394815788734, 'max_depth': 30, 'min_child_weight': 9.472107637181072, 'subsample': 0.6582507950847992, 'colsample_bytree': 0.18672110115829813}. Best is trial 0 with value: 0.4025974025974026.
[I 2026-10-19 15:12:40,797] Trial 2 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 142, 'learning_rate': 0.8786103827267535, 'max_depth': 12, 'min_child_weight': 7.85371695908803, 'subsample': 0.6742463062213513, 'colsample_bytree': 0.8541835718805151}. Best is trial 0 with value: 0.4025974025974026.
[I 2026-10-19 15:12:40,881] Trial 3 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 171, 'learning_rate': 0.23261309448093465, 'max_depth': 20, 'min_child_weight': 9.932121392823717, 'subsample': 0.14772255744937396, 'colsample_bytree': 0.8161390020700421}. Best is trial 3 with value: 0.42857142857142855.
[I 2026-10-19 15:12:41,089] Trial 4 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 165, 'learning_rate': 0.35227555539053423, 'max_depth': 17, 'min_child_weight': 1.1292899006686974, 'subsample': 0.8121846806318622, 'colsample_bytree': 0.29405244854857887}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,214] Trial 5 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 190, 'learning_rate': 0.6451958749217842, 'max_depth': 2, 'min_child_weight': 6.817166458549676, 'subsample': 0.6781952686235405, 'colsample_bytree': 0.5855974265748847}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,310] Trial 6 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 92, 'learning_rate': 0.7997866957416286, 'max_depth': 5, 'min_child_weight': 1.0972021606657256, 'subsample': 0.7298824083258979, 'colsample_bytree': 0.4451965850089332}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,408] Trial 7 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 45, 'learning_rate': 0.3409322529258587, 'max_depth': 17, 'min_child_weight': 1.0310864823763115, 'subsample': 0.8753414144907586, 'colsample_bytree': 0.21260707825592234}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,449] Trial 8 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 31, 'learning_rate': 0.7646664193032672, 'max_depth': 12, 'min_child_weight': 1.8920259641199273, 'subsample': 0.3497420565965439, 'colsample_bytree': 0.4133007665049985}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,551] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 80, 'learning_rate': 0.00980491946944291, 'max_depth': 29, 'min_child_weight': 2.726020369653949, 'subsample': 0.3313090515431988, 'colsample_bytree': 0.8588682329330207}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,783] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 167, 'learning_rate': 0.17109507141557379, 'max_depth': 25, 'min_child_weight': 3.9212177732825118, 'subsample': 0.9836136820348911, 'colsample_bytree': 0.5484944383016154}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:41,941] Trial 11 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 159, 'learning_rate': 0.3165324993946718, 'max_depth': 23, 'min_child_weight': 6.444225447185991, 'subsample': 0.8277949247866042, 'colsample_bytree': 0.5922592694530991}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:42,273] Trial 12 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 170, 'learning_rate': 0.04280226708391896, 'max_depth': 19, 'min_child_weight': 2.7180669765675987, 'subsample': 0.870370307818432, 'colsample_bytree': 0.2735418870423145}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:42,551] Trial 13 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 185, 'learning_rate': 0.03617085167992051, 'max_depth': 23, 'min_child_weight': 6.686746667254663, 'subsample': 0.9679046769809766, 'colsample_bytree': 0.7248622628527119}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:42,736] Trial 14 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 134, 'learning_rate': 0.30048327307181805, 'max_depth': 11, 'min_child_weight': 1.2487704432433648, 'subsample': 0.7662298275811743, 'colsample_bytree': 0.3982538633775489}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:42,953] Trial 15 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 127, 'learning_rate': 0.03508534067748992, 'max_depth': 25, 'min_child_weight': 5.083870999640726, 'subsample': 0.9642074933466296, 'colsample_bytree': 0.43517369177389503}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,110] Trial 16 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 152, 'learning_rate': 0.5211001370268847, 'max_depth': 28, 'min_child_weight': 2.702578685031309, 'subsample': 0.9754801400253714, 'colsample_bytree': 0.3127193467132501}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,229] Trial 17 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 92, 'learning_rate': 0.2791822860566615, 'max_depth': 21, 'min_child_weight': 4.952192976345497, 'subsample': 0.8844346134460246, 'colsample_bytree': 0.2310774539063006}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,372] Trial 18 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 125, 'learning_rate': 0.14619656997945052, 'max_depth': 32, 'min_child_weight': 6.3884879337930265, 'subsample': 0.7365595934332343, 'colsample_bytree': 0.4926742659436193}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,493] Trial 19 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 97, 'learning_rate': 0.5022358164383864, 'max_depth': 19, 'min_child_weight': 2.6411685887037866, 'subsample': 0.9806595804019975, 'colsample_bytree': 0.2877247021046737}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,657] Trial 20 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 116, 'learning_rate': 0.1495199430802553, 'max_depth': 22, 'min_child_weight': 4.567132310132162, 'subsample': 0.8833789266680374, 'colsample_bytree': 0.4942964109000041}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,824] Trial 21 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 164, 'learning_rate': 0.4885296895103746, 'max_depth': 15, 'min_child_weight': 2.113781469976987, 'subsample': 0.8029893211270982, 'colsample_bytree': 0.4327417948511311}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:43,991] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 162, 'learning_rate': 0.3563663323216119, 'max_depth': 28, 'min_child_weight': 3.9351534535085153, 'subsample': 0.8320787530095167, 'colsample_bytree': 0.5710468744255561}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:44,188] Trial 23 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 151, 'learning_rate': 0.22715094993671403, 'max_depth': 24, 'min_child_weight': 5.046227317034176, 'subsample': 0.9913144224930334, 'colsample_bytree': 0.19761573825368556}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:44,398] Trial 24 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 191, 'learning_rate': 0.3641654812662401, 'max_depth': 22, 'min_child_weight': 2.572604673084758, 'subsample': 0.9885111838251625, 'colsample_bytree': 0.27469301586298456}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:44,607] Trial 25 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 171, 'learning_rate': 0.2410974471057437, 'max_depth': 19, 'min_child_weight': 2.490666573460677, 'subsample': 0.8324901504137132, 'colsample_bytree': 0.6082318034354395}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:44,826] Trial 26 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 133, 'learning_rate': 0.08100501841584502, 'max_depth': 31, 'min_child_weight': 3.5629942934459637, 'subsample': 0.8411306519837298, 'colsample_bytree': 0.6452741445760997}. Best is trial 4 with value: 0.4935064935064935.
[I 2026-10-19 15:12:45,059] Trial 27 finished with value: 0.5194805194805194 and parameters: {'n_estimators': 131, 'learning_rate': 0.032561404465890925, 'max_depth': 29, 'min_child_weight': 4.708576208187008, 'subsample': 0.9460432933790982, 'colsample_bytree': 0.5416474858776616}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:45,198] Trial 28 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 98, 'learning_rate': 0.05598212464495256, 'max_depth': 28, 'min_child_weight': 6.5367605566261595, 'subsample': 0.8568640123640403, 'colsample_bytree': 0.47272116322672947}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:45,399] Trial 29 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 156, 'learning_rate': 0.1211302351390167, 'max_depth': 28, 'min_child_weight': 5.829700391868105, 'subsample': 0.8875374389078902, 'colsample_bytree': 0.623129528475557}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:45,610] Trial 30 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 120, 'learning_rate': 0.0010832868099060547, 'max_depth': 32, 'min_child_weight': 5.036672774110102, 'subsample': 0.9759371496988928, 'colsample_bytree': 0.4209854857108454}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:45,859] Trial 31 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 140, 'learning_rate': 0.027254192906036246, 'max_depth': 32, 'min_child_weight': 3.4028533304948247, 'subsample': 0.7576869926883467, 'colsample_bytree': 0.47710326148770427}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:45,984] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 98, 'learning_rate': 0.26386569494768874, 'max_depth': 31, 'min_child_weight': 5.005110490341646, 'subsample': 0.8971817540267135, 'colsample_bytree': 0.4033069846594814}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:46,165] Trial 33 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 122, 'learning_rate': 0.10621448075708505, 'max_depth': 27, 'min_child_weight': 4.589416062993502, 'subsample': 0.8822690023260892, 'colsample_bytree': 0.3821244880156605}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:46,357] Trial 34 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 134, 'learning_rate': 0.2001852114847209, 'max_depth': 31, 'min_child_weight': 2.7956045164325536, 'subsample': 0.9691187717814727, 'colsample_bytree': 0.624613696379069}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:46,572] Trial 35 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 135, 'learning_rate': 0.007554875600478433, 'max_depth': 24, 'min_child_weight': 4.7077692046996775, 'subsample': 0.740192968905845, 'colsample_bytree': 0.6224468878779609}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:46,713] Trial 36 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 75, 'learning_rate': 0.06495114683348967, 'max_depth': 28, 'min_child_weight': 4.264698471643544, 'subsample': 0.9623126733365456, 'colsample_bytree': 0.4488793767965773}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:46,868] Trial 37 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 138, 'learning_rate': 0.2670721633466287, 'max_depth': 28, 'min_child_weight': 5.667653563456777, 'subsample': 0.8911369797242483, 'colsample_bytree': 0.587874366077852}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,129] Trial 38 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 161, 'learning_rate': 0.01914530897469758, 'max_depth': 29, 'min_child_weight': 5.530820242541609, 'subsample': 0.9041794928440884, 'colsample_bytree': 0.5256781235293684}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,225] Trial 39 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 66, 'learning_rate': 0.1259347118690204, 'max_depth': 26, 'min_child_weight': 7.067363323012703, 'subsample': 0.9620294854925171, 'colsample_bytree': 0.42072853530499743}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,384] Trial 40 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 92, 'learning_rate': 0.05037508208501809, 'max_depth': 30, 'min_child_weight': 4.86808488928086, 'subsample': 0.9157742412158562, 'colsample_bytree': 0.5883548162096427}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,600] Trial 41 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 123, 'learning_rate': 0.08301177304172618, 'max_depth': 23, 'min_child_weight': 3.831909512904286, 'subsample': 0.9942625989564249, 'colsample_bytree': 0.4796077877695321}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,837] Trial 42 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 135, 'learning_rate': 0.023845398074685886, 'max_depth': 27, 'min_child_weight': 4.092915441863164, 'subsample': 0.8156669864599282, 'colsample_bytree': 0.5424912139532242}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:47,933] Trial 43 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 55, 'learning_rate': 0.07889933987027758, 'max_depth': 31, 'min_child_weight': 4.764784184443384, 'subsample': 0.8911625442632959, 'colsample_bytree': 0.39994319373821124}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,088] Trial 44 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 110, 'learning_rate': 0.08547639350153419, 'max_depth': 31, 'min_child_weight': 5.962571490773191, 'subsample': 0.8649762779073433, 'colsample_bytree': 0.36474134661647567}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,191] Trial 45 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 48, 'learning_rate': 0.018721081923873083, 'max_depth': 32, 'min_child_weight': 3.8272129293992068, 'subsample': 0.995105020322952, 'colsample_bytree': 0.324636275788433}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,263] Trial 46 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 45, 'learning_rate': 0.018549305513856022, 'max_depth': 32, 'min_child_weight': 6.8385227217011915, 'subsample': 0.9311559031228208, 'colsample_bytree': 0.5021157727226164}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,434] Trial 47 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 120, 'learning_rate': 0.11512440421185821, 'max_depth': 27, 'min_child_weight': 5.66879566120869, 'subsample': 0.9415339780932057, 'colsample_bytree': 0.5103611086417756}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,534] Trial 48 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 66, 'learning_rate': 0.13818515545204973, 'max_depth': 29, 'min_child_weight': 5.062769043757594, 'subsample': 0.8345120636544312, 'colsample_bytree': 0.4671206957991253}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,697] Trial 49 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 84, 'learning_rate': 0.06839152186183713, 'max_depth': 30, 'min_child_weight': 3.913239200329073, 'subsample': 0.9631355761843137, 'colsample_bytree': 0.5209959547325226}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:48,922] Trial 50 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 145, 'learning_rate': 0.06060367827578718, 'max_depth': 31, 'min_child_weight': 5.771767802442337, 'subsample': 0.9918032344542279, 'colsample_bytree': 0.5298176173580481}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,140] Trial 51 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 128, 'learning_rate': 0.06734571327422051, 'max_depth': 30, 'min_child_weight': 3.71435307947946, 'subsample': 0.8522303375630793, 'colsample_bytree': 0.687703608068321}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,269] Trial 52 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 70, 'learning_rate': 0.1367328925078149, 'max_depth': 32, 'min_child_weight': 3.428186879442375, 'subsample': 0.9381575356794409, 'colsample_bytree': 0.43850183790724306}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,391] Trial 53 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 88, 'learning_rate': 0.19725628023230582, 'max_depth': 27, 'min_child_weight': 5.646185918974369, 'subsample': 0.9324453128495025, 'colsample_bytree': 0.41583547190866416}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,564] Trial 54 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 108, 'learning_rate': 0.07576138679122427, 'max_depth': 28, 'min_child_weight': 5.208517529330055, 'subsample': 0.9618045164474809, 'colsample_bytree': 0.3776217844864733}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,649] Trial 55 finished with value: 0.4805194805194805 and parameters: {'n_estimators': 44, 'learning_rate': 0.03733861193589845, 'max_depth': 28, 'min_child_weight': 4.935462892857157, 'subsample': 0.9720388510560921, 'colsample_bytree': 0.5144258568626199}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:49,922] Trial 56 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 159, 'learning_rate': 0.05062858388511696, 'max_depth': 27, 'min_child_weight': 3.9492972524026717, 'subsample': 0.9052718414608455, 'colsample_bytree': 0.44661053314718735}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:50,187] Trial 57 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 130, 'learning_rate': 0.0375556328445265, 'max_depth': 26, 'min_child_weight': 2.9583492367888096, 'subsample': 0.8916451321850242, 'colsample_bytree': 0.46005072459291196}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:50,466] Trial 58 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 151, 'learning_rate': 0.01816241125985922, 'max_depth': 32, 'min_child_weight': 4.016197251623845, 'subsample': 0.8879634550718168, 'colsample_bytree': 0.4070017162866917}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:50,643] Trial 59 finished with value: 0.5064935064935064 and parameters: {'n_estimators': 114, 'learning_rate': 0.08947359748582961, 'max_depth': 30, 'min_child_weight': 4.975605816898458, 'subsample': 0.9293808142946669, 'colsample_bytree': 0.5034603682793725}. Best is trial 27 with value: 0.5194805194805194.
[I 2026-10-19 15:12:50,954] Trial 60 finished with value: 0.4935064935064935 and parameters: {'n_estimators': 144, 'learning_rate': 0.02185396805376158, 'max_depth': 28, 'min_child_weight': 3.091567796294036, 'subsample': 0.9746131871843571, 'colsample_bytree': 0.45676987829544313}. Best is trial 27 with value: 0.5194805194805194.

0.22599387168884277  seconds
Classification report saved as results/Continent/data_30/data_30_lle_xgboost_classification_report.txt
    Accuracy: 0.4935, Time: 18.29s
  - Testing classifier: svm

[I 2026-10-19 15:12:58,951] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,958] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,962] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,968] Trial 41 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,974] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,981] Trial 43 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,987] Trial 44 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,993] Trial 45 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:58,999] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,005] Trial 47 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,011] Trial 48 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,018] Trial 49 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,022] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,028] Trial 51 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,033] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,039] Trial 53 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,046] Trial 54 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,051] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,056] Trial 56 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,063] Trial 57 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,069] Trial 58 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,074] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,079] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,085] Trial 61 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,091] Trial 62 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,097] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,103] Trial 64 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,110] Trial 65 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,115] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,121] Trial 67 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,126] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,132] Trial 69 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,137] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,143] Trial 71 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,150] Trial 72 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,156] Trial 73 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,162] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,168] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,175] Trial 76 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,181] Trial 77 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,188] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,192] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,199] Trial 80 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,205] Trial 81 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,212] Trial 82 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,216] Trial 83 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,221] Trial 84 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,228] Trial 85 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,234] Trial 86 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,240] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,247] Trial 88 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,252] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,257] Trial 90 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,263] Trial 91 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,270] Trial 92 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,276] Trial 93 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,283] Trial 94 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,289] Trial 95 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,295] Trial 96 finished with value: 0.5064935064935064 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,300] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,305] Trial 98 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
[I 2026-10-19 15:12:59,312] Trial 99 finished with value: 0.4935064935064935 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.5064935064935064.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 15:12:59,321] A new study created in memory with name: no-name-2e262ec1-0cf8-4aba-9720-c640d1aa6f9d
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.004484415054321289  seconds
Classification report saved as results/Continent/data_30/data_30_lle_svm_classification_report.txt
    Accuracy: 0.5065, Time: 0.57s
  - Testing classifier: mlp

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:14:09,477] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 99, 'n_neurons_layer1': 100, 'n_neurons_layer2': 52, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 1.0458040929467591e-05}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:14:10,317] Trial 1 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 79, 'n_neurons_layer1': 53, 'n_neurons_layer2': 36, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.003946539544120494}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:15:10,214] Trial 2 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 63, 'n_neurons_layer1': 83, 'n_neurons_layer2': 64, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.014921730990501997}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:10,466] Trial 3 finished with value: 0.4935064935064935 and parameters: {'n_layers': 1, 'n_neurons_layer0': 59, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0054116670350438075}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:10,833] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 74, 'n_neurons_layer1': 17, 'n_neurons_layer2': 2, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0006169584345586184}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:10,947] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 28, 'activation': 'logistic', 'solver': 'sgd', 'alpha': 0.0009447110984630657}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:15:11,684] Trial 6 finished with value: 0.44155844155844154 and parameters: {'n_layers': 2, 'n_neurons_layer0': 27, 'n_neurons_layer1': 56, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 7.79558727199496e-05}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:11,842] Trial 7 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 11, 'n_neurons_layer1': 72, 'n_neurons_layer2': 57, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.0002448241506870253}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:12,243] Trial 8 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 71, 'n_neurons_layer1': 82, 'n_neurons_layer2': 26, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07579771214870996}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:12,383] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 12, 'n_neurons_layer1': 46, 'activation': 'relu', 'solver': 'sgd', 'alpha': 5.247652046562034e-05}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:15:12,671] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 21, 'n_neurons_layer1': 5, 'n_neurons_layer2': 99, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.09488481529964617}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:15:13,137] Trial 11 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 83, 'n_neurons_layer1': 39, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0028661343188571683}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:13,402] Trial 12 finished with value: 0.4935064935064935 and parameters: {'n_layers': 1, 'n_neurons_layer0': 81, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.04677011988021527}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:13,636] Trial 13 finished with value: 0.4935064935064935 and parameters: {'n_layers': 1, 'n_neurons_layer0': 68, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0007081704467199524}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:13,904] Trial 14 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 20, 'n_neurons_layer1': 29, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.00957288493322684}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:14,169] Trial 15 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 41, 'n_neurons_layer1': 61, 'n_neurons_layer2': 84, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0014582742895897039}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:14,308] Trial 16 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 97, 'n_neurons_layer1': 3, 'n_neurons_layer2': 1, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0012416117368693313}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:14,546] Trial 17 finished with value: 0.4935064935064935 and parameters: {'n_layers': 1, 'n_neurons_layer0': 45, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.0013297114648355387}. Best is trial 1 with value: 0.4935064935064935.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:15,148] Trial 18 finished with value: 0.5064935064935064 and parameters: {'n_layers': 2, 'n_neurons_layer0': 65, 'n_neurons_layer1': 98, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07027806746088258}. Best is trial 18 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:15,735] Trial 19 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 63, 'n_neurons_layer1': 100, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.015647807521435592}. Best is trial 18 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:15:16,215] Trial 20 finished with value: 0.4935064935064935 and parameters: {'n_layers': 2, 'n_neurons_layer0': 45, 'n_neurons_layer1': 78, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.04861709925385129}. Best is trial 18 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:16,672] Trial 21 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 42, 'n_neurons_layer1': 61, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.017589990885530378}. Best is trial 18 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:15:16,923] Trial 22 finished with value: 0.4805194805194805 and parameters: {'n_layers': 1, 'n_neurons_layer0': 53, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.038633221929478816}. Best is trial 18 with value: 0.5064935064935064.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:15:17,448] Trial 23 finished with value: 0.4935064935064935 and parameters: {'n_layers': 3, 'n_neurons_layer0': 84, 'n_neurons_layer1': 28, 'n_neurons_layer2': 31, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.005900954915229989}. Best is trial 18 with value: 0.5064935064935064.

{'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010648943990712134, 'hidden_layer_sizes': [87, 76]}

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:16:00,149] A new study created in memory with name: no-name-5a5981c4-21a5-49e3-ab3b-a0df70383840
[I 2026-10-19 15:16:00,151] Trial 0 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.00010184176688709524}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,152] Trial 1 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0003514259478552935}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,154] Trial 2 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 6.6853820000691425e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,155] Trial 3 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.076316887706919e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,156] Trial 4 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.6491505850429898e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,158] Trial 5 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.867243472400389e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,159] Trial 6 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.217069461810261e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,161] Trial 7 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0003052302988957922}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,162] Trial 8 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.3493179487656403e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,163] Trial 9 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.1917947532076006e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,166] Trial 10 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.006192598720329829}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,168] Trial 11 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.346611346361119e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,170] Trial 12 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.852671704927771e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,172] Trial 13 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.008365168139481297}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,174] Trial 14 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 6.345353863218205e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,177] Trial 15 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0003165788794678507}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,179] Trial 16 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.5878765677765205e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,181] Trial 17 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.00015379306717541017}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,183] Trial 18 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0013232959036019475}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,185] Trial 19 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.2648010832280958e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,187] Trial 20 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.6048534935731507e-12}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,190] Trial 21 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.911476816764089e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,192] Trial 22 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.313089704891069e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,194] Trial 23 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.4443336881018447e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,196] Trial 24 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 8.712972169695644e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,199] Trial 25 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.002398245435132154}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,201] Trial 26 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.911798729925965e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,203] Trial 27 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.4229075347843147e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,205] Trial 28 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0009211964499858702}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,208] Trial 29 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.466923136077454e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,210] Trial 30 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.0792407531875777e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,212] Trial 31 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.48926004621077e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,214] Trial 32 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.1777684997305464e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,216] Trial 33 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.768951766481562e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,219] Trial 34 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.721637489766635e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,221] Trial 35 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 9.629368389305592e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,223] Trial 36 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.8588627387711514e-12}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,226] Trial 37 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.7703261058398055e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,228] Trial 38 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.5385437278430147e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,230] Trial 39 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 7.391125974194629e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,232] Trial 40 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 8.884326676577446e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,234] Trial 41 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 6.793247396505525e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,237] Trial 42 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.1724253884072386e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,239] Trial 43 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0004365114850182578}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,241] Trial 44 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.707056056796304e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,243] Trial 45 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.341739866084471e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,245] Trial 46 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.9545724086072103e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,248] Trial 47 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.003071751191629463}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,250] Trial 48 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.3475439013519931e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,252] Trial 49 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 9.835712412134068e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,254] Trial 50 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 9.822449854187849e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,257] Trial 51 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.497752938910866e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,259] Trial 52 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.0570911398027551e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,261] Trial 53 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.731853655219751e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,263] Trial 54 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.6276412297345505e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,265] Trial 55 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.00020305484375588985}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,268] Trial 56 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.106793645407874e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,270] Trial 57 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.748505549514006e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,272] Trial 58 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0007814961409117447}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,274] Trial 59 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 6.324375021434558e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,277] Trial 60 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.008644932932599088}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,279] Trial 61 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.8248815363462958e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,281] Trial 62 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.358109966425399e-12}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,283] Trial 63 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.0859487080806806e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,285] Trial 64 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 8.360830246960456e-12}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,288] Trial 65 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.695297529421558e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,290] Trial 66 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.5055627344912344e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,292] Trial 67 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.533871112370243e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,294] Trial 68 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.1104906810119019e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,297] Trial 69 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.5690109907658264e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,299] Trial 70 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 9.071340614753992e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,301] Trial 71 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.00016776088431464436}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,303] Trial 72 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0023800327479700212}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,306] Trial 73 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.000657531442916355}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,308] Trial 74 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 7.368149571632746e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,310] Trial 75 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.948345250158984e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,312] Trial 76 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.0017312701954124241}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,315] Trial 77 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.4178792523573007e-12}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,317] Trial 78 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.00032412969695043545}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,319] Trial 79 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.8429872842635705e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,322] Trial 80 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.874688947310177e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,324] Trial 81 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.4810514574498314e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,326] Trial 82 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.842426011793015e-06}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,329] Trial 83 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 7.690820567025826e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,332] Trial 84 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.7263843958949948e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,334] Trial 85 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 0.004740925884704429}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,337] Trial 86 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.1214285879167142e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,339] Trial 87 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.1458147979061753e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,342] Trial 88 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.258308740990499e-10}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,344] Trial 89 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.5302952885143874e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,347] Trial 90 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 3.227110259264431e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,349] Trial 91 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.23813180491694e-08}. Best is trial 0 with value: 0.18181818181818182.

Classification report saved as results/Continent/data_30/data_30_lle_mlp_classification_report_2026-10-19_15-16-00.txt
    Accuracy: 0.5065, Time: 180.83s
  - Testing classifier: nb

[I 2026-10-19 15:16:00,352] Trial 92 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 5.933187446017062e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,355] Trial 93 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.9993678960409886e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,357] Trial 94 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 6.484500652304027e-09}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,360] Trial 95 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.0414269084821563e-07}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,362] Trial 96 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 4.1808714857210686e-08}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,365] Trial 97 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 2.0621146715745343e-11}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,367] Trial 98 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 8.896119117423259e-05}. Best is trial 0 with value: 0.18181818181818182.
[I 2026-10-19 15:16:00,370] Trial 99 finished with value: 0.18181818181818182 and parameters: {'var_smoothing': 1.9754278290733366e-07}. Best is trial 0 with value: 0.18181818181818182.

Best hyperparameters:  {'var_smoothing': 0.00010184176688709524}
Best validation accuracy:  0.18181818181818182
Test accuracy: 0.18181818181818182
Time taken: 0.0012161731719970703 seconds
Classification report saved as results/Continent/data_30/data_30_lle_nb_classification_report_2026-10-19_15-16-00.txt
    Accuracy: 0.1818, Time: 0.23s

Evaluating embedding method: umap

[I 2026-10-19 15:16:00,714] A new study created in memory with name: no-name-ce328480-3ae1-4085-a397-6dcc207d30c1
[I 2026-10-19 15:16:00,731] Trial 0 finished with value: 0.4675324675324675 and parameters: {'C': 0.0005432717899635511, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4947398037107298}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,746] Trial 1 finished with value: 0.4675324675324675 and parameters: {'C': 4.3582722534121415e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.679849734643569}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,762] Trial 2 finished with value: 0.4675324675324675 and parameters: {'C': 7.793413271951164e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.40255134195159603}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,777] Trial 3 finished with value: 0.4675324675324675 and parameters: {'C': 0.00012573892231566863, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8429537040659731}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,814] Trial 4 finished with value: 0.4675324675324675 and parameters: {'C': 33.889281934653795, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4588154852603391}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,833] Trial 5 finished with value: 0.4675324675324675 and parameters: {'C': 2.9051503864296565e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.12741548349215082}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,850] Trial 6 finished with value: 0.4675324675324675 and parameters: {'C': 1.0102337988711256e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.028193486915018107}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,868] Trial 7 finished with value: 0.4675324675324675 and parameters: {'C': 0.004282237002040117, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4701799576862653}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,887] Trial 8 finished with value: 0.4675324675324675 and parameters: {'C': 8.549746011644548e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.31887766997951306}. Best is trial 0 with value: 0.4675324675324675.

  - Testing classifier: logreg

[I 2026-10-19 15:16:00,924] Trial 9 finished with value: 0.4675324675324675 and parameters: {'C': 31.733270756541778, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8896251826222196}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,945] Trial 10 finished with value: 0.4675324675324675 and parameters: {'C': 1.5209936281612004e-07, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7637603463055972}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:00,965] Trial 11 finished with value: 0.4675324675324675 and parameters: {'C': 2.8720925858886707e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6538063821012255}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,097] Trial 12 finished with value: 0.4675324675324675 and parameters: {'C': 0.025988259015111613, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6423231655380984}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,118] Trial 13 finished with value: 0.4675324675324675 and parameters: {'C': 4.200861643856842e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9899570787528313}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,159] Trial 14 finished with value: 0.4675324675324675 and parameters: {'C': 55.025248363694914, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.04950961871919879}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,180] Trial 15 finished with value: 0.4675324675324675 and parameters: {'C': 3.6891373363009505e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.05490906580940147}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,222] Trial 16 finished with value: 0.4675324675324675 and parameters: {'C': 168.16463031457135, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5426413269335535}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,383] Trial 17 finished with value: 0.4675324675324675 and parameters: {'C': 0.026213789239098728, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3518555462386328}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,404] Trial 18 finished with value: 0.4675324675324675 and parameters: {'C': 0.00328297643644892, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.27448273232829046}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,425] Trial 19 finished with value: 0.4675324675324675 and parameters: {'C': 5.375230488059048e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5965615726749433}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,456] Trial 20 finished with value: 0.4675324675324675 and parameters: {'C': 0.4326395916606987, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5196025140850964}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,477] Trial 21 finished with value: 0.4675324675324675 and parameters: {'C': 2.0517028309486313e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3166603961222418}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,497] Trial 22 finished with value: 0.4675324675324675 and parameters: {'C': 2.015738251365311e-10, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5033046070969293}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,518] Trial 23 finished with value: 0.4675324675324675 and parameters: {'C': 3.7082932417121666e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.450514048368368}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,541] Trial 24 finished with value: 0.4675324675324675 and parameters: {'C': 1.7644384363928903e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.07780562603969288}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,562] Trial 25 finished with value: 0.4675324675324675 and parameters: {'C': 0.00019410180017056383, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6866572270521658}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,584] Trial 26 finished with value: 0.4675324675324675 and parameters: {'C': 2.0817456702575905e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46010040575479144}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,607] Trial 27 finished with value: 0.4675324675324675 and parameters: {'C': 6.396938025183094e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.05976400946069843}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,627] Trial 28 finished with value: 0.4675324675324675 and parameters: {'C': 8.426981845053008e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5457361256606462}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,648] Trial 29 finished with value: 0.4675324675324675 and parameters: {'C': 1.4851029201168323e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4086937041390682}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,669] Trial 30 finished with value: 0.4675324675324675 and parameters: {'C': 3.3301797620038616e-06, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7811694075082595}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,689] Trial 31 finished with value: 0.4675324675324675 and parameters: {'C': 0.00233759231478454, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9183220338709471}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,710] Trial 32 finished with value: 0.4675324675324675 and parameters: {'C': 1.817883926098935e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7941858187455659}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,731] Trial 33 finished with value: 0.4675324675324675 and parameters: {'C': 1.4469901088746914e-10, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7448316521690269}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,752] Trial 34 finished with value: 0.4675324675324675 and parameters: {'C': 6.114091988974072e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9702210491420065}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,793] Trial 35 finished with value: 0.4675324675324675 and parameters: {'C': 6.645255482948041, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7951765820928292}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,814] Trial 36 finished with value: 0.4675324675324675 and parameters: {'C': 0.00022086663993480522, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7738755698567568}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,835] Trial 37 finished with value: 0.4675324675324675 and parameters: {'C': 3.4811030706412566e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8839721886885784}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,856] Trial 38 finished with value: 0.4675324675324675 and parameters: {'C': 5.6612488593791266e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.349359385055831}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,878] Trial 39 finished with value: 0.4675324675324675 and parameters: {'C': 0.00015921427986081838, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5776875784388642}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,900] Trial 40 finished with value: 0.4675324675324675 and parameters: {'C': 1.1184001229723309e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.1920959949107463}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,918] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 2.3597767852212298e-08, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6031081711200181}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,956] Trial 42 finished with value: 0.4675324675324675 and parameters: {'C': 135.42423609849516, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.440970852952929}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:01,977] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 6.546617279870065e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6957714650211804}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:02,018] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 252.8447458701384, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.26184187752178134}. Best is trial 0 with value: 0.4675324675324675.
[I 2026-10-19 15:16:02,039] Trial 45 finished with value: 0.4805194805194805 and parameters: {'C': 0.13123744898608092, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7358282217099942}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,059] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.011410283248130634, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8828492901041259}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,079] Trial 47 finished with value: 0.45454545454545453 and parameters: {'C': 1.6620711716603382, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5907579220141481}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,098] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 9.048692462793803e-06, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6360377313647122}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,117] Trial 49 finished with value: 0.4675324675324675 and parameters: {'C': 2.8020148831391875e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.31331800346442595}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,134] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 2.869005873963544e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4094979613333977}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,154] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 3.165594114226912e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6923182570168026}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,175] Trial 52 finished with value: 0.45454545454545453 and parameters: {'C': 0.6243493671926061, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6713713386448846}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,197] Trial 53 finished with value: 0.4675324675324675 and parameters: {'C': 1.4126654861407713e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.23857063368658118}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,217] Trial 54 finished with value: 0.4675324675324675 and parameters: {'C': 0.008331823697131487, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5622339184328002}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,239] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 0.0005639459641966144, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5066510810325149}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,260] Trial 56 finished with value: 0.4805194805194805 and parameters: {'C': 0.07223817575723016, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4355240102791274}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,302] Trial 57 finished with value: 0.45454545454545453 and parameters: {'C': 6.0996345345077705, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.48944661912744064}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,322] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 0.002820808248891448, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4102064910486057}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,343] Trial 59 finished with value: 0.44155844155844154 and parameters: {'C': 0.044723219947321965, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3762430149844004}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,364] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 1.1502932978000743e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7657158090522757}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,396] Trial 61 finished with value: 0.45454545454545453 and parameters: {'C': 1.4919870016275802, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4418116046347556}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,417] Trial 62 finished with value: 0.4675324675324675 and parameters: {'C': 5.158053534107624e-09, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.46844922104653547}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,459] Trial 63 finished with value: 0.4675324675324675 and parameters: {'C': 375.60681371797176, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7495713389294383}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,480] Trial 64 finished with value: 0.4675324675324675 and parameters: {'C': 0.001031207405480825, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7318146276485724}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,501] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 1.1139816042776678e-05, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.8444606934655532}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,542] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 5.548271546412788, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.3063238508587427}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,564] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 3.6731729535796776e-08, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9551498970303919}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,585] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 2.9875667123780053e-07, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.895382219375569}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,777] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.03772615725109638, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.454871769421494}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,799] Trial 70 finished with value: 0.4805194805194805 and parameters: {'C': 0.09496166022849954, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5130374356330277}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,830] Trial 71 finished with value: 0.4675324675324675 and parameters: {'C': 0.00783918531535942, 'fit_intercept': True, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.707508556415258}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,851] Trial 72 finished with value: 0.4675324675324675 and parameters: {'C': 0.0019883349855596586, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6334297412066879}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,873] Trial 73 finished with value: 0.4805194805194805 and parameters: {'C': 0.10323109547958054, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4705573240190747}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,895] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 0.03344697618937054, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5276813418620943}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,916] Trial 75 finished with value: 0.4675324675324675 and parameters: {'C': 0.6893715799267484, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.4740802843389769}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,937] Trial 76 finished with value: 0.4805194805194805 and parameters: {'C': 0.16696881478666326, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7154056497856813}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,959] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 4.36874916588971e-05, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5822373541063701}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:02,981] Trial 78 finished with value: 0.45454545454545453 and parameters: {'C': 0.07091651089029108, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6622046759903695}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:03,003] Trial 79 finished with value: 0.45454545454545453 and parameters: {'C': 1.0050746999853684, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.760266621452383}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:03,024] Trial 80 finished with value: 0.4805194805194805 and parameters: {'C': 0.14556496630855015, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7243065279662447}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:03,056] Trial 81 finished with value: 0.45454545454545453 and parameters: {'C': 4.167023084723553, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.39117520512487747}. Best is trial 45 with value: 0.4805194805194805.
[I 2026-10-19 15:16:03,077] Trial 82 finished with value: 0.4805194805194805 and parameters: {'C': 0.16838157573115475, 'fit_intercept': False, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7304989257732997}. Best is trial 45 with value: 0.4805194805194805.

0.01256704330444336  seconds
Classification report saved as results/Continent/data_30/data_30_umap_logreg_classification_report.txt
    Accuracy: 0.4805, Time: 2.83s
  - Testing classifier: dt

[I 2026-10-19 15:16:03,742] Trial 62 finished with value: 0.37662337662337664 and parameters: {'max_depth': 13, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,744] Trial 63 finished with value: 0.38961038961038963 and parameters: {'max_depth': 8, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,747] Trial 64 finished with value: 0.36363636363636365 and parameters: {'max_depth': 18, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,750] Trial 65 finished with value: 0.36363636363636365 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,753] Trial 66 finished with value: 0.3246753246753247 and parameters: {'max_depth': 7, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,756] Trial 67 finished with value: 0.36363636363636365 and parameters: {'max_depth': 10, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,759] Trial 68 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,762] Trial 69 finished with value: 0.36363636363636365 and parameters: {'max_depth': 27, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,765] Trial 70 finished with value: 0.24675324675324675 and parameters: {'max_depth': 20, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,768] Trial 71 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,771] Trial 72 finished with value: 0.33766233766233766 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,774] Trial 73 finished with value: 0.37662337662337664 and parameters: {'max_depth': 3, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,777] Trial 74 finished with value: 0.2597402597402597 and parameters: {'max_depth': 10, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,780] Trial 75 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,783] Trial 76 finished with value: 0.3246753246753247 and parameters: {'max_depth': 7, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,786] Trial 77 finished with value: 0.2857142857142857 and parameters: {'max_depth': 22, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,789] Trial 78 finished with value: 0.3246753246753247 and parameters: {'max_depth': 6, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,792] Trial 79 finished with value: 0.3246753246753247 and parameters: {'max_depth': 6, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,795] Trial 80 finished with value: 0.36363636363636365 and parameters: {'max_depth': 5, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,798] Trial 81 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,801] Trial 82 finished with value: 0.35064935064935066 and parameters: {'max_depth': 2, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,804] Trial 83 finished with value: 0.33766233766233766 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,807] Trial 84 finished with value: 0.24675324675324675 and parameters: {'max_depth': 12, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,810] Trial 85 finished with value: 0.2597402597402597 and parameters: {'max_depth': 28, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,813] Trial 86 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,816] Trial 87 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,820] Trial 88 finished with value: 0.24675324675324675 and parameters: {'max_depth': 9, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,823] Trial 89 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,826] Trial 90 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,829] Trial 91 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,832] Trial 92 finished with value: 0.33766233766233766 and parameters: {'max_depth': 4, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,835] Trial 93 finished with value: 0.36363636363636365 and parameters: {'max_depth': 5, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,838] Trial 94 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,841] Trial 95 finished with value: 0.37662337662337664 and parameters: {'max_depth': 7, 'criterion': 'gini'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,845] Trial 96 finished with value: 0.2857142857142857 and parameters: {'max_depth': 13, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,848] Trial 97 finished with value: 0.33766233766233766 and parameters: {'max_depth': 4, 'criterion': 'log_loss'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,851] Trial 98 finished with value: 0.4025974025974026 and parameters: {'max_depth': 3, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:03,854] Trial 99 finished with value: 0.4155844155844156 and parameters: {'max_depth': 2, 'criterion': 'entropy'}. Best is trial 11 with value: 0.4155844155844156.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:16:03,860] A new study created in memory with name: no-name-aa3e9dd1-1a67-455f-9639-93ca88a82eba
[I 2026-10-19 15:16:04,013] Trial 0 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 179, 'max_depth': 30}. Best is trial 0 with value: 0.3246753246753247.

0.0009856224060058594  seconds
Classification report saved as results/Continent/data_30/data_30_umap_dt_classification_report.txt
    Accuracy: 0.4286, Time: 0.31s
  - Testing classifier: rf

[I 2026-10-19 15:16:04,064] Trial 1 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 58, 'max_depth': 31}. Best is trial 1 with value: 0.36363636363636365.
[I 2026-10-19 15:16:04,102] Trial 2 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 44, 'max_depth': 25}. Best is trial 1 with value: 0.36363636363636365.
[I 2026-10-19 15:16:04,204] Trial 3 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 120, 'max_depth': 11}. Best is trial 1 with value: 0.36363636363636365.
[I 2026-10-19 15:16:04,228] Trial 4 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 26, 'max_depth': 15}. Best is trial 4 with value: 0.37662337662337664.
[I 2026-10-19 15:16:04,261] Trial 5 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 36, 'max_depth': 20}. Best is trial 4 with value: 0.37662337662337664.
[I 2026-10-19 15:16:04,284] Trial 6 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 25, 'max_depth': 20}. Best is trial 6 with value: 0.38961038961038963.
[I 2026-10-19 15:16:04,313] Trial 7 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 32, 'max_depth': 11}. Best is trial 6 with value: 0.38961038961038963.
[I 2026-10-19 15:16:04,386] Trial 8 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 84, 'max_depth': 30}. Best is trial 6 with value: 0.38961038961038963.
[I 2026-10-19 15:16:04,502] Trial 9 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 133, 'max_depth': 31}. Best is trial 6 with value: 0.38961038961038963.
[I 2026-10-19 15:16:04,604] Trial 10 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 134, 'max_depth': 3}. Best is trial 10 with value: 0.4025974025974026.
[I 2026-10-19 15:16:04,666] Trial 11 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 77, 'max_depth': 5}. Best is trial 11 with value: 0.4155844155844156.
[I 2026-10-19 15:16:04,752] Trial 12 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 115, 'max_depth': 2}. Best is trial 12 with value: 0.42857142857142855.
[I 2026-10-19 15:16:04,819] Trial 13 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 81, 'max_depth': 6}. Best is trial 12 with value: 0.42857142857142855.
[I 2026-10-19 15:16:04,850] Trial 14 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 39, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:04,868] Trial 15 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 20, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:04,883] Trial 16 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 16, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:04,922] Trial 17 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 49, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:04,984] Trial 18 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 68, 'max_depth': 11}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,072] Trial 19 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 100, 'max_depth': 17}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,106] Trial 20 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 37, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,203] Trial 21 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 117, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,350] Trial 22 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 183, 'max_depth': 6}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,512] Trial 23 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 190, 'max_depth': 12}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,646] Trial 24 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 155, 'max_depth': 16}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,692] Trial 25 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 54, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,705] Trial 26 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 12, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,761] Trial 27 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 72, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,787] Trial 28 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 30, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,858] Trial 29 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 94, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:05,998] Trial 30 finished with value: 0.3246753246753247 and parameters: {'n_estimators': 162, 'max_depth': 12}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,078] Trial 31 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 106, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,129] Trial 32 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 58, 'max_depth': 8}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,245] Trial 33 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 156, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,379] Trial 34 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 178, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,498] Trial 35 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 148, 'max_depth': 6}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,585] Trial 36 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 99, 'max_depth': 10}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,635] Trial 37 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 54, 'max_depth': 14}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,716] Trial 38 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 99, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,734] Trial 39 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 16, 'max_depth': 13}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,754] Trial 40 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 19, 'max_depth': 10}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,780] Trial 41 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 29, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,811] Trial 42 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 38, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,835] Trial 43 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 26, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,873] Trial 44 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 44, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,905] Trial 45 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 38, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,968] Trial 46 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 71, 'max_depth': 8}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:06,990] Trial 47 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 22, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,001] Trial 48 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 10, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,048] Trial 49 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 57, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,105] Trial 50 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 68, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,224] Trial 51 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 136, 'max_depth': 9}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,236] Trial 52 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 10, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,347] Trial 53 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 124, 'max_depth': 27}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,380] Trial 54 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 37, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,450] Trial 55 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 77, 'max_depth': 19}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,490] Trial 56 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 47, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,570] Trial 57 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 93, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,664] Trial 58 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 119, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,687] Trial 59 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 23, 'max_depth': 8}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,729] Trial 60 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 47, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,751] Trial 61 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 24, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,884] Trial 62 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 151, 'max_depth': 24}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:07,988] Trial 63 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 140, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,007] Trial 64 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 20, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,070] Trial 65 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 81, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,155] Trial 66 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 108, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,319] Trial 67 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 200, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,347] Trial 68 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 32, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,506] Trial 69 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 188, 'max_depth': 9}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,610] Trial 70 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 130, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,684] Trial 71 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 85, 'max_depth': 9}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,732] Trial 72 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 58, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,857] Trial 73 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 169, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:08,990] Trial 74 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 168, 'max_depth': 5}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,044] Trial 75 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 62, 'max_depth': 6}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,110] Trial 76 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 87, 'max_depth': 2}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,128] Trial 77 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 17, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,155] Trial 78 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 28, 'max_depth': 7}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,252] Trial 79 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 127, 'max_depth': 3}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,371] Trial 80 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 153, 'max_depth': 4}. Best is trial 14 with value: 0.45454545454545453.
[I 2026-10-19 15:16:09,396] Trial 81 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 28, 'max_depth': 4}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,507] Trial 82 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 142, 'max_depth': 4}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,531] Trial 83 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 27, 'max_depth': 2}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,544] Trial 84 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 10, 'max_depth': 17}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,580] Trial 85 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 42, 'max_depth': 3}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,656] Trial 86 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 98, 'max_depth': 3}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,698] Trial 87 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 52, 'max_depth': 2}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,733] Trial 88 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 38, 'max_depth': 6}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,762] Trial 89 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 30, 'max_depth': 9}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,790] Trial 90 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 31, 'max_depth': 4}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,835] Trial 91 finished with value: 0.3116883116883117 and parameters: {'n_estimators': 49, 'max_depth': 10}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,905] Trial 92 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 85, 'max_depth': 5}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:09,973] Trial 93 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 89, 'max_depth': 2}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,009] Trial 94 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 43, 'max_depth': 2}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,028] Trial 95 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 19, 'max_depth': 5}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,057] Trial 96 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 34, 'max_depth': 2}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,080] Trial 97 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 25, 'max_depth': 4}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,229] Trial 98 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 197, 'max_depth': 3}. Best is trial 81 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,241] Trial 99 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 10, 'max_depth': 3}. Best is trial 81 with value: 0.4675324675324675.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:16:10,268] A new study created in memory with name: no-name-26ae5848-1164-48b0-9bc6-be82e0e9a78a
[I 2026-10-19 15:16:10,269] Trial 0 finished with value: 0.2857142857142857 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 0 with value: 0.2857142857142857.
[I 2026-10-19 15:16:10,272] Trial 1 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 1 with value: 0.33766233766233766.
[I 2026-10-19 15:16:10,273] Trial 2 finished with value: 0.35064935064935066 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 2 with value: 0.35064935064935066.
[I 2026-10-19 15:16:10,276] Trial 3 finished with value: 0.37662337662337664 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 3 with value: 0.37662337662337664.

0.022312164306640625  seconds
Classification report saved as results/Continent/data_30/data_30_umap_rf_classification_report.txt
    Accuracy: 0.4156, Time: 6.41s
  - Testing classifier: knn

[I 2026-10-19 15:16:10,469] Trial 64 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,472] Trial 65 finished with value: 0.35064935064935066 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,476] Trial 66 finished with value: 0.35064935064935066 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,480] Trial 67 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,483] Trial 68 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,486] Trial 69 finished with value: 0.3246753246753247 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,490] Trial 70 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,493] Trial 71 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,496] Trial 72 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,500] Trial 73 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,504] Trial 74 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,507] Trial 75 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,510] Trial 76 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,514] Trial 77 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,517] Trial 78 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,521] Trial 79 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,524] Trial 80 finished with value: 0.35064935064935066 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,527] Trial 81 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,530] Trial 82 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,533] Trial 83 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,536] Trial 84 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,540] Trial 85 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,543] Trial 86 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,546] Trial 87 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,549] Trial 88 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,553] Trial 89 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,558] Trial 90 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,562] Trial 91 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,565] Trial 92 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'auto'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,568] Trial 93 finished with value: 0.44155844155844154 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,572] Trial 94 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,576] Trial 95 finished with value: 0.42857142857142855 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'algorithm': 'ball_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,580] Trial 96 finished with value: 0.4025974025974026 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,584] Trial 97 finished with value: 0.33766233766233766 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,587] Trial 98 finished with value: 0.36363636363636365 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'algorithm': 'brute'}. Best is trial 10 with value: 0.44155844155844154.
[I 2026-10-19 15:16:10,591] Trial 99 finished with value: 0.38961038961038963 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'algorithm': 'kd_tree'}. Best is trial 10 with value: 0.44155844155844154.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
[I 2026-10-19 15:16:10,596] A new study created in memory with name: no-name-43431adf-43d9-40f5-8efd-14f83f901952
[I 2026-10-19 15:16:10,650] Trial 0 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 62, 'learning_rate': 0.7068604323344632, 'max_depth': 13, 'min_child_weight': 6.623790392515217, 'subsample': 0.6116468105216223, 'colsample_bytree': 0.8632783312984774}. Best is trial 0 with value: 0.36363636363636365.

0.001476287841796875  seconds
Classification report saved as results/Continent/data_30/data_30_umap_knn_classification_report.txt
    Accuracy: 0.4286, Time: 0.33s
  - Testing classifier: xgboost

[I 2026-10-19 15:16:10,857] Trial 1 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 172, 'learning_rate': 0.0470059304979817, 'max_depth': 7, 'min_child_weight': 3.8960981192362523, 'subsample': 0.7762721908508263, 'colsample_bytree': 0.5437222172610026}. Best is trial 1 with value: 0.42857142857142855.
[I 2026-10-19 15:16:10,908] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 106, 'learning_rate': 0.1462410603121168, 'max_depth': 23, 'min_child_weight': 8.416511634990592, 'subsample': 0.10784951095869462, 'colsample_bytree': 0.339135625953917}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:10,988] Trial 3 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 148, 'learning_rate': 0.6548938934423301, 'max_depth': 29, 'min_child_weight': 3.7142272227262167, 'subsample': 0.1127841595860321, 'colsample_bytree': 0.31137283731092424}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,111] Trial 4 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 177, 'learning_rate': 0.49245185332921615, 'max_depth': 13, 'min_child_weight': 7.662810284566365, 'subsample': 0.4829312175986735, 'colsample_bytree': 0.11246343865323885}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,205] Trial 5 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 168, 'learning_rate': 0.6030580493144876, 'max_depth': 7, 'min_child_weight': 8.703988420945592, 'subsample': 0.3016093905193687, 'colsample_bytree': 0.7879056506685604}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,295] Trial 6 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 102, 'learning_rate': 0.7675602230893157, 'max_depth': 17, 'min_child_weight': 6.672794640918677, 'subsample': 0.7732881758669256, 'colsample_bytree': 0.9593181092789662}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,385] Trial 7 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 103, 'learning_rate': 0.3008859782202224, 'max_depth': 25, 'min_child_weight': 9.503088052011227, 'subsample': 0.8295568315430087, 'colsample_bytree': 0.2688304830863152}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,494] Trial 8 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 89, 'learning_rate': 0.8981783174957702, 'max_depth': 24, 'min_child_weight': 2.9206464125126503, 'subsample': 0.8626269229113199, 'colsample_bytree': 0.7757846409947302}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,522] Trial 9 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 35, 'learning_rate': 0.47272362854949945, 'max_depth': 10, 'min_child_weight': 4.979658186452205, 'subsample': 0.2906838191555384, 'colsample_bytree': 0.956863578198055}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,581] Trial 10 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 105, 'learning_rate': 0.44867385066017573, 'max_depth': 19, 'min_child_weight': 8.28577375339437, 'subsample': 0.2349653033613039, 'colsample_bytree': 0.4926654748979614}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,731] Trial 11 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 137, 'learning_rate': 0.10829824206492708, 'max_depth': 18, 'min_child_weight': 4.696208213991691, 'subsample': 0.6440171477192966, 'colsample_bytree': 0.398267853277244}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,883] Trial 12 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 184, 'learning_rate': 0.18136395286723472, 'max_depth': 10, 'min_child_weight': 2.8403634737650103, 'subsample': 0.2425012110319712, 'colsample_bytree': 0.45547865726215125}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:11,946] Trial 13 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 77, 'learning_rate': 0.044538120705433976, 'max_depth': 30, 'min_child_weight': 6.242828378421239, 'subsample': 0.3580557705354172, 'colsample_bytree': 0.36679329772705843}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,093] Trial 14 finished with value: 0.33766233766233766 and parameters: {'n_estimators': 135, 'learning_rate': 0.11681848601201311, 'max_depth': 12, 'min_child_weight': 6.150394642862628, 'subsample': 0.8100276523723926, 'colsample_bytree': 0.635183865953615}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,197] Trial 15 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 166, 'learning_rate': 0.05011126795706977, 'max_depth': 2, 'min_child_weight': 6.663184833915652, 'subsample': 0.4804212605743545, 'colsample_bytree': 0.33093039494108034}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,277] Trial 16 finished with value: 0.35064935064935066 and parameters: {'n_estimators': 85, 'learning_rate': 0.16820113755868912, 'max_depth': 8, 'min_child_weight': 4.859904742637884, 'subsample': 0.4264564720515688, 'colsample_bytree': 0.48532835851194156}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,359] Trial 17 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 93, 'learning_rate': 0.021756459217658383, 'max_depth': 17, 'min_child_weight': 6.180028751717776, 'subsample': 0.45091182461048945, 'colsample_bytree': 0.504553454730167}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,398] Trial 18 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 67, 'learning_rate': 0.3204795042763918, 'max_depth': 21, 'min_child_weight': 7.720058338789915, 'subsample': 0.18768077380913983, 'colsample_bytree': 0.2494474472094742}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,471] Trial 19 finished with value: 0.36363636363636365 and parameters: {'n_estimators': 94, 'learning_rate': 0.10098815998156599, 'max_depth': 21, 'min_child_weight': 7.038602385783441, 'subsample': 0.4192701635287452, 'colsample_bytree': 0.34552733258951257}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,525] Trial 20 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 105, 'learning_rate': 0.190549582160681, 'max_depth': 30, 'min_child_weight': 8.773300617818691, 'subsample': 0.1530043459845648, 'colsample_bytree': 0.4160682379722758}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,554] Trial 21 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 47, 'learning_rate': 0.30604122457563065, 'max_depth': 28, 'min_child_weight': 7.410066837958436, 'subsample': 0.19119003088325542, 'colsample_bytree': 0.22827558522869548}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,589] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 72, 'learning_rate': 0.005534310453504776, 'max_depth': 29, 'min_child_weight': 8.58337913187213, 'subsample': 0.10852560209566305, 'colsample_bytree': 0.5559046211012749}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,651] Trial 23 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 115, 'learning_rate': 0.25581689100301047, 'max_depth': 26, 'min_child_weight': 6.3435406137689965, 'subsample': 0.1551938083563984, 'colsample_bytree': 0.2840863319622528}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,685] Trial 24 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 62, 'learning_rate': 0.03733770255890794, 'max_depth': 31, 'min_child_weight': 8.51329598177179, 'subsample': 0.14300672818227642, 'colsample_bytree': 0.5601619772126631}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,705] Trial 25 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 25, 'learning_rate': 0.12728780687867094, 'max_depth': 23, 'min_child_weight': 8.085558877485983, 'subsample': 0.23576253759591248, 'colsample_bytree': 0.5198986172594874}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,748] Trial 26 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 77, 'learning_rate': 0.02088908050912241, 'max_depth': 27, 'min_child_weight': 6.893073622071596, 'subsample': 0.15818444637278042, 'colsample_bytree': 0.5940267718975925}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,801] Trial 27 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 87, 'learning_rate': 0.299059987710724, 'max_depth': 32, 'min_child_weight': 7.9222507854824356, 'subsample': 0.25493553811699116, 'colsample_bytree': 0.5608416635595667}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,825] Trial 28 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 40, 'learning_rate': 0.0574752928257098, 'max_depth': 28, 'min_child_weight': 9.9856004739181, 'subsample': 0.15626440187457485, 'colsample_bytree': 0.6954430661255707}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,875] Trial 29 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 83, 'learning_rate': 0.0477755946673539, 'max_depth': 30, 'min_child_weight': 9.824900759712786, 'subsample': 0.28097821735468, 'colsample_bytree': 0.592856586893825}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,914] Trial 30 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 66, 'learning_rate': 0.28826549688364594, 'max_depth': 26, 'min_child_weight': 8.434234816101647, 'subsample': 0.21167749139712091, 'colsample_bytree': 0.7107735633282636}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:12,961] Trial 31 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 72, 'learning_rate': 0.05573087238489544, 'max_depth': 27, 'min_child_weight': 8.521691191011303, 'subsample': 0.2928715160247583, 'colsample_bytree': 0.3397064566391992}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,002] Trial 32 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 81, 'learning_rate': 0.005589642711352964, 'max_depth': 23, 'min_child_weight': 8.964310188780631, 'subsample': 0.12428575128981945, 'colsample_bytree': 0.5340442436095317}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,054] Trial 33 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 74, 'learning_rate': 0.12942169243485438, 'max_depth': 32, 'min_child_weight': 7.991803479557956, 'subsample': 0.3246188079711631, 'colsample_bytree': 0.47819394811067273}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,073] Trial 34 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 29, 'learning_rate': 0.10764513421381153, 'max_depth': 29, 'min_child_weight': 7.686155484368349, 'subsample': 0.13156079091231745, 'colsample_bytree': 0.5751770337376039}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,107] Trial 35 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 53, 'learning_rate': 0.3210898414572187, 'max_depth': 31, 'min_child_weight': 8.826766284306201, 'subsample': 0.24728349754561485, 'colsample_bytree': 0.6080194112285507}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,145] Trial 36 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 68, 'learning_rate': 0.07891171911386394, 'max_depth': 26, 'min_child_weight': 7.54035137442899, 'subsample': 0.14131015875107508, 'colsample_bytree': 0.4301187605001582}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,196] Trial 37 finished with value: 0.37662337662337664 and parameters: {'n_estimators': 65, 'learning_rate': 0.05533697529060633, 'max_depth': 26, 'min_child_weight': 7.4149153705532616, 'subsample': 0.3760231147638713, 'colsample_bytree': 0.5315896616566406}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,239] Trial 38 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 71, 'learning_rate': 0.06272036274455253, 'max_depth': 24, 'min_child_weight': 9.509394123222055, 'subsample': 0.2555786788225406, 'colsample_bytree': 0.5913832211061847}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,286] Trial 39 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 80, 'learning_rate': 0.09534643371907034, 'max_depth': 27, 'min_child_weight': 8.478766371856725, 'subsample': 0.23233612567959133, 'colsample_bytree': 0.7062009542613812}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,309] Trial 40 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 35, 'learning_rate': 0.20943976951056156, 'max_depth': 30, 'min_child_weight': 8.186969175914681, 'subsample': 0.13364469994169817, 'colsample_bytree': 0.7898817235151692}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,353] Trial 41 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 80, 'learning_rate': 0.05498401941671284, 'max_depth': 32, 'min_child_weight': 6.145605367054719, 'subsample': 0.13385582420041056, 'colsample_bytree': 0.5159300379750927}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,394] Trial 42 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 75, 'learning_rate': 0.2415194620801089, 'max_depth': 27, 'min_child_weight': 7.373647446415589, 'subsample': 0.13865038818000286, 'colsample_bytree': 0.5721355483985795}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,435] Trial 43 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 72, 'learning_rate': 0.026230844627447663, 'max_depth': 29, 'min_child_weight': 9.323601911653071, 'subsample': 0.18133600025576224, 'colsample_bytree': 0.43789571053026033}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,462] Trial 44 finished with value: 0.38961038961038963 and parameters: {'n_estimators': 39, 'learning_rate': 0.17765694560281767, 'max_depth': 32, 'min_child_weight': 8.094382889774915, 'subsample': 0.22109497947792334, 'colsample_bytree': 0.4992158162178627}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,505] Trial 45 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 81, 'learning_rate': 0.16384159105873375, 'max_depth': 31, 'min_child_weight': 9.516184294724667, 'subsample': 0.16524779286309096, 'colsample_bytree': 0.4989131879526715}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,546] Trial 46 finished with value: 0.45454545454545453 and parameters: {'n_estimators': 71, 'learning_rate': 0.16903305754255826, 'max_depth': 28, 'min_child_weight': 9.66982952851383, 'subsample': 0.21260016522252745, 'colsample_bytree': 0.6398153289673855}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,606] Trial 47 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 112, 'learning_rate': 0.015500262624719402, 'max_depth': 27, 'min_child_weight': 8.592539958925613, 'subsample': 0.18728743740024528, 'colsample_bytree': 0.4955084033750043}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,640] Trial 48 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 58, 'learning_rate': 0.1018508788452964, 'max_depth': 26, 'min_child_weight': 7.791777919513356, 'subsample': 0.16398985444748634, 'colsample_bytree': 0.7048180287285132}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,704] Trial 49 finished with value: 0.4025974025974026 and parameters: {'n_estimators': 105, 'learning_rate': 0.0676589481746427, 'max_depth': 26, 'min_child_weight': 7.370393687153165, 'subsample': 0.2280977027468069, 'colsample_bytree': 0.6311502720686382}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,752] Trial 50 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 96, 'learning_rate': 0.00146284150993016, 'max_depth': 27, 'min_child_weight': 8.3128229843862, 'subsample': 0.12037637621910872, 'colsample_bytree': 0.6114788404943127}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,779] Trial 51 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 36, 'learning_rate': 0.16469978852121753, 'max_depth': 25, 'min_child_weight': 8.064828817244742, 'subsample': 0.27822870436655495, 'colsample_bytree': 0.4737858542077804}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,812] Trial 52 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 58, 'learning_rate': 0.025362723087591105, 'max_depth': 27, 'min_child_weight': 9.739795432667616, 'subsample': 0.1522146356708023, 'colsample_bytree': 0.6683781998375132}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,865] Trial 53 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 92, 'learning_rate': 0.08175868051843443, 'max_depth': 29, 'min_child_weight': 8.275728692356582, 'subsample': 0.21702997149324996, 'colsample_bytree': 0.5816637059096036}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,897] Trial 54 finished with value: 0.4155844155844156 and parameters: {'n_estimators': 52, 'learning_rate': 0.07813338870263575, 'max_depth': 24, 'min_child_weight': 8.705528011448958, 'subsample': 0.19837400278677908, 'colsample_bytree': 0.529115045860453}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,932] Trial 55 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 50, 'learning_rate': 0.04104435633864967, 'max_depth': 30, 'min_child_weight': 8.392260073081315, 'subsample': 0.2689892390259284, 'colsample_bytree': 0.5289187857652274}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,954] Trial 56 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 37, 'learning_rate': 0.06586624199567158, 'max_depth': 31, 'min_child_weight': 9.61018397114003, 'subsample': 0.1146684869854657, 'colsample_bytree': 0.6778894084436482}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:13,995] Trial 57 finished with value: 0.42857142857142855 and parameters: {'n_estimators': 71, 'learning_rate': 0.11929803141925845, 'max_depth': 29, 'min_child_weight': 8.05438455295422, 'subsample': 0.18041039088391858, 'colsample_bytree': 0.5881752292753104}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:14,016] Trial 58 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 30, 'learning_rate': 0.041361081409540056, 'max_depth': 31, 'min_child_weight': 8.877174539694849, 'subsample': 0.15596765397329607, 'colsample_bytree': 0.4747843831796096}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:14,044] Trial 59 finished with value: 0.44155844155844154 and parameters: {'n_estimators': 40, 'learning_rate': 0.0820232180280179, 'max_depth': 29, 'min_child_weight': 9.097528261782681, 'subsample': 0.2656492781815722, 'colsample_bytree': 0.7327782501636262}. Best is trial 2 with value: 0.4675324675324675.
[I 2026-10-19 15:16:14,092] Trial 60 finished with value: 0.4675324675324675 and parameters: {'n_estimators': 74, 'learning_rate': 0.02522407016321225, 'max_depth': 26, 'min_child_weight': 8.811815402008909, 'subsample': 0.26507428974405717, 'colsample_bytree': 0.507302638731266}. Best is trial 2 with value: 0.4675324675324675.

0.04606771469116211  seconds
Classification report saved as results/Continent/data_30/data_30_umap_xgboost_classification_report.txt
    Accuracy: 0.4675, Time: 4.83s
  - Testing classifier: svm

[I 2026-10-19 15:16:15,629] Trial 40 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,634] Trial 41 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,640] Trial 42 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,645] Trial 43 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,649] Trial 44 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,653] Trial 45 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,658] Trial 46 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,663] Trial 47 finished with value: 0.42857142857142855 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,669] Trial 48 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,674] Trial 49 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,680] Trial 50 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,684] Trial 51 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,688] Trial 52 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,694] Trial 53 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,699] Trial 54 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,703] Trial 55 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,709] Trial 56 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,714] Trial 57 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,723] Trial 58 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,727] Trial 59 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'linear', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,733] Trial 60 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,739] Trial 61 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,744] Trial 62 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,750] Trial 63 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,755] Trial 64 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,761] Trial 65 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,769] Trial 66 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,774] Trial 67 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,782] Trial 68 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,787] Trial 69 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,792] Trial 70 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,798] Trial 71 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,803] Trial 72 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,809] Trial 73 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,818] Trial 74 finished with value: 0.4675324675324675 and parameters: {'C': 1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,823] Trial 75 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,829] Trial 76 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,834] Trial 77 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,840] Trial 78 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,844] Trial 79 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'linear', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,850] Trial 80 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,855] Trial 81 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,861] Trial 82 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,867] Trial 83 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,872] Trial 84 finished with value: 0.42857142857142855 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,877] Trial 85 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,881] Trial 86 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'linear', 'degree': 4, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,886] Trial 87 finished with value: 0.4675324675324675 and parameters: {'C': 0.1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,892] Trial 88 finished with value: 0.42857142857142855 and parameters: {'C': 1, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,898] Trial 89 finished with value: 0.4675324675324675 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,903] Trial 90 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,909] Trial 91 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,915] Trial 92 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,920] Trial 93 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 3, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,926] Trial 94 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,932] Trial 95 finished with value: 0.42857142857142855 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,937] Trial 96 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 2, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,943] Trial 97 finished with value: 0.4675324675324675 and parameters: {'C': 0.6, 'kernel': 'rbf', 'degree': 3, 'gamma': 'scale'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,949] Trial 98 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 5, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
[I 2026-10-19 15:16:15,954] Trial 99 finished with value: 0.4805194805194805 and parameters: {'C': 0.3, 'kernel': 'rbf', 'degree': 4, 'gamma': 'auto'}. Best is trial 2 with value: 0.4805194805194805.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
[I 2026-10-19 15:16:15,963] A new study created in memory with name: no-name-ace4821d-01f5-44ab-a2b5-54ddb298b5a9
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:16,123] Trial 0 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 53, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.0001212711704620003}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)

0.0035583972930908203  seconds
Classification report saved as results/Continent/data_30/data_30_umap_svm_classification_report.txt
    Accuracy: 0.4805, Time: 0.53s
  - Testing classifier: mlp

/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:16,344] Trial 1 finished with value: 0.44155844155844154 and parameters: {'n_layers': 3, 'n_neurons_layer0': 7, 'n_neurons_layer1': 29, 'n_neurons_layer2': 31, 'activation': 'identity', 'solver': 'lbfgs', 'alpha': 0.0467946163269153}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:16,580] Trial 2 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 3, 'n_neurons_layer1': 100, 'n_neurons_layer2': 33, 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08402005384531971}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:17,115] Trial 3 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 51, 'n_neurons_layer1': 72, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.03363179553573978}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:17,316] Trial 4 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 45, 'n_neurons_layer1': 38, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0017665978402701388}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:17,328] Trial 5 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 95, 'activation': 'identity', 'solver': 'adam', 'alpha': 0.000844258223246369}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:17,544] Trial 6 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 8, 'n_neurons_layer1': 79, 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001450209957351749}. Best is trial 0 with value: 0.4675324675324675.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:18,381] Trial 7 finished with value: 0.4805194805194805 and parameters: {'n_layers': 3, 'n_neurons_layer0': 24, 'n_neurons_layer1': 63, 'n_neurons_layer2': 69, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.02393111334921213}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:18,562] Trial 8 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 2, 'n_neurons_layer1': 3, 'activation': 'identity', 'solver': 'sgd', 'alpha': 0.0015165288225872644}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:18,745] Trial 9 finished with value: 0.4675324675324675 and parameters: {'n_layers': 1, 'n_neurons_layer0': 80, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 0.0062408111531125484}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:19,071] Trial 10 finished with value: 0.4805194805194805 and parameters: {'n_layers': 2, 'n_neurons_layer0': 39, 'n_neurons_layer1': 49, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 4.093150535971677e-05}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:19,749] Trial 11 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 32, 'n_neurons_layer1': 53, 'n_neurons_layer2': 100, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 6.838001951313783e-05}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-10-19 15:16:20,371] Trial 12 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 34, 'n_neurons_layer1': 60, 'n_neurons_layer2': 94, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.098827912067659}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:20,885] Trial 13 finished with value: 0.44155844155844154 and parameters: {'n_layers': 3, 'n_neurons_layer0': 31, 'n_neurons_layer1': 41, 'n_neurons_layer2': 64, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.0036577019631856954}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:21,093] Trial 14 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 42, 'n_neurons_layer1': 24, 'n_neurons_layer2': 7, 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0003769214740442923}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:21,412] Trial 15 finished with value: 0.44155844155844154 and parameters: {'n_layers': 2, 'n_neurons_layer0': 15, 'n_neurons_layer1': 68, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.00021103422688611425}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:21,840] Trial 16 finished with value: 0.42857142857142855 and parameters: {'n_layers': 2, 'n_neurons_layer0': 35, 'n_neurons_layer1': 88, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.06577130614180131}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:22,136] Trial 17 finished with value: 0.45454545454545453 and parameters: {'n_layers': 2, 'n_neurons_layer0': 26, 'n_neurons_layer1': 49, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.005558529492746626}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:16:22,268] Trial 18 finished with value: 0.42857142857142855 and parameters: {'n_layers': 2, 'n_neurons_layer0': 13, 'n_neurons_layer1': 20, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 1.8521885738197625e-05}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:16:22,792] Trial 19 finished with value: 0.4675324675324675 and parameters: {'n_layers': 3, 'n_neurons_layer0': 12, 'n_neurons_layer1': 61, 'n_neurons_layer2': 63, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.0016589473800308818}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:17:19,210] Trial 20 finished with value: 0.45454545454545453 and parameters: {'n_layers': 3, 'n_neurons_layer0': 50, 'n_neurons_layer1': 82, 'n_neurons_layer2': 70, 'activation': 'logistic', 'solver': 'lbfgs', 'alpha': 0.0001617745031000311}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
[I 2026-10-19 15:17:19,382] Trial 21 finished with value: 0.42857142857142855 and parameters: {'n_layers': 1, 'n_neurons_layer0': 52, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 1.1308501738207809e-05}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:17:19,840] Trial 22 finished with value: 0.4675324675324675 and parameters: {'n_layers': 2, 'n_neurons_layer0': 61, 'n_neurons_layer1': 45, 'activation': 'relu', 'solver': 'lbfgs', 'alpha': 2.307690185513725e-05}. Best is trial 7 with value: 0.4805194805194805.
/home/zeineb/time-series-embedding/src/classifiers/neural_models.py:29: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform('alpha', 1e-5, 1e-1)
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
[I 2026-10-19 15:17:20,026] Trial 23 finished with value: 0.44155844155844154 and parameters: {'n_layers': 1, 'n_neurons_layer0': 39, 'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 0.0001789691485814391}. Best is trial 7 with value: 0.4805194805194805.

{'activation': 'tanh', 'solver': 'lbfgs', 'alpha': 3.482923944218014e-05, 'hidden_layer_sizes': [7, 73, 54]}
Classification report saved as results/Continent/data_30/data_30_umap_mlp_classification_report_2026-10-19_15-24-23.txt
    Accuracy: 0.4675, Time: 487.19s
  - Testing classifier: nb

[I 2026-10-19 15:24:23,330] Trial 72 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.002418618389230005}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,333] Trial 73 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.000576123764705626}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,336] Trial 74 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0050680139764463904}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,339] Trial 75 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.001623604832098941}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,341] Trial 76 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.0009056028918615882}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,344] Trial 77 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0030739873338714975}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,346] Trial 78 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0060941860851096066}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,348] Trial 79 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 3.0986049989107884e-08}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,351] Trial 80 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.00010263639966335749}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,353] Trial 81 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.008891316723989066}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,356] Trial 82 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0031129349785588853}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,358] Trial 83 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0011637895565364176}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,361] Trial 84 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.006528389089525168}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,363] Trial 85 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.0005483176394987359}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,366] Trial 86 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0026362015922043267}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,368] Trial 87 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.0003063734810966703}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,371] Trial 88 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0013486245013247095}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,373] Trial 89 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.004170360245797857}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,376] Trial 90 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.0007799057351983413}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,378] Trial 91 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0015354809573055054}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,381] Trial 92 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.00905365010556061}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,383] Trial 93 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0038778539402995506}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,386] Trial 94 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.00019138766275546287}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,388] Trial 95 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.0006118571096070401}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,391] Trial 96 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.002187941351010055}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,394] Trial 97 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.006888983108328188}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,396] Trial 98 finished with value: 0.4155844155844156 and parameters: {'var_smoothing': 0.0012271887631730282}. Best is trial 4 with value: 0.4155844155844156.
[I 2026-10-19 15:24:23,399] Trial 99 finished with value: 0.4025974025974026 and parameters: {'var_smoothing': 0.000414207582442103}. Best is trial 4 with value: 0.4155844155844156.
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeineb/.conda/envs/timeseries_py312/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Best hyperparameters:  {'var_smoothing': 0.0016395896164580785}
Best validation accuracy:  0.4155844155844156
Test accuracy: 0.4155844155844156
Time taken: 0.0012116432189941406 seconds
Classification report saved as results/Continent/data_30/data_30_umap_nb_classification_report_2026-10-19_15-24-23.txt
    Accuracy: 0.4156, Time: 0.25s

In [ ]:
"""
embedding_methods = ['pca', 'lle', 'umap','nnclr_cnn']
#embedding_methods = ['nnclr_cnn']
classifiers = ['logreg', 'dt', 'rf', 'knn','xgboost', 'svm', 'mlp','nb']
X_train_norm = ntl_window[ntl_window['split'] == 'train'].pivot(index='case_id', columns='time_step', values='ntl_std').dropna()
X_val_norm = ntl_window[ntl_window['split'] == 'val'].pivot(index='case_id', columns='time_step', values='ntl_std').dropna()
X_test_norm = X_val_norm
X_full = ntl_window.pivot(index='case_id', columns='time_step', values='ntl_std').dropna()

dataset_path = f'results/data_{str(d_window)}/data_{str(d_window)}'
os.makedirs(f'results/data_{str(d_window)}',exist_ok=True)

output_dir = f'plots/data_{str(d_window)}'
os.makedirs(output_dir ,exist_ok=True)

y_train = cases_window.loc[X_train_norm.index, 'event_type'].values
y_val = cases_window.loc[X_val_norm.index, 'event_type'].values
y_test =y_val

for embed_method in embedding_methods:
    print(f"\nEvaluating embedding method: {embed_method}")
    # Run embedding
    try:
        train_emb, val_emb, test_emb, embed_time = run_embedding_experiment(
     X_train_norm.values, X_val_norm.values, X_test_norm, y_train, y_val, y_test, embed_method
        )

        # Store embedding results
        results['embedding_results'][embed_method] = {
        'time': embed_time,
        'shape': train_emb.shape if hasattr(train_emb, 'shape') else None
        }

        # Visualize embeddings
        try:
            if embed_method in ['nnclr_cnn', 'nnclr_lstm']:
                # For NNCLR methods, use umap_plt from visualization module
                umap_plt(
                train_emb, val_emb, test_emb, 
                y_train, y_val, y_test, 
                f"{embed_method.upper()} Embedding"
                    )
            else:
                # For other methods, use visualize_embeddings from evaluation module
                fig = visualize_embeddings(
                train_emb, y_train, method='tsne', 
                title=f'{embed_method.upper()} Embedding Visualization'
                    )
                fig.savefig(os.path.join(output_dir, f'{embed_method}_visualization.png'))
                plt.close(fig)
        except Exception as viz_error:
            print(f"  - Warning: Visualization failed: {viz_error}")

        # Run classifier experiments
        for clf_name in classifiers:
            print(f"  - Testing classifier: {clf_name}")

            experiment_name = f"{dataset_path}_{embed_method}_{clf_name}"

            try:
                best_params, test_score, clf_time = run_classifier_experiment(
        train_emb, val_emb, test_emb, y_train, y_val, y_test, 
        clf_name, experiment_name
            )

                # Store results
                if embed_method not in results['combined_results']:
                    results['combined_results'][embed_method] = {}

                results['combined_results'][embed_method][clf_name] = {
            'accuracy': test_score,
            'params': best_params,
            'time': clf_time
                }

                print(f"    Accuracy: {test_score:.4f}, Time: {clf_time:.2f}s")

            except Exception as e:
                print(f"    Error with classifier {clf_name}: {e}")
                results['combined_results'][embed_method][clf_name] = {
            'error': str(e)
            }

    except Exception as e:
        print(f"Error with embedding method {embed_method}: {e}")
        results['embedding_results'][embed_method] = {
        'error': str(e)
            }
            
            """

'\nembedding_methods = [\'pca\', \'lle\', \'umap\',\'nnclr_cnn\']\n#embedding_methods = [\'nnclr_cnn\']\nclassifiers = [\'logreg\', \'dt\', \'rf\', \'knn\',\'xgboost\', \'svm\', \'mlp\',\'nb\']\nX_train_norm = ntl_window[ntl_window[\'split\'] == \'train\'].pivot(index=\'case_id\', columns=\'time_step\', values=\'ntl_std\').dropna()\nX_val_norm = ntl_window[ntl_window[\'split\'] == \'val\'].pivot(index=\'case_id\', columns=\'time_step\', values=\'ntl_std\').dropna()\nX_test_norm = X_val_norm\nX_full = ntl_window.pivot(index=\'case_id\', columns=\'time_step\', values=\'ntl_std\').dropna()\n\ndataset_path = f\'results/data_{str(d_window)}/data_{str(d_window)}\'\nos.makedirs(f\'results/data_{str(d_window)}\',exist_ok=True)\n\noutput_dir = f\'plots/data_{str(d_window)}\'\nos.makedirs(output_dir ,exist_ok=True)\n\ny_train = cases_window.loc[X_train_norm.index, \'event_type\'].values\ny_val = cases_window.loc[X_val_norm.index, \'event_type\'].values\ny_test =y_val\n\nfor embed_method in embedding_methods:\n    print(f"\nEvaluating embedding method: {embed_method}")\n    # Run embedding\n    try:\n        train_emb, val_emb, test_emb, embed_time = run_embedding_experiment(\n     X_train_norm.values, X_val_norm.values, X_test_norm, y_train, y_val, y_test, embed_method\n        )\n\n        # Store embedding results\n        results[\'embedding_results\'][embed_method] = {\n        \'time\': embed_time,\n        \'shape\': train_emb.shape if hasattr(train_emb, \'shape\') else None\n        }\n\n        # Visualize embeddings\n        try:\n            if embed_method in [\'nnclr_cnn\', \'nnclr_lstm\']:\n                # For NNCLR methods, use umap_plt from visualization module\n                umap_plt(\n                train_emb, val_emb, test_emb, \n                y_train, y_val, y_test, \n                f"{embed_method.upper()} Embedding"\n                    )\n            else:\n                # For other methods, use visualize_embeddings from evaluation module\n                fig = visualize_embeddings(\n                train_emb, y_train, method=\'tsne\', \n                title=f\'{embed_method.upper()} Embedding Visualization\'\n                    )\n                fig.savefig(os.path.join(output_dir, f\'{embed_method}_visualization.png\'))\n                plt.close(fig)\n        except Exception as viz_error:\n            print(f"  - Warning: Visualization failed: {viz_error}")\n\n        # Run classifier experiments\n        for clf_name in classifiers:\n            print(f"  - Testing classifier: {clf_name}")\n\n            experiment_name = f"{dataset_path}_{embed_method}_{clf_name}"\n\n            try:\n                best_params, test_score, clf_time = run_classifier_experiment(\n        train_emb, val_emb, test_emb, y_train, y_val, y_test, \n        clf_name, experiment_name\n            )\n\n                # Store results\n                if embed_method not in results[\'combined_results\']:\n                    results[\'combined_results\'][embed_method] = {}\n\n                results[\'combined_results\'][embed_method][clf_name] = {\n            \'accuracy\': test_score,\n            \'params\': best_params,\n            \'time\': clf_time\n                }\n\n                print(f"    Accuracy: {test_score:.4f}, Time: {clf_time:.2f}s")\n\n            except Exception as e:\n                print(f"    Error with classifier {clf_name}: {e}")\n                results[\'combined_results\'][embed_method][clf_name] = {\n            \'error\': str(e)\n            }\n\n    except Exception as e:\n        print(f"Error with embedding method {embed_method}: {e}")\n        results[\'embedding_results\'][embed_method] = {\n        \'error\': str(e)\n            }\n\n            '

In [10]:
cases

,event_type,source_cluster_id,city,country,event_date,event_dates,n_events,catalog_event_date,catalog_event_dates,shift_reason,...,event_end,window_anchor,window_start,window_end,notes,raster_path,Continent,event_type_class,Continent_class,split
case_id,,,,,,,,,,,,,,,,,,,,,
earthquake_2,earthquake,2,Sagaing,Myanmar,2025-03-28,2025-03-28,1,2025-03-28 06:20:52.715,2025-03-28,NaN,...,2025-03-28 06:20:52.715,2025-03-28,2024-03-28,2025-09-24,NaN,rasters/earthquake_2.npz,Asia,0,0,train
earthquake_3,earthquake,3,Iquique,Chile,2014-04-03,2014-04-03,1,2014-04-03 02:43:13.110,2014-04-03;2014-04-03,NaN,...,2014-04-03 02:43:13.110,2014-04-03,2013-04-03,2014-09-30,NaN,rasters/earthquake_3.npz,South America,0,1,val
earthquake_7,earthquake,7,Catia La Mar [La Guaira],Venezuela,2026-06-24,2026-06-24,1,2026-06-24 22:05:04.012,2026-06-24,NaN,...,2026-06-24 22:05:04.012,2026-06-24,2025-06-24,2026-10-08,NaN,rasters/earthquake_7.npz,South America,0,1,train
earthquake_11,earthquake,11,Halabja,Iraq,2017-11-20,2017-11-20,1,2017-11-12 18:18:17.180,2017-11-12,NaN,...,2017-11-12 18:18:17.180,2017-11-12,2016-11-12,2018-05-11,NaN,rasters/earthquake_11.npz,Asia,0,0,val
earthquake_29,earthquake,29,Valparaíso,Chile,2017-05-05,2017-05-05,1,2017-04-24 21:38:30.820,2017-04-23;2017-04-24,NaN,...,2017-04-24 21:38:30.820,2017-04-23,2016-04-23,2017-10-21,NaN,rasters/earthquake_29.npz,South America,0,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
conflict_615_0,conflict,615,Mek'elē,Ethiopia,2020-12-01,2020-12-01;2021-02-16;2021-04-01;2021-06-30;20...,6,NaN,NaN,NaN,...,2021-12-01 00:00:00.000,2020-12-01,2019-12-02,2022-06-01,NaN,rasters/conflict_615_0.npz,Africa,3,4,train
conflict_616_0,conflict,616,Quiha,Ethiopia,2020-12-03,2020-12-03,1,NaN,NaN,NaN,...,2020-12-03 00:00:00.000,2020-12-03,2019-12-04,2021-06-03,NaN,rasters/conflict_616_0.npz,Africa,3,4,train
conflict_617_0,conflict,617,Wukro,Ethiopia,2020-11-16,2020-11-16;2021-02-18;2021-04-01;2021-06-29,4,NaN,NaN,NaN,...,2021-06-29 00:00:00.000,2020-11-16,2019-11-17,2021-12-29,NaN,rasters/conflict_617_0.npz,Africa,3,4,train
conflict_618_0,conflict,618,Maychew,Ethiopia,2020-11-08,2020-11-08;2021-07-09;2021-12-25,3,NaN,NaN,NaN,...,2021-12-25 00:00:00.000,2020-11-08,2019-11-09,2022-06-25,NaN,rasters/conflict_618_0.npz,Africa,3,4,val
conflict_621_0,conflict,621,Mekoni,Ethiopia,2020-11-07,2020-11-07,1,NaN,NaN,NaN,...,2020-11-07 00:00:00.000,2020-11-07,2019-11-08,2021-05-07,NaN,rasters/conflict_621_0.npz,Africa,3,4,val